In [605]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re

StockCode = '600166'
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)
txt = txtRaw[116:]

In [ ]:
txt

In [289]:
StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]

In [381]:
hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])

In [391]:
pd.DataFrame(hc+hp).T

In [382]:
hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])

In [392]:
csdf = pd.DataFrame(hc+hp).T
csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]

In [394]:
csdf['StockCode'] = StockCode
csdf['StockName'] = StockName

In [395]:
csdf

In [607]:
fi = txt[txt.find('【2.主营构成分析】'):]
ff = fi[:fi.find('【3.前5名客户营业收入表】')]
datetimes=re.findall(r'截止日期:([^\s]*)', ff)

In [ ]:
ff

In [320]:
# re.findall(r'截止日期:([^\s]*)', ff)
# re.findall(r'截止日期:(\S{10})', ff)

In [609]:
dd = ff.replace('─','').splitlines(keepends=False)

In [ ]:
dd

In [437]:

# Data = pd.DataFrame(columns=("股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"))
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = re.split(r"\s+", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)
# ddf  = Data.apply(pd.to_numeric, errors='ignore')

In [439]:
ddf = Data

In [440]:
ddfindex = ddf[ddf[0]=='项目名'].index

In [441]:
ddfindex

In [442]:
i = 0
raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

In [443]:
for i in [0,1,2]:
    dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
    dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
    dfd['日期'] = datetimes[i]
    raDF = pd.concat([raDF,dfd], axis=0)

In [444]:
raDF['StockCode'] = StockCode
raDF['StockName'] = StockName

In [446]:
raDF.set_index('日期')

In [346]:
dfd.set_index('日期')

In [331]:
dfd[dfd['项目名'].str.contains('行业', na=False)]

In [330]:
dfd[dfd['项目名'].str.contains('产品', na=False)]

In [329]:
dfd[dfd['项目名'].str.contains('产品', na=False)]['利润比例(%)'].astype(float).sum()

In [650]:
def getBiz(StockCode):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)[116:]   
    # txt = txtRaw[116:]

    StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName


    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',0)
    ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

    for i in [0,1,2]:
        dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
        dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
        dfd['日期'] = datetimes[i]
        raDF = pd.concat([raDF,dfd], axis=0)

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    # raDF.set_index('日期').to_sql('Biz', eng, if_exists='append')
    return(raDF,csdf)

In [651]:
a,b = getBiz('000005')

In [ ]:
list(a['项目名'])[2]

In [409]:
from sqlalchemy import create_engine
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

In [429]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [448]:
StockList.iloc[0,0]

In [428]:
pd.read_sql('StocksList', engs)[['code','name']].loc[0][1]

In [433]:

StockList.loc[15][1]

================== 热点题材

In [592]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re


qf10='热点题材'
client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]

In [546]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [564]:
n = 100

In [565]:
StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]

In [567]:
ftxt = re.findall(r'│(.*)│(关联度.*☆{4,})',txt)

In [568]:
ftdf = pd.DataFrame(ftxt)

In [569]:
ftdf = ftdf.applymap(lambda x: x.rstrip() if isinstance(x, str) else x)

In [570]:
ftdf[1]=ftdf[1].str.len()-4

In [571]:
ftdf

In [572]:
ftdf.columns=['题材','相关度']

In [573]:
ftdf['StockCode']=StockCode
ftdf['StockName']=StockName

In [694]:
def getTop(StockCode, StockName):
    qf10='热点题材'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)

    txt = re.findall(r'│(.*)│(关联度.*☆{4,})',txtRaw)
    txDF = pd.DataFrame(txt)
    txDF = txDF.applymap(lambda x: x.rstrip() if isinstance(x, str) else x)
    txDF[1]=txDF[1].str.len()-4
    txDF.columns=['题材','相关度']
    txDF['StockCode'] = StockCode
    txDF['StockName'] = StockName
    # txDF.set_index('StockCode').to_sql('Top', eng, if_exist='append')
    return(txDF)

In [ ]:
getTop(StockCode,StockName)

======================= 价值分析

In [660]:
from mootdx.quotes import Quotes
import pandas as pd
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', engs)[['code','name']]
n = 1

StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]


qf10='价值分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)[116:]
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [673]:
ftxt = txt[txt.find('【2.盈利预测统计】'):]
etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
dd = etxt.splitlines(keepends=False)

In [ ]:
dd

In [675]:
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = dd[i].split()
    if len(lis)!=7:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)

In [ ]:
Data.loc[0]

In [677]:
Data.columns=list(Data.loc[0])

In [ ]:
Data

In [679]:
Data['StockCode'] = StockCode
Data['StockName'] = StockName

In [ ]:
Data

In [692]:
def getFcast(StockCode, StockName):
    qf10='价值分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    
    ftxt = txt[txt.find('【2.盈利预测统计】'):]
    etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
    dd = etxt.splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = dd[i].split()
        if len(lis)!=7:
            pass
        else:
            df = pd.DataFrame(lis).T
            Data = pd.concat([Data, df],axis=0)
        i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',pd.NA)

    Data.columns=list(Data.loc[0])
    Data['StockCode'] = StockCode
    Data['StockName'] = StockName

    return(Data.tail(-1))

In [ ]:
getFcast('000008', '12dfa').set_index('StockCode')

In [696]:
df = pd.read_sql('Top', eng)

In [713]:
gg  = df.groupby('题材')

In [716]:
gg.groups

{'3D打印': [5098, 5140, 7024, 7860, 8142, 8176, 9400, 9705, 21049, 21566, 21736, 22034], '3D玻璃': [722, 4793, 8303, 9057], '5G概念': [291, 2535, 3614, 4022, 4161, 4374, 4769, 4958, 5158, 7133, 7261, 7714, 8452, 8490, 8540, 9575, 11642, 11987, 12764, 13564, 13961, 14463, 14510, 14633, 17734, 17870, 18623, 18675, 18860, 19265, 19791, 21916], 'AMD概念': [3447], 'ASIC芯片': [2986, 7971, 9136, 9955, 18248, 19797, 20614, 21422, 22787], 'BC电池': [6364, 15190], 'BIPV概念': [1894, 4294, 4520, 7532, 17358, 20228], 'C2M概念': [5537], 'CMP': [7286, 9933, 20453, 20883], 'CPO概念': [2330, 8529, 9324, 11563, 11686, 14632], 'CXO概念': [6230, 8701, 8753, 8934, 10007, 10067, 10142, 10271, 11217, 11374, 11672, 11776, 11842, 12075, 12350, 12385, 15506, 18387, 18697, 19084, 20582, 20699, 20709, 20921, 21205, 21298, 21356, 21375, 21573, 22575, 22806], 'DRAM': [130, 2985, 8159, 19979], 'DRG-DIP': [586, 3065, 7900, 11430, 22405], 'EDA概念': [11370, 11888, 21222], 'EDR概念': [3805, 6745, 7435, 10174, 10643], 'ERP概念': [7920, 8826, 10019, 14887], 'ETC概念': [6382, 9155, 12093], 'F5G概念': [4024, 4677, 6496, 8275, 9339, 9492, 11643, 12610, 14464, 17346, 18279, 18372, 19626], 'GPU': [1740, 9212, 22225], 'HJT电池': [3311, 22090], 'HPV疫苗': [7662, 7757, 19036], 'IGBT': [14376, 18782, 21449, 22814], 'IGZO': [721, 8324], 'IPTV': [1214, 3829, 8327, 11864, 16416], 'IPV6概念': [295, 717, 2166, 4512, 9700, 14518], 'IP变现': [1697, 4072, 4274, 5211, 5500, 7144, 7713, 8762, 9023, 11235, 17301], 'MCU芯片': [4549, 7433, 7969, 7977, 9132, 9210, 18245, 19977], 'MSCI成份': [1064, 1206, 2188, 2780, 2909, 4155, 4310, 4441, 4489, 4813, 4944, 4994, 5062, 5248, 5415, 5511, 5836, 5857, 5981, 6000, 6265, 6544, 6730, 7203, 7506, 9150, 10336, 10580, 10781, 11087, 12644, 13293, 13430, 13527, 13770, 13819, 13987, 14059, 14763, 14772, 15319, 16079, 16188, 16318, 16564, 16728, 16742, 16886, 17014, 17164, 17233, 17317, 17401, 17731, 17973, 18003, 18139, 18400, 18424, 18452, 18557, 19106, 19130, 19345, 19404, 19683, 19884, 19905, 20322, 20426, 20511, 20550, 20698, 20749, 20785, 21152, 21305, 21433, 21615, 22208, 22890], 'MicroLED': [10086, 15394], 'MiniLED': [3504], 'NFT概念': [10918, 17900, 19514], 'NMN概念': [5512], 'OLED概念': [15427, 20356], 'PCB概念': [1764, 2712, 3341, 3696, 4449, 4711, 4832, 5157, 5302, 6198, 6530, 6534, 6621, 9221, 9896, 10195, 10484, 10622, 10800, 10977, 11204, 11456, 11477, 11666, 11832, 11917, 12155, 13286, 14944, 18644, 18886, 19866, 19890, 20062, 20214, 21121, 22644, 22776], 'PCCP管道': [3662, 4800, 5718, 19305], 'PPP概念': [13108, 19601], 'PTA': [4969, 13154, 13966, 16793, 17058], 'PTT纤维': [4971, 7365], 'PVC': [541, 629, 764, 10109, 12856, 16410, 17007, 17272], 'PVDF概念': [6185, 7295, 18994], 'Pancake光学': [1716, 3729, 3847, 6406], 'QFII新进': [110, 614, 728, 790, 856, 1071, 1151, 1265, 1343, 1353, 1538, 1738, 1751, 1848, 1862, 2095, 2361, 2426, 2471, 2614, 2687, 2691, 3034, 3095, 3254, 3300, 3430, 3441, 3491, 3753, 3807, 3832, 4129, 4482, 4519, 4883, 4938, 4982, 5047, 5103, 5176, 5202, 5275, 5306, 5405, 5542, 5579, 5694, 5866, 6004, 6135, 6262, 6278, 6318, 6371, 6375, 6412, 6473, 6478, 6503, 6561, 6768, 6788, 6802, 6825, 6904, 6921, 6937, 6941, 7211, 7265, 7556, 7599, 7814, 7816, 7887, 7935, 8184, 8249, 8252, 8404, 8408, 8412, 8599, 8894, 8939, 9076, 9152, 9202, 9355, 9452, 9460, 9481, 9497, 9502, 9530, 9556, 9581, 9629, 9719, ...], 'QFII重仓': [643, 743, 1631, 2874, 3385, 3977, 3987, 4154, 4395, 4630, 4764, 5020, 5616, 6543, 6586, 6803, 7063, 9852, 10247, 10960, 12831, 13291, 13571, 13742, 13787, 14638, 16150, 16241, 16330, 16401, 16563, 16667, 16786, 16873, 16946, 16958, 17048, 17597, 17807, 17816, 17848, 19128, 19201, 19276, 19538, 19670, 19819, 19960, 21149, 22911], 'RCEP概念': [5467, 10412, 12601, 13325, 17156], 'REITs概念': [8859, 14085, 16132, 16891, 17202, 17602, 17726], 'SOC芯片': [7972, 9135, 9737, 9956, 12409, 18247, 19798, 20446, 20781, 21287, 21445, 21730, 22194, 22441, 22449, 22523, 22572, 22640], 'ST板块': [207, 507, 689, 1520, 3488, 4182, 4652, 8812, 13711, 14958, 15449, 16013, 18067], 'SaaS': [814, 3054, 3287, 3361, 4859, 7825, 8213, 8828, 19861, 21833], 'TCL系': [375, 3313, 5701], 'TCO玻璃': [13408, 14876, 15977, 17403], 'TOPCon电池': [208, 6365, 7644, 8895, 10132, 10261, 14318, 19045, 21303, 22331, 22485], 'VPN': [2165, 4732, 8552, 9114, 10307, 10859, 18663, 21055], 'WiFi6': [9340, 9546], 'eSIM': [6428, 10027], '一体压铸': [2635, 3152, 3558, 4658, 6358, 9037, 9905, 17491, 18929, 20039, 20201], '一体成型电感': [8585], '一带一路': [302, 381, 608, 998, 1268, 1670, 2011, 2029, 2439, 2696, 2970, 2998, 3192, 3207, 3397, 3666, 4144, 4356, 4442, 4726, 4866, 4907, 4948, 4968, 5064, 5204, 5328, 5700, 5766, 6390, 6449, 6545, 6619, 6796, 6987, 7583, 7737, 7878, 8095, 8948, 10071, 10464, 10496, 11220, 12609, 12650, 12703, 12915, 13149, 13452, 13675, 13925, 13933, 14238, 14279, 14289, 14425, 14519, 14648, 14863, 15441, 15698, 16092, 16504, 16650, 16679, 16729, 16792, 16961, 17029, 17035, 17198, 17234, 17366, 17439, 17757, 18257, 18473, 18539, 18910, 19056, 19189, 19525, 19733, 19940, 19956, 20348], '一汽系': [160, 1688, 3804], '万向系': [830, 1135, 1835, 14068], '三峡集团系': [1948, 13030, 16296, 16315], '三网融合': [1215, 2067, 3004, 3181, 3410, 3615, 3830, 4025, 4163, 4184, 7134, 7140, 8276, 8280, 8326, 9515, 10090, 12734, 12911, 12963, 13371, 13723, 14465, 14514, 14635, 15096, 15891, 16016, 18861], '三聚氰胺': [3731, 13505, 14286], '三胞系': [15296], '上实系': [15646], '上汽系': [12976, 15604, 16044], '上海华谊系': [15027, 15058], '上海国资改革': [15066, 16026, 16064, 18433], '上海地产系': [14971, 15274, 15975], '上海大众系': [15000, 15087], '上海电气系': [5250, 15031, 16025, 17538, 22671], '上海科创中心': [12979, 14660, 15068, 16065, 16279, 17541], '上海自贸': [4533, 9848, 12937, 13162, 14998, 15072, 15095, 15107, 15120, 15142, 15221, 15277, 16071, 17330, 17716, 17742, 18043, 18890, 19349, 19367, 20872, 20892], '不可减持(新': [2, 14, 28, 39, 45, 55, 72, 86, 106, 117, 140, 147, 161, 166, 192, 193, 198, 205, 213, 217, 239, 245, 249, 267, 308, 320, 328, 342, 348, 357, 385, 390, 392, 398, 407, 417, 463, 469, 487, 491, 501, 511, 518, 525, 530, 534, 537, 557, 562, 570, 576, 583, 593, 599, 612, 621, 625, 632, 646, 653, 659, 665, 675, 677, 683, 688, 691, 693, 705, 711, 715, 719, 723, 734, 750, 759, 761, 766, 768, 778, 795, 801, 821, 827, 835, 842, 844, 850, 863, 892, 895, 903, 907, 911, 916, 926, 930, 935, 940, 945, ...], '不活跃股': [21176, 21636, 22081, 22652, 22712], '不锈钢': [1772, 2706, 11548, 20007], '专精特新': [1695, 2422, 2599, 2671, 2682, 2723, 2774, 3248, 3347, 3459, 3481, 3594, 3762, 3797, 4089, 4214, 4253, 4259, 4429, 4506, 5077, 5186, 5203, 5235, 5293, 5343, 5376, 5740, 5947, 5999, 6019, 6155, 6176, 6181, 6194, 6214, 6257, 6274, 6284, 6372, 6408, 6413, 6442, 6454, 6462, 6575, 6748, 6751, 6753, 6778, 6795, 6836, 6837, 6867, 6938, 6951, 6969, 7096, 7360, 7579, 7619, 7628, 7799, 7872, 7877, 7888, 7930, 7949, 7951, 8035, 8069, 8085, 8130, 8194, 8210, 8238, 8316, 8383, 8389, 8415, 8426, 8447, 8507, 8515, 8520, 8524, 8615, 8632, 8654, 8736, 8742, 8796, 8856, 8866, 8930, 8932, 8940, 8947, 8955, 8976, ...], '世界杯': [2080, 4270, 12795], '丙烯': [1746, 15870, 16994], '丙烯酸': [5613, 15869], '丙肝治疗': [22732], '业绩预亏': [21041], '业绩预升': [3480, 8928, 19310, 20138], '业绩预增': [3658, 4762, 4882, 4900, 7960], '东亚自贸': [1001, 3184, 5468, 10413, 12602, 13978, 17157, 17762], '东数西算': [1727, 2160, 2281, 3626, 6424, 7993, 8189, 9081, 9692, 9917, 10598, 10762, 16584, 18097, 21016], '东旭系': [212, 509, 4934], '东湖高新区': [2334, 3617, 4026, 7100, 12878, 13110, 13119, 13964, 14001, 14516], '丝绸': [11273, 13516], '两年新股': [10806, 11591, 11681, 11835, 11862, 11898, 11950, 12070, 12105, 12144, 12170, 12175, 12180, 12211, 12245, 12248, 12267, 12275, 12289, 12297, 12300, 12302, 12307, 12314, 12316, 12321, 12328, 12332, 12339, 12342, 12346, 12352, 12355, 12359, 12363, 12370, 12380, 12384, 12388, 12393, 12400, 12402, 12406, 12422, 12426, 12445, 18262, 18375, 18734, 18742, 18744, 18795, 21772, 22061, 22294, 22298, 22351, 22388, 22451, 22457, 22496, 22503, 22538, 22544, 22590, 22616, 22627, 22635, 22700, 22752, 22790, 22821, 22833], '两轮车': [3213, 8301, 11072, 12950, 15289, 17565, 19167, 19566, 19587, 22932], '中交系': [1481, 7383, 13837, 15501, 17601], '中伊概念': [1053, 13935], '中俄贸易': [2012, 2036, 2820, 4499, 9274, 13323, 13932, 19930, 20160, 20189], '中信系': [368, 1361, 1827, 2374, 10395, 12893, 13696, 16714, 17345, 18020], '中兴通讯概念': [6200], '中兵系': [260, 304, 671, 784, 1094, 3590, 3758, 3869, 3950, 13137, 13272, 13294, 13627, 14303, 14441, 14495, 15373, 16487, 17328, 20985], '中化系': [1328, 13744, 14099, 14407, 14523, 14822], '中华老字号': [548, 738, 754, 879, 982, 1351, 1421, 1865, 1883, 1899, 2338, 3577, 4119, 5602, 6224, 12794, 12854, 12902, 13358, 13545, 13577, 13658, 13752, 13769, 13811, 13868, 13877, 13904, 14039, 14297, 14308, 14609, 14751, 14929, 14940, 15010, 15020, 15075, 15177, 15235, 15291, 15297, 15388, 15798, 16107, 16579, 17285, 18186], '中原经济区': [758, 1043, 2142, 3334, 4566, 4774, 5231, 7466, 12627, 12829, 13800, 14917], '中国信科系': [4023, 9520, 13962, 14513, 21917], ...}

In [721]:
gg.count().sort_values('StockCode')

        StockCode   相关度  StockName
题材
智慧粮仓            1     1          1
指纹识别            1     1          1
控制器             1     1          1
可控核聚变           1     1          1
数字孪生            1     1          1
...           ...   ...        ...
昨日涨停          398   398        398
专精特新          427   427        427
含可转债          528   528        528
昨日首板          537   537        537
不可减持(新       2648  2648       2648

[946 rows x 3 columns]

In [723]:
gg.get_group('5G概念')

      StockCode    题材  相关度 StockName
291      000063  5G概念    4      中兴通讯
2535     001270  5G概念    4      铖昌科技
3614     002194  5G概念    4      武汉凡谷
4022     002281  5G概念    4      光迅科技
4161     002313  5G概念    4      日海智能
4374     002369  5G概念    4      卓翼科技
4769     002446  5G概念    4      盛路通信
4958     002491  5G概念    4      通鼎互联
5158     002544  5G概念    4      普天科技
7133     300025  5G概念    4      华星创业
7261     300050  5G概念    4      世纪鼎利
7714     300134  5G概念    4      大富科技
8452     300292  5G概念    5      吴通控股
8490     300299  5G概念    5      富春股份
8540     300310  5G概念    4      宜通世纪
9575     300570  5G概念    4       太辰光
11642    301191  5G概念    4      菲菱科思
11987    301307  5G概念    4       美利信
12764    600050  5G概念    5      中国联通
13564    600246  5G概念    5      万通发展
13961    600345  5G概念    4      长江通信
14463    600487  5G概念    4      亨通光电
14510    600498  5G概念    4      烽火通信
14633    600522  5G概念    4      中天科技
17734    601869  5G概念    4      长飞光纤
17870    601929  5G概念    5      吉视传媒
18623    603220  5G概念    4      中贝通信
18675    603236  5G概念    4      移远通信
18860    603322  5G概念    4      超讯通信
19265    603602  5G概念    4      纵横通信
19791    603890  5G概念    4      春秋电子
21916    688387  5G概念    4    信科移动-U