In [ ]:
import requests

modls = requests.get("http://10.3.68.3:11434/v1/models").json()['data']

In [ ]:
ls = []
n = 0
while n < len(modls):
    ls.append(modls[n]['id'])
    n = n + 1

In [ ]:
from mootdx.quotes import Quotes

历史财务数据列表的读取

In [ ]:
from mootdx.affair import Affair

Affair.files()

In [ ]:
f10 = ['最新提示','公司概况','财务分析','股本结构','股东研究','机构持股','分红融资','高管治理','资金动向','资本运作','热点题材','公司公告','公司报道','经营分析','行业分析','价值分析',]
stockCode = '000001'

In [ ]:
client = Quotes.factory(market='std')
txt = client.F10(stockCode, f10[1])

In [ ]:
txt[:txt.find('〖免责条款〗')]

In [ ]:
from mootdx.quotes import Quotes
from mootdx.consts import MARKET_SH

client = Quotes.factory(market='ext')
client.bars(frequency=9,market=62,symbol='930740')
# client = Quotes.factory(market='std')
# client.index(frequency=9,symbol='000815')

In [ ]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

In [ ]:
api.connect('121.37.183.82', 7709)

In [ ]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(api.get_index_bars(9, 1, '000001', 0, 1))

In [ ]:
api.to_df(api.get_security_bars(9, 0, '000837', 0, 1))

In [ ]:
eapi.to_df(eapi.get_instrument_bars(9, 62, "H30184", 0, 3))

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [ ]:
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
con = eng.connect()

In [ ]:
con.commit()
con.close()

In [ ]:
l = pd.read_sql('EmpIndex', eng)['IndexCode'].to_list()

In [ ]:

for i in l:
    try:
        con.execute(text('DROP TABLE IF EXISTS "'+i+'";'))
        con.commit()
    except:
        pass

con.close()

In [ ]:
tdxIndex = pd.read_sql('tdxIndexs', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
empIndex['EMP']=1

In [ ]:
df = pd.merge(tdxIndex,empIndex,on='IndexCode',how='outer').drop('index',axis=1)

In [ ]:
df[~(df.EMP==1)].drop('EMP',axis=1)

#===================== 数据分析  ================

In [1]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxFS')

============ FSCode 更新 ================

In [ ]:
df = pd.read_excel('g:/gitee/app/stocksic/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

In [ ]:
df = pd.read_excel('/home/ts/app/StocksIC/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

In [3]:
finRAW = pd.read_sql('600409', eng,)
finRAW['report_date']=finRAW['report_date'].astype(object)

In [4]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
trsfin = finRAW.set_index('Index').T
trsfin = trsfin.reset_index().rename(columns={'index':'Code'})

In [ ]:
trsfin

In [5]:
FSCode = pd.read_sql('FSCode',eng)

In [ ]:
FSCode

In [6]:
sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')

In [ ]:
sfin

In [ ]:
s1 = pd.read_excel('/home/ts/App/StocksIC/ff.xlsx')

In [7]:
day = 20231231
ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']

In [8]:
fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)

In [9]:
items = fin.cnName.to_list()
sumite = [item for item in items if any(substr in item for substr in "万")]
for ite in sumite:
    fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000

In [ ]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [ ]:
zcfz = zcfz[~(zcfz["vol"]==0)].reset_index(drop=True)

In [ ]:
zcfz

In [ ]:
for i,ite in enumerate(zcfz.vol.to_list()):
    if ite < 0:
        zcfz.loc[i,'cnName'] ='负：'+ zcfz.loc[i,'cnName']
        zcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [ ]:
fin.query('L1Code=="LRB"')

In [ ]:
zzcfz = fin.query('L1Code=="ZCFZ" and (L3Code=="HJ" or L3Code=="SSGD")')
zzcfz = zzcfz[~(zzcfz["vol"]==0)].reset_index(drop=True)

In [ ]:
for i,ite in enumerate(zzcfz.vol.to_list()):
    if ite < 0:
        zzcfz.loc[i,'cnName'] ='负：'+ zzcfz.loc[i,'cnName']
        zzcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [ ]:
zzcfz

In [ ]:
import plotly.express as px
# import numpy as np
# df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(zcfz, path=['L2Name','cnName'], values="vol"
# fig = px.pie(ssss, values=0,names='L2Name'
                #   color='lifeExp', hover_data=['iso_alpha'],
                #   color_continuous_scale='RdBu',
                #   color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop']))
)
config = {'scrollZoom': True}
fig.show(config=config)

In [ ]:
s1[sel.Code].loc[92].to_list()

In [ ]:
LDZC = sel[sel.L3Code=='LDZC']
FLDZC = sel[sel.L3Code=='FLDZC']
SYZQY = sel[sel.L3Code=='SYZQY']

In [ ]:

ssss = sss[sss.L1Code=='ZCFZ']

In [ ]:
ssss['voll']=

In [ ]:
s1[LDZC.Code.to_list()].loc[92]

In [ ]:
s1.col21.loc[92]

In [ ]:
from  datetime import date
mon = date.today().strftime('%m')
year = date.today().strftime('%Y')
match mon:
    case mon if mon == '12':
        filename='gpcw'+year+'1231.zip'
    case mon if mon < '03':
        filename='gpcw'+year+'1231.zip'
    case mon if '03'<= mon < '06':
        filename='gpcw'+year+'0331.zip'
    case mon if '06'<= mon < '09':
        filename='gpcw'+year+'0630.zip'
    case mon if '09'<= mon < '12':
        filename='gpcw'+year+'0930.zip'

In [ ]:
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()

In [ ]:
import plotly.graph_objects as go

fig =go.Figure(go.Sunburst(
    labels=sel.cnName.to_list(),
    parents=sel.L3Name.to_list(),
    values=s1[sel.Code].loc[92].to_list(),
))
# Update layout for tight margin
# See https://plotly.com/python/creating-and-updating-figures/
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.show()

In [ ]:
df = px.data.tips()

In [ ]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [ ]:
import plotly.graph_objects as go

config = {'displayModeBar': True,'scrollZoom': True,'displaylogo': True,'modeBarButtonsToAdd':['drawline']}

fig = go.Figure(data=[go.Sankey(
    node = dict(
    thickness = 5,
    label = ["Ads", "Net profit", "Total income", "ROI", "Paid services", "Investment", "Expenses", "Maintaining website", "Paying employes", "Advertising", "Personal expenses", "Savings"],
    color = "cyan"
    ),
    link = dict(

    # indices correspond to labels
    source = [0, 1, 4, 2, 3, 2, 6, 6, 6, 1, 1],
    target = [2, 5, 2, 1, 2, 6, 7, 8, 9, 10, 11],
    value = [60000, 40000, 90000, 100000, 10000, 60000, 10000, 30000, 20000, 20000, 40000]
))])

fig.update_layout(
    title="DatavizWRLD.com monthly income and income management of 2021( in USD )",
    font=dict(size = 12, color = 'black')
)

# fig.update_layout(modebar_remove=[''])
fig.show(config=config)

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(go.Sankey(
    arrangement = "snap",
    node = {
        "label": ["A", "B", "C", "D", "E", "F"],
        "x": [0.2, 0.1, 0.5, 0.7, 0.3, 0.5],
        "y": [0.8, 0.5, 0.2, 0.4, 0.2, 0.3],
        'pad':10},  # 10 Pixels
    link = {
        "source": [0, 0, 1, 2, 5, 4, 3, 5],
        "target": [4, 3, 4, 3, 0, 2, 2, 3],
        "value": [1, 2, 1, 1, 1, 1, 1, 2]}))

fig.show()

In [10]:
node = fin.query('L1Code=="LRB" and L3Code!="EMP"')
node = node[~(node["vol"]==0)].reset_index(drop=True).reset_index()

In [11]:
node

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
0,0,96,LRB,利润表,LR,利润,JLRS,净利润归属,col96,归属于母公司所有者的净利润,565671488.0
1,1,97,LRB,利润表,LR,利润,JLRS,净利润归属,col97,少数股东损益,366530592.0
2,2,205,LRB,利润表,LR,利润,JLRS,扣非净利润,col206,扣除非经常性损益后的净利润,554340032.0
3,3,93,LRB,利润表,LR,利润,SDS,所得税,col93,减：所得税（利润总额）,482443872.0
4,4,92,LRB,利润表,LR,利润,LRZE,总额,col92,利润总额,1414646016.0
5,5,95,LRB,利润表,LR,利润,JLR,净利润,col95,净利润,932202112.0
6,6,275,LRB,利润表,LRY,利润,HJYT,合计,col276,近一年净利润,932202112.0
7,7,282,LRB,利润表,LRY,利润,HJY,合计,col283,近一年营业收入（万元）,21920092500.0
8,8,307,LRB,利润表,LRY,利润,HJY,合计,col308,近一年归母净利润（万元）,565671500.0
9,9,308,LRB,利润表,LRY,利润,HJY,合计,col309,近一年扣非净利润（万元）,554340000.0
10,10,318,LRB,利润表,LR,利润,YYZE,总额,col319,营业总收入TTM(万元),21920092500.0
11,11,86,LRB,利润表,LR,利润,YYLRHJ,合计,col86,营业利润,1432255872.0
12,12,88,LRB,利润表,LR,利润,YYLR,营业利润,col88,加：营业外收入,33917692.0
13,13,89,LRB,利润表,LR,利润,YYLR,营业利润,col89,减：营业外支出,51527616.0
14,14,379,LRB,利润表,CBFY,成本费用,HJ,合计,col519,营业总成本(万元),20524038800.0
15,15,75,LRB,利润表,CBFY,成本费用,CB,成本,col75,营业成本,17460619264.0
16,16,76,LRB,利润表,CBFY,成本费用,CB,成本,col76,营业税金及附加,343417696.0
17,17,77,LRB,利润表,CBFY,成本费用,CB,成本,col77,销售费用,172419792.0
18,18,78,LRB,利润表,CBFY,成本费用,CB,成本,col78,管理费用,1712220544.0
19,19,80,LRB,利润表,CBFY,成本费用,CW,成本,col80,财务费用,239848880.0
20,20,83,LRB,利润表,CBFY,成本费用,TZ,成本,col83,投资收益,744693.88
21,21,84,LRB,利润表,CBFY,成本费用,TZSY,投资收益,col84,对联营企业和合营企业（投资收益）,891456.5
22,22,299,LRB,利润表,CBFY,成本费用,SY,损益,col300,其他收益,57034112.0
23,23,300,LRB,利润表,CBFY,成本费用,CB,成本,col301,资产处置收益,17914048.0
24,24,303,LRB,利润表,CBFY,成本费用,CB,成本,col304,研发费用,595513152.0
25,25,380,LRB,利润表,CBFY,成本费用,SY,损益,col520,信用减值损失(万元、2019格式),-17809500.0
26,26,381,LRB,利润表,CBFY,成本费用,SY,损益,col521,资产减值损失(万元、2019格式),-21680600.0
27,27,304,LRB,利润表,CBFY,成本费用,CWFY,财务费用,col305,利息费用(财务费用),246478560.0
28,28,305,LRB,利润表,CBFY,成本费用,CWFY,财务费用,col306,利息收入(财务费用),58204392.0
29,29,362,LRB,利润表,YYSR,营业收入,HJ,合计,col502,营业总收入(万元),21920092500.0
30,30,74,LRB,利润表,YYSR,营业收入,SR,收入,col74,营业收入,21920092160.0
31,31,269,LRB,利润表,ZHSY,综合收益,ZHSYZE,总额,col270,综合收益总额,933213120.0
32,32,268,LRB,利润表,LR,利润,HJ,合计,col269,其他综合收益(利润表),1011021.19
33,33,364,LRB,利润表,ZHSY,综合收益,GS,归属,col504,归属于母公司所有者（综合收益）(万元),566682500.0
34,34,365,LRB,利润表,ZHSY,综合收益,GS,归属,col505,归属于少数股东（综合收益）(万元),366530600.0

In [13]:
link = pd.DataFrame()

In [14]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and (L3Code=="CB" or L3Code=="CW")')['index']
mid['V'] = node.query('L2Code=="CBFY" and (L3Code=="CB" or L3Code=="CW")')['vol']
mid['T'] = node.query('L2Code=="CBFY" and L3Code=="HJ"').values[0][0]
link = pd.concat([link, mid])

# mid = pd.DataFrame()
# mid['S'] = node.query('L2Code=="CBFY" and L3Code=="CWFY"')['index']
# mid['V'] = node.query('L2Code=="CBFY" and L3Code=="CWFY"')['vol']
# mid['T'] = node.query('L2Code=="CBFY" and L3Code=="CW"').values[0][0]
# link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and L3Code=="TZSY"')['index']
mid['V'] = node.query('L2Code=="CBFY" and L3Code=="TZSY"')['vol']
mid['T'] = node.query('L2Code=="CBFY" and L3Code=="TZ"').values[0][0]
link = pd.concat([link, mid])

In [16]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and L3Code=="JLRS" ')['index']
mid['V'] = node.query('L2Code=="LR" and L3Code=="JLRS" ')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="JLR"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="YYLR" or L3Code=="YYLRHJ")')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="YYLR" or L3Code=="YYLRHJ")')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="YYZE"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="SDS")')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="SDS")')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="LRZE"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="HJ")')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="HJ")')['vol']
mid['T'] = node.query('L3Code=="ZHSYZE"').values[0][0]
link = pd.concat([link, mid])

In [17]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="YYSR" and L3Code=="SR"')['index']
mid['V'] = node.query('L2Code=="YYSR" and L3Code=="SR"')['vol']
mid['T'] = node.query('L2Code=="YYSR" and L3Code=="HJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="ZHSY" and L3Code=="GS"')['index']
mid['V'] = node.query('L2Code=="ZHSY" and L3Code=="GS"')['vol']
mid['T'] = node.query('L2Code=="ZHSY" and L3Code=="ZHSYZE"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LRY" and L3Code=="HJY"')['index']
mid['V'] = node.query('L2Code=="LRY" and L3Code=="HJY"')['vol']
mid['T'] = node.query('L2Code=="LRY" and L3Code=="HJYT"').values[0][0]
link = pd.concat([link, mid])

In [28]:
mid = pd.DataFrame()
mid['S'] = node.query('L3Code=="HJ"')['index']
mid['V'] = node.query('L3Code=="HJ"')['vol']
mid['T'] = node.query('L3Code=="YYLRHJ"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L3Code=="HJ"')['index']
mid['V'] = node.query('L3Code=="HJ"')['vol']
mid['T'] = node.query('L3Code=="YYLRHJ"').values[0][0]
link = pd.concat([link, mid])

In [27]:
node.query('L3Code=="YYLRHJ"')

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
11,11,86,LRB,利润表,LR,利润,YYLRHJ,合计,col86,营业利润,1432255872.0

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXMDJW" and L3Code=="ZJEJJ"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L3Code=="JE"')['index']
mid['V'] = node.query('L3Code=="JE"')['vol']
mid['T'] = node.query('L2Code=="DJW" and L3Code=="ZJE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
link

In [29]:
import plotly.graph_objects as go
# override gray link colors with 'source' colors
# change 'magenta' to its 'rgba' value to add opacity


fig = go.Figure(data=[go.Sankey(

    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  node['cnName'].tolist(),
      # color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  link['S'].tolist(),
      target =  link['T'].tolist(),
      value =  abs(link['V']).tolist(),
      # label =  data['data'][0]['link']['label'],
      # color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Sankey分析<br>"+"Code: "+str(day),
                  font_size=10)
fig.show()

In [ ]:
import plotly.graph_objects as go
import urllib, json

url = 'https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/sankey_energy.json'
response = urllib.request.urlopen(url)
data = json.loads(response.read())

# override gray link colors with 'source' colors
opacity = 0.4
# change 'magenta' to its 'rgba' value to add opacity
data['data'][0]['node']['color'] = ['rgba(255,0,255, 0.8)' if color == "magenta" else color for color in data['data'][0]['node']['color']]
data['data'][0]['link']['color'] = [data['data'][0]['node']['color'][src].replace("0.8", str(opacity))
                                    for src in data['data'][0]['link']['source']]

fig = go.Figure(data=[go.Sankey(
    valueformat = ".0f",
    valuesuffix = "TWh",
    # Define nodes
    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  data['data'][0]['node']['label'],
      color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  data['data'][0]['link']['source'],
      target =  data['data'][0]['link']['target'],
      value =  data['data'][0]['link']['value'],
      label =  data['data'][0]['link']['label'],
      color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Energy forecast for 2050<br>Source: Department of Energy & Climate Change, Tom Counsell via <a href='https://bost.ocks.org/mike/sankey/'>Mike Bostock</a>",
                  font_size=10)
fig.show()

==================   绘制瀑布图 =================

In [ ]:
waterfin = node.query('L3Code=="LRHJ" or L3Code=="LCHJ" or L3Code=="JE" ')

In [ ]:
lis = waterfin.query('L3Code=="LCHJ"').index.tolist()

In [ ]:
for i in lis:
    waterfin.loc[i,'vol'] = -waterfin.loc[i,'vol']

In [ ]:
node

In [ ]:
# addd = waterfin.query('L3Code=="ZJE" or L3Code=="ZJEY"')

In [ ]:
# waterfin = waterfin.drop(waterfin.query('L3Code=="ZJE" or L3Code=="ZJEY"')['index'].tolist())

In [ ]:
# waterfin = pd.concat([waterfin, addd]).head(9)

In [ ]:
x = waterfin.cnName.tolist()
x.append("净流量")
y = waterfin["vol"].tolist()
y.append(0)

In [ ]:
x

In [ ]:
waterfin = pd.concat([waterfin,node.query('L2Code=="HLBD" ')])

In [ ]:

import plotly.graph_objects as go

fig = go.Figure(go.Waterfall(
    x = x,
    measure = ["absolute", "relative", "total", "relative", "relative", "total", "relative", "relative", "total","relative","total"],
    y = y, 
    base = 0,
    decreasing = {"marker":{"color":"Maroon", "line":{"color":"red", "width":2}}},
    increasing = {"marker":{"color":"Teal"}},
    totals = {"marker":{"color":"deep sky blue", "line":{"color":"blue", "width":3}}}
))

fig.update_layout(title = "Profit and loss statement", waterfallgap = 0.3)

fig.show()

=============== Table ======================

In [ ]:

import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
                    cells=dict(values=[[100, 90, 80, 90], [95, 85, 75, 95]]))
                        ])
fig.show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Waterfall(
    x = [["2016", "2017", "2017", "2017", "2017", "2018", "2018", "2018", "2018"],
        ["initial", "q1", "q2", "q3", "total", "q1", "q2", "q3", "total"]],
    measure = ["absolute", "relative", "relative", "relative", "total", "relative", "relative", "relative", "total"],
    y = [1, 2, 3, -1, None, 1, 2, -4, None],
    base = 1000
))

fig.add_trace(go.Waterfall(
    x = [["2016", "2017", "2017", "2017", "2017", "2018", "2018", "2018", "2018"],
        ["initial", "q1", "q2", "q3", "total", "q1", "q2", "q3", "total"]],
    measure = ["absolute", "relative", "relative", "relative", "total", "relative", "relative", "relative", "total"],
    y = [1.1, 2.2, 3.3, -1.1, None, 1.1, 2.2, -4.4, None],
    base = 1000
))

fig.update_layout(
    waterfallgroupgap = 0.5,
)

fig.show()