In [ ]:
import requests

modls = requests.get("http://10.3.68.3:11434/v1/models").json()['data']

In [ ]:
ls = []
n = 0
while n < len(modls):
    ls.append(modls[n]['id'])
    n = n + 1

In [ ]:
from mootdx.quotes import Quotes

In [ ]:
f10 = ['最新提示','公司概况','财务分析','股本结构','股东研究','机构持股','分红融资','高管治理','资金动向','资本运作','热点题材','公司公告','公司报道','经营分析','行业分析','价值分析',]
stockCode = '000001'

In [ ]:
client = Quotes.factory(market='std')
txt = client.F10(stockCode, f10[1])

In [ ]:
txt[:txt.find('〖免责条款〗')]

In [ ]:
from mootdx.quotes import Quotes
from mootdx.consts import MARKET_SH

client = Quotes.factory(market='ext')
client.bars(frequency=9,market=62,symbol='930740')
# client = Quotes.factory(market='std')
# client.index(frequency=9,symbol='000815')

In [37]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

In [60]:
api.connect('121.37.183.82', 7709)

In [51]:
eapi.connect('47.112.95.207', 7720)

In [61]:
api.to_df(api.get_index_bars(9, 1, '000001', 0, 2))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,up_count,down_count
0,2889.360,2860.700,2919.030,2860.700,3555405.0,3.568630e+11,2024,8,5,15,0,2024-08-05 15:00,225,2032
1,2878.651,2867.284,2888.201,2845.335,2973008.0,2.958356e+11,2024,8,6,15,0,2024-08-06 15:00,1991,268

In [58]:
eapi.to_df(eapi.get_instrument_bars(9, 62, "930734", 0, 3))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,13075.683594,13181.006836,12899.637695,12930.977539,1173856690,18,0.0,2024,8,2,15,0,2024-08-02 15:00,7924.211914
1,12865.297852,13033.580078,12481.272461,12481.272461,1174532697,13,0.0,2024,8,5,15,0,2024-08-05 15:00,8316.586914
2,12607.154297,12756.541016,12550.964844,12754.417969,1171161029,12,0.0,2024,8,6,15,0,2024-08-06 15:00,6607.971191