In [ ]:
import plotly
colors = plotly.colors.qualitative.Dark24

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
import streamlit as st

In [ ]:
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxFS')
engB = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')

In [ ]:
FSCode = pd.read_sql('FSCode',eng)

In [ ]:
FSCode[FSCode['L1Code']=='HLNL']

In [ ]:
StockIC = pd.read_sql("StockIC", engB)
StockCode = '600256'
day = 20231231

l4name = StockIC[StockIC['StockCode']==StockCode]['L4Name'].tolist()[0]
StockName = StockIC[StockIC['StockCode']==StockCode]['StockName'].tolist()[0]

In [ ]:
def GetFin(StockCode, day):
    finRAW = pd.read_sql(StockCode, eng)
    finRAW['report_date']=finRAW['report_date'].astype(object)
    finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
    trsfin = finRAW.set_index('Index').T
    trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
    FSCode = pd.read_sql('FSCode',eng)
    sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
    ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']
    fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
    items = fin.cnName.to_list()
    sumite = [item for item in items if any(substr in item for substr in "万")]
    for ite in sumite:
        fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000
    return fin

In [ ]:
finF = pd.read_sql('gpcw'+str(day), eng)
mfin = pd.merge(finF,StockIC, left_on='code',right_on='StockCode', how='inner')
mfinsel = mfin[mfin['L4Name']==l4name]
desel = mfin[mfin['L4Name']==l4name].describe().T
fin = GetFin(StockCode,day)

In [ ]:
tasel = mfinsel[['StockCode','StockName','L1Name','L2Name','L3Name','L4Name']]

In [ ]:
ll = ['StockCode','StockName']

In [ ]:
anafin = fin.query('L1Code=="FZNL" and L3Code!="EMP"')

In [ ]:
ta = mfinsel[ll + anafin.Code.tolist()].reset_index(drop=True)

In [ ]:
ta = ta.rename(columns=dict(zip(ta.columns,(ll+anafin.cnName.tolist()))))

In [ ]:
data = pd.merge(anafin, desel.reset_index(drop=False),left_on='Code',right_on='index',how='inner')

lens = (max(data['mean'])-min(data['mean']))/2

In [ ]:
list(data['vol'])

# ================== BarPolar Chart

In [ ]:
import plotly.graph_objects as go
categories = data.cnName.tolist()

fig3 = go.Figure()

fig3.add_trace(go.Barpolar(
    r=list(data['mean']),
    theta=categories,
    name='行业均值',
    marker_color='rgb(106,81,163)',
    base='stack'
))
fig3.add_trace(go.Barpolar(
    r=list(data['vol']),
    theta=categories,
    name=StockName,
    marker_color='rgb(158,100,100)',
    base='stack'
))
fig3.add_trace(go.Barpolar(
    r=list(ta.loc[0])[3:],
    theta=categories,
    name=list(ta.loc[0])[1],
    marker_color='rgb(158,154,200)',
    base='stack'
))
fig3.add_trace(go.Barpolar(
    r=list(ta.loc[2])[3:],
    theta=categories,
    name=list(ta.loc[2])[1],
    marker_color=colors[1],

    base='stack'
))

# fig.update_traces(text=list(data['cnName']))
fig3.update_layout(
    # title='Wind Speed Distribution in Laurel, NE',
    font_size=12,
    legend_font_size=16,

    # polar_radialaxis_ticksuffix='%',
    # polar_angularaxis_rotation=90,

)
fig3.show()

In [ ]:
ta_sort = ta.drop(index=ta[ta['StockCode']==StockCode].index).sort_values('扣非每股收益同比(%)',ascending=False)

In [ ]:
fta = pd.concat([ta_sort.head(8),ta_sort.tail(2)]).drop_duplicates(subset='StockCode').reset_index(drop=True)

In [ ]:
ta

In [ ]:
import plotly.graph_objects as go
categories = data.cnName.tolist()

fig3 = go.Figure()

fig3.add_trace(go.Barpolar(
    r=list(data['mean']),
    theta=categories,
    name='行业均值',
    marker_color='rgb(106,81,163)',
    # base='stack'
))
fig3.add_trace(go.Barpolar(
    r=list(data['vol']),
    theta=categories,
    name=StockName,
    marker_color='rgb(158,100,100)',
    # base='stack'
))
i = 0
while i<len(fta):
    fig3.add_trace(go.Barpolar(
        r=list(fta.loc[i])[3:],
        theta=categories,
        name=list(fta.loc[i])[1],
        marker_color=colors[i],
        visible='legendonly',
        # opacity=0.5
        # base='overlay'
    ))
    i = i+1

# fig.update_traces(text=list(data['cnName']))
fig3.update_layout(
    # title='Wind Speed Distribution in Laurel, NE',
    activeshape_opacity=0.2,
    font_size=12,
    legend_font_size=16,
    legend_title='tee',
    # legend_itemclick='toggleothers',


    # legend_visible=False,
    # showlegend=False,
    # legend_activeselection=False,
    

    # polar_radialaxis_ticksuffix='%',
    # polar_angularaxis_rotation=90,

)
fig3.show()

In [ ]:
len(ta)

#================ Table Chart =============

In [ ]:
fig = go.Figure(data=[go.Table(
    header=dict(values=list(ta.columns),
                line_color='darkslategray',
                fill_color='lightskyblue',
                align='left'),
    cells=dict(values=list(round(ta,2).values.T),
                line_color='darkslategray',
                fill_color='lightcyan',
                align='left'))
])

fig.show()

In [ ]:
'-'.join(list(tasel.head(1).values[0][2:]))

In [ ]:
ta.round(2)

In [ ]:
fig = go.Figure(data=[go.Table(
        header=dict(values=list(ta.columns),fill_color='lightskyblue',),
        cells=dict(values=list(ta.values),fill_color='lightcyan'))
                        ])
fig.show()

In [ ]:
dict(values=list(ta.values))

      default_templates = [
            "ggplot2",
            "seaborn",
            "simple_white",
            "plotly",
            "plotly_white",
            "plotly_dark",
            "presentation",
            "xgridoff",
            "ygridoff",
            "gridon",
            "none",
        ]

In [ ]:
import plotly.express as px
df = px.data.wind()
fig = px.bar_polar(df, r="frequency", theta="direction",
                   color="strength", template="seaborn",
                   color_discrete_sequence= px.colors.sequential.Plasma_r)
fig.show()

In [ ]:
import plotly.express as px

import plotly.graph_objects as go 

r = [4, 6, 5, 3, 7, 8, 2, 9]

# 使用 'Viridis' 颜色方案
colors = px.colors.sequential.Viridis

# 创建BarPolar图表
fig = go.Figure()

for i in range(len(r)):
    fig.add_trace(go.Barpolar(
        r=[r[i]],
        theta=[r[i]],
        marker=dict(color=colors[i])
    ))

# 更新图表的布局（可选）
fig.update_layout(polar=dict(radialaxis=dict(visible=False),
                             angularaxis=dict(showticklabels=True)))

# 显示图表
fig.show()

In [ ]:
import plotly.graph_objects as go
import plotly.express as px

# 使用 'Viridis' 颜色方案
colors = px.colors.qualitative.Dark24

# 准备数据
theta = [0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]
r = [16, 5, 11, 9, 10, 14, 6, 4, 1, 2, 15, 12]

# 创建极坐标条形图
fig = go.Figure(go.Barpolar(
    r=r,
    theta=theta,
    marker=dict(color=colors[23])  # 使用 'Viridis' 颜色方案
))

# 设定图表的布局（可选）
fig.update_layout(polar=dict(radialaxis=dict(visible=False),
                             angularaxis=dict(showticklabels=True)))

# 显示图表
fig.show()

In [ ]:
import plotly.graph_objects as go
import plotly.express as px

# 使用 'Viridis' 颜色方案
colors = px.colors.qualitative.Dark24

# 创建一些示例数据，每个值对应一个不同的颜色索引
data = [1, 2, 3, 4]

fig = go.Figure()

# 使用colorscale属性设置颜色序列
for i in range(len(data)):
    fig.add_trace(go.Scatter(x=[i], y=[data[i]],
                             mode='markers',
                             name=f'Data {i}',
                             marker=dict(color=colors[i],size=12)))

fig.show()

##=========== bar chat

In [ ]:
list(ta.loc[0])[2:]

In [ ]:
list(ta.columns)[2:]

In [ ]:
aa = ta.min()

In [ ]:
tamin = ta.describe().min().min().round(0)

In [156]:
ta

,StockCode,StockName,营业收入增长率(%),净利润增长率(%),净资产增长率(%),固定资产增长率(%),总资产增长率(%),投资收益增长率(%),营业利润增长率(%),扣非每股收益同比(%),扣非净利润同比(%)
0,000096,广聚能源,21.549999,59.869999,5.215,-8.544000,6.306,585.322998,52.919998,54.650002,53.790001
1,000159,国际实业,180.149994,-72.870003,-3.386,33.619999,20.219,-98.922997,-73.790001,159.970001,160.059998
2,000554,泰山石油,18.610001,199.720001,2.717,3.750000,-9.796,-2223.103027,98.419998,132.559998,143.149994
3,001331,胜通能源,-6.850000,-122.980003,-5.130,-30.427000,0.281,-143.554001,-122.410004,-117.879997,-131.100006
4,002221,东华能源,-7.110000,255.220001,3.060,3.748000,1.545,88.823997,800.250000,507.140015,506.920013
5,600256,广汇能源,3.480000,-54.369999,0.341,-3.157000,-4.912,-139.298996,-48.330002,-49.490002,-49.950001
6,600387,*ST海越,-67.699997,-538.010010,-7.915,-10.019000,-2.489,-66.428001,-408.260010,-610.000000,-613.719971
7,603223,恒通股份,-28.719999,13.350000,2.527,-11.239000,11.366,-65.028000,20.469999,0.000000,61.779999
8,603353,和顺石油,-18.040001,-49.660000,-2.117,-0.471000,-4.564,-40.012001,-50.840000,-48.000000,-48.259998
9,834014,特瑞斯,2.010000,-5.690000,3.011,91.505997,-1.227,2014.677979,-6.920000,-42.470001,-3.840000

In [132]:
Tta

,index,0,1,2,3,4,5,6,7,8,9
0,StockCode,000096,000159,000554,001331,002221,600256,600387,603223,603353,834014
1,StockName,广聚能源,国际实业,泰山石油,胜通能源,东华能源,广汇能源,*ST海越,恒通股份,和顺石油,特瑞斯
2,营业收入增长率(%),21.549999,180.149994,18.610001,-6.85,-7.11,3.48,-67.699997,-28.719999,-18.040001,2.01
3,净利润增长率(%),59.869999,-72.870003,199.720001,-122.980003,255.220001,-54.369999,-538.01001,13.35,-49.66,-5.69
4,净资产增长率(%),5.215,-3.386,2.717,-5.13,3.06,0.341,-7.915,2.527,-2.117,3.011
5,固定资产增长率(%),-8.544,33.619999,3.75,-30.427,3.748,-3.157,-10.019,-11.239,-0.471,91.505997
6,总资产增长率(%),6.306,20.219,-9.796,0.281,1.545,-4.912,-2.489,11.366,-4.564,-1.227
7,投资收益增长率(%),585.322998,-98.922997,-2223.103027,-143.554001,88.823997,-139.298996,-66.428001,-65.028,-40.012001,2014.677979
8,营业利润增长率(%),52.919998,-73.790001,98.419998,-122.410004,800.25,-48.330002,-408.26001,20.469999,-50.84,-6.92
9,扣非每股收益同比(%),54.650002,159.970001,132.559998,-117.879997,507.140015,-49.490002,-610.0,0.0,-48.0,-42.470001
10,扣非净利润同比(%),53.790001,160.059998,143.149994,-131.100006,506.920013,-49.950001,-613.719971,61.779999,-48.259998,-3.84

In [131]:
Tta = ta.T.reset_index()

In [149]:
list(Tta.loc[1])[1:]

['广聚能源',
 '国际实业',
 '泰山石油',
 '胜通能源',
 '东华能源',
 '广汇能源',
 '*ST海越',
 '恒通股份',
 '和顺石油',
 '特瑞斯']

In [168]:
data

,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol,index,count,mean,std,min,25%,50%,75%,max
0,183,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col183,营业收入增长率(%),3.48,col183,10.0,9.738000,65.118408,-67.699997,-15.307501,-2.420000,14.827500,180.149994
1,184,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col184,净利润增长率(%),-54.37,col184,10.0,-31.542001,214.523365,-538.010010,-68.245002,-27.675000,48.239999,255.220001
2,185,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col185,净资产增长率(%),0.34,col185,10.0,-0.167700,4.270566,-7.915000,-3.068750,1.434000,2.937500,5.215000
3,186,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col186,固定资产增长率(%),-3.16,col186,10.0,6.876700,33.820701,-30.427000,-9.650250,-1.814000,3.749500,91.505997
4,187,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col187,总资产增长率(%),-4.91,col187,10.0,1.672900,8.824585,-9.796000,-4.045250,-0.473000,5.115750,20.219000
5,188,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col188,投资收益增长率(%),-139.3,col188,10.0,-8.752205,1022.571982,-2223.103027,-129.204996,-65.728001,56.614998,2014.677979
6,189,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col189,营业利润增长率(%),-48.33,col189,10.0,26.150998,305.239641,-408.260010,-68.052501,-27.625001,44.807498,800.250000
7,190,FZNL,发展能力分析,MGZB,每股指标,FZNL,发展能力分析,col190,扣非每股收益同比(%),-49.49,col190,10.0,-1.351999,278.063651,-610.000000,-49.117501,-21.235001,113.082499,507.140015
8,191,FZNL,发展能力分析,FZNL,发展能力分析,FZNL,发展能力分析,col191,扣非净利润同比(%),-49.95,col191,10.0,7.883003,280.445267,-613.719971,-49.527500,24.975001,122.807495,506.920013

In [170]:
list(data.loc[0])[12]

9.737999653816223

In [199]:
import plotly.graph_objects as go

fig = go.Figure()
# fig.add_trace(go.Bar(
#     name='行业均值', 
#     x=list(data['cnName']), 
#     # y=list(ta.loc[i])[2:]+abs(tamin)+8,
#     y=list(data['mean']),
#     # visible='legendonly', 
#     marker=dict(color='rgb(0,152,255)')
# ))
# fig.add_trace(go.Bar(
#     name=StockName, 
#     x=list(data['cnName']), 
#     # y=list(ta.loc[i])[2:]+abs(tamin)+8,
#     y=list(data['vol']),
#     # visible='legendonly', 
#     marker=dict(color='rgb(251,106,78)')
# ))

i =2 
while i<len(ta):
    fig.add_trace(go.Bar(
        name=list(Tta.loc[i])[0], 
        x=list(Tta.loc[1])[1:], 
        # y=list(ta.loc[i])[2:]+abs(tamin)+8,
        y=list(Tta.loc[i])[1:],
        legendgroup="group"+str(i),
        # visible='legendonly', 
        marker=dict(color=colors[i])
    ))
    
    fig.add_trace(go.Scatter(
        legendgroup="group"+str(i),
        mode='lines',
        showlegend=False,
        visible='legendonly',
        marker_color='red',
        x=[list(Tta.loc[1])[1],list(Tta.loc[1])[-1]],
        y=[list(data.loc[i-2])[12],list(data.loc[i-2])[12]]
    ))

    i = i+1 
# i =0 
# while i<len(ta):
#     fig.add_trace(go.Bar(
#         name=list(ta.loc[i])[1], 
#         x=list(ta.columns)[2:], 
#         # y=list(ta.loc[i])[2:]+abs(tamin)+8,
#         y=list(ta.loc[i])[2:],
#         visible='legendonly', 
#         marker=dict(color=colors[i])
#     ))
#     i = i+1 
# fig.add_trace(go.Bar(name=list(ta.loc[1])[1], x=list(ta.columns)[2:], y=list(ta.loc[1])[2:],visible='legendonly', marker=dict(color=colors[1])))
# fig.add_trace(go.Bar(name=list(ta.loc[2])[1], x=list(ta.columns)[2:], y=list(ta.loc[2])[2:], marker=dict(color=colors[2])))
# # fig.add_trace(go.Bar(name="second", x=["a", "b"], y=[2,1]))
# # fig.add_trace(go.Bar(name="third", x=["a", "b"], y=[1,2]))
# # fig.add_trace(go.Bar(name="fourth", x=["a", "b"], y=[2,1]))
# fig.update_layout(barmode='overlay')
# fig.update_yaxes(type='log')
# fig.update_yaxes(rangemode="normal")
# fig.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='LightPink')
fig.update_layout(yaxis_tickformat=',d',legend_itemclick='toggleothers',)
fig.show()