In [1]:
import pandas as pd
from sqlalchemy import create_engine

#eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
#engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')


eng = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/tdxFS')
engB = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/StockBas')
StockIC = pd.read_sql("StockIC", engB)

In [2]:
def GetFin(StockCode, day):
    finRAW = pd.read_sql(StockCode, eng)
    finRAW['report_date']=finRAW['report_date'].astype(object)
    finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
    trsfin = finRAW.set_index('Index').T
    trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
    FSCode = pd.read_sql('FSCode',eng)
    sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
    ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']
    fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
    items = fin.cnName.to_list()
    sumite = [item for item in items if any(substr in item for substr in "万")]
    for ite in sumite:
        fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000
    return fin

In [3]:
StockCode = '002202'
finRAW = pd.read_sql(StockCode, eng)
wCode = pd.read_sql('wCode',eng)
StockName = StockIC[StockIC['StockCode']==StockCode]['StockName'].tolist()[0]

In [4]:
df1 = finRAW[wCode['Code']]*10000

In [5]:
len(finRAW.columns)-90

492

In [6]:
finRAW[list(set(finRAW.columns).difference(set(wCode['Code'])))]

,col259,col161,col103,col354,col174,col5,col146,col243,col63,col458,...,col10,col284,col488,col464,col172,col260,col11,col110,col466,col355
0,0.0,77.90,7.685126e+06,0.0,0.00,0.15,-1.630499e+07,0.0,1.569976e+08,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,2.544511e+07,0.00,0.0,0.0
1,0.0,132.66,1.197952e+07,0.0,2.33,1.36,-5.829481e+07,0.0,2.612048e+08,0.0,...,0.0,0.00,0.0,0.0,8.58,0.0,9.243082e+07,2618333.25,0.0,0.0
2,0.0,68.73,3.043274e+07,0.0,3.55,1.51,-1.859592e+08,0.0,5.990184e+08,0.0,...,0.0,0.00,0.0,0.0,8.23,0.0,2.793599e+08,406137.06,0.0,0.0
3,0.0,34.50,6.026597e+07,0.0,0.98,0.05,-7.417558e+08,0.0,1.637696e+09,0.0,...,0.0,0.00,0.0,0.0,2.29,0.0,2.208590e+08,710.42,0.0,0.0
4,0.0,19.41,6.245883e+07,0.0,1.30,0.05,-4.695437e+08,0.0,2.516624e+09,0.0,...,0.0,0.00,0.0,0.0,2.48,0.0,2.807845e+08,2351.80,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0.0,18.49,1.287120e+09,0.0,2.66,2.88,0.000000e+00,772283968.0,1.014645e+11,0.0,...,0.0,2986.27,0.0,0.0,0.28,0.0,2.510850e+10,14365862.00,0.0,0.0
71,0.0,14.19,2.179002e+09,0.0,7.78,2.88,-3.911544e+09,772278144.0,1.035206e+11,0.0,...,0.0,2986.27,0.0,0.0,0.76,0.0,2.778751e+10,32901018.00,0.0,0.0
72,0.0,15.51,3.118655e+09,0.0,18.66,2.88,0.000000e+00,772292992.0,1.152365e+11,0.0,...,0.0,2986.27,0.0,0.0,1.26,0.0,3.143563e+10,45574544.00,0.0,0.0
73,0.0,16.17,4.269560e+09,0.0,-46.04,2.85,3.872749e+08,772313088.0,1.147972e+11,0.0,...,0.0,2962.69,0.0,0.0,2.01,0.0,3.082547e+10,17770366.00,0.0,0.0
74,0.0,19.25,1.353025e+09,0.0,-10.62,2.86,0.000000e+00,772489536.0,1.161587e+11,0.0,...,0.0,2962.69,0.0,0.0,0.31,0.0,3.123628e+10,14066010.00,0.0,0.0

In [9]:
finRAW.columns

Index(['report_date', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7',
       'col8', 'col9',
       ...
       'col572', 'col573', 'col574', 'col575', 'col576', 'col577', 'col578',
       'col579', 'col580', 'col581'],
      dtype='object', length=582)

In [7]:
finRAW.loc[:, finRAW.columns == list(wCode['Code'])]

ValueError: ('Shapes must match', (582,), (89,))

In [12]:
finRAW = pd.read_sql(StockCode, eng)
finRAW['report_date']=finRAW['report_date'].astype(object)

In [13]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)

In [14]:
finRAW.set_index('Index').T

Index,20041231,20051231,20061231,20070630,20070930,20071231,20080331,20080630,20080930,20081231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
report_date,20041231,20051231,20061231,20070630,20070930,20071231,20080331,20080630,20080930,20081231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
col1,1.31,1.6,3.2,0.29,0.27,1.4,0.08,0.15,0.23,0.65,...,0.52,0.29,0.28,0.28,0.29,0.07,0.32,0.41,0.42,0.13
col2,1.15,1.55,0.0,0.28,0.26,1.36,0.0,0.14,0.0,0.64,...,0.43,0.25,0.23,0.24,0.28,0.08,0.32,0.42,0.4,0.13
col3,0.52,0.96,2.89,0.27,0.28,1.15,0.15,0.22,0.3,0.91,...,4.01,4.29,4.17,4.17,4.15,4.22,4.37,4.46,4.46,4.59
col4,1.82,3.6,6.0,1.4,1.38,5.77,2.91,2.98,3.05,3.72,...,8.31,8.6,8.41,8.41,8.42,8.48,8.64,8.69,8.65,8.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
col577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,130750.31,4467.15,15613.67,17345.82,20702.45,490.8,4055.03,15650.58,19345.18,173823.52
col578,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1207.01,4064.9,4174.32,4802.93,12625.26,0.0,1055.69,6035.01,9996.92,0.0
col579,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.66,0.0,13.83,0.0,27.66,0.0,13.83,0.0,27.66,0.0
col580,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-30421.07,0.0,17888.14,0.0,26217.83,0.0,12598.86,0.0,29076.94,0.0
col581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20069.72,0.0,9767.33,0.0,18361.19,0.0,8229.32,0.0,15741.67,0.0

In [15]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
trsfin = finRAW.set_index('Index').T
trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
FSCode = pd.read_sql('FSCode',eng)
sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
# ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']

In [16]:
sfin

,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,"(20041231, 20041231)",...,"(20221231, 20221231)","(20230331, 20230331)","(20230630, 20230630)","(20230930, 20230930)","(20231231, 20231231)","(20240331, 20240331)","(20240630, 20240630)","(20240930, 20240930)","(20241231, 20241231)","(20250331, 20250331)"
0,0,PD,公告日期,PD,公告日期,PD,公告日期,report_date,日期,20041231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
1,1,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col1,基本每股收益,1.31,...,0.52,0.29,0.28,0.28,0.29,0.07,0.32,0.41,0.42,0.13
2,2,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col2,扣除非经常性损益每股收益,1.15,...,0.43,0.25,0.23,0.24,0.28,0.08,0.32,0.42,0.4,0.13
3,3,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col3,每股未分配利润,0.52,...,4.01,4.29,4.17,4.17,4.15,4.22,4.37,4.46,4.46,4.59
4,4,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col4,每股净资产,1.82,...,8.31,8.6,8.41,8.41,8.42,8.48,8.64,8.69,8.65,8.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,398,XJLL,现金流量表,CZHD,筹资活动,LR,流入,col577,子公司吸收少数股东投资收到的现金（吸收投资）(万元),0.0,...,130750.31,4467.15,15613.67,17345.82,20702.45,490.8,4055.03,15650.58,19345.18,173823.52
399,399,XJLL,现金流量表,CZHD,筹资活动,LC,流出,col578,子公司支付给少数股东的股利、利润（分配股利）(万元),0.0,...,1207.01,4064.9,4174.32,4802.93,12625.26,0.0,1055.69,6035.01,9996.92,0.0
400,400,XJLL,现金流量表,EMP,EMP,EMP,EMP,col579,投资性房地产的折旧及摊销(万元),0.0,...,27.66,0.0,13.83,0.0,27.66,0.0,13.83,0.0,27.66,0.0
401,401,XJLL,现金流量表,BCXM,补充项目,LC,流出,col580,信用减值损失(万元)（现金流）,0.0,...,-30421.07,0.0,17888.14,0.0,26217.83,0.0,12598.86,0.0,29076.94,0.0
402,402,XJLL,现金流量表,BCXM,补充项目,LC,流出,col581,使用权资产折旧/摊销（万元）,0.0,...,20069.72,0.0,9767.33,0.0,18361.19,0.0,8229.32,0.0,15741.67,0.0

In [17]:
# fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
items = sfin.cnName.to_list()
sumite = [item for item in items if any(substr in item for substr in "万")]
for ite in sumite:
    sfin.loc[sfin.cnName==ite,"vol"] = sfin[sfin.cnName==ite]["vol"]*10000

KeyError: 'vol'

In [18]:
len(sumite)

90