In [5]:
import pandas as pd
from sqlalchemy import create_engine

#eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
#engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')


eng = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/tdxFS')
engB = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/StockBas')
StockIC = pd.read_sql("StockIC", engB)

In [6]:
def GetFin(StockCode, day):
    finRAW = pd.read_sql(StockCode, eng)
    finRAW['report_date']=finRAW['report_date'].astype(object)
    finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
    trsfin = finRAW.set_index('Index').T
    trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
    FSCode = pd.read_sql('FSCode',eng)
    sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
    ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']
    fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
    items = fin.cnName.to_list()
    sumite = [item for item in items if any(substr in item for substr in "万")]
    for ite in sumite:
        fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000
    return fin

In [7]:
StockCode = '002202'
finRAW = pd.read_sql(StockCode, eng)
wCode = pd.read_sql('wCode',eng)
StockName = StockIC[StockIC['StockCode']==StockCode]['StockName'].tolist()[0]

In [8]:
df1 = finRAW[wCode['Code']]*10000

In [9]:
len(finRAW.columns)-90

492

In [10]:
finRAW[list(set(finRAW.columns).difference(set(wCode['Code'])))]

,col180,col245,col54,col325,col56,col476,col171,col291,col465,col117,...,col153,col395,col36,col68,col159,col257,col172,col47,col293,col461
0,0.0,0.000000e+00,1.293956e+08,0.0,0.0,0.0,30.63,0.0,0.0,0.0,...,0.0,0.0,0.000000e+00,3.606878e+07,1.80,0.0,0.00,8.466696e+06,0.0,0.0
1,282.0,0.000000e+00,2.282427e+08,0.0,0.0,0.0,45.51,0.0,0.0,0.0,...,0.0,0.0,0.000000e+00,9.600217e+07,2.45,0.0,8.58,-1.187767e+06,0.0,0.0
2,188.0,0.000000e+00,5.068501e+08,0.0,0.0,0.0,55.86,0.0,0.0,0.0,...,0.0,0.0,4.291770e+05,2.893047e+08,2.05,0.0,8.23,3.475874e+07,0.0,0.0
3,487.0,0.000000e+00,1.422915e+09,0.0,0.0,0.0,8.47,0.0,0.0,3369697.5,...,0.0,0.0,0.000000e+00,1.216865e+08,1.45,0.0,2.29,-3.018161e+07,0.0,0.0
4,748.0,0.000000e+00,2.280138e+09,0.0,0.0,0.0,5.43,0.0,0.0,0.0,...,0.0,0.0,0.000000e+00,1.260614e+08,1.24,0.0,2.48,-9.370109e+07,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,819.0,2.436921e+09,5.872441e+10,1.0,0.0,0.0,0.00,0.0,0.0,151517104.0,...,0.0,0.0,8.527651e+07,1.784739e+10,1.08,84122272.0,0.28,1.183905e+09,0.0,0.0
71,570.0,2.445876e+09,5.966391e+10,1.0,0.0,0.0,3.74,0.0,0.0,196247104.0,...,0.0,0.0,8.616624e+07,1.847357e+10,1.07,63843136.0,0.76,1.209708e+09,0.0,0.0
72,517.0,2.496921e+09,7.047467e+10,1.0,0.0,0.0,0.00,0.0,0.0,199649824.0,...,0.0,0.0,1.079955e+08,1.885996e+10,1.04,52420040.0,1.26,1.855143e+09,0.0,0.0
73,420.0,2.476130e+09,7.187394e+10,1.0,0.0,0.0,5.60,0.0,0.0,843929344.0,...,0.0,0.0,2.018427e+08,1.883925e+10,0.95,52420040.0,2.01,1.997869e+09,0.0,0.0
74,676.0,2.382857e+09,7.228909e+10,1.0,0.0,0.0,0.00,0.0,0.0,37261700.0,...,0.0,0.0,3.619003e+08,1.938254e+10,1.02,29088560.0,0.31,2.034905e+09,0.0,0.0

In [11]:
finRAW.loc[:, finRAW.columns == list(wCode['Code'])]

ValueError: ('Shapes must match', (582,), (89,))

In [12]:
finRAW = pd.read_sql(StockCode, eng)
finRAW['report_date']=finRAW['report_date'].astype(object)

In [13]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)

In [14]:
finRAW.set_index('Index').T

Index,20041231,20051231,20061231,20070630,20070930,20071231,20080331,20080630,20080930,20081231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
report_date,20041231,20051231,20061231,20070630,20070930,20071231,20080331,20080630,20080930,20081231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
col1,1.31,1.6,3.2,0.29,0.27,1.4,0.08,0.15,0.23,0.65,...,0.52,0.29,0.28,0.28,0.29,0.07,0.32,0.41,0.42,0.13
col2,1.15,1.55,0.0,0.28,0.26,1.36,0.0,0.14,0.0,0.64,...,0.43,0.25,0.23,0.24,0.28,0.08,0.32,0.42,0.4,0.13
col3,0.52,0.96,2.89,0.27,0.28,1.15,0.15,0.22,0.3,0.91,...,4.01,4.29,4.17,4.17,4.15,4.22,4.37,4.46,4.46,4.59
col4,1.82,3.6,6.0,1.4,1.38,5.77,2.91,2.98,3.05,3.72,...,8.31,8.6,8.41,8.41,8.42,8.48,8.64,8.69,8.65,8.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
col577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,130750.31,4467.15,15613.67,17345.82,20702.45,490.8,4055.03,15650.58,19345.18,173823.52
col578,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1207.01,4064.9,4174.32,4802.93,12625.26,0.0,1055.69,6035.01,9996.92,0.0
col579,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.66,0.0,13.83,0.0,27.66,0.0,13.83,0.0,27.66,0.0
col580,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-30421.07,0.0,17888.14,0.0,26217.83,0.0,12598.86,0.0,29076.94,0.0
col581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20069.72,0.0,9767.33,0.0,18361.19,0.0,8229.32,0.0,15741.67,0.0

In [15]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
trsfin = finRAW.set_index('Index').T
trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
FSCode = pd.read_sql('FSCode',eng)
sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
# ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']

In [16]:
sfin

,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,"(20041231, 20041231)",...,"(20221231, 20221231)","(20230331, 20230331)","(20230630, 20230630)","(20230930, 20230930)","(20231231, 20231231)","(20240331, 20240331)","(20240630, 20240630)","(20240930, 20240930)","(20241231, 20241231)","(20250331, 20250331)"
0,0,PD,公告日期,PD,公告日期,PD,公告日期,report_date,日期,20041231,...,20221231,20230331,20230630,20230930,20231231,20240331,20240630,20240930,20241231,20250331
1,1,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col1,基本每股收益,1.31,...,0.52,0.29,0.28,0.28,0.29,0.07,0.32,0.41,0.42,0.13
2,2,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col2,扣除非经常性损益每股收益,1.15,...,0.43,0.25,0.23,0.24,0.28,0.08,0.32,0.42,0.4,0.13
3,3,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col3,每股未分配利润,0.52,...,4.01,4.29,4.17,4.17,4.15,4.22,4.37,4.46,4.46,4.59
4,4,MGZB,每股指标,MGZB,每股指标,MGZB,每股指标,col4,每股净资产,1.82,...,8.31,8.6,8.41,8.41,8.42,8.48,8.64,8.69,8.65,8.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,398,XJLL,现金流量表,CZHD,筹资活动,LR,流入,col577,子公司吸收少数股东投资收到的现金（吸收投资）(万元),0.0,...,130750.31,4467.15,15613.67,17345.82,20702.45,490.8,4055.03,15650.58,19345.18,173823.52
399,399,XJLL,现金流量表,CZHD,筹资活动,LC,流出,col578,子公司支付给少数股东的股利、利润（分配股利）(万元),0.0,...,1207.01,4064.9,4174.32,4802.93,12625.26,0.0,1055.69,6035.01,9996.92,0.0
400,400,XJLL,现金流量表,EMP,EMP,EMP,EMP,col579,投资性房地产的折旧及摊销(万元),0.0,...,27.66,0.0,13.83,0.0,27.66,0.0,13.83,0.0,27.66,0.0
401,401,XJLL,现金流量表,BCXM,补充项目,LC,流出,col580,信用减值损失(万元)（现金流）,0.0,...,-30421.07,0.0,17888.14,0.0,26217.83,0.0,12598.86,0.0,29076.94,0.0
402,402,XJLL,现金流量表,BCXM,补充项目,LC,流出,col581,使用权资产折旧/摊销（万元）,0.0,...,20069.72,0.0,9767.33,0.0,18361.19,0.0,8229.32,0.0,15741.67,0.0

In [17]:
# fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
items = sfin.cnName.to_list()
sumite = [item for item in items if any(substr in item for substr in "万")]
for ite in sumite:
    sfin.loc[sfin.cnName==ite,"vol"] = sfin[sfin.cnName==ite]["vol"]*10000

KeyError: 'vol'

In [18]:
len(sumite)

90