In [18]:
from sqlalchemy import create_engine
import pandas as pd

In [33]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxIndex')
engT = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxStocks')
IndexLists = pd.read_sql('optIndexs', eng).IndexCode.to_list()

In [46]:
D = pd.read_sql('IndexCons',eng)
d = pd.DataFrame(columns=['code','PCB']).astype(dtype={'PCB':float})
Data = D.loc[D['IndexCode']== Code].reset_index(drop=True)
StockLists = Data[['StockCode','StockName']].values.tolist()

In [53]:
df = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [56]:
DD = pd.read_sql(StockLists[0][0], engT)

In [58]:
dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [69]:
dd['StockCode'] = StockLists[0][0]

In [67]:
dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]

In [70]:
dd

  StockCode StockName   3D  5D  21D  55D
0    002967       NaN -4.7 NaN  NaN  NaN

In [ ]:
for Stock in StockLists:
    try:
        DD = pd.read_sql(Stock[0], engT)
        dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})
        dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]
        dd['5D'] = [(DD.close.pct_change(1)*100).tail(5).sum().round(2)]
        dd['21D'] = [(DD.close.pct_change(1)*100).tail(21).sum().round(2)]
        dd['55D'] = [(DD.close.pct_change(1)*100).tail(55).sum().round(2)]
        dd['StockCode'] = Stock[0] 
        dd['StockName'] = Stock[1]
        dd.reset_index(drop=True, inplace =True)
        # d = d.append(dd[['code','PCB']])
        df = pd.concat([df, dd])
    except:
        pass

In [52]:
df

  StockCode StockName     3D     5D    21D    55D
0       NaN       NaN  -4.70  -5.19   9.12  36.07
0       NaN       NaN  -5.08  -4.97  -2.32  12.04
0       NaN       NaN  -9.16  -9.74  -7.55  26.37
0       NaN       NaN  -8.89  -9.62   5.98  29.76
0       NaN       NaN  -9.77 -13.07  -0.45  20.64
0       NaN       NaN -13.95 -11.35  22.16  47.19
0       NaN       NaN  -1.18  -0.52  16.47  66.49
0       NaN       NaN -12.51 -13.36  -2.30  28.45
0       NaN       NaN -10.95 -12.15  10.07  26.95
0       NaN       NaN -10.09 -12.93   2.61  45.70
0       NaN       NaN  -7.60  -7.43  -4.04   4.07
0       NaN       NaN -10.30 -11.54  -1.18   8.55
0       NaN       NaN  -8.95  -8.97  -6.44  21.86
0       NaN       NaN  -5.34  -5.60  -2.96  21.42
0       NaN       NaN -11.38  -9.40  -8.08  48.02
0       NaN       NaN  -8.87  -7.69  -0.25  25.09
0       NaN       NaN -10.38 -10.17  -0.18  10.12
0       NaN       NaN -15.52 -25.42  11.76  37.00
0       NaN       NaN  -9.06  -8.96  -6.46  10.78
0       NaN       NaN  -4.88  -5.82   1.81  29.24
0       NaN       NaN  30.05  36.66  82.35  89.23
0       NaN       NaN  -4.59  -4.03  11.10  31.09
0       NaN       NaN  30.00  38.81  47.28  80.71
0       NaN       NaN  -5.77  -7.42  10.53  38.44
0       NaN       NaN  -6.27  -6.81   3.35  25.81
0       NaN       NaN  -4.29  -5.03   6.57  23.93
0       NaN       NaN  -4.69  -3.14   9.20  21.92
0       NaN       NaN -12.46 -20.60   6.33  36.92
0       NaN       NaN  -7.29  -9.08  -3.62  18.16