## 申银万国行业分类标准一级 31类
* 每类最少32只

In [1]:
import pandas as pd 
import numpy as np 
from sqlalchemy import create_engine

In [2]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [3]:
# 1. 数据准备 
def load_and_preprocess_data():
    raw_df = pd.read_sql('akStockIC', engB, dtype={'StockCode': str})
    # ic_df = rawDF[rawDF['ICS']=='申银万国行业分类标准'][['StockCode','StockName','IC1']]
    fs_df = pd.read_sql('gpcw20250630', engF, dtype={'code': str}).rename(columns={'code':'StockCode'})
    merged_df = pd.merge(raw_df, fs_df, on='StockCode', how='inner')
    return merged_df

In [5]:
icDF = pd.read_sql('akStockIC', engB, dtype={'StockCode': str})

In [4]:
df = load_and_preprocess_data()

In [38]:
leddf = df[df['ICSCode'].isin(['008003']) & df['IC3'].isin(['LED'])]

In [48]:
leddf[['col223','col226','col222','col228','col227','col224']].describe()

          col223     col226      col222       col228     col227      col224
count  30.000000  30.000000   30.000000    30.000000  30.000000   30.000000
mean    3.579000   3.801633  102.144000   107.666897   3.059967   92.011667
std    15.575526  10.630215   13.526383   595.842053   8.937308   98.468870
min   -46.430000 -20.837000   74.140000 -1371.546000 -13.651000    9.580000
25%    -4.322500  -2.420000   94.855000   -49.119000  -2.087750   23.562500
50%     3.960000   1.707000  100.355000   155.304500   1.526000   44.010000
75%    12.165000  10.041000  108.722500   298.365500   7.675750  110.852500
max    28.540000  26.215000  135.310000  1810.496900  21.415000  381.650000

In [49]:
leddf[['col223','col226','col222','col228','col227','col224']]

       col223  col226  col222     col228  col227  col224
2123    10.51   6.588   92.20   502.0240   4.064   46.25
5620   -46.43 -20.837  103.49   374.4740 -13.651  234.48
5641    28.54  15.653   81.79  1810.4969   6.734   34.20
5692     5.07   2.201   97.11   340.2600   1.961   95.07
8326    16.52  10.130  125.75  -132.2510   7.821   19.76
11718  -12.40 -13.109   94.78  -163.3220 -11.892  103.69
12438   -2.68  -2.601  114.93 -1035.3030  -2.173   73.23
12901   -0.40  -0.337  102.27   -27.3040  -0.294   41.77
13409  -21.23 -12.241   90.75  -980.8670 -11.888   23.25
13981    4.66   3.940   98.37   241.7760   3.477   11.46
14837   24.54  21.394  127.52   182.1910  20.553  310.35
14873   -1.45  -0.735  102.95    54.6040  -0.634   62.70
15443    9.88   8.830  106.35   248.9030   7.439   24.50
15659   -8.16  -6.436   95.24 -1371.5460  -6.002   41.33
15867   12.22   8.815  109.15  1418.1580   7.689  113.24
15920   -1.30  -0.835   98.61   -41.2760  -0.784  118.24
15955   -1.86  -1.110   74.14   -45.8310  -1.066   30.12
16063   -4.87  -1.877  110.19   543.2140  -1.832    9.58
16159   12.00   8.602   95.08   231.0000   7.636   92.12
16175  -10.30  -3.393   86.97    40.4720  -3.100   22.39
16183   23.25  16.492  115.89   314.8530  15.939  267.98
16255   -8.34  -4.371   86.02   182.9050  -3.177  153.16
16488   12.72  11.076  102.19   204.8970  10.625   36.87
17231    0.11   0.086  100.66    -2.8760   0.061   27.69
17426   -5.24  -2.870   91.97  -112.0160  -2.703   88.36
17722   24.91  19.443  117.96   339.4460  19.414  240.07
17878   11.18   9.774  107.44   179.1520   8.842  381.65
18088    8.55  14.349  135.31   -50.2150   6.234   17.70
18406    3.26   1.213   99.19  -147.4690   1.091   20.25
18598   24.11  26.215  100.05   131.4570  21.415   18.89

In [25]:
ddf = df[df['col107']>0]

In [39]:
leddf['col107']/(leddf['col119']+leddf['col128'])

2123     109.513782
5620      -1.725637
5641      -1.841743
5692       1.640649
8326       3.131566
11718      3.284436
12438     -0.718177
12901      0.041513
13409     -0.660623
13981     -1.626164
14837     -0.901949
14873     -0.867650
15443     -0.973966
15659      3.545686
15867     -1.068029
15920      0.094052
15955     -0.126074
16063     -9.668280
16159     -1.299228
16175      0.557899
16183     -1.016506
16255     -0.817270
16488      0.957099
17231     -0.056398
17426      0.069697
17722     -0.857486
17878     -0.385634
18088     -0.332951
18406      0.357576
18598      2.524089
dtype: float64

In [42]:
leddf['col119']/leddf['col27']

2123    -0.039255
5620     0.792184
5641    -0.015874
5692    -0.142508
8326     0.062329
11718   -0.069059
12438   -0.039043
12901   -0.006995
13409    0.744001
13981    0.000500
14837   -0.337410
14873   -0.035904
15443    0.000367
15659   -0.092646
15867   -0.132973
15920   -0.087701
15955   -0.012306
16063    0.097359
16159   -0.110057
16175   -0.015213
16183   -0.162002
16255   -0.141777
16488    0.493357
17231   -0.125732
17426   -1.071931
17722   -0.127736
17878   -0.597007
18088   -0.050131
18406   -0.151815
18598    0.030785
dtype: float64

In [50]:
df.loc[15867]

StockCode                 300219
StockName                   鸿利智汇
ICS                   申银万国行业分类标准
DP           2011-10-10 00:00:00
IC4                          LED
                    ...
col577                       0.0
col578                    276.04
col579                       0.0
col580                       0.0
col581                     177.2
Name: 15867, Length: 592, dtype: object

In [51]:

df.loc[15867][['col107','col119','col128']]

col107    247284800.0
col119   -232308400.0
col128       774562.5
Name: 15867, dtype: object

In [7]:
icDF[icDF['ICSCode'].isin(['008003'])].groupby(['IC1','IC2','IC3'])['IC3'].value_counts()

IC1   IC2   IC3
交通运输  物流    中间产品及消费品供应链服务     7
            仓储物流              6
            公路货运              5
            原材料供应链服务         13
            快递                5
                             ..
食品饮料  食品加工  保健品               8
            肉制品               7
            预加工食品            10
      饮料乳品  乳品               18
            软饮料               8
Name: count, Length: 337, dtype: int64

In [8]:
icDF[icDF['ICSCode'].isin(['008003']) & icDF['IC2'].isin(('有色金属', '能源金属', '锂'))]

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode
2147,600711,盛屯矿业,申银万国行业分类标准,2021-07-30,钴,钴,能源金属,有色金属,S240601,008003
5179,603399,永杉锂业,申银万国行业分类标准,2023-07-04,锂,锂,能源金属,有色金属,S240603,008003
5868,603799,华友钴业,申银万国行业分类标准,2021-07-30,钴,钴,能源金属,有色金属,S240601,008003
6702,605376,博迁新材,申银万国行业分类标准,2023-07-04,镍,镍,能源金属,有色金属,S240602,008003
9422,000408,藏格矿业,申银万国行业分类标准,2023-07-04,锂,锂,能源金属,有色金属,S240603,008003
10190,000762,西藏矿业,申银万国行业分类标准,2021-07-30,锂,锂,能源金属,有色金属,S240603,008003
11938,002192,融捷股份,申银万国行业分类标准,2022-04-01,锂,锂,能源金属,有色金属,S240603,008003
12127,002240,盛新锂能,申银万国行业分类标准,2021-07-30,锂,锂,能源金属,有色金属,S240603,008003
12949,002460,赣锋锂业,申银万国行业分类标准,2021-07-30,锂,锂,能源金属,有色金属,S240603,008003
12969,002466,天齐锂业,申银万国行业分类标准,2021-07-30,锂,锂,能源金属,有色金属,S240603,008003
14021,002756,永兴材料,申银万国行业分类标准,2022-07-29,锂,锂,能源金属,有色金属,S240603,008003
17386,300618,寒锐钴业,申银万国行业分类标准,2021-07-30,钴,钴,能源金属,有色金属,S240601,008003
19610,301219,腾远钴业,申银万国行业分类标准,2022-03-01,钴,钴,能源金属,有色金属,S240601,008003

In [94]:
icDF[icDF['StockCode']=='600295']

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode
882,600295,鄂尔多斯,中国上市公司协会上市公司行业分类标准,2024-02-08,None,黑色金属冶炼和压延加工业,None,制造业,C31,008001
883,600295,鄂尔多斯,巨潮行业分类标准,2023-06-12,钢铁,黑色金属,基础材料,原材料,Z02020301,008002
884,600295,鄂尔多斯,申银万国行业分类标准,2021-07-30,冶钢辅料,冶钢辅料,冶钢原料,钢铁,S230302,008003
885,600295,鄂尔多斯,中证行业分类标准,2021-12-17,其他钢铁,钢铁,钢铁,原材料,15301030,008014

In [9]:
icDF[icDF['ICSCode'].isin(['008014'])].groupby(['IC1','IC2','IC3','IC4'])['IC4'].value_counts()

IC1   IC2   IC3     IC4
主要消费  农牧渔   养殖      动物保健与育种    11
                    渔业产品        8
                    畜牧产品       20
                    饲料         21
            种植      农产品        23
                               ..
金融    资本市场  其他资本市场  其他资本市场      4
                    资产管理        5
            证券公司    证券公司       49
      银行    商业银行    区域性银行      27
                    综合性银行      15
Name: count, Length: 248, dtype: int64

In [79]:
icDF[icDF['ICSCode'].isin(['008003']) & icDF['IC1'].isin(['家用电器'])]

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode
174,600060,海信视像,申银万国行业分类标准,1997-04-22,彩电,彩电,黑色家电,家用电器,S330201,008003
788,600261,阳光照明,申银万国行业分类标准,2021-07-30,照明设备Ⅲ,照明设备Ⅲ,照明设备Ⅱ,家用电器,S330501,008003
1008,600336,澳柯玛,申银万国行业分类标准,2021-07-30,冰洗,冰洗,白色家电,家用电器,S330106,008003
1863,600619,海立股份,申银万国行业分类标准,2021-07-30,家电零部件Ⅲ,家电零部件Ⅲ,家电零部件Ⅱ,家用电器,S330601,008003
2084,600690,海尔智家,申银万国行业分类标准,2021-07-30,冰洗,冰洗,白色家电,家用电器,S330106,008003
...,...,...,...,...,...,...,...,...,...,...
19702,301252,同星科技,申银万国行业分类标准,2023-05-12,家电零部件Ⅲ,家电零部件Ⅲ,家电零部件Ⅱ,家用电器,S330601,008003
19794,301280,珠城科技,申银万国行业分类标准,2024-07-30,家电零部件Ⅲ,家电零部件Ⅲ,家电零部件Ⅱ,家用电器,S330601,008003
19986,301332,德尔玛,申银万国行业分类标准,2023-05-04,清洁小家电,清洁小家电,小家电,家用电器,S330302,008003
20058,301362,民爆光电,申银万国行业分类标准,2023-07-31,照明设备Ⅲ,照明设备Ⅲ,照明设备Ⅱ,家用电器,S330501,008003
20454,301578,辰奕智能,申银万国行业分类标准,2023-12-22,其他黑色家电,其他黑色家电,黑色家电,家用电器,S330202,008003

In [27]:
df[df['StockCode']=='601888']

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode,...,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
3773,601888,中国中免,中国上市公司协会上市公司行业分类标准,2024-02-08,None,商务服务业,None,租赁和商务服务业,L72,008001,...,0.0,0.0,0.0,0.0,0.0,1470.0,9677.0996,0.0,144.71,25474.3691
3774,601888,中国中免,巨潮行业分类标准,2019-05-08,旅游,酒店餐饮与休闲,消费者服务,可选消费,Z04040101,008002,...,0.0,0.0,0.0,0.0,0.0,1470.0,9677.0996,0.0,144.71,25474.3691
3775,601888,中国中免,申银万国行业分类标准,2021-07-30,旅游零售Ⅲ,旅游零售Ⅲ,旅游零售Ⅱ,商贸零售,S450701,008003,...,0.0,0.0,0.0,0.0,0.0,1470.0,9677.0996,0.0,144.71,25474.3691
3776,601888,中国中免,中证行业分类标准,2021-12-17,旅游零售,旅游零售,零售业,可选消费,25503010,008014,...,0.0,0.0,0.0,0.0,0.0,1470.0,9677.0996,0.0,144.71,25474.3691

In [26]:
df[df['IC2'].isin(['旅游零售Ⅱ'])]

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode,...,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
3775,601888,中国中免,申银万国行业分类标准,2021-07-30,旅游零售Ⅲ,旅游零售Ⅲ,旅游零售Ⅱ,商贸零售,S450701,008003,...,0.0,0.0,0.0,0.0,0.0,1470.0,9677.0996,0.0,144.71,25474.3691

In [ ]:
df[df['ICS'].isin(['申银万国行业分类标准']) & df['IC4'].isin(['纺织鞋类制造'])]

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode,...,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
2,600000,浦发银行,申银万国行业分类标准,2021-07-30,股份制银行Ⅲ,股份制银行Ⅲ,股份制银行Ⅱ,银行,S480301,008003,...,26343800.0,0.0,0.0,7402900.0,0.0,0.00,0.0000,0.0000,3.219600e+06,0.0000
6,600004,白云机场,申银万国行业分类标准,2021-07-30,机场,机场,航空机场,交通运输,S421002,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,629.7700,0.0000,3.021500e+02,14277.9502
10,600006,东风股份,申银万国行业分类标准,2021-07-30,商用载货车,商用载货车,商用车,汽车,S280601,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0000,1.687484e+04,307.7900
14,600007,中国国贸,申银万国行业分类标准,2021-07-30,商业地产,商业地产,房地产开发,房地产,S430102,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,25.0000,16883.4902,2.264000e+01,183.5700
18,600008,首创环保,申银万国行业分类标准,2021-07-30,水务及水治理,水务及水治理,环境治理,环保,S760102,008003,...,0.0,0.0,0.0,0.0,0.0,821.35,5789.7202,0.0000,1.615057e+04,2689.3601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20590,301658,首航新能,申银万国行业分类标准,2025-03-14,逆变器,逆变器,光伏设备,电力设备,S630503,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0000,0.000000e+00,1136.0000
20594,301662,宏工科技,申银万国行业分类标准,2025-03-28,锂电专用设备,锂电专用设备,电池,电力设备,S630703,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0000,0.000000e+00,54.8200
20598,301665,泰禾股份,申银万国行业分类标准,2025-03-20,农药,农药,农化制品,基础化工,S220803,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0000,0.000000e+00,9.7700
20602,301678,新恒汇,申银万国行业分类标准,2025-05-30,半导体材料,半导体材料,半导体,电子,S270103,008003,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0000,1.412400e+02,62.0200
20606,302132,中航成飞,申银万国行业分类标准,2021-07-30,军工电子Ⅲ,军工电子Ⅲ,军工电子Ⅱ,国防军工,S650501,008003,...,0.0,0.0,0.0,0.0,0.0,3000.00,60.2800,0.0000,0.000000e+00,10584.5498

In [ ]:
df[df['IC1'].isin('')]

In [ ]:
# 2. 关键指标计算 
def calculate_financial_ratios(df):
    # 核心财务比率计算 
    ratios = {
        # 偿债能力 
        'current_ratio': df['col21'] / df['col54'],  # 流动比率 
        'quick_ratio': (df['col21'] - df['col17']) / df['col54'],  # 速动比率 
        'debt_to_asset': df['col63'] / df['col40'],  # 资产负债率 
        'interest_coverage': np.where(df['col80']  != 0, df['col207'] / df['col80'], np.nan),   # 利息保障倍数 
        
        # 盈利能力 
        'gross_margin': (df['col74'] - df['col75']) / df['col74'],  # 毛利率 
        'net_margin': df['col95'] / df['col74'],  # 净利率 
        'roe': df['col197'],  # 净资产收益率 
        
        # 运营效率 
        'inventory_turnover': df['col75'] / ((df['col17'].shift() + df['col17']) / 2),  # 存货周转率 
        'asset_turnover': df['col74'] / ((df['col40'].shift() + df['col40']) / 2),  # 总资产周转率 
        'receivable_days': 365 / (df['col74'] / ((df['col11'].shift() + df['col11']) / 2)),  # 应收账款周转天数 
        
        # 现金流 
        'operating_cf_ratio': df['col107'] / df['col63'],  # 经营现金流/负债 (col170)
        'cash_flow_margin': df['col107'] / df['col74']  # 经营现金流/营收 (col223)
    }
    
    for name, ratio in ratios.items(): 
        df[name] = ratio 
        
    # 处理无穷大和缺失值 
    df.replace([np.inf,  -np.inf],  np.nan,  inplace=True)
    return df

In [ ]:
# 3. 行业基准值计算 
def calculate_industry_benchmarks(df):
    """
    计算31个行业的7个关键指标基准值：
    1. 中位数（代表行业平均水平）
    2. 75分位数（代表良好水平）
    3. 25分位数（代表警戒水平）
    4. 标准差（离散程度）
    """
    # 确定31个行业 
    industries = df['IC1'].unique()
    
    # 需要计算的指标 
    metrics = [
        'current_ratio', 'quick_ratio', 'debt_to_asset', 'roe',
        'gross_margin', 'asset_turnover', 'operating_cf_ratio'
    ]
    
    # 创建结果容器 
    benchmark_results = {}
    
    for industry in industries:
        industry_df = df[df['IC1'] == industry]
        industry_data = {}
        
        for metric in metrics:
            data = industry_df[metric].dropna()
            
            if len(data) > 3:  # 确保有足够样本 
                industry_data[f'{metric}_median'] = np.median(data) 
                industry_data[f'{metric}_p75'] = np.percentile(data,  75)
                industry_data[f'{metric}_p25'] = np.percentile(data,  25)
                industry_data[f'{metric}_std'] = np.std(data) 
            else:
                # 样本不足时使用全行业数据 
                full_data = df[metric].dropna()
                industry_data[f'{metric}_median'] = np.median(full_data) 
                industry_data[f'{metric}_p75'] = np.percentile(full_data,  75)
                industry_data[f'{metric}_p25'] = np.percentile(full_data,  25)
                industry_data[f'{metric}_std'] = np.std(full_data) 
        
        benchmark_results[industry] = industry_data 
    
    # 转换为DataFrame 
    benchmark_df = pd.DataFrame.from_dict(benchmark_results,  orient='index')
    
    # 添加行业特征描述 
    benchmark_df['industry_risk_profile'] = classify_industry_risk(benchmark_df)
    
    return benchmark_df

In [ ]:
# 4. 行业风险分类 
def classify_industry_risk(benchmark_df):
    """根据行业特征进行风险分类"""
    risk_levels = []
    
    for idx, row in benchmark_df.iterrows(): 
        # 高杠杆行业分类 
        if row['debt_to_asset_median'] > 0.7:
            if '银行' in idx or '房地产' in idx:
                risk_levels.append(' 高杠杆-金融地产')
            else:
                risk_levels.append(' 高杠杆-非金融')
        
        # 周期性行业 
        elif '有色金属' in idx or '煤炭' in idx or '钢铁' in idx:
            risk_levels.append(' 强周期性')
        
        # 防御性行业 
        elif '公用事业' in idx or '医药生物' in idx or '食品饮料' in idx:
            risk_levels.append(' 防御性')
        
        # 成长性行业 
        elif '计算机' in idx or '电子' in idx or '通信' in idx:
            risk_levels.append(' 成长性')
        
        # 一般行业 
        else:
            risk_levels.append(' 一般行业')
    
    return risk_levels

In [ ]:
# 5. 主执行函数 
def main():
    print("正在加载数据...")
    df = load_and_preprocess_data()
    
    print("正在计算财务比率...")
    ratio_df = calculate_financial_ratios(df)
    
    print("正在计算行业基准值...")
    benchmarks = calculate_industry_benchmarks(ratio_df)
    
    # 保存结果 
    benchmarks.to_excel('/home/ts/app/JupLab/industry_benchmarks.xlsx') 
    print("行业基准值计算完成，已保存至 industry_benchmarks.xlsx") 
    
    # 示例输出 
    print("\n部分行业基准值示例:")
    print(benchmarks.head(5)) 
    
    # 特殊行业分析建议 
    print("\n行业分析建议:")
    print("- 金融行业: 重点关注资产负债率和不良贷款率")
    print("- 制造业: 关注存货周转率和毛利率稳定性")
    print("- 科技行业: 研发投入占比和营收增长率是关键")
 
if __name__ == "__main__":
    main()

In [17]:
df = load_and_preprocess_data()

In [18]:
ratio_df = calculate_financial_ratios(df)

## 行业专属补充指标

In [ ]:
# 金融行业特有指标 
if industry == '银行':
    npl_ratio = df['col81'] / df['col404']  # 不良贷款率 
    car = (df['col268'] + df['col72']) / df['risk_weighted_assets']  # 资本充足率 
 
# 房地产行业特有指标 
elif industry == '房地产':
    quick_ratio = (df['col21'] - df['col17']) / df['col54']
    presale_ratio = df['col45'] / df['col63']  # 预售款占比 
 
# 制造业特有指标 
elif industry in ['机械设备', '汽车']:
    inventory_days = 365 / inventory_turnover 
    fixed_asset_turnover = df['col74'] / df['col27']  # 固定资产周转率

## 结果应用场景

In [ ]:
# 基于行业基准设定动态预警阈值
def set_alert_thresholds(company):
    industry = company['industry_name']
    benchmarks = industry_benchmarks.loc[industry] 
    
    # 资产负债率警报：超过行业75分位数的120%
    debt_alert = company['debt_to_asset'] > (benchmarks['debt_to_asset_p75'] * 1.2)
    
    # 现金流警报：低于行业25分位数
    cash_alert = company['operating_cf_ratio'] < benchmarks['operating_cf_ratio_p25']
    
    return {'debt_alert': debt_alert, 'cash_alert': cash_alert}

In [ ]:
# 生成公司行业位置报告
def industry_position_report(company):
    position = {}
    for metric in ['roe', 'gross_margin']:
        value = company[metric]
        industry_median = benchmarks[f'{metric}_median']
        industry_p75 = benchmarks[f'{metric}_p75']
        
        if value > industry_p75:
            position[metric] = '行业前25%'
        elif value > industry_median:
            position[metric] = '行业中上'
        else:
            position[metric] = '行业中下'
    return position

In [ ]:
# 计算行业景气指数
def industry_health_index(industry):
    df = industry_companies[industry]
    weights = {
        'roe': 0.3,
        'revenue_growth': 0.25,
        'operating_cf_ratio': 0.25,
        'debt_to_asset': -0.2  # 负权重
    }
    index = 0
    for metric, weight in weights.items(): 
        index += np.median(df[metric])  * weight
    return index