In [1]:

#from streamlit_echarts import st_pyecharts
#from mootdx.quotes import Quotes
# from chart import makSum
#import re
import plotly.express as px
import pandas as pd
from sqlalchemy import create_engine
# from chart import Kpro,indexChart,d3plt,detailChart,gganChart,gganPx,fenX,getConsStock
#from chart import Kpro,indexChart,getConsStock

In [3]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [4]:

topDF = pd.read_sql('Top', engB)
bizDF = pd.read_sql('mBiz', engB).dropna(subset='营业收入(元)')
bzPDF = pd.read_sql('BizP', engB)


bizDF.loc[bizDF[bizDF['营业收入(元)'].str.endswith('万')].index,'营业收入(元)'] = bizDF[bizDF['营业收入(元)'].str.endswith('万')]['营业收入(元)'].str.replace('万','').astype(float)/10000
bizDF.loc[list(bizDF['营业收入(元)'].str.endswith('亿').dropna().index),'营业收入(元)'] = bizDF.loc[list(bizDF['营业收入(元)'].str.endswith('亿').dropna().index),'营业收入(元)'].str.replace('亿','').astype(float)

bizDF[['毛利率(%)','收入比例(%)','利润比例(%)']] = bizDF[['毛利率(%)','收入比例(%)','利润比例(%)']].astype('float')

  StockCode StockName     营收额   营收占比    采购额  采购占比
0    000002       万科A  206.66  14.47  28.27  3.17

In [ ]:
bizDF.rename(columns={'营业收入(元)':'营业收入(亿元)'}, inplace=True)

In [23]:
bidf = bizDF[bizDF['StockCode']=='600506']

In [27]:
bidf[bidf['项目名'].str.endswith('(地区)')]

,日期,StockCode,StockName,项目名,营业收入(亿元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
106120,2024-06-30,600506,统一股份,华东(地区),5.39,42.49,9898.18万,40.06,18.36
106121,2024-06-30,600506,统一股份,华北(地区),2.62,20.68,5170.31万,20.93,19.70
106122,2024-06-30,600506,统一股份,华中(地区),1.07,8.41,2247.81万,9.10,21.07
106123,2024-06-30,600506,统一股份,华南(地区),1.06,8.37,2159.55万,8.74,20.33
106124,2024-06-30,600506,统一股份,西北(地区),0.838973,6.61,1640.58万,6.64,19.55
106125,2024-06-30,600506,统一股份,东北(地区),0.824423,6.50,1815.46万,7.35,22.02
106126,2024-06-30,600506,统一股份,西南(地区),0.824041,6.49,1658.91万,6.71,20.13
106127,2024-06-30,600506,统一股份,国外(地区),0.040797,0.32,58.71万,0.24,14.39
106128,2024-06-30,600506,统一股份,其他(补充)(地区),0.015106,0.12,57.16万,0.23,37.84
106136,2023-12-31,600506,统一股份,华东(地区),9.34,41.73,1.39亿,37.01,14.90
106137,2023-12-31,600506,统一股份,华北(地区),4.67,20.86,8137.69万,21.63,17.43
106138,2023-12-31,600506,统一股份,华南(地区),2.02,9.03,3723.37万,9.90,18.42
106139,2023-12-31,600506,统一股份,华中(地区),2.02,9.00,3654.33万,9.71,18.14
106140,2023-12-31,600506,统一股份,西北(地区),1.51,6.77,2892.70万,7.69,19.10
106141,2023-12-31,600506,统一股份,西南(地区),1.38,6.18,2652.31万,7.05,19.16
106142,2023-12-31,600506,统一股份,东北(地区),1.35,6.02,2655.15万,7.06,19.71
106143,2023-12-31,600506,统一股份,其他业务(地区),0.092523,0.41,-15.67万,-0.04,-1.69
106153,2023-06-30,600506,统一股份,华东(地区),4.85,39.87,None,NaN,NaN
106154,2023-06-30,600506,统一股份,华北(地区),2.46,20.21,None,NaN,NaN
106155,2023-06-30,600506,统一股份,华中(地区),1.2,9.87,None,NaN,NaN
106156,2023-06-30,600506,统一股份,华南(地区),1.14,9.36,None,NaN,NaN
106157,2023-06-30,600506,统一股份,西北(地区),0.890695,7.32,None,NaN,NaN
106158,2023-06-30,600506,统一股份,西南(地区),0.834945,6.86,None,NaN,NaN
106159,2023-06-30,600506,统一股份,东北(地区),0.781584,6.42,None,NaN,NaN
106160,2023-06-30,600506,统一股份,其他(补充)(地区),0.013006,0.11,None,NaN,NaN