In [1]:

#from streamlit_echarts import st_pyecharts
#from mootdx.quotes import Quotes
# from chart import makSum
#import re
import plotly.express as px
import pandas as pd
from sqlalchemy import create_engine
# from chart import Kpro,indexChart,d3plt,detailChart,gganChart,gganPx,fenX,getConsStock
#from chart import Kpro,indexChart,getConsStock

In [2]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [3]:

topDF = pd.read_sql('Top', engB)
bizDF = pd.read_sql('mBiz', engB).dropna(subset='营业收入(元)')
bzPDF = pd.read_sql('BizP', engB)


bizDF.loc[bizDF[bizDF['营业收入(元)'].str.endswith('万')].index,'营业收入(元)'] = bizDF[bizDF['营业收入(元)'].str.endswith('万')]['营业收入(元)'].str.replace('万','').astype(float)/10000
bizDF.loc[list(bizDF['营业收入(元)'].str.endswith('亿').dropna().index),'营业收入(元)'] = bizDF.loc[list(bizDF['营业收入(元)'].str.endswith('亿').dropna().index),'营业收入(元)'].str.replace('亿','').astype(float)

bizDF[['毛利率(%)','收入比例(%)','利润比例(%)']] = bizDF[['毛利率(%)','收入比例(%)','利润比例(%)']].astype('float')

In [ ]:
bizDF['日期'].drop_duplicates()

0         2024-06-30
9         2023-12-31
18        2023-06-30
4834      2024-03-31
5022      2022-12-31
44571     2023-09-30
63398     2021-12-31
76226     2022-06-30
93616     2023-03-31
93862     2022-09-30
144840    2024-09-30
153151    2021-06-30
157747    2022-03-31
Name: 日期, dtype: object

:

In [4]:
bizDF.rename(columns={'营业收入(元)':'营业收入(亿元)'}, inplace=True)

In [5]:
bidf = bizDF[bizDF['StockCode']=='688099']

In [6]:
bidf

,日期,StockCode,StockName,项目名,营业收入(亿元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
150477,2024-06-30,688099,晶晨股份,(行,30.16,100.00,10.67亿,100.00,35.37
150478,2024-06-30,688099,晶晨股份,商品销售(产品),30.16,100.00,10.67亿,100.00,35.37
150479,2024-06-30,688099,晶晨股份,境外(地区),27.75,91.99,9.93亿,93.04,35.77
150480,2024-06-30,688099,晶晨股份,境内(地区),2.42,8.01,7428.44万,6.96,30.76
150481,2023-12-31,688099,晶晨股份,集成电路(行业),53.71,100.00,19.56亿,100.00,36.41
150482,2023-12-31,688099,晶晨股份,其他业务(行业),1076.42,0.00,215.28,0.00,20.00
150483,2023-12-31,688099,晶晨股份,多媒体智能终端芯片(产品),52.92,98.53,19.34亿,98.90,36.54
150484,2023-12-31,688099,晶晨股份,其他芯片(产品),0.786868,1.47,2158.22万,1.10,27.43
150485,2023-12-31,688099,晶晨股份,其他业务(产品),1076.42,0.00,215.28,0.00,20.00
150486,2023-12-31,688099,晶晨股份,境外(地区),48.46,90.23,17.85亿,91.30,36.84
150487,2023-12-31,688099,晶晨股份,境内(地区),5.25,9.77,1.70亿,8.70,32.41
150488,2023-12-31,688099,晶晨股份,其他业务(地区),1076.42,0.00,215.28,0.00,20.00
150489,2023-12-31,688099,晶晨股份,经销(销售模式),42.16,78.50,15.46亿,79.04,36.66
150490,2023-12-31,688099,晶晨股份,直销(销售模式),11.55,21.50,4.10亿,20.96,35.49
150491,2023-12-31,688099,晶晨股份,其他业务(销售模式),1076.42,0.00,215.28,0.00,20.00
150492,2023-06-30,688099,晶晨股份,销售商品(产品),23.5,100.00,None,NaN,NaN
150493,2023-06-30,688099,晶晨股份,技术服务(产品),1076.42,0.00,None,NaN,NaN
150494,2023-06-30,688099,晶晨股份,境外(地区),21.62,91.97,None,NaN,NaN
150495,2023-06-30,688099,晶晨股份,境内(地区),1.89,8.03,None,NaN,NaN

In [7]:
bizDF[bizDF['日期']=='2024-06-30']

,日期,StockCode,StockName,项目名,营业收入(亿元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
0,2024-06-30,000001,平安银行,总部(地区),419.94,54.44,297.83亿,53.92,70.92
1,2024-06-30,000001,平安银行,南区(地区),124.03,16.08,95.53亿,17.29,77.02
2,2024-06-30,000001,平安银行,东区(地区),106.47,13.80,75.01亿,13.58,70.45
3,2024-06-30,000001,平安银行,北区(地区),78.68,10.20,54.16亿,9.80,68.84
4,2024-06-30,000001,平安银行,西区(地区),37.92,4.92,27.19亿,4.92,71.70
...,...,...,...,...,...,...,...,...,...
165449,2024-06-30,689009,九号公司-WD,其他产品(产品),1.13,1.69,4008.34万,1.97,35.60
165450,2024-06-30,689009,九号公司-WD,中国大陆境内(地区),38.63,57.95,9.57亿,47.13,24.76
165451,2024-06-30,689009,九号公司-WD,中国大陆境外(地区),28.03,42.05,10.73亿,52.87,38.29
165452,2024-06-30,689009,九号公司-WD,自主品牌销售(销售模式),58.6,87.91,17.36亿,85.54,29.63
165453,2024-06-30,689009,九号公司-WD,B及定制产品销售(销售模式),8.06,12.09,2.94亿,14.46,36.43

In [8]:
bidf[bidf['项目名'].str.endswith('(产品)')]

,日期,StockCode,StockName,项目名,营业收入(亿元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
150478,2024-06-30,688099,晶晨股份,商品销售(产品),30.16,100.00,10.67亿,100.0,35.37
150483,2023-12-31,688099,晶晨股份,多媒体智能终端芯片(产品),52.92,98.53,19.34亿,98.9,36.54
150484,2023-12-31,688099,晶晨股份,其他芯片(产品),0.786868,1.47,2158.22万,1.1,27.43
150485,2023-12-31,688099,晶晨股份,其他业务(产品),1076.42,0.00,215.28,0.0,20.00
150492,2023-06-30,688099,晶晨股份,销售商品(产品),23.5,100.00,None,NaN,NaN
150493,2023-06-30,688099,晶晨股份,技术服务(产品),1076.42,0.00,None,NaN,NaN