In [ ]:
from sqlalchemy import create_engine, text
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')

In [1]:
from mootdx.quotes import Quotes
std = Quotes.factory(market='std')
ext = Quotes.factory(market='ext')

2025-09-05 09:25:18,213 - mootdx - WARNING - 目前扩展市场行情接口已经失效, 后期有望修复.

In [13]:
ddf = ext.instruments()

100%|##########| 689/689 [00:48<00:00, 14.22it/s]

In [18]:
ddf[ddf['market']==62]

       category  market    code      name desc
53582         5      62  000012      国债指数
53583         5      62  000013      企债指数
53584         5      62  000022      沪公司债
53585         5      62  000061     沪企债30
53586         5      62  000101      5年信用
...         ...     ...     ...       ...  ...
54248         5      62  H50055      沪大农业
54249         5      62  H50069       港股通
54250         5      62  N00300  沪深300净收益
54251         5      62  N00905  中证500净收益
54252         5      62  SHHKSI      沪港精明

[671 rows x 5 columns]

In [19]:
df = std.stocks(1)

100%|##########| 26/26 [00:01<00:00, 24.29it/s]

In [8]:
df[df['volunit']==100]

         code  volunit  decimal_point     name     pre_close
0      395001      100              2     主板Ａ股  1.485000e+03
1      395002      100              2     主板Ｂ股  1.440000e+02
2      395004      100              2    创业板    1.385000e+03
3      395005      100              2   主板DR    5.877472e-39
4      395006      100              2    创业板DR  5.877472e-39
...       ...      ...            ...      ...           ...
46923  589120      100              3     创新药基  5.877472e-39
46924  589780      100              3  科200FG   5.877472e-39
46925  589820      100              3  科200F    5.877472e-39
46926  589950      100              3  科100FG   5.877472e-39
46927  589960      100              3     科创新源  5.877472e-39

[9023 rows x 5 columns]

In [ ]:
qf10='热点题材'
client = Quotes.factory(market='std')

In [ ]:
txtRaw = client.F10('000001', qf10)[116:]

In [ ]:
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)
txt = re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)
txDF = pd.DataFrame(txt)
txDF[2]=txDF[2].str.len()-4
txDF.columns=['日期','题材','相关度']

In [ ]:
txDF['StockCode'] = '000001'
txDF['StockName'] = 'StockName'

In [ ]:
txDF[['StockCode','StockName','日期','题材','相关度']].set_index('日期').to_sql('Top', eng, if_exists='append')

In [ ]:
std.bars(symbol='600036', frequency=9, offset=10)

In [ ]:
api = TdxHq_API()
api.connect('180.153.18.170', 7709)

In [ ]:
api.to_df(api.get_security_bars(9, 1, '600036', 0, 10))

In [ ]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data))