In [11]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

In [17]:
api.connect('180.153.18.170', 7709)

In [22]:
api.to_df(api.get_security_bars(9, 0, '000001', 1, 25))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,11.38,11.43,11.50,11.36,1026590.0,1.174045e+09,2025,2,10,15,0,2025-02-10 15:00
1,11.40,11.42,11.47,11.37,844520.0,9.638656e+08,2025,2,11,15,0,2025-02-11 15:00
2,11.41,11.42,11.43,11.34,988806.0,1.125324e+09,2025,2,12,15,0,2025-02-12 15:00
3,11.42,11.50,11.55,11.40,1358639.0,1.560710e+09,2025,2,13,15,0,2025-02-13 15:00
4,11.49,11.55,11.55,11.43,973057.0,1.118356e+09,2025,2,14,15,0,2025-02-14 15:00
5,11.60,11.78,11.80,11.55,2061965.0,2.413146e+09,2025,2,17,15,0,2025-02-17 15:00
6,11.76,11.81,11.96,11.76,1996610.0,2.371071e+09,2025,2,18,15,0,2025-02-18 15:00
7,11.80,11.71,11.81,11.68,1177749.0,1.382467e+09,2025,2,19,15,0,2025-02-19 15:00
8,11.71,11.66,11.76,11.65,784396.0,9.172314e+08,2025,2,20,15,0,2025-02-20 15:00
9,11.69,11.64,11.71,11.55,973968.0,1.131034e+09,2025,2,21,15,0,2025-02-21 15:00
10,11.63,11.59,11.69,11.56,949956.0,1.103549e+09,2025,2,24,15,0,2025-02-24 15:00
11,11.56,11.47,11.58,11.46,917156.0,1.055685e+09,2025,2,25,15,0,2025-02-25 15:00
12,11.47,11.52,11.60,11.47,841645.0,9.706412e+08,2025,2,26,15,0,2025-02-26 15:00
13,11.53,11.62,11.63,11.46,977309.0,1.130387e+09,2025,2,27,15,0,2025-02-27 15:00
14,11.58,11.53,11.68,11.50,949088.0,1.100335e+09,2025,2,28,15,0,2025-02-28 15:00
15,11.52,11.51,11.56,11.45,830456.0,9.552664e+08,2025,3,3,15,0,2025-03-03 15:00
16,11.47,11.51,11.55,11.44,683178.0,7.854480e+08,2025,3,4,15,0,2025-03-04 15:00
17,11.52,11.66,11.67,11.48,1080645.0,1.254892e+09,2025,3,5,15,0,2025-03-05 15:00
18,11.69,11.63,11.70,11.60,877407.0,1.021781e+09,2025,3,6,15,0,2025-03-06 15:00
19,11.63,11.67,11.69,11.60,835536.0,9.732367e+08,2025,3,7,15,0,2025-03-07 15:00
20,11.66,11.59,11.67,11.55,663833.0,7.692614e+08,2025,3,10,15,0,2025-03-10 15:00
21,11.54,11.61,11.61,11.52,608975.0,7.042404e+08,2025,3,11,15,0,2025-03-11 15:00
22,11.60,11.85,11.87,11.56,1877318.0,2.210905e+09,2025,3,12,15,0,2025-03-12 15:00
23,11.81,11.84,11.91,11.78,1312371.0,1.555123e+09,2025,3,13,15,0,2025-03-13 15:00
24,11.82,11.97,12.00,11.82,1722417.0,2.057970e+09,2025,3,14,15,0,2025-03-14 15:00

In [18]:
api.to_df(api.get_index_bars(9, 1, '000001', 1, 21))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,up_count,down_count
0,3328.48,3346.72,3349.08,3322.53,5323329.0,6.675554e+11,2025,2,14,15,0,2025-02-14 15:00,1008,1205
1,3355.42,3355.83,3357.12,3333.19,5895465.0,7.501131e+11,2025,2,17,15,0,2025-02-17 15:00,1418,833
2,3348.98,3324.49,3366.01,3314.30,5626792.0,6.967988e+11,2025,2,18,15,0,2025-02-18 15:00,334,1954
3,3320.78,3351.54,3352.09,3320.58,5029129.0,6.751464e+11,2025,2,19,15,0,2025-02-19 15:00,1887,347
4,3347.59,3350.78,3355.56,3338.03,5043571.0,6.700990e+11,2025,2,20,15,0,2025-02-20 15:00,1336,882
5,3356.69,3379.11,3381.06,3339.03,6081902.0,8.556570e+11,2025,2,21,15,0,2025-02-21 15:00,1180,1059
6,3374.08,3373.03,3384.81,3355.87,5981882.0,8.028471e+11,2025,2,24,15,0,2025-02-24 15:00,1127,1111
7,3345.65,3346.04,3369.56,3337.84,5275785.0,7.275098e+11,2025,2,25,15,0,2025-02-25 15:00,648,1619
8,3351.21,3380.21,3380.21,3351.21,5539920.0,7.478873e+11,2025,2,26,15,0,2025-02-26 15:00,1857,417
9,3378.45,3388.06,3388.78,3353.57,5758150.0,7.740600e+11,2025,2,27,15,0,2025-02-27 15:00,969,1260
10,3374.66,3320.90,3383.19,3318.72,5683195.0,7.580549e+11,2025,2,28,15,0,2025-02-28 15:00,244,2047
11,3328.40,3316.93,3349.02,3304.59,5024178.0,6.439807e+11,2025,3,3,15,0,2025-03-03 15:00,1273,923
12,3300.50,3324.21,3327.82,3297.53,4299961.0,5.687284e+11,2025,3,4,15,0,2025-03-04 15:00,1670,556
13,3324.70,3341.96,3342.71,3314.15,4609527.0,5.877676e+11,2025,3,5,15,0,2025-03-05 15:00,900,1337
14,3353.57,3381.10,3387.05,3348.68,5399927.0,7.364381e+11,2025,3,6,15,0,2025-03-06 15:00,1865,378
15,3373.18,3372.55,3390.94,3363.93,5176635.0,6.878790e+11,2025,3,7,15,0,2025-03-07 15:00,738,1515
16,3373.26,3366.16,3375.80,3347.19,4503808.0,5.950264e+11,2025,3,10,15,0,2025-03-10 15:00,1361,876
17,3335.44,3379.83,3379.83,3334.83,4484683.0,5.922858e+11,2025,3,11,15,0,2025-03-11 15:00,1292,918
18,3385.69,3371.92,3392.41,3370.22,5021951.0,6.485017e+11,2025,3,12,15,0,2025-03-12 15:00,1055,1158
19,3371.09,3358.73,3377.12,3341.12,5190134.0,6.362116e+11,2025,3,13,15,0,2025-03-13 15:00,668,1581
20,3361.69,3419.56,3421.23,3360.61,5826633.0,7.500416e+11,2025,3,14,15,0,2025-03-14 15:00,1923,345

In [4]:
eapi.connect('47.112.95.207', 7720)

In [5]:
eapi.to_df(eapi.get_instrument_bars(9, 62, '930791', 0, 10))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,8707.881836,8797.488281,8674.206055,8776.691406,1194252409,18,0.0,2025,3,4,15,0,2025-03-04 15:00,44760.472656
1,8776.000977,8778.389648,8667.570312,8713.416992,1193270097,22,0.0,2025,3,5,15,0,2025-03-05 15:00,40923.316406
2,8748.922852,8863.913086,8733.351562,8843.686523,1196848536,28,0.0,2025,3,6,15,0,2025-03-06 15:00,54901.593750
3,8825.332031,8825.332031,8738.345703,8763.407227,1194864774,25,0.0,2025,3,7,15,0,2025-03-07 15:00,47152.523438
4,8846.940430,8891.053711,8754.330078,8817.967773,1196573242,30,0.0,2025,3,10,15,0,2025-03-10 15:00,53826.226562
5,8740.065430,8834.098633,8727.622070,8834.098633,1196201010,26,0.0,2025,3,11,15,0,2025-03-11 15:00,52372.195312
6,8847.457031,8890.265625,8770.915039,8771.636719,1195247986,25,0.0,2025,3,12,15,0,2025-03-12 15:00,48649.445312
7,8771.099609,8794.520508,8687.205078,8737.503906,1194594867,24,0.0,2025,3,13,15,0,2025-03-13 15:00,46098.199219
8,8739.962891,8931.583008,8732.547852,8931.583008,1199594392,31,0.0,2025,3,14,15,0,2025-03-14 15:00,65719.187500
9,8970.338867,8972.469727,8897.769531,8932.250977,1195014675,23,0.0,2025,3,17,15,0,2025-03-17 15:00,47738.074219

1分钟K线(8)1D240 2D480 3D720 bar, 5分钟K线(0)1D48 5D240 8D384 13D624 bar ,  日K线(9)
每次800   0SZ  1SH  ======= 在线分析

In [29]:
from pytdx.hq import TdxHq_API
import pandas as pd
import plotly.express as px

import numpy as np 

api = TdxHq_API()

In [182]:
api.connect('121.36.81.195', 7709)

In [176]:
stockCodeSel = '002469'

In [179]:
if stockCodeSel < '600000':
    m = 0
else:
    m = 1

In [183]:
df3 = api.to_df(api.get_security_bars(8, m, stockCodeSel, 0, 720))
df5 = api.to_df(api.get_security_bars(0, m, stockCodeSel, 0, 240))
df13 = api.to_df(api.get_security_bars(0, m, stockCodeSel, 0, 624))
df21 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 21))
df55 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 55))
df144 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 144))

In [184]:
df3

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,7.41,7.68,7.68,7.41,2.083450e+07,1.562434e+08,2024,11,15,9,31,2024-11-15 09:31
1,7.65,7.76,7.99,7.65,1.781950e+07,1.409567e+08,2024,11,15,9,32,2024-11-15 09:32
2,7.75,7.88,7.98,7.75,5.401300e+06,4.246970e+07,2024,11,15,9,33,2024-11-15 09:33
3,7.91,7.79,7.92,7.78,4.088200e+06,3.202746e+07,2024,11,15,9,34,2024-11-15 09:34
4,7.80,7.93,7.93,7.79,2.404100e+06,1.885290e+07,2024,11,15,9,35,2024-11-15 09:35
...,...,...,...,...,...,...,...,...,...,...,...,...
715,9.05,9.02,9.05,8.96,9.790000e+05,8.802611e+06,2024,11,19,14,56,2024-11-19 14:56
716,9.05,9.02,9.05,9.00,2.006200e+06,1.811464e+07,2024,11,19,14,57,2024-11-19 14:57
717,9.02,9.02,9.02,9.02,3.270000e+04,2.949510e+05,2024,11,19,14,58,2024-11-19 14:58
718,9.02,9.02,9.02,9.02,5.877472e-39,5.877472e-39,2024,11,19,14,59,2024-11-19 14:59
719,9.13,9.13,9.13,9.13,3.455600e+06,3.154945e+07,2024,11,19,15,0,2024-11-19 15:00

In [ ]:
df750 = api.to_df(api.get_index_bars(9, 1, '000001', 10, 799))

In [28]:
api.to_df(api.get_index_bars(9, 1, '000510', 10, 799))

  value
0  None

====== 数据说明df3三天1分钟k线数据, df5五天5分钟k线数据,df13十三天五分钟k线数据, 其他日k线数据

个股

In [56]:
df3 = api.to_df(api.get_security_bars(8, 0, '000001', 0, 720))
df5 = api.to_df(api.get_security_bars(0, 0, '000001', 0, 240))
df13 = api.to_df(api.get_security_bars(0, 0, '000001', 0, 624))
df21 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 21))
df55 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 55))
df144 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 144))

指数

In [ ]:
df3 = api.to_df(api.get_index_bars(8, 1, '000001', 0, 720))
df5 = api.to_df(api.get_index_bars(0, 1, '000001', 0, 240))
df13 = api.to_df(api.get_index_bars(0, 1, '000001', 0, 624))
df21 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 21))
df55 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 55))
df144 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 144))

In [185]:
lsDF = [df3,df5,df13,df21,df55,df144]
lsD = ['3D','5D',"13D","21D","55D","144D"]
con = [720,240,624,21,55,144]

价格 加 数量 权 (扩展数量加权：权重)

In [186]:
def norm(df, column_name,n):
    min_val = df[column_name].min()
    max_val = df[column_name].max()
    normalized_column = (df[column_name] - min_val) / (max_val - min_val)
    scaled_column = normalized_column * (n - 1) + 1
    discrete_scaled_column = scaled_column.round().astype(int)
    return discrete_scaled_column

In [187]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    weights = norm(df,'vol',con[n])
    weighted_data = np.repeat(df['close'], repeats=weights)
    dDF = pd.DataFrame(weighted_data)
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [ ]:
plDF

In [188]:

fig = px.violin(plDF,y='close',facet_col='周期',facet_col_spacing=0.01,box=True,violinmode='overlay',title='价格加权')
fig.show()

In [ ]:
fig = px.box(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='价格加权')
fig.show()

价格

In [83]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    # weights = norm(df,'amount',con[n])
    # weighted_data = np.repeat(df['close'], repeats=weights)
    dDF = pd.DataFrame(df['close'])
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [84]:
fig = px.violin(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='价格')
fig.show()

In [ ]:
fig = px.box(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='价格')
fig.show()

数量

In [ ]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    dDF = pd.DataFrame(df['amount'])
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [ ]:
fig = px.violin(plDF[plDF['周期'].isin(['21D','55D','144D'])],y='amount',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='数量')
fig.show()

In [ ]:
fig = px.violin(plDF,y='amount',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='数量')
fig.show()

In [ ]:
fig = px.box(plDF,y='amount',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='数量')
fig.show()

In [28]:
df144

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,10.28,10.28,10.39,10.22,1478036.0,1.523139e+09,2024,4,16,15,0,2024-04-16 15:00
1,10.26,10.62,10.63,10.21,2232640.0,2.337577e+09,2024,4,17,15,0,2024-04-17 15:00
2,10.58,10.80,11.03,10.56,3165914.0,3.427339e+09,2024,4,18,15,0,2024-04-18 15:00
3,10.71,10.69,10.82,10.66,1457675.0,1.562376e+09,2024,4,19,15,0,2024-04-19 15:00
4,10.64,10.50,10.81,10.45,2009818.0,2.125723e+09,2024,4,22,15,0,2024-04-22 15:00
...,...,...,...,...,...,...,...,...,...,...,...,...
139,11.58,11.54,11.84,11.51,1717662.0,2.005791e+09,2024,11,12,15,0,2024-11-12 15:00
140,11.50,11.61,11.70,11.48,1086263.0,1.260162e+09,2024,11,13,15,0,2024-11-13 15:00
141,11.59,11.54,11.70,11.53,1159783.0,1.348378e+09,2024,11,14,15,0,2024-11-14 15:00
142,11.50,11.44,11.61,11.42,1215783.0,1.399309e+09,2024,11,15,15,0,2024-11-15 15:00
143,11.63,11.77,11.78,11.62,639682.0,7.492814e+08,2024,11,18,15,0,2024-11-18 15:00

In [85]:
fig = px.violin(df3,y='vol',x='minute',box=True,violinmode='group',title='数量')
fig.show()

In [87]:
fig = px.box(df3,y='vol',x='minute',boxmode='group',title='数量')
fig.show()

========== 三日分钟交易量密度图

In [101]:

fig = px.density_contour(df3, y="hour",x='minute',z='amount',histfunc='sum',nbinsx=60,nbinsy=7)
fig.update_traces(contours_coloring="fill", contours_showlabels = True)

fig.show()

In [109]:
fig = px.density_contour(df3, y="day",x='hour',z='amount',nbinsx=4,nbinsy=3, histfunc='sum')

fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

In [107]:
fig = px.density_contour(df3, y="day",x='minute',z='amount',nbinsx=60,nbinsy=3, histfunc='sum')

fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

分钟交易额统计

In [102]:
api.connect('121.36.81.195', 7709)

In [105]:
dff = api.to_df(api.get_security_bars(8, 1, '600889', 0, 799))

In [106]:
fig = px.density_heatmap(dff, x='minute',y='hour',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=60,nbinsy=7,text_auto='.2r')
fig.show()

In [66]:
dff = api.to_df(api.get_security_bars(0, 0, '000002', 0, 799))
fig = px.density_heatmap(dff, x='minute',y='hour',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=12,nbinsy=7,text_auto='.2r')
fig.show()

小时交易额统计

In [94]:
api.connect('121.36.81.195', 7709)

In [96]:
api.to_df(api.get_security_bars(0, 1, '600489', 0, 799))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,14.44,14.44,14.45,14.42,369200.0,5329053.0,2024,10,24,14,15,2024-10-24 14:15
1,14.43,14.44,14.45,14.42,732600.0,10575052.0,2024,10,24,14,20,2024-10-24 14:20
2,14.44,14.48,14.49,14.44,646700.0,9356777.0,2024,10,24,14,25,2024-10-24 14:25
3,14.49,14.48,14.50,14.47,432200.0,6261785.0,2024,10,24,14,30,2024-10-24 14:30
4,14.47,14.48,14.49,14.46,526800.0,7624959.0,2024,10,24,14,35,2024-10-24 14:35
...,...,...,...,...,...,...,...,...,...,...,...,...
794,12.69,12.72,12.73,12.68,479400.0,6085969.0,2024,11,18,10,55,2024-11-18 10:55
795,12.72,12.79,12.79,12.72,1759100.0,22451982.0,2024,11,18,11,0,2024-11-18 11:00
796,12.79,12.73,12.79,12.72,782000.0,9974316.0,2024,11,18,11,5,2024-11-18 11:05
797,12.73,12.73,12.74,12.72,426800.0,5431590.0,2024,11,18,11,10,2024-11-18 11:10
798,12.73,12.70,12.75,12.70,569200.0,7246116.0,2024,11,18,11,15,2024-11-18 11:15

In [99]:
dff = api.to_df(api.get_security_bars(0, 1, '600489', 0, 799))
fig = px.density_heatmap(dff, x='hour',y='day',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=7,nbinsy=31,text_auto='.2r')
fig.show()

日交易额统计

In [ ]:
dff = api.to_df(api.get_security_bars(9, 0, '000001', 0, 799))

In [81]:

fig = px.density_heatmap(dff, x='day',y='month',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=31,nbinsy=12,text_auto='.2r')
fig.show()

In [ ]:
fig = px.density_contour(df3, y="day",x='minute',z='vol',nbinsx=60,nbinsy=3, histfunc='sum')
# fig = px.density_contour(df3, y="hour",x='minute',z='vol',nbinsx=60,nbinsy=4, histfunc='sum')
# fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

==== 参数 --histfunc: 'count', 'sum', 'avg', 'min', or 'max'   --histnorm: 'percent', 'probability', 'density', or 'probability density'

In [107]:
import pandas as pd
import plotly.express as px
from sqlalchemy import create_engine
# eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxIndex')
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [108]:
idxDF = pd.read_sql('000001', eng)

In [109]:
# ,marginal_x="histogram", marginal_y="histogram"
fig = px.density_heatmap(idxDF[(idxDF['year']>2000) & (idxDF['year']<2025) ], x='day',y='month',z='amount',histfunc='min',histnorm='percent',nbinsx=35,nbinsy=12,text_auto='.2r')
fig.show()

In [ ]:
fig = px.density_heatmap(idxDF, x='month',y='year',z='amount',histfunc='avg',histnorm='percent',nbinsx=12,nbinsy=50,text_auto='.2f')
fig.show()

In [ ]:
fig = px.density_heatmap(df13, x='minute',y='hour',z='amount',histfunc='max',histnorm='percent' ,nbinsx=60,nbinsy=8,text_auto='.2')
fig.show()

In [110]:
opIndex= pd.read_sql('optIndexs',eng)
indexCode = '880682'
indexName = opIndex[opIndex['IndexCode']==indexCode]['IndexName'].values[0]

In [111]:
selDF = pd.read_sql(indexCode, eng)

shDF = pd.read_sql('000001', eng)
szDF = pd.read_sql('399001', eng)
hs300DF = pd.read_sql('000300', eng)
csa500DF = pd.read_sql('000510', eng)
cs500DF = pd.read_sql('000905', eng)
sh50DF = pd.read_sql('000016', eng)
kc50DF = pd.read_sql('000688', eng)
cs1000DF = pd.read_sql('000852', eng)

In [145]:
plData = pd.DataFrame()

In [146]:
plData['datetime'] = shDF.tail(1150)['datetime'].reset_index(drop=True)

In [ ]:
# plData = pd.merge(plData,selDF.tail(1150)[['datetime','close']].rename(columns={'close':indexName}),on='datetime',how='outer')

In [147]:
plData = pd.merge(plData,selDF.tail(1150)[['datetime','close']].rename(columns={'close':indexName}),on='datetime',how='outer')
plData = pd.merge(plData,shDF.tail(1150)[['datetime','close']].rename(columns={'close':'上证指数'}),on='datetime',how='outer')
plData = pd.merge(plData,szDF.tail(1150)[['datetime','close']].rename(columns={'close':'深证成指'}),on='datetime',how='outer')
plData = pd.merge(plData,hs300DF.tail(1150)[['datetime','close']].rename(columns={'close':'沪深300'}),on='datetime',how='outer')
plData = pd.merge(plData,csa500DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证A500'}),on='datetime',how='outer')
plData = pd.merge(plData,cs500DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证500'}),on='datetime',how='outer')
plData = pd.merge(plData,sh50DF.tail(1150)[['datetime','close']].rename(columns={'close':'上证50'}),on='datetime',how='outer')
plData = pd.merge(plData,kc50DF.tail(1150)[['datetime','close']].rename(columns={'close':'科创50'}),on='datetime',how='outer')
plData = pd.merge(plData,cs1000DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证1000'}),on='datetime',how='outer')

In [148]:
plData

,datetime,华为海思,上证指数,深证成指,沪深300,中证A500,中证500,上证50,科创50,中证1000
0,2020-02-20 15:00,NaN,3030.15,11509.091,4144.66,NaN,5706.71,2978.18,1348.34,6134.39
1,2020-02-21 15:00,NaN,3039.67,11629.701,4149.49,4721.95,5784.03,2968.14,1346.86,6243.48
2,2020-02-24 15:00,NaN,3031.23,11772.381,4132.84,4723.18,5865.47,2930.03,1351.71,6380.41
3,2020-02-25 15:00,NaN,3013.05,11856.081,4123.85,4722.04,5897.72,2909.32,1367.37,6407.14
4,2020-02-26 15:00,NaN,2987.93,11497.551,4073.02,4636.17,5743.39,2901.67,1288.24,6221.84
...,...,...,...,...,...,...,...,...,...,...
1146,2024-11-11 15:00,1333.28,3470.07,11388.570,4131.13,4913.93,6330.62,2753.74,1073.84,6579.01
1147,2024-11-12 15:00,1312.24,3421.97,11314.460,4085.74,4862.39,6263.88,2712.27,1050.54,6491.97
1148,2024-11-13 15:00,1328.29,3439.28,11359.290,4110.89,4883.98,6259.84,2728.23,1061.37,6474.39
1149,2024-11-14 15:00,1279.25,3379.84,11037.780,4039.62,4779.67,6078.31,2704.15,1027.32,6272.19
1150,2024-11-15 15:00,1241.71,3330.73,10748.970,3968.83,4687.89,5924.48,2671.45,986.88,6125.51

In [38]:

plData[indexName] = selDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['上证指数'] = szDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['深证成指'] = szDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['沪深300'] = hs300DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证A500'] = csa500DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证500'] = cs500DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['上证50'] = sh50DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['科创50'] = kc50DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证1000'] = cs1000DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')

NameError: name 'selDF' is not defined

In [40]:
plData

NameError: name 'plData' is not defined

In [124]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [125]:
ddd = plData.set_index('datetime').apply(normalize, axis=0)

In [126]:
fig = px.line(ddd.reset_index(),x='datetime', y=plData.columns,line_shape='linear')
# fig = px.area(ddd.reset_index(),x='datetime', y=plData.columns)

fig.update_xaxes(showspikes=True, spikecolor="black", spikesnap="cursor", spikemode="across",spikethickness=0.6)
fig.update_yaxes(showspikes=True, spikecolor="black", spikesnap="cursor", spikemode="across",spikethickness=0.6)
fig.update_traces(hovertemplate='%{y:.2f}')
fig.update_layout(hovermode='x')
fig.show(config={'scrollZoom': True,'displaylogo':False})