In [191]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

### 深圳（0）上海（1）中证（62）国证（102）

In [ ]:
api.connect('180.153.18.170', 7709)

#### 市场标的规模

In [ ]:
api.to_df(api.get_security_count(0))

In [ ]:
api.to_df(api.get_security_list(0, 5000))

In [ ]:
api.to_df(api.get_security_list(0, 20218))

In [ ]:
api.to_df(api.get_security_list(1, 552))

In [ ]:
df = api.to_df(api.get_security_list(0, 0))
i = 1
while i<=260  :
    m = i*100
    df1 = api.to_df(api.get_security_list(0, m))
    df = pd.concat([df,df1])
    i=i+1

In [ ]:
df

In [ ]:
api.to_df(api.get_security_quotes([(0, '000001'), (1, '600300')]))

In [ ]:
api.to_df(api.get_index_bars(9, 102, 'CN5097', 0, 5))

#### 扩展市场

In [201]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(eapi.get_markets())

In [194]:
eapi.get_instrument_count()

68329

In [189]:
mcount = int(eapi.get_instrument_count()/1000)

In [193]:
df = api.to_df(eapi.get_instrument_info(start=0,count=1000))
i = 1
while i<=mcount :
    df1 = api.to_df(eapi.get_instrument_info(start=i*1000,count=1000))
    df = pd.concat([df,df1])
    i = i + 1

In [198]:
df[df['market']==62][['code','name']].reset_index(drop=True)

       code      name
0    000012      国债指数
1    000013      企债指数
2    000022      沪公司债
3    000061     沪企债30
4    000101      5年信用
..      ...       ...
665  H50055      沪大农业
666  H50069       港股通
667  N00300  沪深300净收益
668  N00905  中证500净收益
669  SHHKSI      沪港精明

[670 rows x 2 columns]

In [ ]:
api.to_df(eapi.get_instrument_info(start=68000,count=1000))

In [ ]:
api.to_df(eapi.get_instrument_quote_list(102,5,0,100))

In [207]:
api.to_df(eapi.get_instrument_bars(9, 62, 'H11030', 0, 5))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,2625.909180,2651.721436,2624.106445,2629.984863,1173858940,2,0.0,2025,8,19,15,0,2025-08-19 15:00,7925.310547
1,2630.786133,2658.980713,2614.186523,2657.509521,1174753986,8,0.0,2025,8,20,15,0,2025-08-20 15:00,8532.689453
2,2712.833008,2779.140381,2680.079834,2728.845703,1181580941,11,0.0,2025,8,21,15,0,2025-08-21 15:00,15199.637695
3,2740.640137,2745.457520,2700.150391,2730.112305,1176265556,9,0.0,2025,8,22,15,0,2025-08-22 15:00,10008.832031
4,2734.697754,2768.787598,2722.418945,2768.787598,1178147308,11,0.0,2025,8,25,15,0,2025-08-25 15:00,11846.480469

### 获取k线
* category 
```
 K线种类
0 5分钟K线 1 15分钟K线 2 30分钟K线 3 1小时K线 4 日K线
5 周K线
6 月K线
7 1分钟
8 1分钟K线 9 日K线
10 季K线
11 年K线
```
* market -> 市场代码 0:深圳，1:上海
* stockcode -> 证券代码;
* start -> 指定的范围开始位置;
* count -> 用户要请求的 K 线数目，最大值为 800

In [ ]:
api.to_df(api.get_security_bars(8, 0, '000001', 800, 800))

In [ ]:
api.to_df(api.get_index_bars(9, 1, '000001', 1, 21))

In [ ]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
eapi.to_df(eapi.get_instrument_bars(9, 62, '930791', 0, 10))

1分钟K线(8)1D240 2D480 3D720 bar, 5分钟K线(0)1D48 5D240 8D384 13D624 bar ,  日K线(9)
每次800   0SZ  1SH  ======= 在线分析

In [ ]:
from pytdx.hq import TdxHq_API
import pandas as pd
import plotly.express as px

import numpy as np 

api = TdxHq_API()

In [ ]:
api.connect('121.36.81.195', 7709)

In [ ]:
stockCodeSel = '002469'

In [ ]:
if stockCodeSel < '600000':
    m = 0
else:
    m = 1

In [ ]:
df3 = api.to_df(api.get_security_bars(8, m, stockCodeSel, 0, 720))
df5 = api.to_df(api.get_security_bars(0, m, stockCodeSel, 0, 240))
df13 = api.to_df(api.get_security_bars(0, m, stockCodeSel, 0, 624))
df21 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 21))
df55 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 55))
df144 = api.to_df(api.get_security_bars(9, m, stockCodeSel, 0, 144))

In [ ]:
df3

In [ ]:
df750 = api.to_df(api.get_index_bars(9, 1, '000001', 10, 799))

In [ ]:
api.to_df(api.get_index_bars(9, 1, '000510', 10, 799))

====== 数据说明df3三天1分钟k线数据, df5五天5分钟k线数据,df13十三天五分钟k线数据, 其他日k线数据

个股

In [ ]:
df3 = api.to_df(api.get_security_bars(8, 0, '000001', 0, 720))
df5 = api.to_df(api.get_security_bars(0, 0, '000001', 0, 240))
df13 = api.to_df(api.get_security_bars(0, 0, '000001', 0, 624))
df21 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 21))
df55 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 55))
df144 = api.to_df(api.get_security_bars(9, 0, '000001', 0, 144))

指数

In [ ]:
df3 = api.to_df(api.get_index_bars(8, 1, '000001', 0, 720))
df5 = api.to_df(api.get_index_bars(0, 1, '000001', 0, 240))
df13 = api.to_df(api.get_index_bars(0, 1, '000001', 0, 624))
df21 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 21))
df55 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 55))
df144 = api.to_df(api.get_index_bars(9, 1, '000001', 0, 144))

In [ ]:
lsDF = [df3,df5,df13,df21,df55,df144]
lsD = ['3D','5D',"13D","21D","55D","144D"]
con = [720,240,624,21,55,144]

价格 加 数量 权 (扩展数量加权：权重)

In [ ]:
def norm(df, column_name,n):
    min_val = df[column_name].min()
    max_val = df[column_name].max()
    normalized_column = (df[column_name] - min_val) / (max_val - min_val)
    scaled_column = normalized_column * (n - 1) + 1
    discrete_scaled_column = scaled_column.round().astype(int)
    return discrete_scaled_column

In [ ]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    weights = norm(df,'vol',con[n])
    weighted_data = np.repeat(df['close'], repeats=weights)
    dDF = pd.DataFrame(weighted_data)
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [ ]:
plDF

In [ ]:

fig = px.violin(plDF,y='close',facet_col='周期',facet_col_spacing=0.01,box=True,violinmode='overlay',title='价格加权')
fig.show()

In [ ]:
fig = px.box(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='价格加权')
fig.show()

价格

In [ ]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    # weights = norm(df,'amount',con[n])
    # weighted_data = np.repeat(df['close'], repeats=weights)
    dDF = pd.DataFrame(df['close'])
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [ ]:
fig = px.violin(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='价格')
fig.show()

In [ ]:
fig = px.box(plDF,y='close',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='价格')
fig.show()

数量

In [ ]:
plDF = pd.DataFrame()
for n, df in enumerate(lsDF):
    dDF = pd.DataFrame(df['amount'])
    dDF['周期'] = lsD[n]
    plDF = pd.concat([plDF,dDF])

In [ ]:
fig = px.violin(plDF[plDF['周期'].isin(['21D','55D','144D'])],y='amount',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='数量')
fig.show()

In [ ]:
fig = px.violin(plDF,y='amount',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='数量')
fig.show()

In [ ]:
fig = px.box(plDF,y='amount',facet_col='周期',facet_col_spacing=0.03,boxmode='group',title='数量')
fig.show()

In [ ]:
df144

In [ ]:
fig = px.violin(df3,y='vol',x='minute',box=True,violinmode='group',title='数量')
fig.show()

In [ ]:
fig = px.box(df3,y='vol',x='minute',boxmode='group',title='数量')
fig.show()

========== 三日分钟交易量密度图

In [ ]:

fig = px.density_contour(df3, y="hour",x='minute',z='amount',histfunc='sum',nbinsx=60,nbinsy=7)
fig.update_traces(contours_coloring="fill", contours_showlabels = True)

fig.show()

In [ ]:
fig = px.density_contour(df3, y="day",x='hour',z='amount',nbinsx=4,nbinsy=3, histfunc='sum')

fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

In [ ]:
fig = px.density_contour(df3, y="day",x='minute',z='amount',nbinsx=60,nbinsy=3, histfunc='sum')

fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

分钟交易额统计

In [ ]:
api.connect('121.36.81.195', 7709)

In [ ]:
dff = api.to_df(api.get_security_bars(8, 1, '600889', 0, 799))

In [ ]:
fig = px.density_heatmap(dff, x='minute',y='hour',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=60,nbinsy=7,text_auto='.2r')
fig.show()

In [ ]:
dff = api.to_df(api.get_security_bars(0, 0, '000002', 0, 799))
fig = px.density_heatmap(dff, x='minute',y='hour',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=12,nbinsy=7,text_auto='.2r')
fig.show()

小时交易额统计

In [ ]:
api.connect('121.36.81.195', 7709)

In [ ]:
api.to_df(api.get_security_bars(0, 1, '600489', 0, 799))

In [ ]:
dff = api.to_df(api.get_security_bars(0, 1, '600489', 0, 799))
fig = px.density_heatmap(dff, x='hour',y='day',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=7,nbinsy=31,text_auto='.2r')
fig.show()

日交易额统计

In [ ]:
dff = api.to_df(api.get_security_bars(9, 0, '000001', 0, 799))

In [ ]:

fig = px.density_heatmap(dff, x='day',y='month',z='amount',histfunc='sum',histnorm='percent' ,nbinsx=31,nbinsy=12,text_auto='.2r')
fig.show()

In [ ]:
fig = px.density_contour(df3, y="day",x='minute',z='vol',nbinsx=60,nbinsy=3, histfunc='sum')
# fig = px.density_contour(df3, y="hour",x='minute',z='vol',nbinsx=60,nbinsy=4, histfunc='sum')
# fig.update_traces(contours_coloring="fill", contours_showlabels = True)
fig.show()

==== 参数 --histfunc: 'count', 'sum', 'avg', 'min', or 'max'   --histnorm: 'percent', 'probability', 'density', or 'probability density'

In [ ]:
import pandas as pd
import plotly.express as px
from sqlalchemy import create_engine
# eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxIndex')
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
idxDF = pd.read_sql('000001', eng)

In [ ]:
# ,marginal_x="histogram", marginal_y="histogram"
fig = px.density_heatmap(idxDF[(idxDF['year']>2000) & (idxDF['year']<2025) ], x='day',y='month',z='amount',histfunc='min',histnorm='percent',nbinsx=35,nbinsy=12,text_auto='.2r')
fig.show()

In [ ]:
fig = px.density_heatmap(idxDF, x='month',y='year',z='amount',histfunc='avg',histnorm='percent',nbinsx=12,nbinsy=50,text_auto='.2f')
fig.show()

In [ ]:
fig = px.density_heatmap(df13, x='minute',y='hour',z='amount',histfunc='max',histnorm='percent' ,nbinsx=60,nbinsy=8,text_auto='.2')
fig.show()

In [ ]:
opIndex= pd.read_sql('optIndexs',eng)
indexCode = '880682'
indexName = opIndex[opIndex['IndexCode']==indexCode]['IndexName'].values[0]

In [ ]:
selDF = pd.read_sql(indexCode, eng)

shDF = pd.read_sql('000001', eng)
szDF = pd.read_sql('399001', eng)
hs300DF = pd.read_sql('000300', eng)
csa500DF = pd.read_sql('000510', eng)
cs500DF = pd.read_sql('000905', eng)
sh50DF = pd.read_sql('000016', eng)
kc50DF = pd.read_sql('000688', eng)
cs1000DF = pd.read_sql('000852', eng)

In [ ]:
plData = pd.DataFrame()

In [ ]:
plData['datetime'] = shDF.tail(1150)['datetime'].reset_index(drop=True)

In [ ]:
# plData = pd.merge(plData,selDF.tail(1150)[['datetime','close']].rename(columns={'close':indexName}),on='datetime',how='outer')

In [ ]:
plData = pd.merge(plData,selDF.tail(1150)[['datetime','close']].rename(columns={'close':indexName}),on='datetime',how='outer')
plData = pd.merge(plData,shDF.tail(1150)[['datetime','close']].rename(columns={'close':'上证指数'}),on='datetime',how='outer')
plData = pd.merge(plData,szDF.tail(1150)[['datetime','close']].rename(columns={'close':'深证成指'}),on='datetime',how='outer')
plData = pd.merge(plData,hs300DF.tail(1150)[['datetime','close']].rename(columns={'close':'沪深300'}),on='datetime',how='outer')
plData = pd.merge(plData,csa500DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证A500'}),on='datetime',how='outer')
plData = pd.merge(plData,cs500DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证500'}),on='datetime',how='outer')
plData = pd.merge(plData,sh50DF.tail(1150)[['datetime','close']].rename(columns={'close':'上证50'}),on='datetime',how='outer')
plData = pd.merge(plData,kc50DF.tail(1150)[['datetime','close']].rename(columns={'close':'科创50'}),on='datetime',how='outer')
plData = pd.merge(plData,cs1000DF.tail(1150)[['datetime','close']].rename(columns={'close':'中证1000'}),on='datetime',how='outer')

In [ ]:
plData

In [ ]:

plData[indexName] = selDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['上证指数'] = szDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['深证成指'] = szDF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['沪深300'] = hs300DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证A500'] = csa500DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证500'] = cs500DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['上证50'] = sh50DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['科创50'] = kc50DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')
plData['中证1000'] = cs1000DF.tail(1150)['close'].reset_index(drop=True).set_index('datetime')

In [ ]:
plData

In [ ]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [ ]:
ddd = plData.set_index('datetime').apply(normalize, axis=0)

In [ ]:
fig = px.line(ddd.reset_index(),x='datetime', y=plData.columns,line_shape='linear')
# fig = px.area(ddd.reset_index(),x='datetime', y=plData.columns)

fig.update_xaxes(showspikes=True, spikecolor="black", spikesnap="cursor", spikemode="across",spikethickness=0.6)
fig.update_yaxes(showspikes=True, spikecolor="black", spikesnap="cursor", spikemode="across",spikethickness=0.6)
fig.update_traces(hovertemplate='%{y:.2f}')
fig.update_layout(hovermode='x')
fig.show(config={'scrollZoom': True,'displaylogo':False})