In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
sh = open('D:/new_tdx/T0002/hq_cache/shm.tnf', 'r',encoding="GBK", errors='ignore').read()

In [ ]:
re.findall(r"00\d{4}.{30}", sh)

In [ ]:
from datetime import datetime

In [ ]:
datetime.now().strftime("%Y-%m-%d")

In [ ]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
dd = pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
dd['dp'] = current_date

In [ ]:
dd

In [ ]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

In [ ]:
pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [ ]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

In [4]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [2]:
gz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxGZIndexs.xlsx', dtype={'IndexCode':object})
gzak = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/gzIndex.xlsx', dtype={'IndexCode':object})

In [7]:
pd.merge(m3,gzak, on=['IndexCode'],how='inner')

,IndexCode,IndexName_x,Market,MarketName_x,MarketCode,From_x,IndexName_y,Num,MarketName_y,From_y
0,399001,深证成指,ST,SZ,0,TDX,深证成指,500,GZ,AK
1,399002,深成指R,ST,SZ,0,TDX,深成指R,500,GZ,AK
2,399003,成份Ｂ指,ST,SZ,0,TDX,成份Ｂ指,10,GZ,AK
3,399004,深证100R,ST,SZ,0,TDX,深证100R,100,GZ,AK
4,399005,中小100,ST,SZ,0,TDX,中小100,100,GZ,AK
...,...,...,...,...,...,...,...,...,...,...
292,399697,中关村60,ST,SZ,0,TDX,中关村60,60,GZ,AK
293,399698,优势成长,ST,SZ,0,TDX,优势成长,50,GZ,AK
294,399699,金融科技,ST,SZ,0,TDX,金融科技,0,GZ,AK
295,399750,深主板50,ST,SZ,0,TDX,深主板50,50,GZ,AK
296,399850,深证50,ST,SZ,0,TDX,深证50,50,GZ,AK

In [3]:
pd.merge(gz,gzak, on=['IndexCode'],how='inner')

    IndexCode Market  MarketCode      IndexName  Num MarketName From
0      470006     EX         102  创业板R(港币)(CNH)  100         GZ   AK
1      470007     EX         102  创业板R(美元)(CNH)  100         GZ   AK
2      470026     EX         102         深指ESGR  400         GZ   AK
3      470027     EX         102        100ESGR   80         GZ   AK
4      470028     EX         102         创指ESGR   80         GZ   AK
..        ...    ...         ...            ...  ...        ...  ...
838   PELHKDG     EX         102    中华港股通泛休闲娱乐R   30         GZ   AK
839   PSMHKDG     EX         102      中华国证港股物业R   50         GZ   AK
840   RETHKDG     EX         102     中华房地产信托基金R   30         GZ   AK
841   VALHKDG     EX         102       中华港股通价值R   40         GZ   AK
842   YLVHKDG     EX         102     中华港股通高息低波R   40         GZ   AK

[843 rows x 7 columns]

In [5]:
# zz.drop_duplicates(subset='IndexCode',inplace=True)
m3 = pd.concat([sh, sz])
m3.reset_index(drop=True, inplace=True)

In [ ]:
blkm = pd.merge(blk,m3.drop(columns='From'), on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [ ]:
m3cs = pd.merge(m3,cs[['IndexCode','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [ ]:
m3zz = pd.merge(m3,zz['IndexCode'], on='IndexCode',how='inner')

In [ ]:
pd.merge(cs,zz, on='IndexCode',how='inner')

In [ ]:
cszz = pd.merge(cs,zz, on='IndexCode',how='inner')

In [ ]:
m3cszz = pd.merge(m3,cszz[['IndexCode','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [ ]:
df1 = pd.concat([blkm,m3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df5[~((df5['IndexCode'].str.startswith('88')) & (df5['From'] == 'TDX'))]

In [ ]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [ ]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [ ]:
m3zz = pd.concat([zm,zzm]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
zzm3 = pd.concat([m3zz,m3]).drop_duplicates(subset='IndexCode',keep='first').reset_index(drop=True)

In [ ]:
dddf = pd.concat([blkm,zzm3]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode']).reset_index(drop=True)

In [ ]:
dddf['IndexSTL'] = dddf['IndexSTL'].fillna('指数')

In [ ]:
dddf

In [ ]:
dddf['From'].fillna('TDX', inplace=True)

In [ ]:
dddf

In [ ]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)

In [14]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd
from sqlalchemy import create_engine


eapi =  TdxExHq_API()
api = TdxHq_API()

In [15]:
li = gz['IndexCode'].to_list()

In [17]:
ll = []

In [18]:
with eapi.connect('47.112.95.207', 7720):
    # IndexLists=zz.IndexCode.to_list()   
    for i, IndexCode in enumerate(li):
        try:                
            # print('Index', i, '/', len(IndexLists))
            df = eapi.to_df(eapi.get_instrument_bars(9, 102, IndexCode, 0, 10))
            if df.empty:
                pass
                # print(IndexCode+'EMP !! ')
            else:
                ll.append(IndexCode)
                print(IndexCode+'EMP !! ')                
        except:
            print(IndexCode, 'EXCEPT !' )
            pass

970070EMP !!
980001EMP !!
980015EMP !!
980016EMP !!
980017EMP !!
980018EMP !!
980022EMP !!
980023EMP !!
980027EMP !!
980028EMP !!
980030EMP !!
980032EMP !!
980035EMP !!
980068EMP !!
980076EMP !!
980092EMP !!