In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [4]:
from datetime import datetime

current_date = datetime.now().strftime("%Y-%m-%d")

In [2]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [25]:
opt = pd.read_sql('optIndexs', eng)

In [23]:
optO = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexsO.xlsx',dtype={'IndexCode':object} )

In [27]:
tdxIndexs = opt[~(opt['IndexCode'].isin(optO['IndexCode']))]

In [32]:
tdxIndexs[tdxIndexs['MarketCode'] == 102]['IndexCode']

1354    970070
1355    980001
1356    980015
1357    980016
1358    980017
1359    980018
1360    980022
1361    980023
1362    980027
1363    980028
1364    980030
1365    980032
1366    980035
1367    980068
1368    980076
1369    980092
Name: IndexCode, dtype: object

In [19]:
akCons = pd.read_sql('IndexCons', eng)

In [22]:
akCons[akCons['StockCode']=='600271']

       IndexCode IndexName StockCode StockName IndexSTL          DP
525       880207      北京板块    600271      航天信息       地区  2025-08-30
10652     880493      软件服务    600271      航天信息       行业  2025-08-30
11895     880507      国防军工    600271      航天信息       概念  2025-08-30
15449     880533       物联网    600271      航天信息       概念  2025-08-30
19508     880555     财税数字化    600271      航天信息       概念  2025-08-30
...          ...       ...       ...       ...      ...         ...
171993    H50032      沪城交通    600271      航天信息       指数  2013-08-26
175273    931648   500 ESG    600271      航天信息       指数  2021-06-15
176759    H30552   沪港深通TMT    600271      航天信息       指数  2023-06-12
177151    H50035      沪智交通    600271      航天信息       指数  2014-12-15
178160    H30202      软件指数    600271      航天信息       指数  2022-06-13

[89 rows x 6 columns]

In [5]:
optInd = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [24]:
optSQL[~(optSQL['IndexCode'].isin(optO['IndexCode']))]

,IndexCode,IndexName,Market,MarketName,MarketCode,From,DP,IndexSTL,Num
5,000018,180金融,ST,SH,1,TDX,2007-12-10,行业,41.0
7,000020,中型综指,ST,SH,1,TDX,2008-05-12,规模,862.0
8,000021,180治理,ST,SH,1,TDX,2008-09-10,主题,100.0
9,000025,180基建,ST,SH,1,TDX,2008-12-15,主题,31.0
10,000026,180资源,ST,SH,1,TDX,2008-12-15,主题,18.0
...,...,...,...,...,...,...,...,...,...
1368,980076,通用航空,EX,GZ,102,TDX,None,None,50.0
1369,980092,CNIFCF,EX,GZ,102,TDX,None,None,100.0
1370,990001,中华半导体芯片,EX,ZZ,62,TDX,None,None,NaN
1426,H30106,H300金融服务,EX,ZZ,62,TDX,None,None,NaN
1507,SHHKSI,沪港精明,EX,ZZ,62,TDX,None,None,NaN

In [6]:
optInd[~(optInd['IndexCode'].isin(optSQL['IndexCode']))]

,IndexCode,IndexName,Market,MarketName,MarketCode,From,DP,IndexSTL,Num
5,000018,180金融,ST,SH,1,TDX,2007-12-10,行业,41.0
7,000020,中型综指,ST,SH,1,TDX,2008-05-12,规模,862.0
8,000021,180治理,ST,SH,1,TDX,2008-09-10,主题,100.0
9,000025,180基建,ST,SH,1,TDX,2008-12-15,主题,31.0
10,000026,180资源,ST,SH,1,TDX,2008-12-15,主题,18.0
...,...,...,...,...,...,...,...,...,...
1400,CESHKB,中华香港生物科技,EX,ZZ,62,TDX,NaN,NaN,NaN
1401,CESHKM,中华香港内地指数,EX,ZZ,62,TDX,NaN,NaN,NaN
1402,CESP50,中华港股通优选50,EX,ZZ,62,TDX,NaN,NaN,NaN
1462,H30106,H300金融服务,EX,ZZ,62,TDX,NaN,NaN,NaN
1545,SHHKSI,沪港精明,EX,ZZ,62,TDX,NaN,NaN,NaN

In [5]:
blkDF['DP'] = current_date
akDF['IndexSTL'] = '指数'

In [2]:
OPTdf = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx',dtype={'IndexCode':object})
EMPdf = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/akEMPB.xlsx', dtype={'IndexCode':object})

In [5]:
OPTdf[~OPTdf['IndexCode'].isin(EMPdf['IndexCode'])].set_index('IndexCode')

,IndexName,Market,MarketName,MarketCode,From,DP,IndexSTL,Num
IndexCode,,,,,,,,
000001,上证指数,ST,SH,1,TDX,1991-07-15,综合,2235.0
000009,上证380,ST,SH,1,TDX,2010-11-29,规模,380.0
000010,上证180,ST,SH,1,TDX,2002-07-01,规模,180.0
000015,红利指数,ST,SH,1,TDX,2005-01-04,策略,50.0
000016,上证50,ST,SH,1,TDX,2004-01-02,规模,50.0
...,...,...,...,...,...,...,...,...
H50052,上国改革,EX,SH,62,CS,2014-10-28,主题,50.0
H50053,上证移动,EX,SH,62,CS,2014-07-11,主题,46.0
H50054,上证休闲,EX,SH,62,CS,2014-07-21,主题,50.0
H50055,沪大农业,EX,SH,62,CS,2014-07-22,主题,50.0
SHHKSI,沪港精明,EX,ZZ,62,TDX,NaN,NaN,NaN

In [19]:
401 % 200 == 0

False

In [14]:
thresholds = [300, 600, 900, 1200, 1500, 1800]
n = 600
if n in thresholds:
    print('300')
else:
    print(n)

300

In [4]:
dropdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexs.xlsx',dtype={'IndexCode':object})
empdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/empIndexs.xlsx', dtype={'IndexCode':object})

In [5]:
dropdf.loc[dropdf['IndexCode'].isin(empdf['IndexCode']), 'From'] = 'EMP'

In [ ]:
m = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/IndexM.xlsx', dtype={'IndexCode':object})
zg = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
df62 =m[m['MarketCode']==62]
dff =m[~(m['MarketCode']==62)]

In [ ]:
set(df62['IndexCode'])-set(zg['IndexCode'])

In [ ]:
mzg = pd.merge(df62,zg['IndexCode'],on='IndexCode',how='inner')

In [ ]:
sh = open('D:/new_tdx/T0002/hq_cache/shm.tnf', 'r',encoding="GBK", errors='ignore').read()

In [ ]:
re.findall(r"00\d{4}.{30}", sh)

In [ ]:
from datetime import datetime

In [ ]:
datetime.now().strftime("%Y-%m-%d")

In [ ]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
dd = pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
dd['dp'] = current_date

In [ ]:
pd.d

In [ ]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

In [ ]:
pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [ ]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

In [2]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
# zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
# sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
# sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})
dpdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexDP.xlsx', dtype={'IndexCode':object})
numdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexNum.xlsx', dtype={'IndexCode':object})

In [ ]:
pd.merge(m3,gzak, on=['IndexCode'],how='inner')

In [ ]:
pd.merge(gz,gzak, on=['IndexCode'],how='inner')

In [4]:
# zz.drop_duplicates(subset='IndexCode',inplace=True)
zzgz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})
m3 = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHSZIndexs.xlsx', dtype={'IndexCode':object})
m3.reset_index(drop=True, inplace=True)

In [ ]:
blkm = pd.merge(blk,m3.drop(columns='From'), on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [5]:
m3cs = pd.merge(m3,cs[['IndexCode','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [7]:
m3zz = pd.merge(m3,zzgz['IndexCode'], on='IndexCode',how='inner')

In [9]:
cszz = pd.merge(cs,zzgz[['IndexCode','Market','MarketCode']], on='IndexCode',how='inner')

In [10]:
m3cszz = pd.merge(m3,cszz[['IndexCode','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [11]:
# df1 = pd.concat([blkm,m3]).drop_duplicates(subset='IndexCode',keep='first')
df1 = pd.concat([blk,m3]).drop_duplicates(subset='IndexCode',keep='first')

In [12]:
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')

In [13]:
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')

In [14]:
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')

In [15]:
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [16]:
df55 = pd.concat([df5,zzgz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [17]:
dpm = pd.merge(df55[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'Num', 'IndexSTL']],dpdf[['IndexCode','DP']], on='IndexCode',how='inner')

In [18]:
df6 = pd.concat([dpm,df55]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [19]:
mdf = pd.merge(df6[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'DP', 'IndexSTL']],numdf[['IndexCode','Num']], on='IndexCode',how='inner')

In [20]:
df7 = pd.concat([mdf,df6]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df5[~((df5['IndexCode'].str.startswith('88')) & (df5['From'] == 'TDX'))]

In [ ]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [ ]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [ ]:
m3zz = pd.concat([zm,zzm]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
zzm3 = pd.concat([m3zz,m3]).drop_duplicates(subset='IndexCode',keep='first').reset_index(drop=True)

In [ ]:
dddf = pd.concat([blkm,zzm3]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode']).reset_index(drop=True)

In [ ]:
dddf['IndexSTL'] = dddf['IndexSTL'].fillna('指数')

In [ ]:
dddf

In [ ]:
dddf['From'].fillna('TDX', inplace=True)

In [ ]:
dddf

In [ ]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)

In [ ]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd
from sqlalchemy import create_engine


eapi =  TdxExHq_API()
api = TdxHq_API()

In [ ]:
li = gz['IndexCode'].to_list()

In [ ]:
ll = []

In [ ]:
with eapi.connect('47.112.95.207', 7720):
    # IndexLists=zz.IndexCode.to_list()   
    for i, IndexCode in enumerate(li):
        try:                
            # print('Index', i, '/', len(IndexLists))
            df = eapi.to_df(eapi.get_instrument_bars(9, 102, IndexCode, 0, 10))
            if df.empty:
                pass
                # print(IndexCode+'EMP !! ')
            else:
                ll.append(IndexCode)
                print(IndexCode+'EMP !! ')                
        except:
            print(IndexCode, 'EXCEPT !' )
            pass