In [1]:
from sqlalchemy import create_engine
import pandas as pd
import re

In [ ]:
import plotly.express as px

In [2]:
engB = create_engine('postgresql+psycopg2://sa:11111111@10.145.254.56/StockBas')

In [3]:
df = pd.read_sql('akStockIC', engB)

In [9]:
df['ICS'].drop_duplicates()

0    中国上市公司协会上市公司行业分类标准
1              巨潮行业分类标准
2            申银万国行业分类标准
3              中证行业分类标准
Name: ICS, dtype: object

In [16]:
ddf = df[df['ICS']=='申银万国行业分类标准']['IC1'].drop_duplicates()

In [32]:
df[df['ICS']=='申银万国行业分类标准']['IC1'].value_counts()

IC1
机械设备    670
电子      622
医药生物    554
基础化工    497
电力设备    414
计算机     381
汽车      317
轻工制造    174
建筑装饰    172
有色金属    168
环保      159
传媒      156
国防军工    152
交通运输    144
通信      139
公用事业    138
食品饮料    132
纺织服饰    122
房地产     119
农林牧渔    118
商贸零售    112
社会服务    107
家用电器    107
非银金融     85
建筑材料     82
石油石化     51
钢铁       47
煤炭       42
银行       42
美容护理     35
综合       32
Name: count, dtype: int64

In [35]:
df[df['ICS']=='申银万国行业分类标准']['IC1'].unique()

array(['银行', '房地产', '计算机', '商贸零售', '机械设备', '电力设备', '建筑装饰', '建筑材料', '家用电器',
       '汽车', '纺织服饰', '农林牧渔', '电子', '综合', '公用事业', '医药生物', '通信', '环保',
       '石油石化', '有色金属', '交通运输', '传媒', '非银金融', '基础化工', '社会服务', '轻工制造',
       '国防军工', '美容护理', '食品饮料', '煤炭', '钢铁'], dtype=object)

In [ ]:
df[df['ICS']=='申银万国行业分类标准']['IC1']

IC1
True     6059
False      31
Name: count, dtype: int64

In [4]:
df.head()

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode
0,000001,平安银行,中国上市公司协会上市公司行业分类标准,2024-02-08,None,货币金融服务,None,金融业,J66,008001
1,000001,平安银行,巨潮行业分类标准,2019-05-08,综合性银行,银行,银行,金融,Z07010101,008002
2,000001,平安银行,申银万国行业分类标准,2021-07-30,股份制银行Ⅲ,股份制银行Ⅲ,股份制银行Ⅱ,银行,S480301,008003
3,000001,平安银行,中证行业分类标准,2021-12-17,综合性银行,商业银行,银行,金融,40101010,008014
4,000002,万 科Ａ,中国上市公司协会上市公司行业分类标准,2024-02-08,None,房地产业,None,房地产业,K70,008001

In [2]:
engI = create_engine('postgresql+psycopg2://sa:11111111@10.145.254.56/tdxIndex')
engS = create_engine('postgresql+psycopg2://sa:11111111@10.145.254.56/tdxStocks')

In [26]:
IndexLists = pd.read_sql('optIndexs', engI)[['IndexCode','IndexName']].values.tolist()

In [28]:
IndexLists[1]

['000009', '上证380']

In [3]:
df = pd.read_sql('000001', engI)

In [29]:
(df['close'].pct_change(5)*100).round(2)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
6144   -1.18
6145   -1.26
6146   -1.32
6147   -0.04
6148    2.91
Name: close, Length: 6149, dtype: float64

In [30]:
df['datetime'].str[:10]

0       2000-05-15
1       2000-05-16
2       2000-05-17
3       2000-05-18
4       2000-05-19
           ...
6144    2025-09-05
6145    2025-09-08
6146    2025-09-09
6147    2025-09-10
6148    2025-09-11
Name: datetime, Length: 6149, dtype: object

In [14]:
df.head(6)

,datetime,open,close,high,low,vol,amount,year,month,day,hour,minute,up_count,down_count
0,2000-05-15 15:00,1722.63,1704.58,1726.72,1695.53,71012.0,6.869446e+09,2000,5,15,15,0,179,328
1,2000-05-16 15:00,1706.72,1724.53,1725.90,1706.72,53422.0,5.462887e+09,2000,5,16,15,0,453,54
2,2000-05-17 15:00,1727.42,1725.39,1736.27,1722.71,52691.0,5.512705e+09,2000,5,17,15,0,216,291
3,2000-05-18 15:00,1725.60,1758.53,1758.54,1719.84,83623.0,8.150311e+09,2000,5,18,15,0,470,28
4,2000-05-19 15:00,1761.79,1777.82,1777.98,1754.88,95605.0,1.038733e+10,2000,5,19,15,0,401,98
5,2000-05-22 15:00,1785.89,1824.73,1830.92,1783.30,147285.0,1.562901e+10,2000,5,22,15,0,513,24

In [45]:
fig = px.line(
    df.loc[df['datetime']>='2025-01-01'],
    x = 'datetime',
    y = ['open','close','high','low'],
)
fig.show()

In [ ]:
import plotly.graph_objects  as go 
from plotly.subplots  import make_subplots

In [ ]:
ddf = df.loc[df['datetime']>='2025-01-01']

In [41]:
# 1. 创建双轴画布 
fig = make_subplots(specs=[[{"secondary_y": True}]])
 
# 2. 添加主Y轴数据（大数值量级）
fig.add_trace( 
    go.Scatter(
        x=ddf['datetime'], 
        y=ddf['vol'],
        name="销售额",
        line=dict(color='#FF6B6B', width=3),
        hovertemplate="%{y:.1f}亿<extra></extra>"
    ),
    secondary_y=False 
)

In [ ]:
icdf = pd.read_sql('IndexCons', eng)

In [ ]:
icdf[icdf['IndexCode']=='931151']

In [ ]:
tdxIndexs = opt[opt['IndexCode'].str.startswith('881')]

In [ ]:
sh = tdxIndexs[tdxIndexs['MarketCode'] == 1 ]
sz = tdxIndexs[tdxIndexs['MarketCode'] == 0 ]
zz = tdxIndexs[tdxIndexs['MarketCode'] == 62 ]
gz = tdxIndexs[tdxIndexs['MarketCode'] == 102 ]

In [ ]:
opt[opt['IndexCode'].str.startswith('881')]

In [ ]:
rawD = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
IndexLists = rawD[~rawD['From'].isin(['TDXBLK','EMP'])][['IndexCode','IndexName','IndexSTL']].values.tolist()

In [ ]:
import random
random.shuffle(IndexLists)

In [ ]:
IndexLists[10]

In [ ]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
dpdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexDP.xlsx', dtype={'IndexCode':object})
cnidf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/cniGzSzIndexs.xlsx', dtype={'IndexCode':object})
zzgz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxApiZzGzIndexs.xlsx', dtype={'IndexCode':object})
m3 = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxShSzIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
m3cs = pd.merge(m3.drop('MarketName',axis=1),cs[['IndexCode','MarketName','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [ ]:
m3zz = pd.merge(m3.drop('MarketName',axis=1),zzgz[['IndexCode','MarketName']], on='IndexCode',how='inner')

In [ ]:
cszz = pd.merge(cs,zzgz[['IndexCode','Market','MarketCode']], on='IndexCode',how='inner')
m3cszz = pd.merge(m3.drop('MarketName',axis=1),cszz[['IndexCode','MarketName','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [ ]:
df1 = pd.concat([blk,m3]).drop_duplicates(subset='IndexCode',keep='first')
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])
df6 = pd.concat([df5,zzgz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
dpm = pd.merge(df6[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'Num', 'IndexSTL']],dpdf[['IndexCode','DP']], on='IndexCode',how='inner')
df7 = pd.concat([dpm,df6]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
mdf = pd.merge(df7[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode',
       'DP','From']],cnidf[['IndexCode','Num', 'IndexSTL']], on='IndexCode',how='inner')

In [ ]:
df8 = pd.concat([mdf,df7]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
dropdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/dropIndexs.xlsx', dtype={'IndexCode':object})
empdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/empIndexs.xlsx', dtype={'IndexCode':object})
tdxdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
optDF = pd.concat([tdxdf,dropdf]).drop_duplicates(subset='IndexCode',keep=False).sort_values(by=['IndexCode','MarketCode'])

optDF.loc[optDF['IndexCode'].isin(empdf['IndexCode']), 'From'] = 'EMP'

In [ ]:
optDF.dropna(subset='IndexSTL')

In [ ]:
optDF[optDF.duplicated(subset='IndexName',keep=False)]

In [ ]:
df6[df6.duplicated(subset='IndexName',keep=False)]

In [ ]:
from datetime import datetime

current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
opt = pd.read_sql('optIndexs', eng)

In [ ]:
optO = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexsO.xlsx',dtype={'IndexCode':object} )

In [ ]:
tdxIndexs = opt[~(opt['IndexCode'].isin(optO['IndexCode']))]

In [ ]:
tdxIndexs[tdxIndexs['MarketCode'] == 102]['IndexCode']

In [ ]:
akCons = pd.read_sql('IndexCons', eng)

In [ ]:
akCons[akCons['StockCode']=='600271']

In [ ]:
optInd = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
optSQL[~(optSQL['IndexCode'].isin(optO['IndexCode']))]

In [ ]:
optInd[~(optInd['IndexCode'].isin(optSQL['IndexCode']))]

In [ ]:
blkDF['DP'] = current_date
akDF['IndexSTL'] = '指数'

In [ ]:
OPTdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx',dtype={'IndexCode':object})
EMPdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akEMPB.xlsx', dtype={'IndexCode':object})

In [ ]:
OPTdf[OPTdf['IndexCode'].isin(EMPdf['IndexCode'])]

In [ ]:
OPTdf[OPTdf.duplicated(subset='IndexName',keep=False)]

In [ ]:
finaDF = OPTdf[~OPTdf['IndexCode'].isin(EMPdf['IndexCode'])]

In [ ]:
ofdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/FinaIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
finaDF[~finaDF['IndexCode'].isin(ofdf['IndexCode'])]

In [ ]:
ofdf[~ofdf['IndexCode'].isin(finaDF['IndexCode'])]

In [ ]:
OPTdf[~OPTdf['IndexCode'].isin(EMPdf['IndexCode'])].set_index('IndexCode')

In [ ]:
401 % 200 == 0

In [ ]:
thresholds = [300, 600, 900, 1200, 1500, 1800]
n = 600
if n in thresholds:
    print('300')
else:
    print(n)

In [ ]:
fdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/FinaIndexs.xlsx',dtype={'IndexCode':object})
adf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akGzSzIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
fdf.loc[fdf['IndexCode'].isin(adf['IndexCode']),'IndexSTL'] = adf['IndexSTL']

In [ ]:
adf[['IndexCode','IndexSTL']]

In [ ]:
mdf = pd.merge(fdf.drop('IndexSTL',axis=1), adf[['IndexCode','IndexSTL']], on='IndexCode', how='inner')

In [ ]:
 ddf = pd.concat([mdf,fdf]).drop_duplicates(subset='IndexCode', keep='first')

In [ ]:
ddf.drop_duplicates(subset='IndexName',keep='first')

In [ ]:
fdf[fdf['IndexCode'].isin(adf['IndexCode'])]

In [ ]:
sdf[sdf['IndexCode'].isin(tdf['IndexCode'])]

In [ ]:
dropdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexs.xlsx',dtype={'IndexCode':object})
empdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/empIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
dropdf.loc[dropdf['IndexCode'].isin(empdf['IndexCode']), 'From'] = 'EMP'

In [ ]:
m = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/IndexM.xlsx', dtype={'IndexCode':object})
zg = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
df62 =m[m['MarketCode']==62]
dff =m[~(m['MarketCode']==62)]

In [ ]:
set(df62['IndexCode'])-set(zg['IndexCode'])

In [ ]:
mzg = pd.merge(df62,zg['IndexCode'],on='IndexCode',how='inner')

In [ ]:
sh = open('D:/new_tdx/T0002/hq_cache/shm.tnf', 'r',encoding="GBK", errors='ignore').read()

In [ ]:
re.findall(r"500\d{2}.{30}", sh)

In [ ]:
re.findall(r"00\d{4}.{30}", sh)

In [ ]:
from datetime import datetime

In [ ]:
datetime.now().strftime("%Y-%m-%d")

In [ ]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
dd = pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
dd['dp'] = current_date

In [ ]:
pd.d

In [ ]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

In [ ]:
pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [ ]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

In [ ]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
# zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
# sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
# sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})
dpdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexDP.xlsx', dtype={'IndexCode':object})
numdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexNum.xlsx', dtype={'IndexCode':object})

In [ ]:
pd.merge(m3,gzak, on=['IndexCode'],how='inner')

In [ ]:
pd.merge(gz,gzak, on=['IndexCode'],how='inner')

In [ ]:
# zz.drop_duplicates(subset='IndexCode',inplace=True)
zzgz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})
m3 = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHSZIndexs.xlsx', dtype={'IndexCode':object})
m3.reset_index(drop=True, inplace=True)

In [ ]:
blkm = pd.merge(blk,m3.drop(columns='From'), on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [ ]:
m3cs = pd.merge(m3,cs[['IndexCode','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [ ]:
m3zz = pd.merge(m3,zzgz['IndexCode'], on='IndexCode',how='inner')

In [ ]:
cszz = pd.merge(cs,zzgz[['IndexCode','Market','MarketCode']], on='IndexCode',how='inner')

In [ ]:
m3cszz = pd.merge(m3,cszz[['IndexCode','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [ ]:
# df1 = pd.concat([blkm,m3]).drop_duplicates(subset='IndexCode',keep='first')
df1 = pd.concat([blk,m3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df55 = pd.concat([df5,zzgz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
dpm = pd.merge(df55[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'Num', 'IndexSTL']],dpdf[['IndexCode','DP']], on='IndexCode',how='inner')

In [ ]:
df6 = pd.concat([dpm,df55]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
mdf = pd.merge(df6[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'DP', 'IndexSTL']],numdf[['IndexCode','Num']], on='IndexCode',how='inner')

In [ ]:
df7 = pd.concat([mdf,df6]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df5[~((df5['IndexCode'].str.startswith('88')) & (df5['From'] == 'TDX'))]

In [ ]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [ ]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [ ]:
m3zz = pd.concat([zm,zzm]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
zzm3 = pd.concat([m3zz,m3]).drop_duplicates(subset='IndexCode',keep='first').reset_index(drop=True)

In [ ]:
dddf = pd.concat([blkm,zzm3]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode']).reset_index(drop=True)

In [ ]:
dddf['IndexSTL'] = dddf['IndexSTL'].fillna('指数')

In [ ]:
dddf

In [ ]:
dddf['From'].fillna('TDX', inplace=True)

In [ ]:
dddf

In [ ]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)

In [ ]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd
from sqlalchemy import create_engine


eapi =  TdxExHq_API()
api = TdxHq_API()

In [ ]:
li = gz['IndexCode'].to_list()

In [ ]:
ll = []

In [ ]:
with eapi.connect('47.112.95.207', 7720):
    # IndexLists=zz.IndexCode.to_list()   
    for i, IndexCode in enumerate(li):
        try:                
            # print('Index', i, '/', len(IndexLists))
            df = eapi.to_df(eapi.get_instrument_bars(9, 102, IndexCode, 0, 10))
            if df.empty:
                pass
                # print(IndexCode+'EMP !! ')
            else:
                ll.append(IndexCode)
                print(IndexCode+'EMP !! ')                
        except:
            print(IndexCode, 'EXCEPT !' )
            pass