In [2]:
from sqlalchemy import create_engine
import pandas as pd
import re

In [3]:
rawD = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [4]:
IndexLists = rawD[~rawD['From'].isin(['TDXBLK','EMP'])][['IndexCode','IndexName','IndexSTL']].values.tolist()

In [5]:
import random
random.shuffle(IndexLists)

In [ ]:
IndexLists[10]

['399987', '中证酒', '主题']

:

In [10]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
dpdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexDP.xlsx', dtype={'IndexCode':object})
cnidf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/cniGzSzIndexs.xlsx', dtype={'IndexCode':object})
zzgz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxApiZzGzIndexs.xlsx', dtype={'IndexCode':object})
m3 = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxShSzIndexs.xlsx', dtype={'IndexCode':object})

In [44]:
m3cs = pd.merge(m3.drop('MarketName',axis=1),cs[['IndexCode','MarketName','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [45]:
m3zz = pd.merge(m3.drop('MarketName',axis=1),zzgz[['IndexCode','MarketName']], on='IndexCode',how='inner')

In [47]:
cszz = pd.merge(cs,zzgz[['IndexCode','Market','MarketCode']], on='IndexCode',how='inner')
m3cszz = pd.merge(m3.drop('MarketName',axis=1),cszz[['IndexCode','MarketName','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [48]:
df1 = pd.concat([blk,m3]).drop_duplicates(subset='IndexCode',keep='first')
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])
df6 = pd.concat([df5,zzgz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [49]:
dpm = pd.merge(df6[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'Num', 'IndexSTL']],dpdf[['IndexCode','DP']], on='IndexCode',how='inner')
df7 = pd.concat([dpm,df6]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [50]:
mdf = pd.merge(df7[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode',
       'DP','From']],cnidf[['IndexCode','Num', 'IndexSTL']], on='IndexCode',how='inner')

In [51]:
df8 = pd.concat([mdf,df7]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [52]:
dropdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/dropIndexs.xlsx', dtype={'IndexCode':object})
empdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/empIndexs.xlsx', dtype={'IndexCode':object})
tdxdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexs.xlsx', dtype={'IndexCode':object})

In [53]:
optDF = pd.concat([tdxdf,dropdf]).drop_duplicates(subset='IndexCode',keep=False).sort_values(by=['IndexCode','MarketCode'])

optDF.loc[optDF['IndexCode'].isin(empdf['IndexCode']), 'From'] = 'EMP'

In [55]:
optDF.dropna(subset='IndexSTL')

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
0,000001,上证指数,ST,SH,1,1991-07-15,TDX,2235.0,综合
8,000009,上证380,ST,SH,1,2010-11-29,TDX,380.0,规模
9,000010,上证180,ST,SH,1,2002-07-01,TDX,180.0,规模
13,000015,红利指数,ST,SH,1,2005-01-04,TDX,50.0,策略
14,000016,上证50,ST,SH,1,2004-01-02,TDX,50.0,规模
...,...,...,...,...,...,...,...,...,...
1689,H50042,上红价值,EX,SH,62,2014-03-21,CS,50.0,策略
1693,H50052,上国改革,EX,SH,62,2014-10-28,CS,50.0,主题
1694,H50053,上证移动,EX,SH,62,2014-07-11,CS,46.0,主题
1695,H50054,上证休闲,EX,SH,62,2014-07-21,CS,50.0,主题
1696,H50055,沪大农业,EX,SH,62,2014-07-22,CS,50.0,主题

In [ ]:
optDF[optDF.duplicated(subset='IndexName',keep=False)]

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
83,000097,高端装备,ST,SH,1,2011-05-24,TDX,60.0,主题
141,000170,50AH优选,ST,SH,1,NaN,TDX,NaN,NaN
143,000300,沪深300,ST,ZZ,1,2005-04-08,TDX,300.0,规模
162,000807,食品饮料,EX,ZZ,62,2012-02-17,CS,50.0,行业
180,000847,腾讯济安,ST,SH,1,2013-11-18,TDX,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1621,H30257,500信息,EX,ZZ,62,2013-11-06,CS,83.0,行业
1622,H30263,腾讯济安,EX,ZZ,62,2013-11-18,CS,100.0,策略
1636,H30373,百发100,EX,ZZ,62,2014-07-30,CS,100.0,策略
1643,H30535,互联网,EX,ZZ,62,2015-01-12,CS,50.0,主题
1648,H30597,新材料,EX,ZZ,62,2015-02-13,CS,50.0,主题

In [23]:
df6[df6.duplicated(subset='IndexName',keep=False)]

,IndexCode,IndexName,Market,MarketName,MarketCode,From,Num,DP,IndexSTL
4,000006,地产指数,ST,SH,1,TDX,23.0,1993-05-03,行业
1,000013,企债指数,EX,ZZ,62,tdxApi,NaN,NaN,NaN
140,000170,50AH优选,ST,SH,1,TDX,NaN,NaN,NaN
0,000300,沪深300,ST,SH,1,TDX,300.0,2005-04-08,规模
160,000823,800有色,ST,SH,1,TDX,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
474,H30252,500工业,EX,ZZ,62,CS,115.0,2013-11-06,行业
475,H30255,500医药,EX,ZZ,62,CS,55.0,2013-11-06,行业
476,H30257,500信息,EX,ZZ,62,CS,83.0,2013-11-06,行业
477,H30263,腾讯济安,EX,ZZ,62,CS,100.0,2013-11-18,策略
490,H30373,百发100,EX,ZZ,62,CS,100.0,2014-07-30,策略

,IndexCode,IndexName,Market,MarketName,MarketCode,From,Num,DP,IndexSTL
0,000001,上证指数,ST,SH,1,TDX,2235.0,1991-07-15,综合
1,000002,A股指数,ST,SH,1,TDX,2193.0,1992-02-21,规模
2,000003,Ｂ股指数,ST,SH,1,TDX,NaN,NaN,NaN
2,000004,工业指数,ST,SH,1,TDX,1674.0,1993-05-03,行业
3,000005,商业指数,ST,SH,1,TDX,172.0,1993-05-03,行业
...,...,...,...,...,...,...,...,...,...
550,H50055,沪大农业,EX,SH,62,CS,50.0,2014-07-22,主题
667,H50069,港股通,EX,ZZ,62,tdxApi,NaN,NaN,NaN
668,N00300,沪深300净收益,EX,ZZ,62,tdxApi,NaN,NaN,NaN
669,N00905,中证500净收益,EX,ZZ,62,tdxApi,NaN,NaN,NaN
670,SHHKSI,沪港精明,EX,ZZ,62,tdxApi,NaN,NaN,NaN

In [ ]:
from datetime import datetime

current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
opt = pd.read_sql('optIndexs', eng)

In [ ]:
optO = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexsO.xlsx',dtype={'IndexCode':object} )

In [ ]:
tdxIndexs = opt[~(opt['IndexCode'].isin(optO['IndexCode']))]

In [ ]:
tdxIndexs[tdxIndexs['MarketCode'] == 102]['IndexCode']

In [ ]:
akCons = pd.read_sql('IndexCons', eng)

In [ ]:
akCons[akCons['StockCode']=='600271']

In [ ]:
optInd = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
optSQL[~(optSQL['IndexCode'].isin(optO['IndexCode']))]

In [ ]:
optInd[~(optInd['IndexCode'].isin(optSQL['IndexCode']))]

In [ ]:
blkDF['DP'] = current_date
akDF['IndexSTL'] = '指数'

In [64]:
OPTdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx',dtype={'IndexCode':object})
EMPdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akEMPB.xlsx', dtype={'IndexCode':object})

In [68]:
OPTdf[OPTdf['IndexCode'].isin(EMPdf['IndexCode'])]

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
380,399415,I100,ST,SZ,0,2014-09-12,TDX,100,定制指数
381,399416,I300,ST,SZ,0,2014-09-12,TDX,300,定制指数
481,399679,深证200R,ST,SZ,0,2015-06-18,TDX,200,规模
1143,931127,浙江新动能,EX,ZZ,62,2019-01-22,CS,100,主题
1271,931852,每经品牌100,EX,ZZ,62,2022-05-10,CS,99,策略
1355,H11121,富国多空,EX,ZZ,62,2011-07-26,CS,106,策略
1356,H11136,中国互联网,EX,ZZ,62,2011-09-20,CS,29,主题
1394,H30082,300两倍,EX,ZZ,62,2013-04-03,CS,300,策略
1395,H30083,300反向,EX,ZZ,62,2013-04-03,CS,300,策略
1425,H30373,百发100,EX,ZZ,62,2014-07-30,CS,100,策略
1431,H30537,淘金100,EX,ZZ,62,2015-01-21,CS,100,主题

In [66]:
OPTdf[OPTdf.duplicated(subset='IndexName',keep=False)]

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
66,000097,高端装备,ST,SH,1,2011-05-24,TDX,60,主题
140,000807,食品饮料,EX,ZZ,62,2012-02-17,CS,50,行业
219,000992,全指金融,ST,ZZ,1,2011-08-02,TDX,140,主题
255,399237,运输指数,ST,SZ,0,2013-03-04,TDX,0,行业
269,399262,数字经济,ST,SZ,0,NaN,TDX,50,主题
282,399281,电子50,ST,SZ,0,2020-05-08,TDX,50,主题
382,399417,新能源车,ST,SZ,0,2014-09-24,TDX,50,主题
383,399418,数据要素,ST,SZ,0,2014-11-21,TDX,50,主题
397,399438,绿色电力,ST,SZ,0,2014-12-30,TDX,50,主题
412,399608,科技100,ST,SZ,0,2010-10-18,TDX,100,主题
499,399699,金融科技,ST,SZ,0,2017-06-09,TDX,0,主题
511,399805,互联金融,ST,ZZ,0,2015-02-10,TDX,65,主题
538,399991,一带一路,ST,ZZ,0,2015-02-16,TDX,92,主题
541,399994,信息安全,ST,ZZ,0,2015-03-12,TDX,63,主题
543,399996,智能家居,ST,ZZ,0,2014-09-17,TDX,100,主题
593,880372,食品饮料,ST,TDXBLK,1,2025-09-04,TDXBLK,124,行业
595,880387,家用电器,ST,TDXBLK,1,2025-09-04,TDXBLK,91,行业
597,880398,医疗保健,ST,TDXBLK,1,2025-09-04,TDXBLK,175,行业
628,880482,房地产,ST,TDXBLK,1,2025-09-04,TDXBLK,100,行业
630,880490,通信设备,ST,TDXBLK,1,2025-09-04,TDXBLK,136,行业
631,880491,半导体,ST,TDXBLK,1,2025-09-04,TDXBLK,183,行业
634,880494,互联网,ST,TDXBLK,1,2025-09-04,TDXBLK,80,行业
670,880545,云计算,ST,TDXBLK,1,2025-09-04,TDXBLK,207,概念
671,880546,卫星导航,ST,TDXBLK,1,2025-09-04,TDXBLK,204,概念
684,880560,高端装备,ST,TDXBLK,1,2025-09-04,TDXBLK,324,概念
715,880592,互联金融,ST,TDXBLK,1,2025-09-04,TDXBLK,202,概念
717,880594,一带一路,ST,TDXBLK,1,2025-09-04,TDXBLK,699,概念
785,880667,数据要素,ST,TDXBLK,1,2025-09-04,TDXBLK,375,概念
848,880731,新材料,ST,TDXBLK,1,2025-09-04,TDXBLK,396,概念
870,880753,绿色电力,ST,TDXBLK,1,2025-09-04,TDXBLK,324,概念
882,880765,海洋经济,ST,TDXBLK,1,2025-09-04,TDXBLK,62,概念
992,880901,信息安全,ST,TDXBLK,1,2025-09-04,TDXBLK,200,概念
997,880906,智能家居,ST,TDXBLK,1,2025-09-04,TDXBLK,258,概念
1026,880948,人工智能,ST,TDXBLK,1,2025-09-04,TDXBLK,899,概念
1029,880951,新能源车,ST,TDXBLK,1,2025-09-04,TDXBLK,951,概念
1035,880957,工业互联,ST,TDXBLK,1,2025-09-04,TDXBLK,339,概念
1078,930697,家用电器,EX,ZZ,62,2015-07-07,CS,67,行业
1109,930851,云计算,EX,ZZ,62,2016-07-20,CS,50,主题
1123,930986,金融科技,EX,ZZ,62,2017-06-22,CS,57,主题
1124,930997,新能源车,EX,ZZ,62,2017-07-19,CS,50,主题
1139,931071,人工智能,EX,ZZ,62,2018-11-21,CS,50,主题
1157,931160,通信设备,EX,ZZ,62,2013-07-15,CS,50,主题
1163,931187,科技100,EX,ZZ,62,2019-05-30,CS,100,主题
1196,931461,电子50,EX,ZZ,62,2009-07-22,CS,50,主题
1210,931494,消费电子,EX,ZZ,62,2020-06-12,CS,50,主题
1211,931495,工业互联,EX,ZZ,62,2020-07-08,CS,50,主题
1224,931582,数字经济,EX,ZZ,62,2020-11-09,CS,50,主题
1226,931585,卫星导航,EX,ZZ,62,2020-11-09,CS,50,主题
1259,931775,房地产,EX,ZZ,62,2013-07-15,CS,78,行业
1272,931855,通用航空,EX,ZZ,62,2025-04-02,CS,50,主题
1276,931897,绿色电力,EX,ZZ,62,2012-12-21,CS,50,行业
1287,932056,海洋经济,EX,ZZ,62,2024-07-23,CS,211,主题
1290,932075,全指金融,EX,ZZ,62,2023-03-13,CS,50,行业
1334,980030,消费电子,EX,GZ,102,NaN,tdxApi,50,主题
1338,980076,通用航空,EX,GZ,102,NaN,tdxApi,50,主题
1400,H30171,运输指数,EX,ZZ,62,2013-07-15,CS,90,行业
1401,H30178,医疗保健,EX,ZZ,62,2013-07-15,CS,110,主题
1403,H30184,半导体,EX,ZZ,62,2013-07-15,CS,84,行业
1430,H30535,互联网,EX,ZZ,62,2015-01-12,CS,50,主题
1435,H30597,新材料,EX,ZZ,62,2015-02-13,CS,50,主题

In [60]:
finaDF = OPTdf[~OPTdf['IndexCode'].isin(EMPdf['IndexCode'])]

In [61]:
ofdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/FinaIndexs.xlsx', dtype={'IndexCode':object})

In [62]:
finaDF[~finaDF['IndexCode'].isin(ofdf['IndexCode'])]

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
981,880889,不活跃股,ST,TDXBLK,1,2025-09-04,TDXBLK,3,风格
1320,932422,A500红利低波,EX,ZZ,62,2025-04-09,CS,50,策略

In [63]:
ofdf[~ofdf['IndexCode'].isin(finaDF['IndexCode'])]

,IndexCode,IndexName,Market,MarketName,MarketCode,From,DP,IndexSTL,Num
295,399300,沪深300,ST,SZ,0,TDX,2005-04-08,NaN,NaN
373,399404,大盘低波,ST,SZ,0,TDX,2013-12-05,NaN,NaN
521,399852,中证1000,ST,SZ,0,TDX,2023-09-11,NaN,NaN
522,399901,小康指数,ST,SZ,0,TDX,2010-04-01,NaN,NaN
523,399903,中证100,ST,SZ,0,TDX,2006-05-29,NaN,NaN
524,399905,中证500,ST,SZ,0,TDX,2007-01-15,NaN,NaN
525,399913,300医药,ST,SZ,0,TDX,2007-07-02,NaN,NaN
526,399914,300金融,ST,SZ,0,TDX,2007-07-02,NaN,NaN
527,399928,中证能源,ST,SZ,0,TDX,2009-07-03,NaN,NaN
528,399932,中证消费,ST,SZ,0,TDX,2009-07-03,NaN,NaN
529,399933,中证医药,ST,SZ,0,TDX,2009-07-03,NaN,NaN
530,399934,中证金融,ST,SZ,0,TDX,2009-07-03,NaN,NaN
531,399935,中证信息,ST,SZ,0,TDX,2009-07-03,NaN,NaN
691,880556,昨ST连板,ST,SH,1,EMP,2025-08-25,风格,3.0
1064,899003,创新成指,EX,ZZ,62,TDX,NaN,NaN,NaN
1065,899050,北证50,EX,ZZ,62,TDX,NaN,NaN,NaN
1066,899601,北证专精特新,EX,ZZ,62,TDX,NaN,NaN,NaN
1119,930835,环保专利,EX,ZZ,62,TDX,NaN,NaN,NaN
1137,930984,MG新经济,EX,ZZ,62,TDX,NaN,NaN,NaN
1150,931065,财通浙30,EX,ZZ,62,TDX,NaN,NaN,NaN
1155,931070,中金100,EX,ZZ,62,TDX,NaN,NaN,NaN
1158,931086,MG新经济AUD,EX,ZZ,62,TDX,NaN,NaN,NaN
1196,931374,交银理财长三角,EX,ZZ,62,TDX,NaN,NaN,NaN
1230,931496,交银理财大湾区,EX,ZZ,62,TDX,NaN,NaN,NaN
1231,931520,科技50领先,EX,ZZ,62,TDX,NaN,NaN,NaN
1263,931654,广银理财沪港深健,EX,ZZ,62,TDX,NaN,NaN,NaN
1264,931655,广银理财沪港深科,EX,ZZ,62,TDX,NaN,NaN,NaN
1274,931722,国新港股通央企红,EX,ZZ,62,TDX,NaN,NaN,NaN
1293,931840,大盘蓝筹25USD,EX,ZZ,62,TDX,NaN,NaN,NaN
1294,931841,新能车15USD,EX,ZZ,62,TDX,NaN,NaN,NaN
1295,931842,半导体15USD,EX,ZZ,62,TDX,NaN,NaN,NaN
1300,931877,科创创业50净收益,EX,ZZ,62,TDX,NaN,NaN,NaN
1307,932021,中证红利SGD,EX,ZZ,62,TDX,NaN,NaN,NaN
1308,932022,中证红利(全)SGD,EX,ZZ,62,TDX,NaN,NaN,NaN
1309,932023,中证红利(净)SGD,EX,ZZ,62,TDX,NaN,NaN,NaN
1315,932047,中证REITs全收益,EX,ZZ,62,TDX,NaN,NaN,NaN
1316,932049,国新港股通央企综,EX,ZZ,62,TDX,NaN,NaN,NaN
1370,990001,中华半导体芯片,EX,ZZ,62,TDX,NaN,NaN,NaN
1426,H30106,H300金融服务,EX,ZZ,62,TDX,NaN,NaN,NaN
1507,SHHKSI,沪港精明,EX,ZZ,62,TDX,NaN,NaN,NaN

In [ ]:
OPTdf[~OPTdf['IndexCode'].isin(EMPdf['IndexCode'])].set_index('IndexCode')

In [ ]:
401 % 200 == 0

In [ ]:
thresholds = [300, 600, 900, 1200, 1500, 1800]
n = 600
if n in thresholds:
    print('300')
else:
    print(n)

In [35]:
fdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/FinaIndexs.xlsx',dtype={'IndexCode':object})
adf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akGzSzIndexs.xlsx', dtype={'IndexCode':object})

In [37]:
fdf.loc[fdf['IndexCode'].isin(adf['IndexCode']),'IndexSTL'] = adf['IndexSTL']

In [42]:
adf[['IndexCode','IndexSTL']]

     IndexCode IndexSTL
0       399050       主题
1       399060     定制指数
2       399289     定制指数
3       399291       策略
4       399303       规模
...        ...      ...
1230   PSMHKDG       规模
1231   VALHKDG       规模
1232   YLVHKDG       规模
1233    CESRET       规模
1234   RETHKDG       规模

[1235 rows x 2 columns]

In [44]:
mdf = pd.merge(fdf.drop('IndexSTL',axis=1), adf[['IndexCode','IndexSTL']], on='IndexCode', how='inner')

In [46]:
 ddf = pd.concat([mdf,fdf]).drop_duplicates(subset='IndexCode', keep='first')

In [54]:
ddf.drop_duplicates(subset='IndexName',keep='first')

,IndexCode,IndexName,Market,MarketName,MarketCode,From,DP,Num,IndexSTL
0,399001,深证成指,ST,SZ,0,TDX,1995-01-23,500.0,规模
1,399002,深成指R,ST,SZ,0,TDX,1995-01-23,500.0,规模
2,399004,深证100R,ST,SZ,0,TDX,2003-01-02,100.0,规模
3,399005,中小100,ST,SZ,0,TDX,2006-01-24,100.0,规模
4,399006,创业板指,ST,SZ,0,TDX,2010-06-01,100.0,规模
...,...,...,...,...,...,...,...,...,...
1503,H50052,上国改革,EX,SH,62,CS,2014-10-28,50.0,主题
1504,H50053,上证移动,EX,SH,62,CS,2014-07-11,46.0,主题
1505,H50054,上证休闲,EX,SH,62,CS,2014-07-21,50.0,主题
1506,H50055,沪大农业,EX,SH,62,CS,2014-07-22,50.0,主题
1507,SHHKSI,沪港精明,EX,ZZ,62,TDX,NaN,NaN,NaN

In [38]:
fdf[fdf['IndexCode'].isin(adf['IndexCode'])]

,IndexCode,IndexName,Market,MarketName,MarketCode,From,DP,IndexSTL,Num
224,399001,深证成指,ST,SZ,0,TDX,1995-01-23,行业,500.0
225,399002,深成指R,ST,SZ,0,TDX,1995-01-23,行业,500.0
226,399004,深证100R,ST,SZ,0,TDX,2003-01-02,行业,100.0
227,399005,中小100,ST,SZ,0,TDX,2006-01-24,行业,100.0
228,399006,创业板指,ST,SZ,0,TDX,2010-06-01,行业,100.0
...,...,...,...,...,...,...,...,...,...
1365,980032,新能电池,EX,GZ,102,TDX,NaN,NaN,30.0
1366,980035,化肥农药,EX,GZ,102,TDX,NaN,NaN,80.0
1367,980068,蓝色100,EX,GZ,102,TDX,NaN,NaN,100.0
1368,980076,通用航空,EX,GZ,102,TDX,NaN,NaN,50.0
1369,980092,CNIFCF,EX,GZ,102,TDX,NaN,NaN,100.0

In [12]:
sdf[sdf['IndexCode'].isin(tdf['IndexCode'])]

    IndexCode IndexName         DP   Num IndexSTL From
0      000001      上证指数 1990-12-19  2237       规模  SSE
1      000002      Ａ股指数 1990-12-19  2195       规模  SSE
2      000003      Ｂ股指数 1992-02-21    41       规模  SSE
3      000004      工业指数 1993-04-30  1676       行业  SSE
4      000005      商业指数 1993-04-30   172       行业  SSE
..        ...       ...        ...   ...      ...  ...
264    H50052      上国改革 2014-03-31    50       主题  SSE
265    H50053      上证移动 2012-06-29    46       主题  SSE
266    H50054      上证休闲 2013-12-31    50       主题  SSE
267    H50055      沪大农业 2013-12-31    50       主题  SSE
279    H50069       港股通 2014-11-14   553       主题  SSE

[196 rows x 6 columns]

In [ ]:
dropdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexs.xlsx',dtype={'IndexCode':object})
empdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/empIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
dropdf.loc[dropdf['IndexCode'].isin(empdf['IndexCode']), 'From'] = 'EMP'

In [ ]:
m = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/IndexM.xlsx', dtype={'IndexCode':object})
zg = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
df62 =m[m['MarketCode']==62]
dff =m[~(m['MarketCode']==62)]

In [ ]:
set(df62['IndexCode'])-set(zg['IndexCode'])

In [ ]:
mzg = pd.merge(df62,zg['IndexCode'],on='IndexCode',how='inner')

In [2]:
sh = open('D:/new_tdx/T0002/hq_cache/shm.tnf', 'r',encoding="GBK", errors='ignore').read()

In [8]:
re.findall(r"500\d{2}.{30}", sh)

[]

In [ ]:
re.findall(r"00\d{4}.{30}", sh)

In [ ]:
from datetime import datetime

In [ ]:
datetime.now().strftime("%Y-%m-%d")

In [ ]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
dd = pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
dd['dp'] = current_date

In [ ]:
pd.d

In [ ]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

In [ ]:
pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [ ]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

In [ ]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
# zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
# sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
# sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})
dpdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexDP.xlsx', dtype={'IndexCode':object})
numdf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/akIndexNum.xlsx', dtype={'IndexCode':object})

In [ ]:
pd.merge(m3,gzak, on=['IndexCode'],how='inner')

In [ ]:
pd.merge(gz,gzak, on=['IndexCode'],how='inner')

In [ ]:
# zz.drop_duplicates(subset='IndexCode',inplace=True)
zzgz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZGZIndexs.xlsx', dtype={'IndexCode':object})
m3 = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHSZIndexs.xlsx', dtype={'IndexCode':object})
m3.reset_index(drop=True, inplace=True)

In [ ]:
blkm = pd.merge(blk,m3.drop(columns='From'), on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [ ]:
m3cs = pd.merge(m3,cs[['IndexCode','Num','IndexSTL','DP']], on='IndexCode',how='inner')

In [ ]:
m3zz = pd.merge(m3,zzgz['IndexCode'], on='IndexCode',how='inner')

In [ ]:
cszz = pd.merge(cs,zzgz[['IndexCode','Market','MarketCode']], on='IndexCode',how='inner')

In [ ]:
m3cszz = pd.merge(m3,cszz[['IndexCode','Num','DP','IndexSTL']], on='IndexCode',how='inner')

In [ ]:
# df1 = pd.concat([blkm,m3]).drop_duplicates(subset='IndexCode',keep='first')
df1 = pd.concat([blk,m3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df2 = pd.concat([m3cs,df1]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df3 = pd.concat([m3zz,df2]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df4 = pd.concat([m3cszz,df3]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
df5 = pd.concat([df4,cszz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df55 = pd.concat([df5,zzgz]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
dpm = pd.merge(df55[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'Num', 'IndexSTL']],dpdf[['IndexCode','DP']], on='IndexCode',how='inner')

In [ ]:
df6 = pd.concat([dpm,df55]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
mdf = pd.merge(df6[['IndexCode', 'IndexName', 'Market', 'MarketName', 'MarketCode', 'From',
       'DP', 'IndexSTL']],numdf[['IndexCode','Num']], on='IndexCode',how='inner')

In [ ]:
df7 = pd.concat([mdf,df6]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode'])

In [ ]:
df5[~((df5['IndexCode'].str.startswith('88')) & (df5['From'] == 'TDX'))]

In [ ]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [ ]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [ ]:
m3zz = pd.concat([zm,zzm]).drop_duplicates(subset='IndexCode',keep='first')

In [ ]:
zzm3 = pd.concat([m3zz,m3]).drop_duplicates(subset='IndexCode',keep='first').reset_index(drop=True)

In [ ]:
dddf = pd.concat([blkm,zzm3]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode']).reset_index(drop=True)

In [ ]:
dddf['IndexSTL'] = dddf['IndexSTL'].fillna('指数')

In [ ]:
dddf

In [ ]:
dddf['From'].fillna('TDX', inplace=True)

In [ ]:
dddf

In [ ]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)

In [ ]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd
from sqlalchemy import create_engine


eapi =  TdxExHq_API()
api = TdxHq_API()

In [ ]:
li = gz['IndexCode'].to_list()

In [ ]:
ll = []

In [ ]:
with eapi.connect('47.112.95.207', 7720):
    # IndexLists=zz.IndexCode.to_list()   
    for i, IndexCode in enumerate(li):
        try:                
            # print('Index', i, '/', len(IndexLists))
            df = eapi.to_df(eapi.get_instrument_bars(9, 102, IndexCode, 0, 10))
            if df.empty:
                pass
                # print(IndexCode+'EMP !! ')
            else:
                ll.append(IndexCode)
                print(IndexCode+'EMP !! ')                
        except:
            print(IndexCode, 'EXCEPT !' )
            pass