tdx历史财务数据列表数据更新 ==> /home/ts/app/TDXapp/MtdxGetFS.py

In [1]:
from mootdx.quotes import Quotes

In [2]:
from mootdx.affair import Affair

Affair.files()

[{'filename': 'gpcw20250930.zip',
  'hash': '1f43e000d0fd371127b8a68a3246308c',
  'filesize': 164},
 {'filename': 'gpcw20241231.zip',
  'hash': '104c22b147e2c6218524c9668550f428',
  'filesize': 165},
 {'filename': 'gpcw20240930.zip',
  'hash': '7bea4a1e1b073134df6ad0697f894c5e',
  'filesize': 5001231},
 {'filename': 'gpcw20240630.zip',
  'hash': 'd2ad176161ebbc0cea95a46ddc316432',
  'filesize': 5417150},
 {'filename': 'gpcw20240331.zip',
  'hash': '32b46d83fafb9bf34cdaa6a2ee6098ef',
  'filesize': 4804152},
 {'filename': 'gpcw20231231.zip',
  'hash': 'c1100696fd7bdbf25cae68deaed4bc51',
  'filesize': 5468274},
 {'filename': 'gpcw20230930.zip',
  'hash': 'd53189bc8707ce054cd3e88907b01fbe',
  'filesize': 5028799},
 {'filename': 'gpcw20230630.zip',
  'hash': '6eccde665769bd918aa9eb9ef069f294',
  'filesize': 5372412},
 {'filename': 'gpcw20230331.zip',
  'hash': 'cc82c9cfe36c959961afec8c9ec5667d',
  'filesize': 4675628},
 {'filename': 'gpcw20221231.zip',
  'hash': '16cd9dc3394c9c62ffa40863bf4d6c80',
  'filesize': 5422849},
 {'filename': 'gpcw20220930.zip',
  'hash': 'a87b429d20fafcb0f0fae8c18a34f022',
  'filesize': 4739647},
 {'filename': 'gpcw20220630.zip',
  'hash': '388547269ea77c3e157a14b42a94da69',
  'filesize': 5235312},
 {'filename': 'gpcw20220331.zip',
  'hash': '4860a94e71d5966490d31404f735cc13',
  'filesize': 4289078},
 {'filename': 'gpcw20211231.zip',
  'hash': '4b10a7a8ed6dceeb997b8461ceb7e74f',
  'filesize': 5350532},
 {'filename': 'gpcw20210930.zip',
  'hash': '4d98251550972802dbf00e64587857fb',
  'filesize': 4371643},
 {'filename': 'gpcw20210630.zip',
  'hash': '77ab995bea1dc63c624cb37fdb5ec2a8',
  'filesize': 4902587},
 {'filename': 'gpcw20210331.zip',
  'hash': '537e832746e1e879dadbe6ccfe0e9bb0',
  'filesize': 3891382},
 {'filename': 'gpcw20201231.zip',
  'hash': 'e2982c4be8fd7226ea946059c826cb1a',
  'filesize': 5203885},
 {'filename': 'gpcw20200930.zip',
  'hash': '3c50dbae8b384d4fad66187f0397c054',
  'filesize': 3884774},
 {'filename': 'gpcw20200630.zip',
  'hash': '463a687b51c3d67ba6c629c9555f9e89',
  'filesize': 4353139},
 {'filename': 'gpcw20200331.zip',
  'hash': 'fdaf9cdc00eae291504dbcb18c5d530b',
  'filesize': 3391501},
 {'filename': 'gpcw20191231.zip',
  'hash': 'cb611652fbc28670e4fef26c86fc799a',
  'filesize': 4982946},
 {'filename': 'gpcw20190930.zip',
  'hash': 'a5eb625ef7119a931bd3170bf00948a6',
  'filesize': 3438618},
 {'filename': 'gpcw20190630.zip',
  'hash': '7188858dc51c66d12e7c8a71f4409b92',
  'filesize': 3649092},
 {'filename': 'gpcw20190331.zip',
  'hash': '897085c49b6982dbf64bcb3f92445f8a',
  'filesize': 3061304},
 {'filename': 'gpcw20181231.zip',
  'hash': '3b24e10aafdec9dfa0e11605106e37b2',
  'filesize': 4652987},
 {'filename': 'gpcw20180930.zip',
  'hash': 'fa6dcf1ab27044ac82f0e3f8a563a51f',
  'filesize': 3135557},
 {'filename': 'gpcw20180630.zip',
  'hash': 'bdc415d009029b6ebb6202be49b84919',
  'filesize': 3288624},
 {'filename': 'gpcw20180331.zip',
  'hash': '23012b317a4c7a09181617a16d19e113',
  'filesize': 2903371},
 {'filename': 'gpcw20171231.zip',
  'hash': 'b4f2411554bc62c2d37c2cada20897fe',
  'filesize': 4149384},
 {'filename': 'gpcw20170930.zip',
  'hash': '9297cff84992997b5dc745321d8a1f33',
  'filesize': 2968495},
 {'filename': 'gpcw20170630.zip',
  'hash': '65020bdfd1153caf2d50fd53eae5e8e8',
  'filesize': 3062756},
 {'filename': 'gpcw20170331.zip',
  'hash': '5c584a97e332a2d9fa413ff8e361241c',
  'filesize': 2610960},
 {'filename': 'gpcw20161231.zip',
  'hash': '0f3c8c558d4be3af8c57a1910299ad04',
  'filesize': 3473699},
 {'filename': 'gpcw20160930.zip',
  'hash': 'b17612159923b15a077b5c312130a234',
  'filesize': 2608065},
 {'filename': 'gpcw20160630.zip',
  'hash': 'b07189cc097c2b9ae82f9c08ccbacda2',
  'filesize': 2689632},
 {'filename': 'gpcw20160331.zip',
  'hash': 'cfc5995b6abe8770fdf5b3c619c60087',
  'filesize': 2264567},
 {'filename': 'gpcw20151231.zip',
  'hash': 'a40dad3ce16f05939773f033ba123c5a',
  'filesize': 3100235},
 {'filename': 'gpcw20150930.zip',
  'hash': '78c547582ce6df6448be33d066f0644a',
  'filesize': 2347475},
 {'filename': 'gpcw20150630.zip',
  'hash': 'f0c8b7deee96344d1344e60c38290af7',
  'filesize': 2404599},
 {'filename': 'gpcw20150331.zip',
  'hash': '32d4d2c3c4f481c42d5a7375602217bf',
  'filesize': 2114295},
 {'filename': 'gpcw20141231.zip',
  'hash': 'fffe3f69bca1dc256440ba7a8d518fde',
  'filesize': 2908163},
 {'filename': 'gpcw20140930.zip',
  'hash': '7f4758281dad8c3b3ce9ded39ccef474',
  'filesize': 2134103},
 {'filename': 'gpcw20140630.zip',
  'hash': '9adbdddde730b731d58b766d67cfebfe',
  'filesize': 2188709},
 {'filename': 'gpcw20140331.zip',
  'hash': 'ec414e608a77bc6eaa0c968b27ff216f',
  'filesize': 1905679},
 {'filename': 'gpcw20131231.zip',
  'hash': '7e84b7ce046b570522cecf5363f41276',
  'filesize': 2575522},
 {'filename': 'gpcw20130930.zip',
  'hash': 'bd2c6643e9015db98e51cc028026e3e7',
  'filesize': 1992745},
 {'filename': 'gpcw20130630.zip',
  'hash': '1596692970d557bcfbfc0ec6e7214f99',
  'filesize': 2093451},
 {'filename': 'gpcw20130331.zip',
  'hash': 'b091dd3a6a8fbe12c0412e7f30c50bca',
  'filesize': 1835905},
 {'filename': 'gpcw20121231.zip',
  'hash': '64862815cf3ac0aff74c7b6d499273cd',
  'filesize': 2324540},
 {'filename': 'gpcw20120930.zip',
  'hash': '15af3808c1d12e08cb51d278dce7c446',
  'filesize': 1950982},
 {'filename': 'gpcw20120630.zip',
  'hash': '19eca6fb2bd72ca9bc4f65192ff9f0ac',
  'filesize': 2028464},
 {'filename': 'gpcw20120331.zip',
  'hash': '5c56781b97080327d7a321fffdf2de4c',
  'filesize': 1765943},
 {'filename': 'gpcw20111231.zip',
  'hash': '1fc1b8e14a55e7e97983c24edcc400ba',
  'filesize': 2151074},
 {'filename': 'gpcw20110930.zip',
  'hash': '8afa970b3c2ea42968a4905e6c8fca50',
  'filesize': 1815598},
 {'filename': 'gpcw20110630.zip',
  'hash': '63935fc605bb16a130ce66161dcfeae1',
  'filesize': 1882359},
 {'filename': 'gpcw20110331.zip',
  'hash': 'f7a4175cdae5faa544c547a6e3b08219',
  'filesize': 1590650},
 {'filename': 'gpcw20101231.zip',
  'hash': 'a17a5df832dd24aa50f8e539372f4d7b',
  'filesize': 2037083},
 {'filename': 'gpcw20100930.zip',
  'hash': '01c20588d87500b821a63e41a507b449',
  'filesize': 1596438},
 {'filename': 'gpcw20100630.zip',
  'hash': '706cb472640c345a9fc4bfde6206f008',
  'filesize': 1645431},
 {'filename': 'gpcw20100331.zip',
  'hash': 'b7591b86d4eec2863605bce1dc794f49',
  'filesize': 1321820},
 {'filename': 'gpcw20091231.zip',
  'hash': 'a02e7cedda00a604f88c1636cc0f4f0a',
  'filesize': 1921042},
 {'filename': 'gpcw20090930.zip',
  'hash': '84329524e8a1e86f9e5f61f41c023ceb',
  'filesize': 1283547},
 {'filename': 'gpcw20090630.zip',
  'hash': '3c3b9769aca4e9fc44cdc1a50d48403d',
  'filesize': 1356800},
 {'filename': 'gpcw20090331.zip',
  'hash': '128dc4c8222dd8af03d87da43a9a56a8',
  'filesize': 1114583},
 {'filename': 'gpcw20081231.zip',
  'hash': '6e154f7339af2bdb84f7b4c7f9b5978b',
  'filesize': 1797655},
 {'filename': 'gpcw20080930.zip',
  'hash': '5612a509b9b4e1f663ed24faedba883d',
  'filesize': 1176095},
 {'filename': 'gpcw20080630.zip',
  'hash': 'd6c55e68b001b1677184d0d38f84c142',
  'filesize': 1255013},
 {'filename': 'gpcw20080331.zip',
  'hash': 'e231c9856360c2426bb8ae759f7e8526',
  'filesize': 1106414},
 {'filename': 'gpcw20071231.zip',
  'hash': 'a013b6e523f89eac3643c41d17d3150c',
  'filesize': 1589750},
 {'filename': 'gpcw20070930.zip',
  'hash': '1694f1a97ee7cc44d42c213f0f2f5b18',
  'filesize': 1111946},
 {'filename': 'gpcw20070630.zip',
  'hash': 'd956462bd57803dff2761e634c0d2dbe',
  'filesize': 1168873},
 {'filename': 'gpcw20070331.zip',
  'hash': '30fd6443f8082593ca6ec27971225cbf',
  'filesize': 988819},
 {'filename': 'gpcw20061231.zip',
  'hash': 'b529bd601c8d1b53f40125ba0a7eca86',
  'filesize': 1317201},
 {'filename': 'gpcw20060930.zip',
  'hash': '5469f0f78a270011fbfc23aac5ae54ef',
  'filesize': 1066953},
 {'filename': 'gpcw20060630.zip',
  'hash': '1f9315d85318d93bb008cccbd93ba871',
  'filesize': 1068857},
 {'filename': 'gpcw20060331.zip',
  'hash': '7e03a8bf22809c3f0cbef850d53724f4',
  'filesize': 957446},
 {'filename': 'gpcw20051231.zip',
  'hash': '1ad63ea2e002d427945f2d46a14d6d62',
  'filesize': 1200852},
 {'filename': 'gpcw20050930.zip',
  'hash': '953e3eebf2c10258e35bb0af3b3c7f87',
  'filesize': 1003049},
 {'filename': 'gpcw20050630.zip',
  'hash': 'ae81dda5f1230092238c6b0aeedfa5b1',
  'filesize': 1012091},
 {'filename': 'gpcw20050331.zip',
  'hash': '20e57102bb6f9ec9f15188abb683d782',
  'filesize': 922720},
 {'filename': 'gpcw20041231.zip',
  'hash': '8ad577022a341b3aa26070b82d555a73',
  'filesize': 1160394},
 {'filename': 'gpcw20040930.zip',
  'hash': '22ff0fe517051b338e1e723f6ab60f16',
  'filesize': 987039},
 {'filename': 'gpcw20040630.zip',
  'hash': '78ebbb7afcdbb114207c49e9b82271b8',
  'filesize': 997066},
 {'filename': 'gpcw20040331.zip',
  'hash': 'c84db7b332d858c0ab095cbfef2dd4f1',
  'filesize': 870556},
 {'filename': 'gpcw20031231.zip',
  'hash': '6d235d9ac919d916713d9d526479e8c3',
  'filesize': 1061743},
 {'filename': 'gpcw20030930.zip',
  'hash': '00e216175d0fd01be17e6ace51cfa891',
  'filesize': 828185},
 {'filename': 'gpcw20030630.zip',
  'hash': 'ff0304ab3b436da1a62b1f628ff14a3a',
  'filesize': 848611},
 {'filename': 'gpcw20030331.zip',
  'hash': '12f067024fed759f3c8bc2985fe5e099',
  'filesize': 745850},
 {'filename': 'gpcw20021231.zip',
  'hash': '398a0bbfc63269a645b05668883ee28e',
  'filesize': 912894},
 {'filename': 'gpcw20020930.zip',
  'hash': '2af32da3a68fb6612c301a4fe6d062e9',
  'filesize': 547942},
 {'filename': 'gpcw20020630.zip',
  'hash': '6f8bbfd52fb78e93dd29763c1e107e44',
  'filesize': 790977},
 {'filename': 'gpcw20020331.zip',
  'hash': '04af0d7c6bdbddfb9a4523b8f87e2349',
  'filesize': 475527},
 {'filename': 'gpcw20011231.zip',
  'hash': 'ca9ef1de8e6b91f0004bd90c999b1b29',
  'filesize': 849002},
 {'filename': 'gpcw20010930.zip',
  'hash': '29de48302fbd1d00f9a206753cf59ef7',
  'filesize': 49210},
 {'filename': 'gpcw20010630.zip',
  'hash': '99a3a89bfc547667b4e49e9694dd7886',
  'filesize': 709625},
 {'filename': 'gpcw20010331.zip',
  'hash': '366894c1ac4f1675f7938a4503d77db6',
  'filesize': 7701},
 {'filename': 'gpcw20001231.zip',
  'hash': '963fd8d3e46cd29043459f0779197086',
  'filesize': 792345},
 {'filename': 'gpcw20000930.zip',
  'hash': 'a97798a88e7376e76e982464e4c977d1',
  'filesize': 165},
 {'filename': 'gpcw20000630.zip',
  'hash': 'c2b1944322abe9f68d17aa701eb3ea84',
  'filesize': 647439},
 {'filename': 'gpcw20000331.zip',
  'hash': 'fd78805cd5d53af1e1933b9e74d5d565',
  'filesize': 164},
 {'filename': 'gpcw19991231.zip',
  'hash': '026668afcf7470d7035d3b333005cb7f',
  'filesize': 728345},
 {'filename': 'gpcw19990930.zip',
  'hash': '338b7a63556f9f957e04abf2ca225f97',
  'filesize': 165},
 {'filename': 'gpcw19990630.zip',
  'hash': '25765b00e0fef2effa76b59b4830a0f4',
  'filesize': 452380},
 {'filename': 'gpcw19990331.zip',
  'hash': '91f28f6218c3536d49c3eb0d4f0ca5a6',
  'filesize': 164},
 {'filename': 'gpcw19981231.zip',
  'hash': '89c7236dce0b3310c79a1074119f0a01',
  'filesize': 653281},
 {'filename': 'gpcw19980930.zip',
  'hash': '513a38c33a3fe4cce70866c51af61e6a',
  'filesize': 165},
 {'filename': 'gpcw19980630.zip',
  'hash': 'b45c28028f20c9ba0b747b4c7ca2bb74',
  'filesize': 392201},
 {'filename': 'gpcw19980331.zip',
  'hash': 'f57ec2e2b8c3fd0c647b41286f4925cc',
  'filesize': 165},
 {'filename': 'gpcw19971231.zip',
  'hash': 'dfb95056614758b7a714e8d460675c01',
  'filesize': 445132},
 {'filename': 'gpcw19970930.zip',
  'hash': '473030a7f6b094f82721f9259afd871e',
  'filesize': 165},
 {'filename': 'gpcw19970630.zip',
  'hash': 'e3676d7f75f487a6069586654b5920df',
  'filesize': 208333},
 {'filename': 'gpcw19970331.zip',
  'hash': '8f3546638a9ec8071a33529781431404',
  'filesize': 165},
 {'filename': 'gpcw19961231.zip',
  'hash': '196b5b2556a0edaff74551369ff8b7e3',
  'filesize': 375797},
 {'filename': 'gpcw19960930.zip',
  'hash': '5d8a50cb96e1ffd8bdb8aff8d42533b5',
  'filesize': 165},
 {'filename': 'gpcw19960630.zip',
  'hash': 'f2ae763ff7e388403a5e8e25bc2c5aaf',
  'filesize': 129609},
 {'filename': 'gpcw19960331.zip',
  'hash': '0694c7f50eb3397a49e29a096f1f940a',
  'filesize': 165},
 {'filename': 'gpcw19951231.zip',
  'hash': '320ab529c628626d15cecc0ad9ba6fd9',
  'filesize': 315535},
 {'filename': 'gpcw19950930.zip',
  'hash': '13a87d567d7272b4783e05b591bcb521',
  'filesize': 164},
 {'filename': 'gpcw19950630.zip',
  'hash': '895ddef7a57a211856af9a7f25a1f574',
  'filesize': 84191},
 {'filename': 'gpcw19950331.zip',
  'hash': '789582a038b2c87b71c43d5c9c3dedcb',
  'filesize': 165},
 {'filename': 'gpcw19941231.zip',
  'hash': '2a6e032ec8c793d56ca4d9a7e3cf1806',
  'filesize': 208857},
 {'filename': 'gpcw19940930.zip',
  'hash': '7408e359dc754b8766dc8798f545a4aa',
  'filesize': 164},
 {'filename': 'gpcw19940630.zip',
  'hash': '4dd7d986d16705d547b8f7058d5aa316',
  'filesize': 65681},
 {'filename': 'gpcw19940331.zip',
  'hash': '45a12a3b1ae30a2ae7e44afed12517ec',
  'filesize': 165},
 {'filename': 'gpcw19931231.zip',
  'hash': 'bec975cb7dcffc687051c6a275730fbe',
  'filesize': 129827},
 {'filename': 'gpcw19930930.zip',
  'hash': '2c2f781d9a7d2aa97b38f327eb2dfdbc',
  'filesize': 164},
 {'filename': 'gpcw19930630.zip',
  'hash': 'ddc873b36dfa630708a4888718874355',
  'filesize': 164},
 {'filename': 'gpcw19930331.zip',
  'hash': '8e64c9d26048263d740d10dcf04fc32a',
  'filesize': 165},
 {'filename': 'gpcw19921231.zip',
  'hash': '7aec3a3907c167e20da14bf95321949e',
  'filesize': 71449},
 {'filename': 'gpcw19920930.zip',
  'hash': '7104257176c9336b95d6267081777758',
  'filesize': 165},
 {'filename': 'gpcw19920630.zip',
  'hash': '6ea4a8f02d3b476cfc890a37514d0fb3',
  'filesize': 165},
 {'filename': 'gpcw19920331.zip',
  'hash': 'a6098d5720ab5b370e7d38e18623344d',
  'filesize': 165},
 {'filename': 'gpcw19911231.zip',
  'hash': '6fdb9103831f6d2b1c0ae9f5b3b692cc',
  'filesize': 27564},
 {'filename': 'gpcw19910930.zip',
  'hash': '6d2ec40e0cbb58db53a9bd7bbfc26a7f',
  'filesize': 165},
 {'filename': 'gpcw19910630.zip',
  'hash': '74db5fb0c3b249878c53c4dd880619a8',
  'filesize': 165},
 {'filename': 'gpcw19910331.zip',
  'hash': '1792cb5b47b6a1ae01794d3972b0adbf',
  'filesize': 165},
 {'filename': 'gpcw19901231.zip',
  'hash': '04f2f7f299130200a9a2cf0057b65c44',
  'filesize': 12634},
 {'filename': 'gpcw19900630.zip',
  'hash': '6bb4c75c61c7066d3a03b3e24008b33f',
  'filesize': 165},
 {'filename': 'gpcw19891231.zip',
  'hash': 'b0ad534ba255a73fe9368b8a0d5551c6',
  'filesize': 333},
 {'filename': 'gpcw19881231.zip',
  'hash': '4fcec5f4cf87d4f97d7f39adbf58145d',
  'filesize': 164}]

In [ ]:
===============

In [3]:
f10 = ['最新提示','公司概况','财务分析','股本结构','股东研究','机构持股','分红融资','高管治理','资金动向','资本运作','热点题材','公司公告','公司报道','经营分析','行业分析','价值分析',]
stockCode = '000001'

In [4]:
client = Quotes.factory(market='std')
txt = client.F10(stockCode, f10[1])

In [5]:
txt[:txt.find('〖免责条款〗')]

'公司概况☆ ◇000001 平安银行 更新日期：2024-12-23◇ 通达信沪深京F10\r\n★本栏包括【1.基本资料】【2.发行和交易】【3.员工效益】【4.参股控股】\r\n\r\n【1.基本资料】\r\n┌───────┬───────────────────────────────┐\r\n│公司名称      │平安银行股份有限公司                                          │\r\n├───────┼───────────────────────────────┤\r\n│英文全称      │Ping An Bank Co., Ltd.                                        │\r\n├───────┼───────────┬───────┬───────────┤\r\n│证券简称      │平安银行              │证券代码      │000001                │\r\n├───────┼───────────┴───────┴───────────┤\r\n│曾用简称      │深发展A->S深发展A->深发展A                                    │\r\n├───────┼───────────────────────────────┤\r\n│关联上市      │---                                                           │\r\n├───────┼───────────┬───────┬───────────┤\r\n│通达信研究行业│银行-全国性银行       │证监会行业    │货币金融服务          │\r\n├───────┼───────────┼───────┼───────────┤\r\n│证券类别      │深交所主板A股         │上市日期      │1991-04-03            │\r\n├───────┼───────────┼───────┼───────────┤\r\n│法人代表      │谢永林                │总经理        │冀光恒                │\r\n├───────┼───────────┼───────┼───────────┤\r\n│公司董秘      │周强                  │董事长        │谢永林                │\r\n├───────┼───────────┴───────┴───────────┤\r\n│会计事务所    │安永华明会计师事务所(特殊普通合伙)                            │\r\n├───────┼───────────┬───────┬───────────┤\r\n│联系电话      │0755-82080387         │传真          │0755-82080386         │\r\n├───────┼───────────┴───────┴───────────┤\r\n│公司网址      │www.bank.pingan.com                                           │\r\n├───────┼───────────────────────────────┤\r\n│电子邮箱      │PAB_db@pingan.com.cn                                          │\r\n├───────┼───────────────────────────────┤\r\n│注册地址      │广东省深圳市罗湖区深南东路5047号                              │\r\n├───────┼───────────────────────────────┤\r\n│办公地址      │广东省深圳市深南东路5047号；广东省深圳市福田区益田路5023号平安│\r\n│              │金融中心B座                                                   │\r\n├───────┼───────────────────────────────┤\r\n│经营范围      │（一）吸收公众存款；（二）发放短期、中期和长期贷款；（三）办理│\r\n│              │国内外结算；（四）办理票据承兑与贴现；（五）发行金融债券；（六│\r\n│              │）代理发行、代理兑付、承销政府债券；（七）买卖政府债券、金融债│\r\n│              │券；（八）从事同业拆借；（九）买卖、代理买卖外汇；（十）从事银│\r\n│              │行卡业务；（十一）提供信用证服务及担保；（十二）代理收付款项及│\r\n│              │代理保险业务；（十三）提供保管箱服务；（十四）结汇、售汇业务；│\r\n│              │（十五）离岸银行业务；（十六）资产托管业务；（十七）办理黄金业│\r\n│              │务；（十八）财务顾问、资信调查、咨询、见证业务；（十九）经有关│\r\n│              │监管机构批准的其他业务。                                      │\r\n├───────┼───────────────────────────────┤\r\n│主营业务      │办理人民币存、贷、结算、汇兑业务；人民币票据承兑和贴现；各项信│\r\n│              │托业务；经人民银行批准发行或买卖人民币有价证券；外汇存款、汇款│\r\n│              │；境内境外借款；在境内境外发行或代理发行外币有价证券外汇存款、│\r\n│              │汇款、境内境外汇借款等。                                      │\r\n├───────┼───────────────────────────────┤\r\n│公司简介      │深圳发展银行股份有限公司系在对中华人民共和国深圳经济特区内原6 │\r\n│              │家农村信用社进行股份制改造的基础上设立的股份制商业银行。1987年│\r\n│              │5月10日以自由认购的形式首次向社会公开发售人民币普通股,于1987年│\r\n│              │12月22日正式设立。1988年4月7日，本行普通股在深圳经济特区证券公│\r\n│              │司首家挂牌公开上市。深发展股东大会以及平安银行股份有限公司于20│\r\n│              │12年2月9日召开的2012年第一次临时股东大会分别审议通过了深发展吸│\r\n│              │收合并平安银行的方案的议案以及深发展与平安银行签署吸收合并协议│\r\n│              │的议案。深圳发展银行股份有限公司于2012年2月9日召开的2012年第一│\r\n│              │次临时股东大会审议通过了《深圳发展银行股份有限公司关于更名的议│\r\n│              │案》，同意本公司的中文名称由“深圳发展银行股份有限公司”变更为│\r\n│              │“平安银行股份有限公司”。中国银行业监督管理委员会于2012年4月2│\r\n│              │4日以《中国银监会关于深圳发展银行吸收合并平安银行的批复》（银 │\r\n│              │监复〔2012〕192号）批准了本次吸收合并。2012年7月27日本公司在深│\r\n│              │圳市市场监督管理局办理完毕相关变更手续，并取得新的《企业法人营│\r\n│              │业执照》。证券简称自2012年8月2日由“深发展A”变更为“平安银行 │\r\n│              │”。                                                          │\r\n└───────┴───────────────────────────────┘\r\n\r\n【2.发行和交易】\r\n┌─────────┬─────────┬─────────┬─────────┐\r\n│股票类别          │A股               │发行制度          │核准制            │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│网上发行日期      │1989-03-10        │上市日期          │1991-04-03        │\r\n├─────────┼─────────┴─────────┴─────────┤\r\n│发行方式          │公开招募                                                  │\r\n├─────────┼─────────┬─────────┬─────────┤\r\n│发行量(万股)      │67.50             │发行价格(元)      │40.00             │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│发行费用(万)      │0.00              │发行总市值(万)    │2700.00           │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│每股面值          │1.00元            │募集资金净额(万)  │2700.00           │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│上市首日开盘价    │49.00             │上市首日收盘价    │49.00             │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│摊薄发行市盈率    │0.00              │加权发行市盈率    │---               │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│发行前每股净资产  │0.00              │发行后每股净资产  │0.00              │\r\n├─────────┼─────────┼─────────┼─────────┤\r\n│网上定价中签率%   │0.00              │网下配售中签率%   │---               │\r\n├─────────┼─────────┴─────────┴─────────┤\r\n│主承销商          │巨田证券有限责任公司                                      │\r\n├─────────┼─────────────────────────────┤\r\n│保荐人            │华润深国投信托有限公司                                    │\r\n└─────────┴─────────────────────────────┘\r\n\r\n【3.员工效益】 截止日期:2024-06-30，本期在职员工总数:40830，较上期变动:-5.31%\r\n┌─────────┬─────┬─────┬─────┬─────┬─────┐\r\n│指标/日期         │    2023年│    2022年│    2021年│    2020年│    2019年│\r\n├─────────┼─────┼─────┼─────┼─────┼─────┤\r\n│人均扣非净利润(元)│  107.68万│  102.71万│   89.12万│   75.70万│   82.00万│\r\n│人均营业总收入(元)│  381.96万│  406.94万│  416.68万│  403.03万│  402.76万│\r\n│人均薪酬(元)      │   48.01万│   52.36万│   55.10万│   56.86万│   58.28万│\r\n└─────────┴─────┴─────┴─────┴─────┴─────┘\r\n\r\n【4.参股控股】(前30) 截止日期:2024-06-30 共1家\r\n┌────────────┬────┬──────┬──────┬───────┐\r\n│关联方名称              │参控关系│ 持股比例(%)│投资金额(元)│      主营业务│\r\n├────────────┼────┼──────┼──────┼───────┤\r\n│平安理财有限责任公司    │子公司  │      100.00│     50.00亿│      资产管理│\r\n└────────────┴────┴──────┴──────┴───────┘\r\n\r\n'

In [6]:
from mootdx.quotes import Quotes
from mootdx.consts import MARKET_SH

client = Quotes.factory(market='ext')
client.bars(frequency=9,market=62,symbol='930740')
# client = Quotes.factory(market='std')
# client.index(frequency=9,symbol='000815')

2024-12-23 14:42:15,193 - mootdx - WARNING - 目前扩展市场行情接口已经失效, 后期有望修复.

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
datetime,,,,,,,,,,,,,,
2022-02-08 15:00:00,6006.825195,6111.714355,6002.967285,6111.714355,1194942316,82,0.0,2022,2,8,15,0,2022-02-08 15:00,47455.421875
2022-02-09 15:00:00,6104.010742,6143.085938,6091.513672,6104.534668,1194067684,45,0.0,2022,2,9,15,0,2022-02-09 15:00,44038.890625
2022-02-10 15:00:00,6100.211914,6170.574219,6074.973145,6167.916504,1193831582,42,0.0,2022,2,10,15,0,2022-02-10 15:00,43116.617188
2022-02-11 15:00:00,6156.144043,6238.849121,6155.191406,6189.784180,1197928696,52,0.0,2022,2,11,15,0,2022-02-11 15:00,59120.968750
2022-02-14 15:00:00,6170.565430,6173.572266,6047.046387,6065.971680,1195128441,47,0.0,2022,2,14,15,0,2022-02-14 15:00,48182.472656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-17 15:00:00,7394.705078,7452.752441,7390.379395,7395.830078,1194452767,40,0.0,2024,12,17,15,0,2024-12-17 15:00,45543.121094
2024-12-18 15:00:00,7424.293457,7503.697754,7424.293457,7456.256348,1194976388,45,0.0,2024,12,18,15,0,2024-12-18 15:00,47588.515625
2024-12-19 15:00:00,7421.272949,7472.816406,7395.867676,7417.515625,1193464118,39,0.0,2024,12,19,15,0,2024-12-19 15:00,41681.210938
2024-12-20 15:00:00,7415.318359,7427.383789,7363.925781,7363.932129,1192924159,36,0.0,2024,12,20,15,0,2024-12-20 15:00,39571.996094
2024-12-23 15:00:00,7364.312012,7496.261230,7364.312012,7452.854004,1197102610,52,0.0,2024,12,23,15,0,2024-12-23 15:00,55894.070312

In [7]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

In [8]:
api.connect('121.37.183.82', 7709)

In [9]:
eapi.connect('47.112.95.207', 7720)

In [10]:
api.to_df(api.get_index_bars(9, 1, '000001', 0, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,up_count,down_count
0,3367.904,3351.257,3384.992,3348.277,5567472.0,6.231178e+11,2024,12,23,15,0,2024-12-23 15:00,295,2005

In [11]:
api.to_df(api.get_security_bars(9, 0, '000837', 0, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,9.58,9.19,9.59,9.16,217719.0,202557424.0,2024,12,23,15,0,2024-12-23 15:00

In [12]:
eapi.to_df(eapi.get_instrument_bars(9, 62, "H30184", 0, 3))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,6161.324707,6417.234863,6156.957031,6371.828613,1203787749,5,0.0,2024,12,19,15,0,2024-12-19 15:00,98479.789062
1,6352.063477,6712.355957,6345.296875,6597.959961,1208396708,24,0.0,2024,12,20,15,0,2024-12-20 15:00,137902.562500
2,6595.555176,6681.301758,6458.434082,6467.571777,1206370557,20,0.0,2024,12,23,15,0,2024-12-23 15:00,118657.976562

In [13]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [14]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [15]:
pd.read_excel('/home/ts/app/StocksIC/stocksIC.xlsx',dtype={'StockCode':'object'}).set_index('StockCode').to_sql('StockIC', eng)

FileNotFoundError: [Errno 2] No such file or directory: '/home/ts/app/StocksIC/stocksIC.xlsx'

In [16]:
pd.read_sql('StocksIC', eng)

ProgrammingError: (psycopg.errors.SyntaxError) syntax error at or near "StocksIC"
LINE 1: StocksIC
        ^
[SQL: StocksIC]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [17]:
con = eng.connect()

In [18]:
con.commit()
con.close()

In [19]:
l = pd.read_sql('EmpIndex', eng)['IndexCode'].to_list()

ProgrammingError: (psycopg.errors.SyntaxError) syntax error at or near "EmpIndex"
LINE 1: EmpIndex
        ^
[SQL: EmpIndex]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [20]:

for i in l:
    try:
        con.execute(text('DROP TABLE IF EXISTS "'+i+'";'))
        con.commit()
    except:
        pass

con.close()

NameError: name 'l' is not defined

In [21]:
tdxIndex = pd.read_sql('tdxIndexs', eng)
empIndex = pd.read_sql('EmpIndex', eng)

ProgrammingError: (psycopg.errors.SyntaxError) syntax error at or near "tdxIndexs"
LINE 1: tdxIndexs
        ^
[SQL: tdxIndexs]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [17]:
empIndex['EMP']=1

NameError: name 'empIndex' is not defined

In [18]:
df = pd.merge(tdxIndex,empIndex,on='IndexCode',how='outer').drop('index',axis=1)

NameError: name 'tdxIndex' is not defined

In [ ]:
df[~(df.EMP==1)].drop('EMP',axis=1)

#============ FSCode 更新 ===============

In [22]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxFS')

ModuleNotFoundError: No module named 'psycopg2'

In [ ]:
df = pd.read_excel('g:/gitee/app/stocksic/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

In [ ]:
df = pd.read_excel('/home/ts/app/StocksIC/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

#===================== 数据分析 数据加载  ================

In [23]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')


finRAW = pd.read_sql('000002', eng,)
finRAW['report_date']=finRAW['report_date'].astype(object)

finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
trsfin = finRAW.set_index('Index').T
trsfin = trsfin.reset_index().rename(columns={'index':'Code'})

In [24]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [25]:
def GetFin(StockCode, day):
    finRAW = pd.read_sql(StockCode, eng)
    finRAW['report_date']=finRAW['report_date'].astype(object)
    finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
    trsfin = finRAW.set_index('Index').T
    trsfin = trsfin.reset_index().rename(columns={'index':'Code'})
    FSCode = pd.read_sql('FSCode',eng)
    sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')
    ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']
    fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
    items = fin.cnName.to_list()
    sumite = [item for item in items if any(substr in item for substr in "万")]
    for ite in sumite:
        fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000
    return fin

In [26]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [27]:
def GetFinF(file):
    from pytdx.hq import TdxHq_API
    from pytdx.crawler.base_crawler import demo_reporthook
    from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler

    api = TdxHq_API()
    api.connect('119.147.212.81', 7709)

    # file = 'gpcw'+str(day)+'.zip'

    datacrawler = HistoryFinancialCrawler()
    pd.set_option('display.max_columns', None)

    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=file, path_to_download="/tmp/tmpfile.zip")
    dd = datacrawler.to_df(data=result)
    dd['report_date']= dd['report_date'].astype(object)
    dd.to_sql(file[:-4],eng)

    # return dd

In [28]:
file = 'gpcw'+str(20240331)+'.zip'

In [29]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler

api = TdxHq_API()
api.connect('119.147.212.81', 7709)

crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()

## ================

In [30]:
from mootdx.affair import Affair

fff = Affair.files()

In [31]:
i = 10
while i <= 59:
   file =  fff[i]['filename']
   GetFinF(file)
   i= i+1

Downloaded 30000, Total is 0
Downloaded 60000, Total is 0
Downloaded 90000, Total is 0
Downloaded 120000, Total is 0
Downloaded 150000, Total is 0
Downloaded 180000, Total is 0
Downloaded 210000, Total is 0
Downloaded 240000, Total is 0
Downloaded 270000, Total is 0
Downloaded 300000, Total is 0
Downloaded 330000, Total is 0
Downloaded 360000, Total is 0
Downloaded 390000, Total is 0
Downloaded 420000, Total is 0
Downloaded 450000, Total is 0
Downloaded 480000, Total is 0
Downloaded 510000, Total is 0
Downloaded 540000, Total is 0
Downloaded 570000, Total is 0
Downloaded 600000, Total is 0
Downloaded 630000, Total is 0
Downloaded 660000, Total is 0
Downloaded 690000, Total is 0
Downloaded 720000, Total is 0
Downloaded 750000, Total is 0
Downloaded 780000, Total is 0
Downloaded 810000, Total is 0
Downloaded 840000, Total is 0
Downloaded 870000, Total is 0
Downloaded 900000, Total is 0
Downloaded 930000, Total is 0
Downloaded 960000, Total is 0
Downloaded 990000, Total is 0
Downloaded 1020000, Total is 0
Downloaded 1050000, Total is 0
Downloaded 1080000, Total is 0
Downloaded 1110000, Total is 0
Downloaded 1140000, Total is 0
Downloaded 1170000, Total is 0
Downloaded 1200000, Total is 0
Downloaded 1230000, Total is 0
Downloaded 1260000, Total is 0
Downloaded 1290000, Total is 0
Downloaded 1320000, Total is 0
Downloaded 1350000, Total is 0
Downloaded 1380000, Total is 0
Downloaded 1410000, Total is 0
Downloaded 1440000, Total is 0
Downloaded 1470000, Total is 0
Downloaded 1500000, Total is 0
Downloaded 1530000, Total is 0
Downloaded 1560000, Total is 0
Downloaded 1590000, Total is 0
Downloaded 1620000, Total is 0
Downloaded 1650000, Total is 0
Downloaded 1680000, Total is 0
Downloaded 1710000, Total is 0
Downloaded 1740000, Total is 0
Downloaded 1770000, Total is 0
Downloaded 1800000, Total is 0
Downloaded 1830000, Total is 0
Downloaded 1860000, Total is 0
Downloaded 1890000, Total is 0
Downloaded 1920000, Total is 0
Downloaded 1950000, Total is 0
Downloaded 1980000, Total is 0
Downloaded 2010000, Total is 0
Downloaded 2040000, Total is 0
Downloaded 2070000, Total is 0
Downloaded 2100000, Total is 0
Downloaded 2130000, Total is 0
Downloaded 2160000, Total is 0
Downloaded 2190000, Total is 0
Downloaded 2220000, Total is 0
Downloaded 2250000, Total is 0
Downloaded 2280000, Total is 0
Downloaded 2310000, Total is 0
Downloaded 2340000, Total is 0
Downloaded 2370000, Total is 0
Downloaded 2400000, Total is 0
Downloaded 2430000, Total is 0
Downloaded 2460000, Total is 0
Downloaded 2490000, Total is 0
Downloaded 2520000, Total is 0
Downloaded 2550000, Total is 0
Downloaded 2580000, Total is 0
Downloaded 2610000, Total is 0
Downloaded 2640000, Total is 0
Downloaded 2670000, Total is 0
Downloaded 2700000, Total is 0
Downloaded 2730000, Total is 0
Downloaded 2760000, Total is 0
Downloaded 2790000, Total is 0
Downloaded 2820000, Total is 0
Downloaded 2850000, Total is 0
Downloaded 2880000, Total is 0
Downloaded 2910000, Total is 0
Downloaded 2940000, Total is 0
Downloaded 2970000, Total is 0
Downloaded 3000000, Total is 0
Downloaded 3030000, Total is 0
Downloaded 3060000, Total is 0
Downloaded 3090000, Total is 0
Downloaded 3120000, Total is 0
Downloaded 3150000, Total is 0
Downloaded 3180000, Total is 0
Downloaded 3210000, Total is 0
Downloaded 3240000, Total is 0
Downloaded 3270000, Total is 0
Downloaded 3300000, Total is 0
Downloaded 3330000, Total is 0
Downloaded 3360000, Total is 0
Downloaded 3390000, Total is 0
Downloaded 3420000, Total is 0
Downloaded 3450000, Total is 0
Downloaded 3480000, Total is 0
Downloaded 3510000, Total is 0
Downloaded 3540000, Total is 0
Downloaded 3570000, Total is 0
Downloaded 3600000, Total is 0
Downloaded 3630000, Total is 0
Downloaded 3660000, Total is 0
Downloaded 3690000, Total is 0
Downloaded 3720000, Total is 0
Downloaded 3750000, Total is 0
Downloaded 3780000, Total is 0
Downloaded 3810000, Total is 0
Downloaded 3840000, Total is 0
Downloaded 3870000, Total is 0
Downloaded 3900000, Total is 0
Downloaded 3930000, Total is 0
Downloaded 3960000, Total is 0
Downloaded 3990000, Total is 0
Downloaded 4020000, Total is 0
Downloaded 4050000, Total is 0
Downloaded 4080000, Total is 0
Downloaded 4110000, Total is 0
Downloaded 4140000, Total is 0
Downloaded 4170000, Total is 0
Downloaded 4200000, Total is 0
Downloaded 4230000, Total is 0
Downloaded 4260000, Total is 0
Downloaded 4290000, Total is 0
Downloaded 4320000, Total is 0
Downloaded 4350000, Total is 0
Downloaded 4380000, Total is 0
Downloaded 4410000, Total is 0
Downloaded 4440000, Total is 0
Downloaded 4470000, Total is 0
Downloaded 4500000, Total is 0
Downloaded 4530000, Total is 0
Downloaded 4560000, Total is 0
Downloaded 4590000, Total is 0
Downloaded 4620000, Total is 0
Downloaded 4650000, Total is 0
Downloaded 4680000, Total is 0
Downloaded 4710000, Total is 0
Downloaded 4739647, Total is 0

ValueError: Table 'gpcw20220930' already exists.

In [32]:
GetFinF(20221231)

TypeError: can only concatenate str (not "int") to str

In [33]:
FSCode = pd.read_sql('FSCode',eng)

In [34]:
day = 20231231
ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']

In [35]:
sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')

In [36]:
fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)
items = fin.cnName.to_list()
sumite = [item for item in items if any(substr in item for substr in "万")]
for ite in sumite:
    fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000

In [37]:
node = fin.query('L1Code=="LRB" and L3Code!="EMP"')
node = node[~(node["vol"]==0)].reset_index(drop=True).reset_index()

In [35]:
s1 = pd.read_excel('/home/ts/App/StocksIC/ff.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [36]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [37]:
zcfz = zcfz[~(zcfz["vol"]==0)].reset_index(drop=True)

In [38]:
for i,ite in enumerate(zcfz.vol.to_list()):
    if ite < 0:
        zcfz.loc[i,'cnName'] ='负：'+ zcfz.loc[i,'cnName']
        zcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [38]:
fin.query('L1Code=="LRB"')

,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
74,74,LRB,利润表,YYSR,营业收入,SR,收入,col74,营业收入,465739087872.0
75,75,LRB,利润表,CBFY,成本费用,CB,成本,col75,营业成本,394783850496.0
76,76,LRB,利润表,CBFY,成本费用,CB,成本,col76,营业税金及附加,18584610816.0
77,77,LRB,利润表,CBFY,成本费用,CB,成本,col77,销售费用,12272115712.0
78,78,LRB,利润表,CBFY,成本费用,CB,成本,col78,管理费用,5766947840.0
...,...,...,...,...,...,...,...,...,...,...
377,377,LRB,利润表,CBFY,成本费用,SY,损益,col517,信用减值损失(万元),0.0
378,378,LRB,利润表,CBFY,成本费用,SY,损益,col518,净敞口套期收益(万元),0.0
379,379,LRB,利润表,CBFY,成本费用,HJ,合计,col519,营业总成本(万元),435658360000.0
380,380,LRB,利润表,CBFY,成本费用,SY,损益,col520,信用减值损失(万元、2019格式),-377876800.0
381,381,LRB,利润表,CBFY,成本费用,SY,损益,col521,资产减值损失(万元、2019格式),-3489952500.0

In [39]:
zzcfz = fin.query('L1Code=="ZCFZ" and (L3Code=="HJ" or L3Code=="SSGD")')
zzcfz = zzcfz[~(zzcfz["vol"]==0)].reset_index(drop=True)

In [40]:
for i,ite in enumerate(zzcfz.vol.to_list()):
    if ite < 0:
        zzcfz.loc[i,'cnName'] ='负：'+ zzcfz.loc[i,'cnName']
        zzcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [41]:
import plotly.express as px
# import numpy as np
# df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(zcfz, path=['L2Name','cnName'], values="vol"
# fig = px.pie(ssss, values=0,names='L2Name'
                #   color='lifeExp', hover_data=['iso_alpha'],
                #   color_continuous_scale='RdBu',
                #   color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop']))
)
config = {'scrollZoom': True}
fig.show(config=config)

NameError: name 'zcfz' is not defined

In [43]:
s1[sel.Code].loc[92].to_list()

NameError: name 's1' is not defined

In [44]:
LDZC = sel[sel.L3Code=='LDZC']
FLDZC = sel[sel.L3Code=='FLDZC']
SYZQY = sel[sel.L3Code=='SYZQY']

NameError: name 'sel' is not defined

In [ ]:

ssss = sss[sss.L1Code=='ZCFZ']

In [ ]:
ssss['voll']=

In [45]:
s1[LDZC.Code.to_list()].loc[92]

NameError: name 's1' is not defined

In [46]:
s1.col21.loc[92]

NameError: name 's1' is not defined

In [47]:
from  datetime import date
mon = date.today().strftime('%m')
year = date.today().strftime('%Y')
match mon:
    case mon if mon == '12':
        filename='gpcw'+year+'1231.zip'
    case mon if mon < '03':
        filename='gpcw'+year+'1231.zip'
    case mon if '03'<= mon < '06':
        filename='gpcw'+year+'0331.zip'
    case mon if '06'<= mon < '09':
        filename='gpcw'+year+'0630.zip'
    case mon if '09'<= mon < '12':
        filename='gpcw'+year+'0930.zip'

In [48]:
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()

In [49]:
import plotly.graph_objects as go

fig =go.Figure(go.Sunburst(
    labels=sel.cnName.to_list(),
    parents=sel.L3Name.to_list(),
    values=s1[sel.Code].loc[92].to_list(),
))
# Update layout for tight margin
# See https://plotly.com/python/creating-and-updating-figures/
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.show()

NameError: name 'sel' is not defined

In [50]:
df = px.data.tips()

In [51]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [52]:
import plotly.graph_objects as go

config = {'displayModeBar': True,'scrollZoom': True,'displaylogo': True,'modeBarButtonsToAdd':['drawline']}

fig = go.Figure(data=[go.Sankey(
    node = dict(
    thickness = 5,
    label = ["Ads", "Net profit", "Total income", "ROI", "Paid services", "Investment", "Expenses", "Maintaining website", "Paying employes", "Advertising", "Personal expenses", "Savings"],
    color = "cyan"
    ),
    link = dict(

    # indices correspond to labels
    source = [0, 1, 4, 2, 3, 2, 6, 6, 6, 1, 1],
    target = [2, 5, 2, 1, 2, 6, 7, 8, 9, 10, 11],
    value = [60000, 40000, 90000, 100000, 10000, 60000, 10000, 30000, 20000, 20000, 40000]
))])

fig.update_layout(
    title="DatavizWRLD.com monthly income and income management of 2021( in USD )",
    font=dict(size = 12, color = 'black')
)

# fig.update_layout(modebar_remove=[''])
fig.show(config=config)

In [53]:
import plotly.graph_objects as go

fig = go.Figure(go.Sankey(
    arrangement = "snap",
    node = {
        "label": ["A", "B", "C", "D", "E", "F"],
        "x": [0.2, 0.1, 0.5, 0.7, 0.3, 0.5],
        "y": [0.8, 0.5, 0.2, 0.4, 0.2, 0.3],
        'pad':10},  # 10 Pixels
    link = {
        "source": [0, 0, 1, 2, 5, 4, 3, 5],
        "target": [4, 3, 4, 3, 0, 2, 2, 3],
        "value": [1, 2, 1, 1, 1, 1, 1, 2]}))

fig.show()

In [ ]:
node.query('L2Code=="CBFY" and L3Code=="HJ"')

In [54]:
link = pd.DataFrame()

In [55]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and (L3Code=="CB" or L3Code=="CW")')['index']
mid['V'] = node.query('L2Code=="CBFY" and (L3Code=="CB" or L3Code=="CW")')['vol']
mid['T'] = node.query('L2Code=="CBFY" and L3Code=="HJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and L3Code=="TZSY"')['index']
mid['V'] = node.query('L2Code=="CBFY" and L3Code=="TZSY"')['vol']
mid['T'] = node.query('L2Code=="CBFY" and L3Code=="TZ"').values[0][0]
link = pd.concat([link, mid])

In [56]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="SDS" or L3Code =="LRZE") ')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="SDS"or L3Code =="LRZE")')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="JLR"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="YYLR" or L3Code=="YYLRHJ")')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="YYLR" or L3Code=="YYLRHJ")')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="LRZE"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['T'] = node.query('L2Code=="LR" and L3Code=="JLRS" ')['index']
mid['V'] = node.query('L2Code=="LR" and L3Code=="JLRS" ')['vol']
mid['S'] = node.query('L2Code=="LR" and L3Code=="JLR"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="HJ")')['index']
mid['V'] = node.query('L2Code=="LR" and (L3Code=="JLR" or L3Code=="HJ")')['vol']
mid['T'] = node.query('L3Code=="ZHSYZE"').values[0][0]
link = pd.concat([link, mid])

In [57]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="YYSR" and L3Code=="SR"')['index']
mid['V'] = node.query('L2Code=="YYSR" and L3Code=="SR"')['vol']
mid['T'] = node.query('L2Code=="YYSR" and L3Code=="HJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['T'] = node.query('L2Code=="ZHSY" and L3Code=="GS"')['index']
mid['V'] = node.query('L2Code=="ZHSY" and L3Code=="GS"')['vol']
mid['S'] = node.query('L2Code=="ZHSY" and L3Code=="ZHSYZE"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="LRY" and L3Code=="HJY"')['index']
mid['V'] = node.query('L2Code=="LRY" and L3Code=="HJY"')['vol']
mid['T'] = node.query('L2Code=="LRY" and L3Code=="HJYJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['T'] = node.query('L2Code=="LRY" and L3Code=="HJYS"')['index']
mid['V'] = node.query('L2Code=="LRY" and L3Code=="HJYS"')['vol']
mid['S'] = node.query('L2Code=="LRY" and L3Code=="HJYJ"').values[0][0]
link = pd.concat([link, mid])

In [58]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and L3Code=="HJ"')['index']
mid['V'] = node.query('L2Code=="CBFY" and L3Code=="HJ"')['vol']
mid['T'] = node.query('L3Code=="YYLRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="YYSR" and L3Code=="HJ"')['index']
mid['V'] = node.query('L2Code=="YYSR" and L3Code=="HJ"')['vol']
mid['T'] = node.query('L3Code=="YYLRHJ"').values[0][0]
link = pd.concat([link, mid])

In [59]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and (L3Code=="SY" or L3Code=="TZ")')['index']
mid['V'] = node.query('L2Code=="CBFY" and (L3Code=="SY" or L3Code=="TZ")')['vol']
mid['T'] = node.query('L2Code=="LR" and L3Code=="YYLRHJ"').values[0][0]
link = pd.concat([link, mid])

In [60]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CBFY" and L3Code=="CWFY"')['index']
mid['V'] = node.query('L2Code=="CBFY" and L3Code=="CWFY" ')['vol']
mid['T'] = node.query('L2Code=="CBFY" and L3Code=="CW"').values[0][0]
link = pd.concat([link, mid])

==============================

In [61]:
node.query('L2Code=="LR" and L3Code=="YYLRHJ"')

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
9,9,86,LRB,利润表,LR,利润,YYLRHJ,合计,col86,营业利润,29251702784.0

In [62]:
node.query('L3Code=="YYLRHJ"')

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
9,9,86,LRB,利润表,LR,利润,YYLRHJ,合计,col86,营业利润,29251702784.0

In [63]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [64]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [65]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [66]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXMDJW" and L3Code=="ZJEJJ"').values[0][0]
link = pd.concat([link, mid])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L3Code=="JE"')['index']
mid['V'] = node.query('L3Code=="JE"')['vol']
mid['T'] = node.query('L2Code=="DJW" and L3Code=="ZJE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
link

In [67]:
import plotly.graph_objects as go
# override gray link colors with 'source' colors
# change 'magenta' to its 'rgba' value to add opacity


fig = go.Figure(data=[go.Sankey(

    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  node['cnName'].tolist(),
      # color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  link['S'].tolist(),
      target =  link['T'].tolist(),
      value =  abs(link['V']).tolist(),
      # label =  data['data'][0]['link']['label'],
      # color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Sankey分析<br>"+"Code: "+str(day),
                  font_size=10)
fig.show()

In [68]:
import plotly.graph_objects as go
import urllib, json

url = 'https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/sankey_energy.json'
response = urllib.request.urlopen(url)
data = json.loads(response.read())

# override gray link colors with 'source' colors
opacity = 0.4
# change 'magenta' to its 'rgba' value to add opacity
data['data'][0]['node']['color'] = ['rgba(255,0,255, 0.8)' if color == "magenta" else color for color in data['data'][0]['node']['color']]
data['data'][0]['link']['color'] = [data['data'][0]['node']['color'][src].replace("0.8", str(opacity))
                                    for src in data['data'][0]['link']['source']]

fig = go.Figure(data=[go.Sankey(
    valueformat = ".0f",
    valuesuffix = "TWh",
    # Define nodes
    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  data['data'][0]['node']['label'],
      color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  data['data'][0]['link']['source'],
      target =  data['data'][0]['link']['target'],
      value =  data['data'][0]['link']['value'],
      label =  data['data'][0]['link']['label'],
      color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Energy forecast for 2050<br>Source: Department of Energy & Climate Change, Tom Counsell via <a href='https://bost.ocks.org/mike/sankey/'>Mike Bostock</a>",
                  font_size=10)
fig.show()

==================   绘制瀑布图 =================

In [69]:
li =['col502','col519','col86','col92','col95','col206','col270']

In [70]:
x = []
y = []

In [71]:
for i, ite in enumerate(li):
    if ite =='col519':
        x.append(node[node.Code==ite].cnName.values[0])
        y.append(-node[node.Code==ite].vol.values[0])
    else:
        x.append(node[node.Code==ite].cnName.values[0])
        y.append(node[node.Code==ite].vol.values[0])

In [72]:
for i, ite in enumerate(li):
        x.append(node[node.Code==ite].cnName.values[0])
        y.append(node[node.Code==ite].vol.values[0])

In [73]:
xx = pd.DataFrame(x).rename(columns={0:'cnName'})
yy = pd.DataFrame(y).rename(columns={0:'vol'})

In [74]:
xxx = pd.concat([xx,yy],axis=1)

In [75]:

import plotly.express as px

fig = px.bar(xxx, x='cnName', y='vol')

fig.show()

====================================

In [76]:
waterfin = node.query('L3Code=="LRHJ" or L3Code=="LCHJ" or L3Code=="JE" ')

In [77]:
lis = waterfin.query('L3Code=="LCHJ"').index.tolist()

In [78]:
for i in lis:
    waterfin.loc[i,'vol'] = -waterfin.loc[i,'vol']

In [79]:
node

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
0,0,74,LRB,利润表,YYSR,营业收入,SR,收入,col74,营业收入,465739087872.0
1,1,75,LRB,利润表,CBFY,成本费用,CB,成本,col75,营业成本,394783850496.0
2,2,76,LRB,利润表,CBFY,成本费用,CB,成本,col76,营业税金及附加,18584610816.0
3,3,77,LRB,利润表,CBFY,成本费用,CB,成本,col77,销售费用,12272115712.0
4,4,78,LRB,利润表,CBFY,成本费用,CB,成本,col78,管理费用,5766947840.0
5,5,80,LRB,利润表,CBFY,成本费用,CW,成本,col80,财务费用,3714825472.0
6,6,82,LRB,利润表,CBFY,成本费用,SY,损益,col82,公允价值变动净收益,340112544.0
7,7,83,LRB,利润表,CBFY,成本费用,TZ,成本,col83,投资收益,2687829760.0
8,8,84,LRB,利润表,CBFY,成本费用,TZSY,投资收益,col84,对联营企业和合营企业（投资收益）,58933924.0
9,9,86,LRB,利润表,LR,利润,YYLRHJ,合计,col86,营业利润,29251702784.0
10,10,88,LRB,利润表,LR,利润,YYLR,营业利润,col88,加：营业外收入,1149550336.0
11,11,89,LRB,利润表,LR,利润,YYLR,营业利润,col89,减：营业外支出,595824256.0
12,12,92,LRB,利润表,LR,利润,LRZE,总额,col92,利润总额,29805428736.0
13,13,93,LRB,利润表,LR,利润,SDS,所得税,col93,减：所得税（利润总额）,9349869568.0
14,14,95,LRB,利润表,LR,利润,JLR,净利润,col95,净利润,20455559168.0
15,15,96,LRB,利润表,LR,利润,JLRS,净利润归属,col96,归属于母公司所有者的净利润,12162683904.0
16,16,97,LRB,利润表,LR,利润,JLRS,净利润归属,col97,少数股东损益,8292874240.0
17,17,205,LRB,利润表,LR,利润,JLRS,扣非净利润,col206,扣除非经常性损益后的净利润,9793841152.0
18,18,206,LRB,利润表,LR,利润,JLRL,获利能力分析,col207,息税前利润(EBIT),32545832960.0
19,19,207,LRB,利润表,LR,利润,JLRL,获利能力分析,col208,息税折旧摊销前利润(EBITDA),39309377536.0
20,20,268,LRB,利润表,LR,利润,HJ,合计,col269,其他综合收益(利润表),1372238592.0
21,21,269,LRB,利润表,ZHSY,综合收益,ZHSYZE,总额,col270,综合收益总额,21827796992.0
22,22,275,LRB,利润表,LRY,利润,HJYJ,合计,col276,近一年净利润,20455559168.0
23,23,282,LRB,利润表,LRY,利润,HJY,合计,col283,近一年营业收入（万元）,465739080000.0
24,24,300,LRB,利润表,CBFY,成本费用,SY,损益,col301,资产处置收益,10858912.0
25,25,303,LRB,利润表,CBFY,成本费用,CB,成本,col304,研发费用,535987744.0
26,26,304,LRB,利润表,CBFY,成本费用,CWFY,财务费用,col305,利息费用(财务费用),5737473536.0
27,27,305,LRB,利润表,CBFY,成本费用,CWFY,财务费用,col306,利息收入(财务费用),2997068032.0
28,28,307,LRB,利润表,LRY,利润,HJYS,合计,col308,近一年归母净利润（万元）,12162685000.0
29,29,308,LRB,利润表,LRY,利润,HJYS,合计,col309,近一年扣非净利润（万元）,9793841200.0
30,30,318,LRB,利润表,LR,利润,YYZE,总额,col319,营业总收入TTM(万元),465739080000.0
31,31,362,LRB,利润表,YYSR,营业收入,HJ,合计,col502,营业总收入(万元),465739080000.0
32,32,364,LRB,利润表,ZHSY,综合收益,GS,归属,col504,归属于母公司所有者（综合收益）(万元),13037743799.999998
33,33,365,LRB,利润表,ZHSY,综合收益,GS,归属,col505,归属于少数股东（综合收益）(万元),8790053100.0
34,34,379,LRB,利润表,CBFY,成本费用,HJ,合计,col519,营业总成本(万元),435658360000.0
35,35,380,LRB,利润表,CBFY,成本费用,SY,损益,col520,信用减值损失(万元、2019格式),-377876800.0
36,36,381,LRB,利润表,CBFY,成本费用,SY,损益,col521,资产减值损失(万元、2019格式),-3489952500.0

In [ ]:
# addd = waterfin.query('L3Code=="ZJE" or L3Code=="ZJEY"')

In [ ]:
# waterfin = waterfin.drop(waterfin.query('L3Code=="ZJE" or L3Code=="ZJEY"')['index'].tolist())

In [ ]:
# waterfin = pd.concat([waterfin, addd]).head(9)

In [80]:
x = waterfin.cnName.tolist()
x.append("净流量")
y = waterfin["vol"].tolist()
y.append(0)

In [ ]:
x

In [81]:
waterfin = pd.concat([waterfin,node.query('L2Code=="HLBD" ')])

In [82]:

import plotly.graph_objects as go

fig = go.Figure(go.Waterfall(
    x = x,
    measure = ["absolute", "relative", "total", "relative", "relative", "total", "relative", "relative", "total","relative","total"],
    y = y, 
    base = 0,
    decreasing = {"marker":{"color":"Maroon", "line":{"color":"red", "width":2}}},
    increasing = {"marker":{"color":"Teal"}},
    totals = {"marker":{"color":"deep sky blue", "line":{"color":"blue", "width":3}}}
))

fig.update_layout(title = "Profit and loss statement", waterfallgap = 0.3)

fig.show()

=============== Table ======================

In [ ]:
tasel = mfinsel[['StockCode','StockName','L1Name','L2Name','L3Name','L4Name']]

In [ ]:
len(tasel)

In [ ]:

import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(
        header=dict(values=list(tasel.columns)),
        cells=dict(values=[tasel.StockCode,tasel.StockName,tasel.L1Name,tasel.L2Name,tasel.L3Name,tasel.L4Name]))
                        ])
fig.show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Waterfall(
    x = [["2016", "2017", "2017", "2017", "2017", "2018", "2018", "2018", "2018"],
        ["initial", "q1", "q2", "q3", "total", "q1", "q2", "q3", "total"]],
    measure = ["absolute", "relative", "relative", "relative", "total", "relative", "relative", "relative", "total"],
    y = [1, 2, 3, -1, None, 1, 2, -4, None],
    base = 1000
))

fig.add_trace(go.Waterfall(
    x = [["2016", "2017", "2017", "2017", "2017", "2018", "2018", "2018", "2018"],
        ["initial", "q1", "q2", "q3", "total", "q1", "q2", "q3", "total"]],
    measure = ["absolute", "relative", "relative", "relative", "total", "relative", "relative", "relative", "total"],
    y = [1.1, 2.2, 3.3, -1.1, None, 1.1, 2.2, -4.4, None],
    base = 1000
))

fig.update_layout(
    waterfallgroupgap = 0.5,
)

fig.show()

=================

In [84]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
StockIC = pd.read_sql("StockIC", engB)

In [85]:
StockCode = '600409'
day = 20240331

In [86]:
l4name = StockIC[StockIC['StockCode']==StockCode]['L4Name'].tolist()[0]
StockName = StockIC[StockIC['StockCode']==StockCode]['StockName'].tolist()[0]

In [ ]:
# finF = GetFinF(day)

In [87]:
finF = pd.read_sql('gpcw'+str(day), eng)

In [88]:
mfin = pd.merge(finF,StockIC, left_on='code',right_on='StockCode', how='inner')

In [89]:
mfinsel = mfin[mfin['L4Name']==l4name]

In [90]:
desel = mfinsel.describe().T

In [91]:
fin = GetFin(StockCode,day)

In [92]:
anafin = fin.query('L1Code=="MGZB" and L3Code!="EMP"')

In [93]:
data = pd.merge(anafin, desel.reset_index(drop=False),left_on='Code',right_on='index',how='inner')

In [94]:
lens = (max(data['mean'])-min(data['mean']))/2

In [95]:
data['L1Name'].head(1).tolist()[0]

'每股指标'

In [96]:

import plotly.graph_objects as go

categories = data.cnName.tolist()

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
      r=data['mean'].tolist(),
      theta=categories,
      # fill='toself',
      name='mean'
))
fig.add_trace(go.Scatterpolar(
      r=data.vol.tolist(),
      theta=categories,
      # line_close=True,
      # fill='toself',
      name='20240331'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[round((min(anafin.vol)-(3*lens)),2), max(anafin.vol)+lens]
    )),
  showlegend=False
)

fig.show()

In [97]:
import plotly.express as px

fig1 = px.bar_polar(data, r=data['min'], theta=data['cnName'])
# fig = px.line_polar(data, r=data['std'], theta=data['cnName'], line_close=True)
config = {'scrollZoom': True}
fig.show(config=config)
# fig1.show()

In [98]:
import plotly.graph_objects as go
categories = data.cnName.tolist()

fig3 = go.Figure()

fig3.add_trace(go.Barpolar(
    r=list(data['mean']),
    theta=categories,
    name='行业均值',
    # marker_color='rgb(106,81,163)'
))
fig3.add_trace(go.Barpolar(
    r=list(data['vol']),
    theta=categories,
    name=StockName,
    # marker_color='rgb(158,154,200)'
))
fig3.show()

In [ ]:
data

In [99]:

import plotly.graph_objects as go

categories = ['processing cost','mechanical properties','chemical stability',
              'thermal stability', 'device integration']

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
      r=[1, 5, 2, 2, 3],
      theta=categories,
      fill='tonext',
      name='Product A'
))
fig.add_trace(go.Scatterpolar(
      r=[4, 3, 2.5, 1, 2],
      theta=categories,
      fill='tonext',
      name='Product B'
))
fig.update_traces(line_dash='dot')
fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 5]
    )),
  showlegend=False,
  
)

fig.show()

In [100]:
import plotly.graph_objects as go
config = {'scrollZoom': True, 'displaylogo':False,'displayFraction':True} 
fig = go.Figure()
categories = data.cnName.tolist()
fig.add_trace(go.Barpolar(
    r=list(data['mean']),
    theta=categories,
    name='meam',
    marker_color='rgb(106,81,163)'
))
fig.add_trace(go.Barpolar(
    r=list(data['vol']),
    theta=categories,
    name='vol',
    marker_color='rgb(158,154,200)'
))

# fig.update_traces(text=list(data['cnName']))
fig.update_layout(
    title='Wind Speed Distribution in Laurel, NE',
    font_size=12,
    legend_font_size=16,
    # barnorm='percent',
    # polar_radialaxis_ticksuffix='%',
    # polar_angularaxis_rotation=90,

)
fig.show(config=config)
# fig.show()

/home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/plotly/offline/offline.py:152: UserWarning:


Unrecognized config options supplied: ['displayFraction']

In [101]:
import plotly.express as px
config = {'scrollZoom': True, 'displaylogo':False,}
# 创建一个示例数据集
df = px.data.iris()

# 使用 Plotly Express 生成散点图
fig = px.scatter(df, x="sepal_width", y="sepal_length")

fig.show(config=config)