201303开始 www.szse.cn
201804开始 docs.static.szse.cn
https://akshare.akfamily.xyz/data/stock/stock.html#id9

In [2]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd

个股信息查询-东财

In [40]:
df1 = ak.stock_individual_info_em(symbol="600489").set_index('item').T
df2 = ak.stock_individual_info_em(symbol="600409").set_index('item').T

In [46]:
pd.concat([df1,df2])

item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
value,23.44,600489,中金黄金,4847312564.0,4847312564.0,113621006500.160004,113621006500.160004,贵金属,20030814
value,6.23,600409,三友化工,2064349448.0,2064349448.0,12860897061.040001,12860897061.040001,化学原料,20030618

信息披露公告-巨潮资讯

In [24]:
cl = ['年报', '半年报', '一季报', '三季报']

ak.stock_zh_a_disclosure_report_cninfo(symbol="600489", market="沪深京", category="一季报", start_date="19990101", end_date="20251231")

  0%|          | 0/1 [00:00<?, ?it/s]

,代码,简称,公告标题,公告时间,公告链接
0,600489,中金黄金,中金黄金股份有限公司2025年第一季度报告,2025-04-30 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
1,600489,中金黄金,中金黄金股份有限公司2024年第一季度报告,2024-04-27 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
2,600489,中金黄金,中金黄金股份有限公司2023年第一季度报告,2023-04-27 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
3,600489,中金黄金,中金黄金股份有限公司2022年第一季度报告,2022-04-21 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
4,600489,中金黄金,中金黄金股份有限公司2021年第一季度报告,2021-04-30 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
5,600489,中金黄金,中金黄金股份有限公司2021年第一季度报告正文,2021-04-30 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
6,600489,中金黄金,2020年第一季度报告,2020-04-30 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
7,600489,中金黄金,2020年第一季度报告正文,2020-04-30 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
8,600489,中金黄金,2019年第一季度报告,2019-04-27 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
9,600489,中金黄金,2018年第一季度报告,2018-04-27 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
10,600489,中金黄金,2017年第一季度报告,2017-04-27 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
11,600489,中金黄金,2016年第一季度报告,2016-04-29 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
12,600489,中金黄金,2015年第一季度报告,2015-04-25 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
13,600489,中金黄金,2014年第一季度报告,2014-04-26 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
14,600489,中金黄金,2013年第一季度报告,2013-04-26 00:00:00,http://www.cninfo.com.cn/new/disclosure/detail...
15,600489,中金黄金,2012年第一季度报告,2012-04-27 06:30:00,http://www.cninfo.com.cn/new/disclosure/detail...
16,600489,中金黄金,2011年第一季度报告,2011-04-25 06:30:00,http://www.cninfo.com.cn/new/disclosure/detail...
17,600489,中金黄金,2010年第一季度报告,2010-04-27 06:30:00,http://www.cninfo.com.cn/new/disclosure/detail...
18,600489,中金黄金,2009年第一季度报告,2009-04-29 06:30:00,http://www.cninfo.com.cn/new/disclosure/detail...
19,600489,中金黄金,2008年第一季度报告,2008-04-23 06:30:00,http://www.cninfo.com.cn/new/disclosure/detail...
20,600489,中金黄金,2007年第一季度报告,2007-04-28 05:30:30,http://www.cninfo.com.cn/new/disclosure/detail...
21,600489,中金黄金,中金黄金2006年第一季度报告,2006-04-22 05:15:08,http://www.cninfo.com.cn/new/disclosure/detail...
22,600489,中金黄金,中金黄金2005年第一季度报告,2005-04-29 05:05:34,http://www.cninfo.com.cn/new/disclosure/detail...
23,600489,中金黄金,中金黄金2004年第一季度报告,2004-04-29 05:28:32,http://www.cninfo.com.cn/new/disclosure/detail...

In [ ]:

engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [ ]:
StockLists=pd.read_sql('akStocksList', engS)['StockCode'].to_list()

In [ ]:
ak.stock_industry_change_cninfo(symbol="002179", start_date="11000101", end_date="22000101")

### 每股指标

In [ ]:
ak.stock_zh_a_spot_em()

In [ ]:
ak.stock_research_report_em()

In [ ]:
ak.stock_industry_pe_ratio_cninfo(symbol="国证行业分类", date="20250630")

In [ ]:
ak.stock_a_indicator_lg(symbol="all")

#### 乐咕乐股-指数市盈率

In [ ]:
ak.stock_index_pe_lg(symbol="上证50")

### 指数市净率

In [ ]:
ak.stock_index_pb_lg(symbol="上证50")

## A 股估值指标

* 百度
* indicator="总市值"; choice of {"总市值", "市盈率(TTM)", "市盈率(静)", "市净率", "市现率"}
* period="近一年"; choice of {"近一年", "近三年", "近五年", "近十年", "全部"}

In [ ]:
ak.stock_zh_valuation_baidu(symbol="000001", indicator="市盈率(TTM)", period="近一年")

* 东方财富网
* PE(TTM) PE(静) 市净率	PEG值	市现率	市销率

In [ ]:
ak.stock_value_em(symbol="002202")

In [ ]:
ak.stock_a_ttm_lyr()

In [ ]:
icdf = pd.read_sql('akStockIC',engB)

In [ ]:
ak.stock_zygc_em(symbol="SZ"+"000008")

In [ ]:
icdf[icdf['StockCode']=='688409']

In [ ]:
icdf.drop_duplicates(subset='证券代码')

In [ ]:
ldf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
IndexLists = ldf[~ldf['From'].isin(['TDXBLK','EMP'])][['IndexCode','IndexName']].values.tolist()

In [ ]:
StockLists=pd.read_sql('akStocksList', engS)['StockCode'].to_list()

In [ ]:
emp = pd.read_sql('EmpIndex', eng)

In [ ]:
ak.index_stock_cons("399657")

In [ ]:
pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})[['IndexCode','IndexName']].values.tolist()

In [ ]:
IndexLists = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})[['IndexCode','IndexName']].values.tolist()

In [ ]:
IndexLists[1][0]

In [ ]:
ll = []

In [ ]:
IndexLists[12][0]

In [ ]:
ll.append(IndexLists[12][0])

In [ ]:
ll.append('103')

In [ ]:
ll

In [ ]:
df = ak.index_stock_cons(IndexLists[0][0])
df['IndexCode'] = IndexLists[0][0]
df['IndexName'] = IndexLists[0][1] 
for i in IndexLists[1:3]:
    try:
        tmp = ak.index_stock_cons(i[0]).drop_duplicates(subset='品种代码',keep='first')
        tmp['IndexCode'] = i[0]
        tmp['IndexName'] = i[1]
        df = pd.concat([df,tmp])
        print(i[0]+'ok !')
    except:
        ll = ll.append(i[0])
        print(i[0]+'EMP !! ')

In [ ]:
df.columns.values

In [ ]:
df.rename(columns={'品种代码':'StockCode', '品种名称':'StockName', '纳入日期':'DP'},inplace=True)

In [ ]:
df[['IndexCode', 'IndexName','StockCode', 'StockName', 'DP']].set_index('IndexCode')

In [ ]:
df

In [ ]:
IndexLists[1:3]

In [ ]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [ ]:
pd.read_sql('akStockIC', engB)

In [ ]:
akdf.drop('index',axis=1).set_index('证券代码').to_sql('akStockIC',engB,if_exists='replace')

In [ ]:
StockList = pd.read_sql('akStocksList', eng)

In [ ]:
StocksCode = StockList['StockCode'].tolist()

In [ ]:
idf = ak.stock_industry_change_cninfo(symbol=StocksCode[0], start_date="11000101", end_date="22000101")
for code in StocksCode[1:]:
    df_tmp = ak.stock_industry_change_cninfo(symbol=code, start_date="11000101", end_date="22000101")
    idf = pd.concat([idf,df_tmp])
    print('code '+code+' :concat !')

### 主营介绍

* 同花顺

In [ ]:
ak.stock_zyjs_ths(symbol="002202")

* 东财

In [ ]:
ak.stock_zygc_em(symbol="SZ002202")

### 行业分类

In [ ]:
InduList = ["巨潮行业分类标准", "申银万国行业分类标准", "巨潮产业细分标准",  "全球行业分类标准"]

In [ ]:
df = ak.stock_industry_category_cninfo("证监会行业分类标准")
for iList in InduList:
    dfx = ak.stock_industry_category_cninfo(iList)
    df = pd.concat([df,dfx])

In [ ]:
df0 = ak.stock_industry_category_cninfo(symbol=InduList[0])
df1 = ak.stock_industry_category_cninfo(symbol=InduList[1])

In [ ]:
df = pd.concat([df0,df1])

In [ ]:
ak.stock_industry_category_cninfo('全球行业分类标准')

In [ ]:
ak.stock_industry_category_cninfo("申银万国行业分类标准")

* 上市公司行业归属的变动情况-巨潮资讯

In [ ]:
ak.stock_industry_change_cninfo(symbol="600004")

* 申万个股行业分类变动历史

In [ ]:
ak.stock_industry_change_cninfo(symbol="600230", start_date="11000101", end_date="20260101")

In [ ]:
ak.stock_industry_clf_hist_sw()

In [ ]:
ak.stock_info_sz_change_name("简称变更")

In [ ]:
ak.stock_profile_cninfo('600382')

In [ ]:
ak.index_stock_cons_csindex(symbol="H50056")

In [ ]:
StockLists.index('002142')

In [ ]:
ak.sw_index_third_cons(symbol="859822.SI")

In [ ]:
df = pd.DataFrame(columns=['新证券简称', '行业中类', '行业大类', '行业次类', '行业门类', '机构名称', '行业编码', '分类标准','分类标准编码', '证券代码', '变更日期'], dtype=object)
for i in StockLists[5000:5020]:
    tempdf = ak.stock_industry_change_cninfo(symbol=i, start_date="11000101", end_date="22000101")
    tempdf = tempdf[tempdf['分类标准编码'].isin(['008001','008002','008003','008014'])].sort_values(by='分类标准编码')
    df = pd.concat([df,tempdf])

In [ ]:
ak.stock_industry_change_cninfo(symbol="601989", start_date="11000101", end_date="22000101")

In [ ]:
ddf = ak.stock_industry_change_cninfo(symbol="002142", start_date="11000101", end_date="22000101")

In [ ]:
ddf = ak.stock_industry_change_cninfo(symbol="002142", start_date="11000101", end_date="22000101")
ddf[~ddf['分类标准'].str.contains('旧')].drop_duplicates(subset='分类标准',keep='last')

In [ ]:
df[['新证券简称','证券代码','分类标准', '变更日期','行业中类', '行业大类', '行业次类', '行业门类', '行业编码',
       '分类标准编码' ]].rename(columns={'新证券简称':'StockName','证券代码':'StockCode','分类标准':'ICS', '变更日期':'DP','行业中类':'IC4', '行业大类':'IC3', '行业次类':'IC2', '行业门类':'IC1', '行业编码':'ICode',
       '分类标准编码':'ICSCode' }).set_index('StockCode')

In [ ]:
ak.stock_zygc_em(symbol="SZ"+"301338")

In [ ]:
ak.stock_industry_pe_ratio_cninfo(symbol="国证行业分类", date="20250812")

In [ ]:
ak.stock_analyst_detail_em(
        analyst_id="11000423631", indicator="最新跟踪成分股"
    )

In [ ]:
ak.stock_hot_rank_em()

## 申万行业信息

### 申万一级行业信息

In [ ]:
ak.sw_index_first_info()

### 申万二级行业信息

In [ ]:
ak.sw_index_second_info()

### 申万三级行业信息

In [ ]:
ak.sw_index_third_info()

### 申万三级行业成份

In [ ]:
ak.sw_index_third_cons(symbol="850111.SI")

## 指数

In [ ]:
ak.index_csindex_all()

In [ ]:
ak.stock_zh_index_spot_em(symbol="上证系列指数")

## 股票指数信息一览表

In [ ]:
ak.index_stock_info()

### 国证指数

In [ ]:
ak.index_all_cni()

In [ ]:
ak.index_all_cni().to_excel('G:/Gitee/App/TDXapp/tdxAppData/gzIndex.xlsx')

## 股票指数 最新成份

In [ ]:
ak.index_stock_cons("000001")

### 中证

In [ ]:
ak.index_stock_cons_csindex("H30035")

### 国证

In [ ]:
ak.index_detail_cni(symbol='H30035', date='202508')

====================

In [ ]:
wcidf = ak.drewry_wci_index('shanghai-los angeles')

In [ ]:
cidf = ak.index_ci_cx()

In [ ]:
ak.index_global_name_table()

In [ ]:
ak.index_kq_fz(symbol="景气指数")

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(wcidf,x='date', y=wcidf['wci'],line_shape='linear')
fig.show()

In [ ]:
ak.index_stock_cons_csindex('000888')

In [ ]:
ak.index_stock_cons('000888')

In [ ]:
ak.stock_industry_category_cninfo(symbol="全球行业分类标准")

In [ ]:
ak.stock_industry_change_cninfo(symbol="000001", start_date="20200101", end_date="20250808")

In [ ]:
ak.stock_share_change_cninfo(symbol="002594", start_date="20091227", end_date="20251021")

In [ ]:
ak.stock_profile_cninfo(symbol="600288")

In [ ]:
ak.tool_trade_date_hist_sina()

## 股票市场总貌
### 上海证券交易所
* 目标地址: http://www.sse.com.cn/market/stockdata/statistic/
* 描述: 上海证券交易所-股票数据总貌
* 限量: 单次返回最近交易日的股票数据总貌(当前交易日的数据需要交易所收盘后统计)

In [ ]:
ak.stock_sse_summary()

### 上海证券交易所-每日概况
* 目标地址: http://www.sse.com.cn/market/stockdata/overview/day/
* 描述: 上海证券交易所-数据-股票数据-成交概况-股票成交概况-每日股票情况
* 限量: 单次返回指定日期的每日概况数据, 当前交易日数据需要在收盘后获取; 注意仅支持获取在 20211227（包含）之后的数据

In [ ]:
ak.stock_sse_deal_daily(date="20250730")

### 深圳证券交易所
* 目标地址: http://www.szse.cn/market/overview/index.html
* 描述: 深圳证券交易所-市场总貌-证券类别统计
* 限量: 单次返回指定 date 的市场总貌数据-证券类别统计(当前交易日的数据需要交易所收盘后统计)

In [ ]:
ak.stock_szse_summary(date="20250730")

### 股票行业成交
* 目标地址: http://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
* 描述: 深圳证券交易所-统计资料-股票行业成交数据
* 限量: 单次返回指定 symbol 和 date 的统计资料-股票行业成交数据

In [ ]:
ak.stock_szse_sector_summary(symbol="当年", date="202402")

In [ ]:
df1 = ak.stock_szse_sector_summary(symbol="当年", date="202506").drop('项目名称-英文',axis=1)
df2 = ak.stock_szse_sector_summary(symbol="当年", date="202406").drop('项目名称-英文',axis=1)

In [ ]:
((((df1['成交金额-人民币元']/df1['交易天数']))/100000000)-(((df2['成交金额-人民币元']/df2['交易天数']))/100000000)).round(2)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201301").drop('项目名称-英文',axis=1)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201701").drop('项目名称-英文',axis=1)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import BytesIO, StringIO

初始化需要修改代码，2018年4月后数据不用修改

In [ ]:
def stock_szse_sector_summary(
    symbol: str = "当月", date: str = "202501"
) -> pd.DataFrame:
    """
    深圳证券交易所-统计资料-股票行业成交数据
    https://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
    :param symbol: choice of {"当月", "当年"}
    :type symbol: str
    :param date: 交易年月
    :type date: str
    :return: 股票行业成交数据
    :rtype: pandas.DataFrame
    """
    url = "https://www.szse.cn/market/periodical/month/index.html"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    tags_list = soup.find_all(name="div", attrs={"class": "g-container"})[1].find_all(
        "script"
    )
    tags_dict = [
        eval(
            item.string[item.string.find("{") : item.string.find("}") + 1]
            .replace("\n", "")
            .replace(" ", "")
            .replace("value", "'value'")
            .replace("text", "'text'")
        )
        for item in tags_list
    ]
    date_url_dict = dict(
        zip(
            [item["text"] for item in tags_dict],
            [item["value"][2:] for item in tags_dict],
        )
    )
    date_format = "-".join([date[:4], date[4:]])
    url = f"https://www.szse.cn/market/periodical/month/{date_url_dict[date_format]}"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    url = [
        item for item in soup.find_all("a") if item.get_text() == "股票行业成交数据"
    ][0]["href"]

    if 'http' in url :
        pass
    else:
        url = 'https://www.szse.cn'+url

    if symbol == "当月":
        r = requests.get(url)
        r.encoding = 'GBK'
        temp_df = pd.read_html(StringIO(r.text), encoding="gbk")[0]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]
    else:
        temp_df = pd.read_html(url, encoding="gbk")[1]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]

    temp_df["交易天数"] = pd.to_numeric(temp_df["交易天数"], errors="coerce")
    temp_df["成交金额-人民币元"] = pd.to_numeric(
        temp_df["成交金额-人民币元"], errors="coerce"
    )
    temp_df["成交金额-占总计"] = pd.to_numeric(
        temp_df["成交金额-占总计"], errors="coerce"
    )
    temp_df["成交股数-股数"] = pd.to_numeric(temp_df["成交股数-股数"], errors="coerce")
    temp_df["成交股数-占总计"] = pd.to_numeric(
        temp_df["成交股数-占总计"], errors="coerce"
    )
    temp_df["成交笔数-笔"] = pd.to_numeric(temp_df["成交笔数-笔"], errors="coerce")
    temp_df["成交笔数-占总计"] = pd.to_numeric(
        temp_df["成交笔数-占总计"], errors="coerce"
    )
    return temp_df

In [ ]:
stock_szse_sector_summary(symbol="当月", date="201501")

In [ ]:
gen = (f"{year}{month:02d}" for year in range(2000,2101) for month in range(1,13))

In [ ]:
# 生成2010-2015年所有月份的序列 
ylist = [f"{year}{month:02d}" for year in range(2013, 2025) for month in range(1,13)] + ['202501']

In [ ]:
ddf = []

In [ ]:
for n in ylist:
    df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
    df['日期'] = n
    ddf.append(df)

In [ ]:
dff = pd.concat(ddf)

In [ ]:
dff.set_index('日期')

In [ ]:
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/StockBas')

In [ ]:
dff.set_index('日期').to_sql('szSum', eng, if_exists="replace")

In [ ]:
ddf = pd.DataFrame(columns=[ '日期','项目名称', '交易天数', '成交金额-人民币元', '成交金额-占总计', '成交股数-股数', '成交股数-占总计',
       '成交笔数-笔', '成交笔数-占总计'],dtype='object')

In [ ]:
n = ylist[0]
df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
df['日期'] = n
# ddf.append(df)
ddf = pd.concat([ddf, df],axis=0,ignore_index=True,copy=False)

### 个股信息查询
#### 1、东财
* 目标地址: http://quote.eastmoney.com/concept/sh603777.html?from=classic
* 描述: 东方财富-个股-股票信息
* 限量: 单次返回指定 symbol 的个股信息

In [ ]:
ak.stock_individual_info_em(symbol="600996")

行情报价

In [ ]:
ak.stock_bid_ask_em(symbol="600996")

### 主营介绍
同花顺
* 目标地址: https://basic.10jqka.com.cn/new/000066/operate.html
* 限量: 单次返回所有数据

In [ ]:
ak.stock_zyjs_ths(symbol="000066")

#### 主营构成-东财
* 目标地址: https://emweb.securities.eastmoney.com/PC_HSF10/BusinessAnalysis/Index?type=web&code=SH688041#
* 描述: 东方财富网-个股-主营构成
* 限量: 单次返回所有历史数据

In [ ]:
ak.stock_zygc_em(symbol="SZ000066")

实时行情数据-东财 沪深京A stock_zh_a_spot_em()

沪A股  _sh_
        深A股 _sz_
        京A股 _bj_
        新股 _new_  
        创业板 _cy_  
        科创板 _kc_

In [ ]:
ak.stock_zh_a_spot_em()

 单次返回指定股票最近一个交易日的分时数据, 包含盘前数据

In [ ]:
ak.stock_intraday_em(symbol="000409")

In [ ]:
ak.stock_intraday_em(symbol="000409").groupby('买卖盘性质').sum()

目标地址: https://data.eastmoney.com/gsrl/gsdt.html
公司动态

In [ ]:
ak.stock_gsrl_gsdt_em(date="20250211")

沪深新股
目标地址: https://quote.eastmoney.com/center/gridlist.html#newshares

In [ ]:
ak.stock_zh_a_new_em()

机构调研http://data.eastmoney.com/jgdy/tj.html
http://data.eastmoney.com/jgdy/xx.html

单次返回所有历史数据

In [ ]:
ak.stock_jgdy_tj_em(date="20210128")

In [ ]:
ak.stock_jgdy_detail_em(date="20241211")

In [ ]:
ak.stock_zyjs_ths(symbol="600996")

In [ ]:
ak.stock_zygc_em(symbol="SH600996")

In [ ]:
ak.stock_zygc_ym(symbol="000001")

上市公司质押比例
目标地址: https://data.eastmoney.com/gpzy/pledgeRatio.aspx 查询具体交易日

重要股东股权质押明细 https://data.eastmoney.com/gpzy/pledgeDetail.aspx

In [ ]:
ak.stock_gpzy_pledge_ratio_em(date="20250207")

In [ ]:
ak.stock_gpzy_pledge_ratio_detail_em()

In [ ]:
def calculate_alert_liquidation_price(initial_price, pledge_rate, interest_rate, alert_ratio=1.6, liquidation_ratio=1.4):
    """
    initial_price: 初始股价（元）
    pledge_rate: 质押率（0-1）
    interest_rate: 融资利率（年化，0-1）
    alert_ratio: 预警线系数（默认160%）
    liquidation_ratio: 平仓线系数（默认140%）
    """
    factor = initial_price * pledge_rate * (1 + interest_rate)
    alert_price = factor * alert_ratio
    liquidation_price = factor * liquidation_ratio
    return alert_price, liquidation_price

In [ ]:
calculate_alert_liquidation_price(8.2, 0.4999, 0.06)

个股商誉明细 目标地址: https://data.eastmoney.com/sy/list.html

行业商誉 目标地址: https://data.eastmoney.com/sy/hylist.html

In [ ]:
ak.stock_sy_em(date="20221231")

In [ ]:
ak.stock_sy_hy_em(date="20231231")

分析师指数 目标地址: https://data.eastmoney.com/invest/invest/list.html
 分析师详情 https://data.eastmoney.com/invest/invest/11000257131.html

In [ ]:
ak.stock_analyst_rank_em()

In [ ]:
ak.stock_analyst_detail_em(analyst_id="11000280036", indicator="最新跟踪成分股")

千股千评 目标地址: https://data.eastmoney.com/stockcomment/

In [ ]:
ak.stock_comment_em()

In [ ]:
ak.stock_comment_detail_zlkp_jgcyd_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_zhpj_lspf_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_scrd_focus_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_scrd_desire_daily_em(symbol="600996")

停复牌信息

In [ ]:
ak.stock_tfp_em()

个股新闻 目标地址: https://so.eastmoney.com/news/s
财经内容精选 目标地址: https://cxdata.caixin.com/pc/

In [ ]:
ak.stock_news_em(symbol="600996")

In [ ]:
ak.stock_news_main_cx()

年报季报 目标地址: http://data.eastmoney.com/bbsj/202412/yjbb.html

date="20200331"; choice of {"0331一季报", "0630中报", "0930三季报", "1231年报"}; 从 20100331 开始

In [ ]:
ak.stock_yjbb_em(date="20241231")

In [ ]:
ak.stock_yjkb_em(date="20241231")

In [ ]:
ak.stock_yjyg_em(date="20241231")

预约披露时间-东方财富

In [ ]:
ak.stock_yysj_em(symbol="沪深A股", date="20241231")

预约披露时间-巨潮资讯 目标地址: http://www.cninfo.com.cn/new/commonUrl?url=data/yypl

period="2021年报"; 近四期的财务报告; e.g., choice of {"2021一季", "2021半年报", "2021三季", "2021年报"}

In [ ]:
ak.stock_report_disclosure(market="沪深京", period="2024年报")

上市公司行业归属的变动情况-巨潮资讯

In [ ]:
ak.stock_industry_change_cninfo(symbol="002594", start_date="20050101", end_date="20250212")

公司股本变动-巨潮资讯

In [ ]:
fd = ak.stock_share_change_cninfo(symbol="600996", start_date="20050101", end_date="20250212")

In [ ]:
df = ak.stock_profile_cninfo(symbol="600996")

高管持股

In [ ]:
ak.stock_ggcg_em(symbol="全部")

分红配送

In [ ]:
ak.stock_fhps_em(date="20241231")

In [ ]:
ak.stock_fhps_detail_em(symbol="600409")

In [ ]:
ak.stock_fhps_detail_ths(symbol="600409")

资金流向 

symbol="即时"; choice of {“即时”, "3日排行", "5日排行", "10日排行", "20日排行"}

个股资金流：individual  概念资金流：concept 行业资金流：industry

In [ ]:
ak.stock_fund_flow_individual(symbol="即时")

筹码分布 adjust=""; choice of {"qfq": "前复权", "hfq": "后复权", "": "不复权"}

In [ ]:
ak.stock_cyq_em(symbol="600996", adjust="")

个股研报

In [ ]:
ak.stock_research_report_em(symbol="600409")

股东户数

In [ ]:
ak.stock_zh_a_gdhs(symbol="20241231")

In [ ]:
ak.stock_zh_a_gdhs_detail_em(symbol="600996")

限售股解禁详情

In [ ]:
ak.stock_restricted_release_detail_em(start_date="20240326", end_date="20250212")

股票列表-A股 目标地址: 沪深京三个交易所

In [ ]:
ak.stock_info_a_code_name()

symbol="主板A股"; choice of {"主板A股", "主板B股", "科创板"}

In [ ]:
ak.stock_info_sh_name_code(symbol="主板A股")

symbol="A股列表"; choice of {"A股列表", "B股列表", "CDR列表", "AB股列表"}

In [ ]:
ak.stock_info_sz_name_code(symbol="A股列表")

In [ ]:
ak.stock_info_bj_name_code()

### 暂停/终止上市
* 上证
* symbol="全部"; choice of {"全部", "沪市", "科创板"}

In [ ]:
ak.stock_info_sh_delist(symbol="全部")

#### 终止/暂停上市
* 深证
* symbol="终止上市公司"; choice of {"暂停上市公司", "终止上市公司"}

In [ ]:
ak.stock_info_sz_delist(symbol="终止上市公司")

两网及退市

In [ ]:
ak.stock_staq_net_stop()

### 股票更名

In [ ]:
ak.stock_info_change_name(symbol="600008")

* 深证
* symbol="全称变更"; choice of {"全称变更", "简称变更"}

In [ ]:
ak.stock_info_sz_change_name(symbol="全称变更")

symbol="证监会行业分类"; choice of {"证监会行业分类", "国证行业分类"}

In [ ]:
ak.stock_industry_pe_ratio_cninfo(symbol="证监会行业分类", date="20250212")

In [ ]:
ak.stock_hold_num_cninfo(date="20240930")

实际控制人持股变动

symbol="全部"; choice of {"单独控制", "实际控制人", "一致行动人", "家族控制", "全部"}; 从 2010 开始

In [ ]:
ak.stock_hold_control_cninfo(symbol="全部")

对外担保 symbol="全部"; choice of {"全部", "深市主板", "沪市", "创业板", "科创板"}

In [ ]:
ak.stock_cg_guarantee_cninfo(symbol="全部", start_date="20240601", end_date="20250212")

股权质押

In [ ]:
ak.stock_cg_equity_mortgage_cninfo(date="20250212")

A 股个股指标
symbol="000001"; 参见 ak.stock_a_indicator_lg(symbol="all") 获取股票代码

pe	市盈率
pe_ttm	市盈率TTM
pb		市净率
ps	市销率
ps_ttm	市销率TTM
dv_ratio		股息率
dv_ttm		股息率TTM
total_mv		总市值

In [ ]:
ak.stock_a_indicator_lg(symbol="600409")

A 股股息率 symbol="上证A股"; choice of {"上证A股", "深证A股", "创业板", "科创板"}

In [ ]:
ak.stock_a_gxl_lg(symbol="深证A股")

大盘拥挤度

In [ ]:
ak.stock_a_congestion_lg()

股债利差

In [ ]:
ak.stock_ebs_lg()

A 股等权重与中位数市盈率

In [ ]:
ak.stock_a_ttm_lyr()

A 股等权重与中位数市净率

In [ ]:
ak.stock_a_all_pb()

主板市盈率 symbol="上证"; choice of {"上证", "深证", "创业板", "科创版"}

In [ ]:
ak.stock_market_pe_lg(symbol="上证")

指数市盈率symbol="上证50"; choice of {"上证50", "沪深300", "上证380", "创业板50", "中证500", "上证180", "深证红利", "深证100", "中证1000", "上证红利", "中证100", "中证800"}

In [ ]:
ak.stock_index_pe_lg(symbol="上证50")

主板市净率 symbol="上证"; choice of {"上证", "深证", "创业板", "科创版"}

In [ ]:
ak.stock_market_pb_lg(symbol="上证")

In [ ]:
ak.stock_index_pb_lg(symbol="上证50")

个股估值

In [ ]:
ak.stock_value_em(symbol="300766")

创新高和新低的股票数量 symbol="all"; {"all": "全部A股", "sz50": "上证50", "hs300": "沪深300", "zz500": "中证500"}

In [ ]:
ak.stock_a_high_low_statistics(symbol="zz500")

破净股统计 symbol="全部A股"; choice of {"全部A股", "沪深300", "上证50", "中证500"}

In [ ]:
ak.stock_a_below_net_asset_statistics(symbol="全部A股")

In [ ]:
ak.stock_report_fund_hold(symbol="基金持仓", date="20241231")

机构买卖每日统计 
机构席位追踪 symbol="近一月"; choice of {"近一月", "近三月", "近六月", "近一年"}

In [ ]:
ak.stock_lhb_jgmmtj_em(start_date="20250101", end_date="20250212")

In [ ]:
ak.stock_lhb_jgstatistic_em(symbol="近一月")

活跃 A 股统计 symbol='近三月'; choice of {'近一月', '近三月', '近六月', '近一年'}

In [ ]:
ak.stock_dzjy_hygtj(symbol='近三月')

融资融券汇总

标的证券名单及保证金比例查询

In [ ]:
ak.stock_margin_ratio_pa(date="20250213")

In [ ]:
ak.stock_margin_account_info()

In [ ]:
ak.stock_margin_sse(start_date="20250212", end_date="20250212")

In [ ]:
ak.stock_margin_szse(date="20250212")

In [ ]:
ak.stock_margin_detail_sse(date="20250212")

In [ ]:
ak.stock_margin_detail_szse(date="20250212")

In [ ]:
ak.stock_margin_underlying_info_szse(date="20250212")

盈利预测-东方财富  symbol="", 默认为获取全部数据; symbol="船舶制造", 则获取具体行业板块的数据; 行业板块可以通过 ak.stock_board_industry_name_em() 接口获取

In [ ]:
ak.stock_profit_forecast_em()

indicator="预测年报每股收益"; choice of {"预测年报每股收益", "预测年报净利润", "业绩预测详表-机构", "业绩预测详表-详细指标预测"}

In [ ]:
ak.stock_profit_forecast_ths(symbol="600519", indicator="预测年报每股收益")

### 概念板块
* 同花顺

In [ ]:
ak.stock_board_concept_name_ths()

* 东方财富

In [ ]:
ak.stock_board_concept_name_em()

东方财富-成份股 symbol="车联网"; 可以通过调用 ak.stock_board_concept_name_em() 查看东方财富-概念板块的所有行业名称

In [ ]:
ak.stock_board_concept_cons_em(symbol="高带宽内存")

东方财富-指数 symbol="长寿药"; 可以通过调用 ak.stock_board_concept_name_em() 查看东方财富-概念板块的所有概念代码
 
 period="5"; choice of {"1", "5", "15", "30", "60"}

In [ ]:
ak.stock_board_concept_hist_em(symbol="高带宽内存", period="daily", start_date="20220101", end_date="20250212", adjust="")

### 行业板块
* 同花顺

In [ ]:
ak.stock_board_industry_summary_ths()

* 东方财富

In [ ]:
ak.stock_board_industry_name_em()

东方财富-成份股

In [ ]:
ak.stock_board_industry_cons_em(symbol="电机")

In [ ]:
ak.stock_board_industry_hist_em(symbol="小金属", start_date="20211201", end_date="20250212", period="日k", adjust="")

同花顺  行业板块

In [ ]:
ak.stock_board_industry_summary_ths()

In [ ]:
ak.stock_board_industry_index_ths(symbol="元件", start_date="20240101", end_date="20250212")

股票热度 关注 讨论 交易

关注排行榜 symbol="最热门"; choice of {"本周新增", "最热门"}

In [ ]:
ak.stock_hot_follow_xq(symbol="最热门")

In [ ]:
ak.stock_hot_tweet_xq(symbol="最热门")

In [ ]:
ak.stock_hot_deal_xq(symbol="最热门")

问财

In [ ]:
ak.stock_hot_rank_wc(date="20250212")

东财 单次返回当前交易日前 100 个股票的人气排名数据

In [ ]:
ak.stock_hot_rank_em()

飙升榜-A股

In [ ]:
ak.stock_hot_up_em()

历史趋势及粉丝特征

In [ ]:
ak.stock_hot_rank_detail_em(symbol="SH600996")

热门关键词

In [ ]:
ak.stock_hot_keyword_em(symbol="SH600996")

内部交易

In [ ]:
ak.stock_inner_trade_xq()

热搜股票 time="今日"; choice of {"今日", "1小时"}

In [ ]:
ak.stock_hot_search_baidu(symbol="A股", date="20240213", time="今日")

强势股池

In [ ]:
ak.stock_zt_pool_strong_em(date='20250206')

In [ ]:
ak.stock_zt_pool_sub_new_em(date='20250123')

In [ ]:
ak.stock_info_cjzc_em()

In [ ]:
ak.stock_info_global_em()

In [ ]:
ak.stock_info_global_sina()

In [ ]:
ak.stock_info_global_futu()

In [ ]:
ak.stock_info_global_ths()

In [ ]:
ak.stock_info_global_cls(symbol="全部")

技术指标 symbol="创月新高"; choice of {"创月新高", "半年新高", "一年新高", "历史新高"}

创新高cxg 创新低cxd 

连续上涨lxsz 连续下跌lxxd 持续放量cxfl 持续缩量cxsl 向上突破xstp 向下突破xxtp 量价齐升ljqs 量价齐跌ljqd 险资举牌xzjp

In [ ]:
ak.stock_rank_cxg_ths(symbol="创月新高")

In [ ]:
ak.stock_rank_cxd_ths(symbol="创月新低")

In [ ]:
ak.stock_rank_lxsz_ths()

In [ ]:
ak.stock_rank_cxfl_ths()

In [ ]:
ak.stock_rank_cxsl_ths()

In [ ]:
ak.stock_rank_xzjp_ths()

ESG评级

In [ ]:
ak.stock_esg_rate_sina()

In [ ]:
ak.stock_esg_msci_sina()

In [ ]:
ak.stock_esg_rft_sina()

In [ ]:
ak.stock_esg_zd_sina()

In [ ]:
ak.stock_esg_hz_sina()

A股股票指数数据 symbol="上证系列指数"；choice of {"沪深重要指数", "上证系列指数", "深证系列指数", "指数成份", "中证系列指数"}

In [ ]:
ak.stock_zh_index_spot_em(symbol="中证系列指数")

历史行情数据-东方财富 period="daily"; choice of {'daily', 'weekly', 'monthly'}

In [ ]:
ak.index_zh_a_hist(symbol="931144", period="daily", start_date="20250212", end_date="20250212")

中国股票指数成份

In [ ]:
ak.index_stock_info()

In [ ]:
ak.index_stock_cons(symbol="000300")

In [ ]:
ak.index_stock_cons_csindex(symbol="000300")

In [ ]:
ak.sw_index_first_info()

In [ ]:
ak.sw_index_second_info()

In [ ]:
ak.sw_index_third_info()

申万三级行业成份 symbol="850111.SI"; 行业代码; 可以通过 ak.sw_index_third_info() 获取所有行业代码

In [ ]:
ak.sw_index_third_cons(symbol="859822.SI")

In [ ]:
ak.drewry_wci_index(symbol="composite")

In [ ]:
ak.index_neaw_cx()

汽车销量排行

In [ ]:
ak.car_market_cate_cpca(symbol="占比", indicator="零售")

In [ ]:
ak.car_market_cate_cpca(symbol="轿车", indicator="零售")

盖世研究院 symbol="车型榜"; choice of {"车企榜", "品牌榜", "车型榜"}

In [ ]:
ak.car_sale_rank_gasgoo(symbol="车企榜", date="202412")

In [ ]:
ak.car_sale_rank_gasgoo(symbol="品牌榜", date="202412")

In [ ]:
ak.car_sale_rank_gasgoo(symbol="车型榜", date="202412")

电影票房

In [ ]:
ak.movie_boxoffice_realtime()

In [ ]:
ak.movie_boxoffice_daily(date="20250201")

In [ ]:
ak.movie_boxoffice_yearly(date="2025")

In [ ]:
ak.video_tv()

In [ ]:
ak.video_variety_show()

In [ ]:
ak.business_value_artist()

In [ ]:
ak.online_value_artist()

微博舆情报告 time_period="CNHOUR12"

CNHOUR2	2小时
CNHOUR6	6小时
CNHOUR12	12小时
CNHOUR24	1天
CNDAY7	1周
CNDAY30	1月

In [ ]:
ak.stock_js_weibo_report(time_period="CNHOUR24")

In [ ]:
df = ak.index_news_sentiment_scope()

In [ ]:
df

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(df.tail(100), x='日期', y='市场情绪指数',)
fig.show()

In [ ]:
fig = px.line(df.tail(100), x='日期', y='沪深300指数',)
fig.show()

In [ ]:
ak.index_analysis_weekly_sw(symbol="市场表征", date="20250228")

In [ ]:
dfg = ak.macro_cons_gold()

In [ ]:
from datetime import datetime, date

dfgg = dfg[dfg['日期'] >= datetime.strptime('2016-12-19',  "%Y-%m-%d").date()]

In [ ]:
fig = px.line(dfgg, x='日期', y='总库存',)
fig.show()

In [ ]:
dfd = ak.spot_hist_sge(symbol='Au99.99')

In [ ]:
fig = px.line(dfd, x='date', y='close',)
fig.show()