201303开始 www.szse.cn
201804开始 docs.static.szse.cn

In [ ]:
import akshare as ak

In [ ]:
ak.stock_sse_summary()

In [ ]:
df1 = ak.stock_szse_sector_summary(symbol="当年", date="202501").drop('项目名称-英文',axis=1)
df2 = ak.stock_szse_sector_summary(symbol="当年", date="202401").drop('项目名称-英文',axis=1)

In [ ]:
((((df1['成交金额-人民币元']/df1['交易天数']))/100000000)-(((df2['成交金额-人民币元']/df2['交易天数']))/100000000)).round(2)

In [ ]:
df1

In [ ]:
(((df1['成交金额-人民币元']/df1['交易天数']))/100000000).round(2)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201301").drop('项目名称-英文',axis=1)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201701").drop('项目名称-英文',axis=1)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import BytesIO, StringIO

In [ ]:
def stock_szse_sector_summary(
    symbol: str = "当月", date: str = "202501"
) -> pd.DataFrame:
    """
    深圳证券交易所-统计资料-股票行业成交数据
    https://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
    :param symbol: choice of {"当月", "当年"}
    :type symbol: str
    :param date: 交易年月
    :type date: str
    :return: 股票行业成交数据
    :rtype: pandas.DataFrame
    """
    url = "https://www.szse.cn/market/periodical/month/index.html"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    tags_list = soup.find_all(name="div", attrs={"class": "g-container"})[1].find_all(
        "script"
    )
    tags_dict = [
        eval(
            item.string[item.string.find("{") : item.string.find("}") + 1]
            .replace("\n", "")
            .replace(" ", "")
            .replace("value", "'value'")
            .replace("text", "'text'")
        )
        for item in tags_list
    ]
    date_url_dict = dict(
        zip(
            [item["text"] for item in tags_dict],
            [item["value"][2:] for item in tags_dict],
        )
    )
    date_format = "-".join([date[:4], date[4:]])
    url = f"https://www.szse.cn/market/periodical/month/{date_url_dict[date_format]}"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    url = [
        item for item in soup.find_all("a") if item.get_text() == "股票行业成交数据"
    ][0]["href"]

    if 'http' in url :
        pass
    else:
        url = 'https://www.szse.cn'+url

    if symbol == "当月":
        r = requests.get(url)
        r.encoding = 'GBK'
        temp_df = pd.read_html(StringIO(r.text), encoding="gbk")[0]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]
    else:
        temp_df = pd.read_html(url, encoding="gbk")[1]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]

    temp_df["交易天数"] = pd.to_numeric(temp_df["交易天数"], errors="coerce")
    temp_df["成交金额-人民币元"] = pd.to_numeric(
        temp_df["成交金额-人民币元"], errors="coerce"
    )
    temp_df["成交金额-占总计"] = pd.to_numeric(
        temp_df["成交金额-占总计"], errors="coerce"
    )
    temp_df["成交股数-股数"] = pd.to_numeric(temp_df["成交股数-股数"], errors="coerce")
    temp_df["成交股数-占总计"] = pd.to_numeric(
        temp_df["成交股数-占总计"], errors="coerce"
    )
    temp_df["成交笔数-笔"] = pd.to_numeric(temp_df["成交笔数-笔"], errors="coerce")
    temp_df["成交笔数-占总计"] = pd.to_numeric(
        temp_df["成交笔数-占总计"], errors="coerce"
    )
    return temp_df

In [ ]:
stock_szse_sector_summary(symbol="当月", date="201501")

In [ ]:
gen = (f"{year}{month:02d}" for year in range(2000,2101) for month in range(1,13))

In [ ]:
# 生成2010-2015年所有月份的序列 
ylist = [f"{year}{month:02d}" for year in range(2013, 2025) for month in range(1,13)] + ['202501']

In [96]:
ddf = []

In [105]:
for n in ylist:
    df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
    df['日期'] = n
    ddf.append(df)

In [107]:
dff = pd.concat(ddf)

In [109]:
dff.set_index('日期')

,项目名称,交易天数,成交金额-人民币元,成交金额-占总计,成交股数-股数,成交股数-占总计,成交笔数-笔,成交笔数-占总计
日期,,,,,,,,
201301,合计,20,2054160688434,100.00,197195635654,100.00,115351682,100.00
201301,农林牧渔,20,54183340895,2.64,5024299710,2.55,3374326,2.93
201301,采掘业,20,65349366373,3.18,4453033741,2.26,3444772,2.99
201301,制造业,20,1255719941277,61.13,120556785708,61.14,72696561,63.02
201301,食品饮料,20,128754478326,6.27,6590206552,3.34,5808212,5.04
...,...,...,...,...,...,...,...,...
202501,居民服务,18,1380962740,0.01,148411858,0.01,217920,0.02
202501,教育,18,32550128302,0.25,7073096176,0.64,3040949,0.28
202501,卫生,18,42095615991,0.33,5628801958,0.51,4706600,0.44
202501,文化传播,18,107581655354,0.84,14651178792,1.33,10017645,0.93
202501,综合,18,17007503667,0.13,1587321004,0.14,1653162,0.15

In [111]:
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/StockBas')

In [112]:
dff.set_index('日期').to_sql('szSum', eng, if_exists="replace")

-1

In [93]:
ddf = pd.DataFrame(columns=[ '日期','项目名称', '交易天数', '成交金额-人民币元', '成交金额-占总计', '成交股数-股数', '成交股数-占总计',
       '成交笔数-笔', '成交笔数-占总计'],dtype='object')

In [85]:
n = ylist[0]
df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
df['日期'] = n
# ddf.append(df)
ddf = pd.concat([ddf, df],axis=0,ignore_index=True,copy=False)

/tmp/ipykernel_541144/803631906.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ddf = pd.concat([ddf, df],axis=0,ignore_index=True,copy=False)

In [52]:
import pandas as pd
df = pd.DataFrame()

In [117]:
dff[dff.日期=='202412']

,项目名称,交易天数,成交金额-人民币元,成交金额-占总计,成交股数-股数,成交股数-占总计,成交笔数-笔,成交笔数-占总计,日期
0,合计,22,21093681186493,100.00,1862477781843,100.00,1581329725,100.00,202412
1,农林牧渔,22,160726665758,0.76,21241892181,1.14,14280510,0.90,202412
2,采矿业,22,130838497470,0.62,14660600695,0.79,13189246,0.83,202412
3,制造业,22,13078946170932,62.00,1055937271104,56.70,995135256,62.93,202412
4,水电煤气,22,204350402127,0.97,32782606928,1.76,22156403,1.40,202412
5,建筑业,22,200734155181,0.95,35830720114,1.92,20460439,1.29,202412
6,批发零售,22,744169094819,3.53,89531505352,4.81,61236594,3.87,202412
7,运输仓储,22,150245733492,0.71,14972748442,0.80,16007758,1.01,202412
8,住宿餐饮,22,37769593070,0.18,4426863731,0.24,3849052,0.24,202412
9,信息技术,22,3473063064751,16.46,242965861754,13.05,225696836,14.27,202412
10,金融业,22,955962888941,4.53,66362052441,3.56,47085862,2.98,202412
11,房地产,22,240054049267,1.14,55276390615,2.97,22776626,1.44,202412
12,商务服务,22,794953450154,3.77,110866726049,5.95,60113860,3.80,202412
13,科研服务,22,221822619192,1.05,12926285058,0.69,18736620,1.18,202412
14,公共环保,22,195953054772,0.93,36163448063,1.94,20227863,1.28,202412
15,居民服务,22,4364225980,0.02,359477135,0.02,466295,0.03,202412
16,教育,22,101944632327,0.48,20271272076,1.09,8033400,0.51,202412
17,卫生,22,93833854684,0.44,12182138091,0.65,8438480,0.53,202412
18,文化传播,22,269105484894,1.28,33253017038,1.79,20664603,1.31,202412
19,综合,22,34843548682,0.17,2466904976,0.13,2774022,0.18,202412