201303开始 www.szse.cn
201804开始 docs.static.szse.cn
https://akshare.akfamily.xyz/data/stock/stock.html#id9

In [ ]:
import akshare as ak

In [ ]:
ak.stock_sse_summary()

In [ ]:
df1 = ak.stock_szse_sector_summary(symbol="当年", date="202501").drop('项目名称-英文',axis=1)
df2 = ak.stock_szse_sector_summary(symbol="当年", date="202401").drop('项目名称-英文',axis=1)

In [ ]:
((((df1['成交金额-人民币元']/df1['交易天数']))/100000000)-(((df2['成交金额-人民币元']/df2['交易天数']))/100000000)).round(2)

In [ ]:
df1

In [ ]:
(((df1['成交金额-人民币元']/df1['交易天数']))/100000000).round(2)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201301").drop('项目名称-英文',axis=1)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201701").drop('项目名称-英文',axis=1)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import BytesIO, StringIO

初始化需要修改代码，2018年4月后数据不用修改

In [ ]:
def stock_szse_sector_summary(
    symbol: str = "当月", date: str = "202501"
) -> pd.DataFrame:
    """
    深圳证券交易所-统计资料-股票行业成交数据
    https://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
    :param symbol: choice of {"当月", "当年"}
    :type symbol: str
    :param date: 交易年月
    :type date: str
    :return: 股票行业成交数据
    :rtype: pandas.DataFrame
    """
    url = "https://www.szse.cn/market/periodical/month/index.html"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    tags_list = soup.find_all(name="div", attrs={"class": "g-container"})[1].find_all(
        "script"
    )
    tags_dict = [
        eval(
            item.string[item.string.find("{") : item.string.find("}") + 1]
            .replace("\n", "")
            .replace(" ", "")
            .replace("value", "'value'")
            .replace("text", "'text'")
        )
        for item in tags_list
    ]
    date_url_dict = dict(
        zip(
            [item["text"] for item in tags_dict],
            [item["value"][2:] for item in tags_dict],
        )
    )
    date_format = "-".join([date[:4], date[4:]])
    url = f"https://www.szse.cn/market/periodical/month/{date_url_dict[date_format]}"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    url = [
        item for item in soup.find_all("a") if item.get_text() == "股票行业成交数据"
    ][0]["href"]

    if 'http' in url :
        pass
    else:
        url = 'https://www.szse.cn'+url

    if symbol == "当月":
        r = requests.get(url)
        r.encoding = 'GBK'
        temp_df = pd.read_html(StringIO(r.text), encoding="gbk")[0]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]
    else:
        temp_df = pd.read_html(url, encoding="gbk")[1]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]

    temp_df["交易天数"] = pd.to_numeric(temp_df["交易天数"], errors="coerce")
    temp_df["成交金额-人民币元"] = pd.to_numeric(
        temp_df["成交金额-人民币元"], errors="coerce"
    )
    temp_df["成交金额-占总计"] = pd.to_numeric(
        temp_df["成交金额-占总计"], errors="coerce"
    )
    temp_df["成交股数-股数"] = pd.to_numeric(temp_df["成交股数-股数"], errors="coerce")
    temp_df["成交股数-占总计"] = pd.to_numeric(
        temp_df["成交股数-占总计"], errors="coerce"
    )
    temp_df["成交笔数-笔"] = pd.to_numeric(temp_df["成交笔数-笔"], errors="coerce")
    temp_df["成交笔数-占总计"] = pd.to_numeric(
        temp_df["成交笔数-占总计"], errors="coerce"
    )
    return temp_df

In [ ]:
stock_szse_sector_summary(symbol="当月", date="201501")

In [ ]:
gen = (f"{year}{month:02d}" for year in range(2000,2101) for month in range(1,13))

In [ ]:
# 生成2010-2015年所有月份的序列 
ylist = [f"{year}{month:02d}" for year in range(2013, 2025) for month in range(1,13)] + ['202501']

In [ ]:
ddf = []

In [ ]:
for n in ylist:
    df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
    df['日期'] = n
    ddf.append(df)

In [ ]:
dff = pd.concat(ddf)

In [ ]:
dff.set_index('日期')

In [ ]:
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/StockBas')

In [ ]:
dff.set_index('日期').to_sql('szSum', eng, if_exists="replace")

In [ ]:
ddf = pd.DataFrame(columns=[ '日期','项目名称', '交易天数', '成交金额-人民币元', '成交金额-占总计', '成交股数-股数', '成交股数-占总计',
       '成交笔数-笔', '成交笔数-占总计'],dtype='object')

In [ ]:
n = ylist[0]
df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
df['日期'] = n
# ddf.append(df)
ddf = pd.concat([ddf, df],axis=0,ignore_index=True,copy=False)

In [ ]:
import pandas as pd
df = pd.DataFrame()

个股信息查询

In [ ]:
ak.stock_individual_info_em(symbol="600996")

行情报价

In [ ]:
ak.stock_bid_ask_em(symbol="600996")

实时行情数据-东财 沪深京A stock_zh_a_spot_em()

沪A股  _sh_
        深A股 _sz_
        京A股 _bj_
        新股 _new_  
        创业板 _cy_  
        科创板 _kc_

In [ ]:
ak.stock_zh_a_spot_em()

 单次返回指定股票最近一个交易日的分时数据, 包含盘前数据

In [ ]:
ak.stock_intraday_em(symbol="000409")

In [ ]:
ak.stock_intraday_em(symbol="000409").groupby('买卖盘性质').sum()

目标地址: https://data.eastmoney.com/gsrl/gsdt.html
公司动态

In [ ]:
ak.stock_gsrl_gsdt_em(date="20250211")

沪深新股
目标地址: https://quote.eastmoney.com/center/gridlist.html#newshares

In [ ]:
ak.stock_zh_a_new_em()

机构调研http://data.eastmoney.com/jgdy/tj.html
http://data.eastmoney.com/jgdy/xx.html

单次返回所有历史数据

In [ ]:
ak.stock_jgdy_tj_em(date="20210128")

In [ ]:
ak.stock_jgdy_detail_em(date="20241211")

In [ ]:
ak.stock_zyjs_ths(symbol="600996")

In [ ]:
ak.stock_zygc_em(symbol="SH600996")

In [ ]:
ak.stock_zygc_ym(symbol="000001")

上市公司质押比例
目标地址: https://data.eastmoney.com/gpzy/pledgeRatio.aspx 查询具体交易日

重要股东股权质押明细 https://data.eastmoney.com/gpzy/pledgeDetail.aspx

In [ ]:
ak.stock_gpzy_pledge_ratio_em(date="20250207")

In [ ]:
ak.stock_gpzy_pledge_ratio_detail_em()

In [13]:
def calculate_alert_liquidation_price(initial_price, pledge_rate, interest_rate, alert_ratio=1.6, liquidation_ratio=1.4):
    """
    initial_price: 初始股价（元）
    pledge_rate: 质押率（0-1）
    interest_rate: 融资利率（年化，0-1）
    alert_ratio: 预警线系数（默认160%）
    liquidation_ratio: 平仓线系数（默认140%）
    """
    factor = initial_price * pledge_rate * (1 + interest_rate)
    alert_price = factor * alert_ratio
    liquidation_price = factor * liquidation_ratio
    return alert_price, liquidation_price

In [16]:
calculate_alert_liquidation_price(8.2, 0.4999, 0.06)

(6.95220928, 6.083183119999999)

个股商誉明细 目标地址: https://data.eastmoney.com/sy/list.html

行业商誉 目标地址: https://data.eastmoney.com/sy/hylist.html

In [19]:
ak.stock_sy_em(date="20221231")

  0%|          | 0/5 [00:00<?, ?it/s]

,序号,股票代码,股票简称,商誉,商誉占净资产比例,净利润,净利润同比,上年商誉,公告日期,交易市场
0,1,600530,交大昂立,5.486739e+07,0.147861,-4.986218e+08,-54.903798,1.688461e+08,2023-08-31,沪市主板
1,2,002564,*ST天沃,2.429851e+07,-0.010913,-2.580749e+09,-0.910830,2.429851e+07,2023-06-29,深市主板
2,3,002721,ST金一,6.894604e+07,-0.020076,-3.659533e+09,-1.780492,1.926003e+08,2023-04-30,深市主板
3,4,688799,华纳药厂,3.238198e+07,0.019523,1.828048e+08,0.137123,NaN,2023-04-29,科创板
4,5,688788,科思科技,2.515280e+07,0.009359,-1.966061e+08,-2.101968,5.512249e+04,2023-04-29,科创板
...,...,...,...,...,...,...,...,...,...,...
2494,2495,836422,润普食品,5.391823e+06,0.018622,7.357377e+07,0.703225,5.391823e+06,2023-02-06,NaN
2495,2496,430017,星昊医药,0.000000e+00,0.000000,8.150963e+07,0.173327,NaN,2023-02-03,NaN
2496,2497,603053,成都燃气,6.660304e+07,0.015079,4.915500e+08,0.005682,6.660304e+07,2023-01-18,沪市主板
2497,2498,601098,中南传媒,6.238508e+07,0.004039,1.399232e+09,-0.076656,6.238508e+07,2023-01-18,沪市主板
2498,2499,601018,宁波港,3.219650e+08,0.004200,4.226620e+09,-0.025752,3.219650e+08,2023-01-18,沪市主板

In [21]:
ak.stock_sy_hy_em(date="20231231")

  0%|          | 0/1 [00:00<?, ?it/s]

     行业名称  公司家数          商誉规模           净资产  商誉规模占净资产规模比例         净利润规模
0      游戏    23  2.972601e+10  1.185570e+11      0.250732  7.022739e+09
1      教育    11  3.179869e+09  1.354283e+10      0.234801 -5.270962e+08
2   房地产服务    11  8.569860e+09  4.512111e+10      0.189930 -1.315902e+09
3    航空机场     3  1.397192e+10  7.818833e+10      0.178696 -8.903528e+09
4    医药商业    25  4.122066e+10  2.653666e+11      0.155335  1.772126e+10
..    ...   ...           ...           ...           ...           ...
81   工程建设    44  1.661460e+10  3.122459e+12      0.005321  1.910344e+11
82   钢铁行业    19  1.921853e+09  5.112758e+11      0.003759  3.363866e+10
83   煤炭行业    12  1.659432e+09  5.200968e+11      0.003191  6.363816e+10
84   化纤行业    10  3.643058e+08  1.434480e+11      0.002540  1.120562e+10
85     银行    12  3.264649e+10  1.361581e+13      0.002398  1.295915e+12

[86 rows x 6 columns]

分析师指数 目标地址: https://data.eastmoney.com/invest/invest/list.html
 分析师详情 https://data.eastmoney.com/invest/invest/11000257131.html

In [22]:
ak.stock_analyst_rank_em()

  0%|          | 0/2 [00:00<?, ?it/s]

,序号,分析师名称,分析师单位,年度指数,2024年收益率,3个月收益率,6个月收益率,12个月收益率,成分股个数,2024最新个股评级-股票名称,2024最新个股评级-股票代码,分析师ID,行业代码,行业,更新日期,年度
0,1,任志强,华福证券,6424.01,135.17,57.00,129.50,135.17,0,寒武纪,688256,11000213851,270000,电子,2024-12-31,2024
1,2,洪烨,中国银河,2185.79,118.58,31.05,118.58,118.58,5,吉冈精密,836720,11000341237,280000,汽车,2024-12-31,2024
2,3,张宁,国联民生,2136.08,113.61,27.64,41.63,113.61,19,广和通,300638,11000455635,730000,通信,2024-12-31,2024
3,4,范想想,中国银河,2398.42,110.82,52.93,113.77,110.82,27,恒拓开源,834415,11000280036,None,None,2024-12-31,2024
4,5,徐巡,华福证券,2051.02,105.10,56.23,85.29,105.10,0,兆易创新,603986,11000409032,270000,电子,2024-12-31,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,田源,华源证券,1528.51,33.17,-1.55,8.88,33.17,15,长华集团,605018,11000206526,240000,有色金属,2024-12-31,2024
96,97,尹欣驰,中信证券,1512.41,33.09,5.87,22.72,33.09,14,潍柴动力,000338,11000295837,280000,汽车,2024-12-31,2024
97,98,马天诣,民生证券,1897.77,33.00,22.41,38.11,33.00,56,科创新源,300731,11000283632,730000,通信,2024-12-31,2024
98,99,许旖珊,方正证券,1028.00,32.91,3.99,39.18,32.91,25,新华保险,601336,11000275531,490000,非银金融,2024-12-31,2024
99,100,李国盛,申万宏源,1551.97,32.87,20.75,30.82,32.87,8,中兴通讯,000063,11000332332,730000,通信,2024-12-31,2024

In [28]:
ak.stock_analyst_detail_em(analyst_id="11000280036", indicator="最新跟踪成分股")

    序号    股票代码  股票名称        调入日期      最新评级日期 当前评级名称  成交价格(前复权)   最新价格   阶段涨跌幅
0    1  836957  汉维科技  2024-08-22  2024-08-22     买入   6.300000  12.22   93.97
1    2  873703  广厦环能  2024-08-16  2025-01-16     买入  15.550000  23.88   53.57
2    3  837821  则成电子  2024-08-16  2024-10-25     买入  28.180000  38.39   36.23
3    4  831726   朱老六  2024-08-16  2024-08-16     买入   7.500620  21.42  185.60
4    5  835579  机科股份  2024-08-13  2024-08-13     买入  11.660000  21.50   84.39
5    6  833580  科创新材  2024-08-13  2024-08-13     增持   5.780000  12.14  110.03
6    7  430510  丰光精密  2024-08-01  2024-09-02     买入  11.980000  20.80   73.62
7    8  830879  基康仪器  2024-07-29  2024-10-28     买入   7.988699  13.09   63.83
8    9  833509  同惠电子  2024-07-25  2024-08-20     买入   8.020000  16.79  109.35
9   10  833171  国航远洋  2024-07-24  2025-01-20     买入   3.770000   6.43   70.56
10  11  834415  恒拓开源  2024-07-23  2024-11-12     买入   5.670000  19.85  250.09
11  12  833429   康比特  2024-07-17  2024-10-28     买入  11.140000  16.11   44.61
12  13  833394   民士达  2024-07-17  2024-10-16     买入  13.880000  24.74   78.24
13  14  838971  天马新材  2024-06-24  2024-10-11     买入   9.430000  32.21  241.57

千股千评 目标地址: https://data.eastmoney.com/stockcomment/

In [29]:
ak.stock_comment_em()

  0%|          | 0/11 [00:00<?, ?it/s]

,序号,代码,名称,最新价,涨跌幅,换手率,市盈率,主力成本,机构参与度,综合得分,上升,目前排名,关注指数,交易日
0,1,000001,平安银行,11.42,0.00,0.51,4.18,11.380622,0.541804,64.396310,202,2179,83.2,2025-02-12
1,2,000002,万 科Ａ,7.96,9.94,3.91,-3.97,7.539059,0.550982,69.922956,-2413,875,85.2,2025-02-12
2,3,000004,国华网安,14.00,2.19,14.55,-38.80,13.938765,0.213077,58.466346,-451,3809,82.8,2025-02-12
3,4,000006,深振业Ａ,7.20,2.27,2.54,-13.92,7.082710,0.327324,58.223056,-967,3866,73.6,2025-02-12
4,5,000007,全新好,6.72,-0.15,1.65,549.76,6.676980,0.185104,57.998573,-10,3915,63.6,2025-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5103,5104,688799,华纳药厂,40.63,-0.34,1.58,18.04,40.486471,0.329885,62.657392,309,2652,62.4,2025-02-12
5104,5105,688800,瑞可达,69.70,-0.99,4.96,78.15,69.318720,0.448869,74.839927,-370,247,69.2,2025-02-12
5105,5106,688819,天能股份,26.70,0.68,0.25,13.30,26.494071,0.229188,69.026574,1,1060,67.6,2025-02-12
5106,5107,688981,中芯国际,104.32,3.43,4.91,225.02,102.065502,0.626726,75.063606,-982,228,91.6,2025-02-12
5107,5108,689009,九号公司-WD,51.36,2.19,1.61,28.49,50.954294,0.348417,71.154707,174,654,74.4,2025-02-12

In [31]:
ak.stock_comment_detail_zlkp_jgcyd_em(symbol="600996")

           交易日     机构参与度
0   2024-12-13  36.91340
1   2024-12-16  30.80520
2   2024-12-17  26.92608
3   2024-12-18  26.65452
4   2024-12-19  26.99040
5   2024-12-20  33.40812
6   2024-12-23  26.64996
7   2024-12-24  29.35492
8   2024-12-25  23.05644
9   2024-12-26  23.09272
10  2024-12-27  25.30916
11  2024-12-30  24.32328
12  2024-12-31  27.09092
13  2025-01-02  25.30900
14  2025-01-03  28.01332
15  2025-01-06  20.06948
16  2025-01-07  26.78832
17  2025-01-08  21.75748
18  2025-01-09  21.44772
19  2025-01-10  22.57536
20  2025-01-13  20.63868
21  2025-01-14  24.70524
22  2025-01-15  23.01748
23  2025-01-16  23.16596
24  2025-01-17  22.94548
25  2025-01-20  26.18156
26  2025-01-21  26.60108
27  2025-01-22  24.54024
28  2025-01-23  25.14752
29  2025-01-24  22.17268
30  2025-01-27  23.35612
31  2025-02-05  18.60832
32  2025-02-06  25.34544
33  2025-02-07  27.82560
34  2025-02-10  37.42116
35  2025-02-11  27.94884
36  2025-02-12  40.26636

In [32]:
ak.stock_comment_detail_zhpj_lspf_em(symbol="600996")

           交易日         评分
0   2024-12-24  47.936069
1   2024-12-25  46.976482
2   2024-12-26  52.021819
3   2024-12-27  46.448018
4   2024-12-30  52.092268
5   2024-12-31  51.899500
6   2025-01-02  46.295104
7   2025-01-03  44.399592
8   2025-01-06  45.505899
9   2025-01-07  52.587585
10  2025-01-08  45.951431
11  2025-01-09  50.145111
12  2025-01-10  49.193679
13  2025-01-13  50.601447
14  2025-01-14  54.171501
15  2025-01-15  52.066273
16  2025-01-16  49.853787
17  2025-01-17  50.700474
18  2025-01-20  49.643825
19  2025-01-21  48.107862
20  2025-01-22  47.635009
21  2025-01-23  47.269681
22  2025-01-24  46.148962
23  2025-01-27  50.228994
24  2025-02-05  47.632670
25  2025-02-06  48.277929
26  2025-02-07  48.899032
27  2025-02-10  58.495768
28  2025-02-11  50.163329
29  2025-02-12  63.532849

In [33]:
ak.stock_comment_detail_scrd_focus_em(symbol="600996")

           交易日  用户关注指数
0   2024-12-25    69.6
1   2024-12-26    70.4
2   2024-12-27    70.0
3   2024-12-30    70.8
4   2024-12-31    70.8
5   2025-01-02    72.4
6   2025-01-03    73.2
7   2025-01-06    73.6
8   2025-01-07    72.8
9   2025-01-08    74.0
10  2025-01-09    73.6
11  2025-01-10    72.4
12  2025-01-13    73.2
13  2025-01-14    73.6
14  2025-01-15    72.8
15  2025-01-16    73.6
16  2025-01-17    75.6
17  2025-01-20    75.2
18  2025-01-21    75.2
19  2025-01-22    74.8
20  2025-01-23    74.8
21  2025-01-24    74.4
22  2025-01-27    75.6
23  2025-02-05    77.6
24  2025-02-06    77.6
25  2025-02-07    75.2
26  2025-02-10    78.0
27  2025-02-11    88.4
28  2025-02-12    84.4

In [36]:
ak.stock_comment_detail_scrd_desire_daily_em(symbol="600996")

          交易日  当日意愿上升  5日平均参与意愿变化
0  2025-02-05    7.36        2.70
1  2025-02-06   -7.75        2.05
2  2025-02-07   10.94        2.69
3  2025-02-10   -5.35        1.00
4  2025-02-11   -6.55        1.00

停复牌信息

In [39]:
ak.stock_tfp_em()

,序号,代码,名称,停牌时间,停牌截止时间,停牌期限,停牌原因,所属市场,预计复牌时间
0,0,600863,内蒙华电,2025-02-11,NaT,连续停牌,刊登重要公告,上交所主板,NaT
1,1,688739,成大生物,2025-02-11,NaT,连续停牌,刊登重要公告,上交所科创板,NaT
2,2,603963,*ST大药,2025-02-10,NaT,连续停牌,刊登重要公告,上交所风险警示板,NaT
3,3,002527,新时达,2025-02-10,NaT,连续停牌,刊登重要公告,深交所主板,NaT
4,4,001395,亚联机械,2025-02-07,2025-02-07,盘中停牌,交易异常波动,深交所主板,NaT
...,...,...,...,...,...,...,...,...,...
316,316,000989,九芝堂,2024-04-25,2024-04-25,停牌一天,刊登重要公告,深交所风险警示板,2024-04-26
317,317,300965,恒宇信通,2024-04-25,2024-04-25,停牌一天,刊登重要公告,深交所风险警示板,2024-04-26
318,318,603088,宁波精达,2024-04-23,2024-04-29,连续停牌,刊登重要公告,上交所主板,2024-04-30
319,319,000559,万向钱潮,2024-04-17,2024-04-30,连续停牌,拟筹划重大资产重组,深交所主板,2024-05-06
320,320,002715,登云股份,2024-04-15,2024-04-26,连续停牌,拟筹划重大资产重组,深交所主板,2024-04-29

In [44]:
ak.stock_news_em(symbol="600996")

,关键词,新闻标题,新闻内容,发布时间,文章来源,新闻链接
0,600996,哪吒“点燃”影视板块！影视ETF(159855)大涨3.73%！光线传媒、吉视传媒、贵广网络等领涨,截至2025年2月10日 13:56，中证影视主题指数(930781)强势上涨3.87%，成...,2025-02-10 14:24:06,界面新闻,http://stock.eastmoney.com/a/20250210331488878...
1,600996,248只股中线走稳 站上半年线,贵广网络 9.99 2.77 8.69 9.25 6.46 600193 创兴资源 10.1...,2025-02-10 15:26:36,证券时报网,http://finance.eastmoney.com/a/202502103314943...
2,600996,181只股中线走稳 站上半年线,贵广网络 9.99 2.67 8.69 9.25 6.46 600193 创兴资源 10.1...,2025-02-10 14:28:58,证券时报网,http://finance.eastmoney.com/a/202502103314894...
3,600996,传媒行业今日涨3.25% 主力资金净流入4.89亿元,8.18 20.86 5178.27 002558 巨人网络 5.13 3.99 4919....,2025-02-10 17:49:19,证券时报网,http://stock.eastmoney.com/a/20250210331523159...
4,600996,沪指涨0.85%，创指涨1.81%：尾盘券商地产急涨,传媒股继续大涨，光线传媒（300251）、华数传媒（000156）、浙数文化（600633）...,2025-02-12 15:13:52,澎湃新闻,http://finance.eastmoney.com/a/202502123317254...
...,...,...,...,...,...,...
92,600996,广播电视概念股局部冲高 广西广电涨停,10时51分，广西广电涨停，海看股份涨超5%，贵广网络、东方明珠等跟涨。 （文章来源：上海证...,2024-08-28 11:00:59,上海证券报·中国证券网,http://finance.eastmoney.com/a/202408283168140...
93,600996,低调理学博士 接手200亿贵州习酒,股权变动消息一出，“习酒借壳概念股”贵绳股份和贵广网络，连续走出好几个涨停板。 两家都是国资...,2024-09-27 17:06:18,21世纪经济报道,http://finance.eastmoney.com/a/202409273193855...
94,600996,影视股盘中走强，影视ETF（516620）涨超1.3%,影视盘中走强，祥源文旅、海看股份、贵广网络、捷成股份、东方明珠等多股上涨，影视ETF（516...,2024-08-28 11:00:31,每日经济新闻,http://stock.eastmoney.com/a/20240828316814172...
95,600996,59只股中线走稳 站上半年线,到目前为止，今日有59只A股价格突破了半年线，其中乖离率较大的个股有华立科技、双飞集团、浙江...,2024-08-28 15:17:51,证券时报网,http://finance.eastmoney.com/a/202408283168325...
96,600996,8月29日投资避雷针：大缩水！这家上市公司算力服务器采购量从128台减至8台,6、贵广网络：2024年上半年净亏损4.19亿元。 7、禾迈股份：2024年上半年净利润同比...,2024-08-29 08:21:57,财联社,http://finance.eastmoney.com/a/202408293169125...