201303开始 www.szse.cn
201804开始 docs.static.szse.cn

In [1]:
import akshare as ak

In [2]:
ak.stock_sse_summary()

      项目         股票         主板       科创板
0   流通股本   46808.24   45163.83   1644.41
1    总市值  520992.46   452901.3  68091.16
2  平均市盈率      14.09      13.02     43.51
3   上市公司       2282       1697       585
4   上市股票       2321       1736       585
5   流通市值  489062.98  436523.25  52539.73
6   报告时间   20250210   20250210  20250210
8    总股本   49412.66   47181.67   2230.99

In [29]:
df1 = ak.stock_szse_sector_summary(symbol="当年", date="202501").drop('项目名称-英文',axis=1)
df2 = ak.stock_szse_sector_summary(symbol="当年", date="202401").drop('项目名称-英文',axis=1)

/home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/bs4/__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
/home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/bs4/__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

In [35]:
((((df1['成交金额-人民币元']/df1['交易天数']))/100000000)-(((df2['成交金额-人民币元']/df2['交易天数']))/100000000)).round(2)

0     3129.19
1       12.13
2        8.76
3     2161.28
4       -0.92
5      -25.95
6      139.09
7       18.15
8       -2.06
9      473.19
10     183.32
11      18.57
12     153.99
13      -8.87
14      -7.30
15       0.16
16       3.85
17       3.80
18       0.45
19      -2.46
dtype: float64

In [30]:
df1

,项目名称,交易天数,成交金额-人民币元,成交金额-占总计,成交股数-股数,成交股数-占总计,成交笔数-笔,成交笔数-占总计
0,合计,18,12797346256776,100.00,1102116260223,100.00,1072706301,100.00
1,农林牧渔,18,81959102700,0.64,9399492707,0.85,7661044,0.71
2,采矿业,18,92263889071,0.72,9878192740,0.90,9355248,0.87
3,制造业,18,8629767870655,67.43,658476162920,59.75,715973899,66.74
4,水电煤气,18,92119234528,0.72,16229887048,1.47,12802444,1.19
5,建筑业,18,79341083157,0.62,15274277217,1.39,10222345,0.95
6,批发零售,18,446585758971,3.49,52130678407,4.73,40706994,3.79
7,运输仓储,18,101119645056,0.79,10863950008,0.99,11426446,1.07
8,住宿餐饮,18,12977773203,0.10,2114778738,0.19,1728478,0.16
9,信息技术,18,1778343828765,13.90,129291809569,11.73,137478307,12.82
10,金融业,18,556014586952,4.34,41461501835,3.76,31633210,2.95
11,房地产,18,130027421601,1.02,31788728507,2.88,13878880,1.29
12,商务服务,18,403570860326,3.15,71465288349,6.48,38310245,3.57
13,科研服务,18,110626856303,0.86,6923026099,0.63,10972681,1.02
14,公共环保,18,82012479434,0.64,17729676291,1.61,10919804,1.02
15,居民服务,18,1380962740,0.01,148411858,0.01,217920,0.02
16,教育,18,32550128302,0.25,7073096176,0.64,3040949,0.28
17,卫生,18,42095615991,0.33,5628801958,0.51,4706600,0.44
18,文化传播,18,107581655354,0.84,14651178792,1.33,10017645,0.93
19,综合,18,17007503667,0.13,1587321004,0.14,1653162,0.15

In [37]:
(((df1['成交金额-人民币元']/df1['交易天数']))/100000000).round(2)

0     7109.64
1       45.53
2       51.26
3     4794.32
4       51.18
5       44.08
6      248.10
7       56.18
8        7.21
9      987.97
10     308.90
11      72.24
12     224.21
13      61.46
14      45.56
15       0.77
16      18.08
17      23.39
18      59.77
19       9.45
dtype: float64

In [50]:
ak.stock_szse_sector_summary(symbol="当月", date="201803").drop('项目名称-英文',axis=1)

MissingSchema: Invalid URL '/market/periodical/documents/P020180502701363979059.html': No scheme supplied. Perhaps you meant https:///market/periodical/documents/P020180502701363979059.html?