201303开始 www.szse.cn
201804开始 docs.static.szse.cn
https://akshare.akfamily.xyz/data/stock/stock.html#id9

In [91]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd


engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [92]:
icdf = pd.read_sql('akStockIC',engB)

In [95]:
icdf.to_sql('akRawStockIC',engB)

-1

In [93]:
icdf.drop_duplicates(subset='证券代码')

,证券代码,新证券简称,行业中类,行业大类,行业次类,行业门类,机构名称,行业编码,分类标准,分类标准编码,变更日期
0,600000,浦发银行,其他商业银行,银行业,金融、保险业,金融、保险业,上海浦东发展银行股份有限公司,I0199,证监会行业分类标准（2001）,008009,1992-10-19
11,600004,白云机场,机场及航空运输辅助业,交通运输辅助业,交通运输、仓储业,交通运输、仓储业,广州白云国际机场股份有限公司,F1115,证监会行业分类标准（2001）,008009,2000-09-19
21,600006,东风股份,汽车制造业,交通运输设备制造业,机械、设备、仪表,制造业,东风汽车股份有限公司,C7505,证监会行业分类标准（2001）,008009,1999-07-21
33,600007,中国国贸,租赁服务业,租赁服务业,社会服务业,社会服务业,中国国际贸易中心股份有限公司,K3901,证监会行业分类标准（2001）,008009,1997-10-15
40,600839,四川长虹,家电,家电,家电,家电,四川长虹电器股份有限公司,N12,新财富行业分类标准,008004,2008-10-20
...,...,...,...,...,...,...,...,...,...,...,...
51682,301636,泽润新能,None,电气机械和器材制造业,None,制造业,江苏泽润新能科技股份有限公司,C38,证监会行业分类标准（2012）,008021,2024-01-25
51689,301662,宏工科技,None,专用设备制造业,None,制造业,宏工科技股份有限公司,C35,证监会行业分类标准（2012）,008021,2023-05-05
51694,301665,泰禾股份,农药,农药,化学制品,化工,南通泰禾化工股份有限公司,S220303,申银万国行业分类标准(旧),008018,2021-03-31
51699,301678,新恒汇,None,计算机、通信和其他电子设备制造业,None,制造业,新恒汇电子股份有限公司,C39,证监会行业分类标准（2012）,008021,2023-03-15
51703,302132,中航成飞,电子,电子,电子,电子,中航电测仪器股份有限公司,N08,新财富行业分类标准,008004,2010-08-06

In [ ]:
ldf = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
IndexLists = ldf[~ldf['From'].isin(['TDXBLK','EMP'])][['IndexCode','IndexName']].values.tolist()

In [45]:
StockLists=pd.read_sql('akStocksList', engS)['StockCode'].to_list()

In [ ]:
emp = pd.read_sql('EmpIndex', eng)

In [ ]:
ak.index_stock_cons("399657")

In [ ]:
pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})[['IndexCode','IndexName']].values.tolist()

In [ ]:
IndexLists = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/optIndexs.xlsx', dtype={'IndexCode':object})[['IndexCode','IndexName']].values.tolist()

In [ ]:
IndexLists[1][0]

In [ ]:
ll = []

In [ ]:
IndexLists[12][0]

In [ ]:
ll.append(IndexLists[12][0])

In [ ]:
ll.append('103')

In [ ]:
ll

In [ ]:
df = ak.index_stock_cons(IndexLists[0][0])
df['IndexCode'] = IndexLists[0][0]
df['IndexName'] = IndexLists[0][1] 
for i in IndexLists[1:3]:
    try:
        tmp = ak.index_stock_cons(i[0]).drop_duplicates(subset='品种代码',keep='first')
        tmp['IndexCode'] = i[0]
        tmp['IndexName'] = i[1]
        df = pd.concat([df,tmp])
        print(i[0]+'ok !')
    except:
        ll = ll.append(i[0])
        print(i[0]+'EMP !! ')

In [ ]:
df.columns.values

In [ ]:
df.rename(columns={'品种代码':'StockCode', '品种名称':'StockName', '纳入日期':'DP'},inplace=True)

In [ ]:
df[['IndexCode', 'IndexName','StockCode', 'StockName', 'DP']].set_index('IndexCode')

In [ ]:
df

In [ ]:
IndexLists[1:3]

In [ ]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [ ]:
pd.read_sql('akStockIC', engB)

In [ ]:
akdf.drop('index',axis=1).set_index('证券代码').to_sql('akStockIC',engB,if_exists='replace')

In [ ]:
StockList = pd.read_sql('akStocksList', eng)

In [ ]:
StocksCode = StockList['StockCode'].tolist()

In [ ]:
idf = ak.stock_industry_change_cninfo(symbol=StocksCode[0], start_date="11000101", end_date="22000101")
for code in StocksCode[1:]:
    df_tmp = ak.stock_industry_change_cninfo(symbol=code, start_date="11000101", end_date="22000101")
    idf = pd.concat([idf,df_tmp])
    print('code '+code+' :concat !')

### 主营介绍

* 同花顺

In [90]:
ak.stock_zyjs_ths(symbol="002202")

,股票代码,主营业务,产品类型,产品名称,经营范围
0,002202,风机制造、风电服务、风电场投资与开发以及水务等其他业务。,风机及零部件销售、风电场开发、风电服务,风机及零部件销售、风电服务、风电场开发,大型风力发电机组生产销售及技术引进与开发、应用；建设及运营中试型风力发电场；制造及销售风力发...

* 东财

In [21]:
ak.stock_zygc_em(symbol="SZ002202")

,股票代码,报告日期,分类类型,主营构成,主营收入,收入比例,主营成本,成本比例,主营利润,利润比例,毛利率
0,002202,2025-06-30,NaN,风电行业,2.792043e+10,0.978391,2.370461e+10,0.981268,4.215822e+09,0.962518,0.150994
1,002202,2025-06-30,NaN,其他,6.166695e+08,0.021609,4.524993e+08,0.018732,1.641702e+08,0.037482,0.266221
2,002202,2025-06-30,按产品分类,风机及零部件销售,2.185228e+10,0.765750,2.011046e+10,0.832486,1.741828e+09,0.397678,0.079709
3,002202,2025-06-30,按产品分类,风电场开发,3.171937e+09,0.111151,1.349074e+09,0.055846,1.822863e+09,0.416179,0.574685
4,002202,2025-06-30,按产品分类,风电服务,2.896207e+09,0.101489,2.245075e+09,0.092936,6.511318e+08,0.148660,0.224822
...,...,...,...,...,...,...,...,...,...,...,...
195,002202,2017-12-31,按产品分类,风电服务,2.060891e+09,0.082011,1.744471e+09,0.099511,3.164195e+08,0.041640,0.153535
196,002202,2017-12-31,按产品分类,风机零部件销售,7.363328e+08,0.029302,6.086937e+08,0.034722,1.276391e+08,0.016797,0.173344
197,002202,2017-12-31,按产品分类,其他,3.684040e+08,0.014660,1.374066e+08,0.007838,2.309973e+08,0.030398,0.627022
198,002202,2017-12-31,按产品分类,3.0MW,3.053859e+08,0.012153,2.416462e+08,0.013784,6.373969e+07,0.008388,0.208718
199,002202,2017-12-31,按地区分类,国内销售,2.304171e+10,0.916920,1.606921e+10,0.916645,6.972501e+09,0.917555,0.302603

### 行业分类

In [ ]:
InduList = ["巨潮行业分类标准", "申银万国行业分类标准", "巨潮产业细分标准",  "全球行业分类标准"]

In [ ]:
df = ak.stock_industry_category_cninfo("证监会行业分类标准")
for iList in InduList:
    dfx = ak.stock_industry_category_cninfo(iList)
    df = pd.concat([df,dfx])

In [ ]:
df0 = ak.stock_industry_category_cninfo(symbol=InduList[0])
df1 = ak.stock_industry_category_cninfo(symbol=InduList[1])

In [ ]:
df = pd.concat([df0,df1])

In [85]:
ak.stock_industry_category_cninfo('全球行业分类标准')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [86]:
ak.stock_industry_category_cninfo("申银万国行业分类标准")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

* 上市公司行业归属的变动情况-巨潮资讯

In [87]:
ak.stock_industry_change_cninfo(symbol="600004")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

* 申万个股行业分类变动历史

In [33]:
ak.stock_industry_change_cninfo(symbol="600489", start_date="11000101", end_date="20260101")

,新证券简称,行业中类,行业大类,行业次类,行业门类,机构名称,行业编码,分类标准,分类标准编码,证券代码,变更日期
0,中金黄金,贵金属矿采选业,有色金属矿采选业,采掘业,采掘业,中金黄金股份有限公司,B0730,证监会行业分类标准（2001）,008009,600489,2000-06-23
1,中金黄金,有色金属冶炼,有色金属冶炼,有色金属冶炼,有色金属,中金黄金股份有限公司,S240101,申银万国行业分类标准(旧),008018,600489,2003-08-12
2,中金黄金,贵金属,有色金属,基础材料,原材料,中金黄金股份有限公司,Z02020402,巨潮行业分类标准(旧),008013,600489,2003-08-14
3,中金黄金,NaN,有色金属矿采选业,NaN,采矿业,中金黄金股份有限公司,B09,证监会行业分类标准（2012）,008021,600489,2003-08-14
4,中金黄金,黄金,黄金,有色金属冶炼与加工,有色金属,中金黄金股份有限公司,S240105,申银万国行业分类标准(旧),008018,600489,2007-07-02
5,中金黄金,黄金,黄金,贵金属,有色金属,中金黄金股份有限公司,S240401,申银万国行业分类标准,008003,600489,2008-06-02
6,中金黄金,黄金,黄金,黄金,有色金属,中金黄金股份有限公司,S240401,申银万国行业分类标准(旧),008018,600489,2008-06-02
7,中金黄金,有色金属,有色金属,有色金属,有色金属,中金黄金股份有限公司,N11,新财富行业分类标准,008004,600489,2008-10-20
8,中金黄金,贵金属,有色金属,基础材料,原材料,中金黄金股份有限公司,Z02020402,巨潮行业分类标准,008002,600489,2019-05-08
9,中金黄金,黄金及其它贵金属,有色金属,原材料,原材料,中金黄金股份有限公司,01010503,中证行业分类标准(旧),008019,600489,2020-03-16
10,中金黄金,黄金,贵金属,有色金属,原材料,中金黄金股份有限公司,15202010,中证行业分类标准,008014,600489,2021-12-17
11,中金黄金,NaN,有色金属矿采选业,NaN,采矿业,中金黄金股份有限公司,B09,中国上市公司协会上市公司行业分类标准,008001,600489,2024-02-08

In [24]:
ak.stock_industry_clf_hist_sw()

       symbol  start_date industry_code update_time
0      000001  1991-04-03        440101  2015-10-27
1      000001  2014-02-21        480101  2024-09-27
2      000001  2021-07-30        480301  2021-07-31
3      000002  1991-01-29        430101  2015-10-27
4      000003  1991-04-14        510101  2015-10-27
...       ...         ...           ...         ...
12657  920111  2024-10-29        630802  2025-02-19
12658  920112  2025-08-21        640209  2025-08-21
12659  920116  2024-12-24        710301  2025-02-19
12660  920118  2024-08-21        630805  2025-02-19
12661  920128  2024-11-25        270203  2025-02-19

[12662 rows x 4 columns]

In [23]:
ak.stock_info_sz_change_name("简称变更")

            变更日期    证券代码   证券简称  变更前简称  变更后简称
0     1994-01-03  000005   ST星源   深原野Ａ   深星源Ａ
1     1994-11-01  000503   国新健康    琼化纤    琼海虹
2     1995-05-22  000503   国新健康    琼海虹   琼海虹Ａ
3     1996-05-17  000530   冰山冷热   连大冷Ａ   大冷股份
4     1996-10-03  000568   泸州老窖   川老窖Ａ   泸州老窖
...          ...     ...    ...    ...    ...
7167  2025-08-14  300300   海峡创新   ST峡创   海峡创新
7168  2025-08-19  301632   广东建科  C广东建科   广东建科
7169  2025-08-21  002822  *ST中装   ST中装  *ST中装
7170  2025-08-22  000713   国投丰乐   丰乐种业   国投丰乐
7171  2025-08-27  002316   亚联发展   ST亚联   亚联发展

[7172 rows x 5 columns]

In [25]:
ak.stock_profile_cninfo('600382')

,公司名称,英文名称,曾用简称,A股代码,A股简称,B股代码,B股简称,H股代码,H股简称,入选指数,...,官方网站,电子邮箱,联系电话,传真,注册地址,办公地址,邮政编码,主营业务,经营范围,机构简介
0,广东明珠集团股份有限公司,"Guangdong Mingzhu Group Co., Ltd.",广东明珠>> *ST广珠>> ST广珠,600382,广东明珠,None,None,None,None,国证Ａ指,...,www.gdmzh.com,600382@gdmzh.com,0753-3338549,0753-3338549,广东省兴宁市官汕路99号,广东省兴宁市官汕路99号,514500,铁矿采选、铁精粉生产销售。,非煤矿山矿产资源开采；金属矿石销售；非金属矿及制品销售；实业投资；股权投资；科创企业孵化服务...,公司前身为创建于1971年的广东省球阀厂。1991年以广东省球阀厂为主体组建了广东明珠球阀集...

In [26]:
ak.index_stock_cons_csindex(symbol="H50056")

,日期,指数代码,指数名称,指数英文名称,成分券代码,成分券名称,成分券英文名称,交易所,交易所英文名称
0,2025-08-28,H50056,沪智家居,SSE Smart Home,600060,海信视像,"Hisense Visual Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
1,2025-08-28,H50056,沪智家居,SSE Smart Home,600071,凤凰光学,Phoenix Optical Co Ltd,上海证券交易所,Shanghai Stock Exchange
2,2025-08-28,H50056,沪智家居,SSE Smart Home,600171,上海贝岭,Shanghai Belling Corp Ltd,上海证券交易所,Shanghai Stock Exchange
3,2025-08-28,H50056,沪智家居,SSE Smart Home,600336,澳柯玛,Aucma Co Ltd,上海证券交易所,Shanghai Stock Exchange
4,2025-08-28,H50056,沪智家居,SSE Smart Home,600363,联创光电,Jiangxi Lianchuang Optoelectronic Science and ...,上海证券交易所,Shanghai Stock Exchange
5,2025-08-28,H50056,沪智家居,SSE Smart Home,600601,方正科技,Founder Technology Group Corp.,上海证券交易所,Shanghai Stock Exchange
6,2025-08-28,H50056,沪智家居,SSE Smart Home,600637,东方明珠,"Shanghai Oriental Pearl Media Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
7,2025-08-28,H50056,沪智家居,SSE Smart Home,600690,海尔智家,"Haier Smart Home Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
8,2025-08-28,H50056,沪智家居,SSE Smart Home,600839,四川长虹,Sichuan Changhong Electric Co Ltd,上海证券交易所,Shanghai Stock Exchange
9,2025-08-28,H50056,沪智家居,SSE Smart Home,600877,电科芯片,CETC Chips Technology Inc.,上海证券交易所,Shanghai Stock Exchange
10,2025-08-28,H50056,沪智家居,SSE Smart Home,600959,江苏有线,Jiangsu Broadcasting Cable Information Network...,上海证券交易所,Shanghai Stock Exchange
11,2025-08-28,H50056,沪智家居,SSE Smart Home,600996,贵广网络,Guizhou Broadcasting & TV Information Network ...,上海证券交易所,Shanghai Stock Exchange
12,2025-08-28,H50056,沪智家居,SSE Smart Home,601138,工业富联,"Foxconn Industrial Internet Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
13,2025-08-28,H50056,沪智家居,SSE Smart Home,601231,环旭电子,Universal Scientific Industrial (Shanghai) Co....,上海证券交易所,Shanghai Stock Exchange
14,2025-08-28,H50056,沪智家居,SSE Smart Home,603005,晶方科技,"China Wafer Level CSP Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
15,2025-08-28,H50056,沪智家居,SSE Smart Home,603083,剑桥科技,"CIG ShangHai CO., LTD.",上海证券交易所,Shanghai Stock Exchange
16,2025-08-28,H50056,沪智家居,SSE Smart Home,603160,汇顶科技,"Shenzhen Huiding Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
17,2025-08-28,H50056,沪智家居,SSE Smart Home,603195,公牛集团,"GONGNIU GROUP CO., LTD.",上海证券交易所,Shanghai Stock Exchange
18,2025-08-28,H50056,沪智家居,SSE Smart Home,603236,移远通信,"Quectel Wireless Solutions Co., Ltd",上海证券交易所,Shanghai Stock Exchange
19,2025-08-28,H50056,沪智家居,SSE Smart Home,603486,科沃斯,"Ecovacs Robotics Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
20,2025-08-28,H50056,沪智家居,SSE Smart Home,603501,豪威集团,"Omni Vision Integrated Circuits Group, Inc.",上海证券交易所,Shanghai Stock Exchange
21,2025-08-28,H50056,沪智家居,SSE Smart Home,603583,捷昌驱动,"Zhejiang Jiecang Linear Motion Technology Co.,...",上海证券交易所,Shanghai Stock Exchange
22,2025-08-28,H50056,沪智家居,SSE Smart Home,603629,利通电子,"Jiangsu Lettall Electronic Co.,Ltd",上海证券交易所,Shanghai Stock Exchange
23,2025-08-28,H50056,沪智家居,SSE Smart Home,603728,鸣志电器,"Shanghai Moons' Electric Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
24,2025-08-28,H50056,沪智家居,SSE Smart Home,603738,泰晶科技,Hubei TKD Crystal Electronic Science and Techn...,上海证券交易所,Shanghai Stock Exchange
25,2025-08-28,H50056,沪智家居,SSE Smart Home,603816,顾家家居,"Jason Furniture (Hangzhou) Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
26,2025-08-28,H50056,沪智家居,SSE Smart Home,603833,欧派家居,Oppein Home Group Inc.,上海证券交易所,Shanghai Stock Exchange
27,2025-08-28,H50056,沪智家居,SSE Smart Home,603868,飞科电器,"Shanghai Flyco Electrical Appliance Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
28,2025-08-28,H50056,沪智家居,SSE Smart Home,603893,瑞芯微,"Fuzhou Rockchip Electronics Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
29,2025-08-28,H50056,沪智家居,SSE Smart Home,605117,德业股份,"Ningbo Deye Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
30,2025-08-28,H50056,沪智家居,SSE Smart Home,688018,乐鑫科技,"Espressif Systems (Shanghai) Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
31,2025-08-28,H50056,沪智家居,SSE Smart Home,688049,炬芯科技,"Actions Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
32,2025-08-28,H50056,沪智家居,SSE Smart Home,688099,晶晨股份,"Amlogic (Shanghai) Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
33,2025-08-28,H50056,沪智家居,SSE Smart Home,688127,蓝特光学,"Zhejiang Lante Optics Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
34,2025-08-28,H50056,沪智家居,SSE Smart Home,688169,石头科技,"Beijing Roborock Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
35,2025-08-28,H50056,沪智家居,SSE Smart Home,688220,翱捷科技,"ASR Microelectronics Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
36,2025-08-28,H50056,沪智家居,SSE Smart Home,688256,寒武纪,Cambricon Technologies Corporation Limited,上海证券交易所,Shanghai Stock Exchange
37,2025-08-28,H50056,沪智家居,SSE Smart Home,688332,中科蓝讯,"Shenzhen Bluetrum Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
38,2025-08-28,H50056,沪智家居,SSE Smart Home,688368,晶丰明源,"Shanghai Bright Power Semiconductor Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
39,2025-08-28,H50056,沪智家居,SSE Smart Home,688385,复旦微电,"Shanghai Fudan Microelectronics Group CO.,LTD.",上海证券交易所,Shanghai Stock Exchange
40,2025-08-28,H50056,沪智家居,SSE Smart Home,688475,萤石网络,"Hangzhou EZVIZ Network Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
41,2025-08-28,H50056,沪智家居,SSE Smart Home,688508,芯朋微,Wuxi Chipown Micro-electronics Limited,上海证券交易所,Shanghai Stock Exchange
42,2025-08-28,H50056,沪智家居,SSE Smart Home,688521,芯原股份,"VeriSilicon Microelectronics (Shanghai) Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
43,2025-08-28,H50056,沪智家居,SSE Smart Home,688536,思瑞浦,3PEAK INCORPORATED,上海证券交易所,Shanghai Stock Exchange
44,2025-08-28,H50056,沪智家居,SSE Smart Home,688608,恒玄科技,"Bestechnic (Shanghai) Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
45,2025-08-28,H50056,沪智家居,SSE Smart Home,688609,九联科技,"Unionman Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
46,2025-08-28,H50056,沪智家居,SSE Smart Home,688696,极米科技,"Chengdu XGimi Technology Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
47,2025-08-28,H50056,沪智家居,SSE Smart Home,688766,普冉股份,"Puya Semiconductor (Shanghai) Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
48,2025-08-28,H50056,沪智家居,SSE Smart Home,688787,海天瑞声,Beijing Haitian Ruisheng Science Technology Ltd.,上海证券交易所,Shanghai Stock Exchange
49,2025-08-28,H50056,沪智家居,SSE Smart Home,688981,中芯国际,Semiconductor Manufacturing International Corp...,上海证券交易所,Shanghai Stock Exchange

In [80]:
StockLists.index('002142')

2936

In [27]:
ak.sw_index_third_cons(symbol="859822.SI")

,序号,股票代码,股票简称,纳入时间,申万1级,申万2级,申万3级,价格,市盈率,市盈率ttm,市净率,股息率,市值,归母净利润同比增长(09-30),归母净利润同比增长(06-30),营业收入同比增长(09-30),营业收入同比增长(06-30)
0,1,300957.SZ,贝泰妮,2021-04-01,—,—,品牌化妆品,46.91,39.50,74.72,3.28,1.27,198.71,-49.01,-83.97,-15.43,-13.51
1,2,300740.SZ,水羊股份,2018-02-22,—,—,品牌化妆品,22.74,80.66,69.58,4.30,NaN,88.69,16.54,4.67,9.02,5.19
2,3,600315.SH,上海家化,2001-03-22,—,—,品牌化妆品,26.32,NaN,NaN,2.54,0.11,176.93,11.66,-15.25,4.75,-10.59
3,4,603605.SH,珀莱雅,2017-11-22,—,—,品牌化妆品,84.12,21.46,20.20,5.88,1.41,333.12,13.80,28.87,7.21,8.13
4,5,603630.SH,拉芳家化,2017-03-20,—,—,品牌化妆品,25.14,136.86,536.74,2.97,0.55,56.62,-82.89,-53.30,-4.27,-6.27
5,6,600223.SH,福瑞达,2024-02-06,—,—,品牌化妆品,8.07,33.69,36.58,1.98,1.36,82.04,-15.16,-14.10,-7.05,-1.63
6,7,301371.SZ,敷尔佳,2023-08-08,—,—,品牌化妆品,26.56,20.89,25.10,2.52,4.34,138.14,-32.54,-39.77,-8.15,-26.39
7,8,603983.SH,丸美生物,2019-08-01,—,—,品牌化妆品,40.19,47.17,45.94,4.79,1.87,161.16,5.21,22.07,30.83,28.01

In [ ]:
df = pd.DataFrame(columns=['新证券简称', '行业中类', '行业大类', '行业次类', '行业门类', '机构名称', '行业编码', '分类标准','分类标准编码', '证券代码', '变更日期'], dtype=object)
for i in StockLists[5000:5020]:
    tempdf = ak.stock_industry_change_cninfo(symbol=i, start_date="11000101", end_date="22000101")
    tempdf = tempdf[tempdf['分类标准编码'].isin(['008001','008002','008003','008014'])].sort_values(by='分类标准编码')
    df = pd.concat([df,tempdf])

In [62]:
ak.stock_industry_change_cninfo(symbol="600996", start_date="11000101", end_date="22000101")

,新证券简称,行业中类,行业大类,行业次类,行业门类,机构名称,行业编码,分类标准,分类标准编码,证券代码,变更日期
0,贵广网络,传播与文化,传播与文化,传播与文化,传播与文化,贵州省广播电视信息网络股份有限公司,N27,新财富行业分类标准,008004,600996,2016-12-05
1,贵广网络,有线电视网络,有线电视网络,文化传媒,传媒,贵州省广播电视信息网络股份有限公司,S720103,申银万国行业分类标准(旧),008018,600996,2016-12-05
2,贵广网络,NaN,电信、广播电视和卫星传输服务,NaN,信息传输、软件和信息技术服务业,贵州省广播电视信息网络股份有限公司,I63,证监会行业分类标准（2012）,008021,600996,2016-12-05
3,贵广网络,广播与有线电视,传媒,传媒,可选消费,贵州省广播电视信息网络股份有限公司,Z04050102,巨潮行业分类标准(旧),008013,600996,2016-12-26
4,贵广网络,广播与有线电视,传媒,传媒,可选消费,贵州省广播电视信息网络股份有限公司,Z04050102,巨潮行业分类标准,008002,600996,2019-05-15
5,贵广网络,广播与有线电视,传媒,传媒,可选消费,贵州省广播电视信息网络股份有限公司,03040102,中证行业分类标准(旧),008019,600996,2020-03-16
6,贵广网络,电视广播Ⅲ,电视广播Ⅲ,电视广播Ⅱ,传媒,贵州省广播电视信息网络股份有限公司,S721001,申银万国行业分类标准,008003,600996,2021-07-30
7,贵广网络,广播与电视,文化娱乐,传媒,通信服务,贵州省广播电视信息网络股份有限公司,50302040,中证行业分类标准,008014,600996,2021-12-17
8,贵广网络,NaN,电信、广播电视和卫星传输服务,NaN,信息传输、软件和信息技术服务业,贵州省广播电视信息网络股份有限公司,I63,中国上市公司协会上市公司行业分类标准,008001,600996,2024-02-08

In [78]:
ddf = ak.stock_industry_change_cninfo(symbol="002142", start_date="11000101", end_date="22000101")
ddf[~ddf['分类标准'].str.contains('旧')].drop_duplicates(subset='分类标准',keep='last')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [74]:
df[['新证券简称','证券代码','分类标准', '变更日期','行业中类', '行业大类', '行业次类', '行业门类', '行业编码',
       '分类标准编码' ]].rename(columns={'新证券简称':'StockName','证券代码':'StockCode','分类标准':'ICS', '变更日期':'DP','行业中类':'IC4', '行业大类':'IC3', '行业次类':'IC2', '行业门类':'IC1', '行业编码':'ICode',
       '分类标准编码':'ICSCode' }).set_index('StockCode')

,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode
StockCode,,,,,,,,,
301337,亚华电子,中国上市公司协会上市公司行业分类标准,2024-02-08,NaN,软件和信息技术服务业,NaN,信息传输、软件和信息技术服务业,I65,008001
301337,亚华电子,巨潮行业分类标准,2023-05-26,应用软件,计算机软件,软件与互联网,信息技术,Z08010301,008002
301337,亚华电子,申银万国行业分类标准,2023-04-27,IT服务Ⅲ,IT服务Ⅲ,IT服务Ⅱ,计算机,S710301,008003
301337,亚华电子,申银万国行业分类标准,2023-05-04,垂直应用软件,垂直应用软件,软件开发,计算机,S710401,008003
301337,亚华电子,中证行业分类标准,2023-05-26,行业应用软件,软件开发,计算机,信息技术,45101020,008014
...,...,...,...,...,...,...,...,...,...
301367,瑞迈特,中证行业分类标准,2022-11-01,医疗设备,医疗器械,医疗,医药卫生,35101010,008014
301368,丰立智能,中国上市公司协会上市公司行业分类标准,2024-02-08,NaN,通用设备制造业,NaN,制造业,C34,008001
301368,丰立智能,巨潮行业分类标准,2022-12-15,基础件,通用机械,工业品,工业,Z03010504,008002
301368,丰立智能,申银万国行业分类标准,2022-11-25,金属制品,金属制品,通用设备,机械设备,S640108,008003
301368,丰立智能,中证行业分类标准,2022-12-15,动力机械,通用机械,机械制造,工业,20401020,008014

In [75]:
ak.stock_zygc_em(symbol="SZ"+"301338")

,股票代码,报告日期,分类类型,主营构成,主营收入,收入比例,主营成本,成本比例,主营利润,利润比例,毛利率
0,301338,2025-06-30,按产品分类,锡膏印刷设备,2.919889e+08,0.643689,1.560849e+08,0.591866,1.359040e+08,0.715655,0.465442
1,301338,2025-06-30,按产品分类,点胶设备,6.049741e+07,0.133366,4.174567e+07,0.158298,1.875174e+07,0.098745,0.309959
2,301338,2025-06-30,按产品分类,封装设备,5.917624e+07,0.130454,5.061375e+07,0.191925,8.562488e+06,0.045089,0.144695
3,301338,2025-06-30,按产品分类,柔性自动化设备,2.451180e+07,0.054036,1.015489e+07,0.038507,1.435690e+07,0.075602,0.585714
4,301338,2025-06-30,按产品分类,其他(补充),1.744369e+07,0.038455,5.117325e+06,0.019405,1.232636e+07,0.064909,0.706637
...,...,...,...,...,...,...,...,...,...,...,...
195,301338,2019-12-31,按地区分类,其中:欧洲,2.313960e+07,0.044914,NaN,NaN,NaN,NaN,NaN
196,301338,2019-12-31,按地区分类,其中:中国香港、中国台湾,9.507600e+06,0.018454,NaN,NaN,NaN,NaN,NaN
197,301338,2019-12-31,按地区分类,其中:保税区,8.405600e+06,0.016315,NaN,NaN,NaN,NaN,NaN
198,301338,2019-12-31,按地区分类,其中:其他,3.220500e+06,0.006251,NaN,NaN,NaN,NaN,NaN
199,301338,2018-12-31,按产品分类,锡膏印刷设备,3.499702e+08,0.807097,2.045303e+08,0.788900,1.454399e+08,0.834153,0.415578

In [8]:
ak.stock_industry_pe_ratio_cninfo(symbol="国证行业分类", date="20250812")

,变动日期,行业分类,行业层级,行业编码,行业名称,公司数量,纳入计算公司数量,总市值-静态,净利润-静态,静态市盈率-加权平均,静态市盈率-中位数,静态市盈率-算术平均
0,2025-08-12,国证行业分类标准2019,1,C01,能源,84.0,61.0,38795.1795,3395.8808,11.42,20.68,39.58
1,2025-08-12,国证行业分类标准2019,2,C0101,能源,84.0,61.0,38795.1795,3395.8808,11.42,20.68,39.58
2,2025-08-12,国证行业分类标准2019,3,C010101,能源设备与服务,26.0,19.0,2300.7553,120.4336,19.10,38.78,68.18
3,2025-08-12,国证行业分类标准2019,4,C01010101,能源设备,15.0,11.0,893.9582,34.2988,26.06,38.78,50.04
4,2025-08-12,国证行业分类标准2019,4,C01010102,能源服务,11.0,8.0,1406.7971,86.1348,16.33,35.72,93.12
...,...,...,...,...,...,...,...,...,...,...,...,...
288,2025-08-12,国证行业分类标准2019,4,C11020101,房地产信托,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,2025-08-12,国证行业分类标准2019,3,C110202,房地产租赁,18.0,17.0,2274.5267,66.8294,34.03,83.86,120.65
290,2025-08-12,国证行业分类标准2019,4,C11020201,房地产租赁,18.0,17.0,2274.5267,66.8294,34.03,83.86,120.65
291,2025-08-12,国证行业分类标准2019,3,C110203,其他房地产服务,4.0,2.0,95.4692,1.8719,51.00,58.92,58.92
292,2025-08-12,国证行业分类标准2019,4,C11020301,其他房地产服务,4.0,2.0,95.4692,1.8719,51.00,58.92,58.92

In [9]:
ak.stock_analyst_detail_em(
        analyst_id="11000423631", indicator="最新跟踪成分股"
    )

   序号    股票代码 股票名称        调入日期      最新评级日期 当前评级名称  成交价格(前复权)    最新价格   阶段涨跌幅
0   1  300502  新易盛  2025-05-16  2025-05-16     买入  84.372799  354.95  320.71

In [10]:
ak.stock_hot_rank_em()

    当前排名        代码   股票名称      最新价        涨跌额    涨跌幅
0      1  SH688256  寒武纪-U  1485.92 -95.396064  -6.42
1      2  SZ002195   岩山科技     8.43   0.397896   4.72
2      3  SZ002600   领益智造    15.51  -0.715011  -4.61
3      4  SZ000831   中国稀土    58.32   5.832000  10.00
4      5  SH600895   张江高科    39.50   0.849250   2.15
..   ...       ...    ...      ...        ...    ...
95    96  SH600580   卧龙电驱    33.48  -0.405108  -1.21
96    97  SZ300748   金力永磁    42.90   0.313170   0.73
97    98  SZ002681   奋达科技     7.96  -0.307256  -3.86
98    99  SZ002475   立讯精密    45.66  -0.433770  -0.95
99   100  SH603177   德创环保    14.50   1.452900  10.02

[100 rows x 6 columns]

## 申万行业信息

### 申万一级行业信息

In [ ]:
ak.sw_index_first_info()

### 申万二级行业信息

In [ ]:
ak.sw_index_second_info()

### 申万三级行业信息

In [11]:
ak.sw_index_third_info()

          行业代码      行业名称   上级行业  成份个数  静态市盈率  TTM(滚动)市盈率   市净率  静态股息率
0    850111.SI        种子    种植业     8  90.33       94.92  3.29   0.67
1    850113.SI     其他种植业    种植业     6  57.68       50.29  2.40   0.62
2    850122.SI      水产养殖     渔业     4  80.40       85.02  1.02   0.43
3    850142.SI      畜禽饲料     饲料    10  26.99       15.02  1.84   1.24
4    850151.SI      果蔬加工  农产品加工     5  60.63       51.90  4.03   1.80
..         ...       ...    ...   ...    ...         ...   ...    ...
253  859714.SI    综合环境治理   环境治理    15  27.96       30.71  1.87   1.66
254  859721.SI     环保设备Ⅲ  环保设备Ⅱ    28  33.67       32.30  1.91   1.70
255  859811.SI      生活用纸   个护用品     8  40.71       36.52  2.53   1.89
256  859821.SI  化妆品制造及其他    化妆品     6  27.48       55.70  3.07   5.08
257  859822.SI     品牌化妆品    化妆品     8  30.65       33.30  3.69   1.42

[258 rows x 8 columns]

### 申万三级行业成份

In [12]:
ak.sw_index_third_cons(symbol="850111.SI")

,序号,股票代码,股票简称,纳入时间,申万1级,申万2级,申万3级,价格,市盈率,市盈率ttm,市净率,股息率,市值,归母净利润同比增长(09-30),归母净利润同比增长(06-30),营业收入同比增长(09-30),营业收入同比增长(06-30)
0,1,600313.SH,农发种业,2018-12-26,—,—,种子,6.47,149.33,128.02,3.55,NaN,70.02,14.13,13.55,47.86,85.29
1,2,000713.SZ,丰乐种业,1997-04-22,—,—,种子,7.18,63.12,60.41,2.22,0.28,44.09,NaN,22.88,NaN,-5.50
2,3,000998.SZ,隆平高科,2000-12-11,—,—,种子,9.98,128.79,NaN,2.38,0.40,146.65,-247.26,-102.72,-16.11,-32.03
3,4,300087.SZ,荃银高科,2010-06-03,—,—,种子,9.39,77.75,93.33,4.73,0.53,88.95,-85.85,-87.62,1.81,24.13
4,5,300189.SZ,神农种业,2011-03-24,—,—,种子,5.04,NaN,NaN,7.27,NaN,51.61,6.69,88.18,38.66,-22.16
5,6,600371.SH,万向德农,2011-10-10,—,—,种子,9.29,51.65,74.43,4.90,1.61,27.18,-39.33,-34.41,-24.39,-21.87
6,7,600354.SH,敦煌种业,2007-07-03,—,—,种子,6.70,70.90,48.49,5.01,NaN,35.36,73.43,61.85,21.63,34.15
7,8,002041.SZ,登海种业,2005-04-18,—,—,种子,9.88,153.54,222.92,2.41,0.29,86.94,-33.42,-18.37,-9.41,-30.04

## 指数

In [ ]:
ak.index_csindex_all()

In [ ]:
ak.stock_zh_index_spot_em(symbol="上证系列指数")

## 股票指数信息一览表

In [ ]:
ak.index_stock_info()

### 国证指数

In [ ]:
ak.index_all_cni()

In [ ]:
ak.index_all_cni().to_excel('G:/Gitee/App/TDXapp/tdxAppData/gzIndex.xlsx')

## 股票指数 最新成份

In [ ]:
ak.index_stock_cons("000002")

### 中证

In [ ]:
ak.index_stock_cons_csindex("881463")

### 国证

In [ ]:
ak.index_detail_cni(symbol='980150', date='202507')

====================

In [ ]:
wcidf = ak.drewry_wci_index('shanghai-los angeles')

In [ ]:
cidf = ak.index_ci_cx()

In [ ]:
ak.index_global_name_table()

In [ ]:
ak.index_kq_fz(symbol="景气指数")

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(wcidf,x='date', y=wcidf['wci'],line_shape='linear')
fig.show()

In [ ]:
ak.index_stock_cons_csindex('000888')

In [ ]:
ak.index_stock_cons('000888')

In [ ]:
ak.stock_industry_category_cninfo(symbol="全球行业分类标准")

In [ ]:
ak.stock_industry_change_cninfo(symbol="000001", start_date="20200101", end_date="20250808")

In [ ]:
ak.stock_share_change_cninfo(symbol="002594", start_date="20091227", end_date="20251021")

In [ ]:
ak.stock_profile_cninfo(symbol="600288")

In [ ]:
ak.tool_trade_date_hist_sina()

## 股票市场总貌
### 上海证券交易所
* 目标地址: http://www.sse.com.cn/market/stockdata/statistic/
* 描述: 上海证券交易所-股票数据总貌
* 限量: 单次返回最近交易日的股票数据总貌(当前交易日的数据需要交易所收盘后统计)

In [ ]:
ak.stock_sse_summary()

### 上海证券交易所-每日概况
* 目标地址: http://www.sse.com.cn/market/stockdata/overview/day/
* 描述: 上海证券交易所-数据-股票数据-成交概况-股票成交概况-每日股票情况
* 限量: 单次返回指定日期的每日概况数据, 当前交易日数据需要在收盘后获取; 注意仅支持获取在 20211227（包含）之后的数据

In [ ]:
ak.stock_sse_deal_daily(date="20250730")

### 深圳证券交易所
* 目标地址: http://www.szse.cn/market/overview/index.html
* 描述: 深圳证券交易所-市场总貌-证券类别统计
* 限量: 单次返回指定 date 的市场总貌数据-证券类别统计(当前交易日的数据需要交易所收盘后统计)

In [ ]:
ak.stock_szse_summary(date="20250730")

### 股票行业成交
* 目标地址: http://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
* 描述: 深圳证券交易所-统计资料-股票行业成交数据
* 限量: 单次返回指定 symbol 和 date 的统计资料-股票行业成交数据

In [ ]:
ak.stock_szse_sector_summary(symbol="当年", date="202402")

In [ ]:
df1 = ak.stock_szse_sector_summary(symbol="当年", date="202506").drop('项目名称-英文',axis=1)
df2 = ak.stock_szse_sector_summary(symbol="当年", date="202406").drop('项目名称-英文',axis=1)

In [ ]:
((((df1['成交金额-人民币元']/df1['交易天数']))/100000000)-(((df2['成交金额-人民币元']/df2['交易天数']))/100000000)).round(2)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201301").drop('项目名称-英文',axis=1)

In [ ]:
ak.stock_szse_sector_summary(symbol="当月", date="201701").drop('项目名称-英文',axis=1)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import BytesIO, StringIO

初始化需要修改代码，2018年4月后数据不用修改

In [ ]:
def stock_szse_sector_summary(
    symbol: str = "当月", date: str = "202501"
) -> pd.DataFrame:
    """
    深圳证券交易所-统计资料-股票行业成交数据
    https://docs.static.szse.cn/www/market/periodical/month/W020220511355248518608.html
    :param symbol: choice of {"当月", "当年"}
    :type symbol: str
    :param date: 交易年月
    :type date: str
    :return: 股票行业成交数据
    :rtype: pandas.DataFrame
    """
    url = "https://www.szse.cn/market/periodical/month/index.html"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    tags_list = soup.find_all(name="div", attrs={"class": "g-container"})[1].find_all(
        "script"
    )
    tags_dict = [
        eval(
            item.string[item.string.find("{") : item.string.find("}") + 1]
            .replace("\n", "")
            .replace(" ", "")
            .replace("value", "'value'")
            .replace("text", "'text'")
        )
        for item in tags_list
    ]
    date_url_dict = dict(
        zip(
            [item["text"] for item in tags_dict],
            [item["value"][2:] for item in tags_dict],
        )
    )
    date_format = "-".join([date[:4], date[4:]])
    url = f"https://www.szse.cn/market/periodical/month/{date_url_dict[date_format]}"
    r = requests.get(url)
    r.encoding = "utf8"
    soup = BeautifulSoup(r.text, features="lxml")
    url = [
        item for item in soup.find_all("a") if item.get_text() == "股票行业成交数据"
    ][0]["href"]

    if 'http' in url :
        pass
    else:
        url = 'https://www.szse.cn'+url

    if symbol == "当月":
        r = requests.get(url)
        r.encoding = 'GBK'
        temp_df = pd.read_html(StringIO(r.text), encoding="gbk")[0]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]
    else:
        temp_df = pd.read_html(url, encoding="gbk")[1]
        temp_df.columns = [
            "项目名称",
            "项目名称-英文",
            "交易天数",
            "成交金额-人民币元",
            "成交金额-占总计",
            "成交股数-股数",
            "成交股数-占总计",
            "成交笔数-笔",
            "成交笔数-占总计",
        ]

    temp_df["交易天数"] = pd.to_numeric(temp_df["交易天数"], errors="coerce")
    temp_df["成交金额-人民币元"] = pd.to_numeric(
        temp_df["成交金额-人民币元"], errors="coerce"
    )
    temp_df["成交金额-占总计"] = pd.to_numeric(
        temp_df["成交金额-占总计"], errors="coerce"
    )
    temp_df["成交股数-股数"] = pd.to_numeric(temp_df["成交股数-股数"], errors="coerce")
    temp_df["成交股数-占总计"] = pd.to_numeric(
        temp_df["成交股数-占总计"], errors="coerce"
    )
    temp_df["成交笔数-笔"] = pd.to_numeric(temp_df["成交笔数-笔"], errors="coerce")
    temp_df["成交笔数-占总计"] = pd.to_numeric(
        temp_df["成交笔数-占总计"], errors="coerce"
    )
    return temp_df

In [ ]:
stock_szse_sector_summary(symbol="当月", date="201501")

In [ ]:
gen = (f"{year}{month:02d}" for year in range(2000,2101) for month in range(1,13))

In [ ]:
# 生成2010-2015年所有月份的序列 
ylist = [f"{year}{month:02d}" for year in range(2013, 2025) for month in range(1,13)] + ['202501']

In [ ]:
ddf = []

In [ ]:
for n in ylist:
    df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
    df['日期'] = n
    ddf.append(df)

In [ ]:
dff = pd.concat(ddf)

In [ ]:
dff.set_index('日期')

In [ ]:
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/StockBas')

In [ ]:
dff.set_index('日期').to_sql('szSum', eng, if_exists="replace")

In [ ]:
ddf = pd.DataFrame(columns=[ '日期','项目名称', '交易天数', '成交金额-人民币元', '成交金额-占总计', '成交股数-股数', '成交股数-占总计',
       '成交笔数-笔', '成交笔数-占总计'],dtype='object')

In [ ]:
n = ylist[0]
df = ak.stock_szse_sector_summary(symbol="当月", date= n ).drop('项目名称-英文',axis=1)
df['日期'] = n
# ddf.append(df)
ddf = pd.concat([ddf, df],axis=0,ignore_index=True,copy=False)

### 个股信息查询
#### 1、东财
* 目标地址: http://quote.eastmoney.com/concept/sh603777.html?from=classic
* 描述: 东方财富-个股-股票信息
* 限量: 单次返回指定 symbol 的个股信息

In [ ]:
ak.stock_individual_info_em(symbol="600996")

行情报价

In [ ]:
ak.stock_bid_ask_em(symbol="600996")

### 主营介绍
同花顺
* 目标地址: https://basic.10jqka.com.cn/new/000066/operate.html
* 限量: 单次返回所有数据

In [38]:
ak.stock_zyjs_ths(symbol="000066")

,股票代码,主营业务,产品类型,产品名称,经营范围
0,000066,计算产业、系统装备及其他业务。,计算产业、系统装备,计算产业、系统装备,计算机软件、硬件、终端及其外部设备、网络系统及系统集成、电子产品及零部件、金融机具、税控机具...

#### 主营构成-东财
* 目标地址: https://emweb.securities.eastmoney.com/PC_HSF10/BusinessAnalysis/Index?type=web&code=SH688041#
* 描述: 东方财富网-个股-主营构成
* 限量: 单次返回所有历史数据

In [37]:
ak.stock_zygc_em(symbol="SZ000066")

,股票代码,报告日期,分类类型,主营构成,主营收入,收入比例,主营成本,成本比例,主营利润,利润比例,毛利率
0,000066,2024-12-31,NaN,计算产业,1.070153e+10,0.753483,9.138324e+09,0.760125,1.563204e+09,0.716860,0.146073
1,000066,2024-12-31,NaN,系统装备,2.683068e+09,0.188912,2.312758e+09,0.192375,3.703103e+08,0.169818,0.138017
2,000066,2024-12-31,NaN,其他,8.181567e+08,0.057606,5.710450e+08,0.047499,2.471117e+08,0.113321,0.302035
3,000066,2024-12-31,按产品分类,计算产业,1.070153e+10,0.753483,9.138324e+09,0.760125,1.563204e+09,0.716860,0.146073
4,000066,2024-12-31,按产品分类,系统装备,2.683068e+09,0.188912,2.312758e+09,0.192375,3.703103e+08,0.169818,0.138017
...,...,...,...,...,...,...,...,...,...,...,...
195,000066,2019-06-30,按产品分类,园区及物业服务,3.171339e+07,0.007324,1.721776e+07,0.005057,1.449564e+07,0.015661,0.457082
196,000066,2019-06-30,按产品分类,其他,1.066304e+06,0.000246,1.552112e+06,0.000456,-4.858084e+05,-0.000525,-0.455600
197,000066,2019-06-30,按地区分类,国内,3.226267e+09,0.745056,2.466162e+09,0.724354,7.601056e+08,0.821204,0.235599
198,000066,2019-06-30,按地区分类,其他(补充),4.305256e+08,0.099423,3.604920e+08,0.105883,7.003362e+07,0.075663,0.162670
199,000066,2019-06-30,按地区分类,日本及其他,2.627162e+08,0.060670,2.413414e+08,0.070886,2.137475e+07,0.023093,0.081361

实时行情数据-东财 沪深京A stock_zh_a_spot_em()

沪A股  _sh_
        深A股 _sz_
        京A股 _bj_
        新股 _new_  
        创业板 _cy_  
        科创板 _kc_

In [ ]:
ak.stock_zh_a_spot_em()

 单次返回指定股票最近一个交易日的分时数据, 包含盘前数据

In [ ]:
ak.stock_intraday_em(symbol="000409")

In [ ]:
ak.stock_intraday_em(symbol="000409").groupby('买卖盘性质').sum()

目标地址: https://data.eastmoney.com/gsrl/gsdt.html
公司动态

In [ ]:
ak.stock_gsrl_gsdt_em(date="20250211")

沪深新股
目标地址: https://quote.eastmoney.com/center/gridlist.html#newshares

In [ ]:
ak.stock_zh_a_new_em()

机构调研http://data.eastmoney.com/jgdy/tj.html
http://data.eastmoney.com/jgdy/xx.html

单次返回所有历史数据

In [ ]:
ak.stock_jgdy_tj_em(date="20210128")

In [ ]:
ak.stock_jgdy_detail_em(date="20241211")

In [ ]:
ak.stock_zyjs_ths(symbol="600996")

In [ ]:
ak.stock_zygc_em(symbol="SH600996")

In [ ]:
ak.stock_zygc_ym(symbol="000001")

上市公司质押比例
目标地址: https://data.eastmoney.com/gpzy/pledgeRatio.aspx 查询具体交易日

重要股东股权质押明细 https://data.eastmoney.com/gpzy/pledgeDetail.aspx

In [ ]:
ak.stock_gpzy_pledge_ratio_em(date="20250207")

In [ ]:
ak.stock_gpzy_pledge_ratio_detail_em()

In [ ]:
def calculate_alert_liquidation_price(initial_price, pledge_rate, interest_rate, alert_ratio=1.6, liquidation_ratio=1.4):
    """
    initial_price: 初始股价（元）
    pledge_rate: 质押率（0-1）
    interest_rate: 融资利率（年化，0-1）
    alert_ratio: 预警线系数（默认160%）
    liquidation_ratio: 平仓线系数（默认140%）
    """
    factor = initial_price * pledge_rate * (1 + interest_rate)
    alert_price = factor * alert_ratio
    liquidation_price = factor * liquidation_ratio
    return alert_price, liquidation_price

In [ ]:
calculate_alert_liquidation_price(8.2, 0.4999, 0.06)

个股商誉明细 目标地址: https://data.eastmoney.com/sy/list.html

行业商誉 目标地址: https://data.eastmoney.com/sy/hylist.html

In [ ]:
ak.stock_sy_em(date="20221231")

In [ ]:
ak.stock_sy_hy_em(date="20231231")

分析师指数 目标地址: https://data.eastmoney.com/invest/invest/list.html
 分析师详情 https://data.eastmoney.com/invest/invest/11000257131.html

In [ ]:
ak.stock_analyst_rank_em()

In [ ]:
ak.stock_analyst_detail_em(analyst_id="11000280036", indicator="最新跟踪成分股")

千股千评 目标地址: https://data.eastmoney.com/stockcomment/

In [ ]:
ak.stock_comment_em()

In [ ]:
ak.stock_comment_detail_zlkp_jgcyd_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_zhpj_lspf_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_scrd_focus_em(symbol="600996")

In [ ]:
ak.stock_comment_detail_scrd_desire_daily_em(symbol="600996")

停复牌信息

In [ ]:
ak.stock_tfp_em()

个股新闻 目标地址: https://so.eastmoney.com/news/s
财经内容精选 目标地址: https://cxdata.caixin.com/pc/

In [ ]:
ak.stock_news_em(symbol="600996")

In [ ]:
ak.stock_news_main_cx()

年报季报 目标地址: http://data.eastmoney.com/bbsj/202412/yjbb.html

date="20200331"; choice of {"0331一季报", "0630中报", "0930三季报", "1231年报"}; 从 20100331 开始

In [ ]:
ak.stock_yjbb_em(date="20241231")

In [ ]:
ak.stock_yjkb_em(date="20241231")

In [ ]:
ak.stock_yjyg_em(date="20241231")

预约披露时间-东方财富

In [ ]:
ak.stock_yysj_em(symbol="沪深A股", date="20241231")

预约披露时间-巨潮资讯 目标地址: http://www.cninfo.com.cn/new/commonUrl?url=data/yypl

period="2021年报"; 近四期的财务报告; e.g., choice of {"2021一季", "2021半年报", "2021三季", "2021年报"}

In [ ]:
ak.stock_report_disclosure(market="沪深京", period="2024年报")

上市公司行业归属的变动情况-巨潮资讯

In [ ]:
ak.stock_industry_change_cninfo(symbol="002594", start_date="20050101", end_date="20250212")

公司股本变动-巨潮资讯

In [ ]:
fd = ak.stock_share_change_cninfo(symbol="600996", start_date="20050101", end_date="20250212")

In [ ]:
df = ak.stock_profile_cninfo(symbol="600996")

高管持股

In [ ]:
ak.stock_ggcg_em(symbol="全部")

分红配送

In [ ]:
ak.stock_fhps_em(date="20241231")

In [ ]:
ak.stock_fhps_detail_em(symbol="600409")

In [ ]:
ak.stock_fhps_detail_ths(symbol="600409")

资金流向 

symbol="即时"; choice of {“即时”, "3日排行", "5日排行", "10日排行", "20日排行"}

个股资金流：individual  概念资金流：concept 行业资金流：industry

In [ ]:
ak.stock_fund_flow_individual(symbol="即时")

筹码分布 adjust=""; choice of {"qfq": "前复权", "hfq": "后复权", "": "不复权"}

In [ ]:
ak.stock_cyq_em(symbol="600996", adjust="")

个股研报

In [ ]:
ak.stock_research_report_em(symbol="600409")

股东户数

In [ ]:
ak.stock_zh_a_gdhs(symbol="20241231")

In [ ]:
ak.stock_zh_a_gdhs_detail_em(symbol="600996")

限售股解禁详情

In [ ]:
ak.stock_restricted_release_detail_em(start_date="20240326", end_date="20250212")

股票列表-A股 目标地址: 沪深京三个交易所

In [ ]:
ak.stock_info_a_code_name()

symbol="主板A股"; choice of {"主板A股", "主板B股", "科创板"}

In [ ]:
ak.stock_info_sh_name_code(symbol="主板A股")

symbol="A股列表"; choice of {"A股列表", "B股列表", "CDR列表", "AB股列表"}

In [ ]:
ak.stock_info_sz_name_code(symbol="A股列表")

In [ ]:
ak.stock_info_bj_name_code()

### 暂停/终止上市
* 上证
* symbol="全部"; choice of {"全部", "沪市", "科创板"}

In [ ]:
ak.stock_info_sh_delist(symbol="全部")

#### 终止/暂停上市
* 深证
* symbol="终止上市公司"; choice of {"暂停上市公司", "终止上市公司"}

In [ ]:
ak.stock_info_sz_delist(symbol="终止上市公司")

两网及退市

In [ ]:
ak.stock_staq_net_stop()

### 股票更名

In [ ]:
ak.stock_info_change_name(symbol="600008")

* 深证
* symbol="全称变更"; choice of {"全称变更", "简称变更"}

In [ ]:
ak.stock_info_sz_change_name(symbol="全称变更")

symbol="证监会行业分类"; choice of {"证监会行业分类", "国证行业分类"}

In [ ]:
ak.stock_industry_pe_ratio_cninfo(symbol="证监会行业分类", date="20250212")

In [ ]:
ak.stock_hold_num_cninfo(date="20240930")

实际控制人持股变动

symbol="全部"; choice of {"单独控制", "实际控制人", "一致行动人", "家族控制", "全部"}; 从 2010 开始

In [ ]:
ak.stock_hold_control_cninfo(symbol="全部")

对外担保 symbol="全部"; choice of {"全部", "深市主板", "沪市", "创业板", "科创板"}

In [ ]:
ak.stock_cg_guarantee_cninfo(symbol="全部", start_date="20240601", end_date="20250212")

股权质押

In [ ]:
ak.stock_cg_equity_mortgage_cninfo(date="20250212")

A 股个股指标
symbol="000001"; 参见 ak.stock_a_indicator_lg(symbol="all") 获取股票代码

pe	市盈率
pe_ttm	市盈率TTM
pb		市净率
ps	市销率
ps_ttm	市销率TTM
dv_ratio		股息率
dv_ttm		股息率TTM
total_mv		总市值

In [ ]:
ak.stock_a_indicator_lg(symbol="600409")

A 股股息率 symbol="上证A股"; choice of {"上证A股", "深证A股", "创业板", "科创板"}

In [ ]:
ak.stock_a_gxl_lg(symbol="深证A股")

大盘拥挤度

In [ ]:
ak.stock_a_congestion_lg()

股债利差

In [ ]:
ak.stock_ebs_lg()

A 股等权重与中位数市盈率

In [ ]:
ak.stock_a_ttm_lyr()

A 股等权重与中位数市净率

In [ ]:
ak.stock_a_all_pb()

主板市盈率 symbol="上证"; choice of {"上证", "深证", "创业板", "科创版"}

In [ ]:
ak.stock_market_pe_lg(symbol="上证")

指数市盈率symbol="上证50"; choice of {"上证50", "沪深300", "上证380", "创业板50", "中证500", "上证180", "深证红利", "深证100", "中证1000", "上证红利", "中证100", "中证800"}

In [ ]:
ak.stock_index_pe_lg(symbol="上证50")

主板市净率 symbol="上证"; choice of {"上证", "深证", "创业板", "科创版"}

In [ ]:
ak.stock_market_pb_lg(symbol="上证")

In [ ]:
ak.stock_index_pb_lg(symbol="上证50")

个股估值

In [ ]:
ak.stock_value_em(symbol="300766")

创新高和新低的股票数量 symbol="all"; {"all": "全部A股", "sz50": "上证50", "hs300": "沪深300", "zz500": "中证500"}

In [ ]:
ak.stock_a_high_low_statistics(symbol="zz500")

破净股统计 symbol="全部A股"; choice of {"全部A股", "沪深300", "上证50", "中证500"}

In [ ]:
ak.stock_a_below_net_asset_statistics(symbol="全部A股")

In [ ]:
ak.stock_report_fund_hold(symbol="基金持仓", date="20241231")

机构买卖每日统计 
机构席位追踪 symbol="近一月"; choice of {"近一月", "近三月", "近六月", "近一年"}

In [ ]:
ak.stock_lhb_jgmmtj_em(start_date="20250101", end_date="20250212")

In [ ]:
ak.stock_lhb_jgstatistic_em(symbol="近一月")

活跃 A 股统计 symbol='近三月'; choice of {'近一月', '近三月', '近六月', '近一年'}

In [ ]:
ak.stock_dzjy_hygtj(symbol='近三月')

融资融券汇总

标的证券名单及保证金比例查询

In [ ]:
ak.stock_margin_ratio_pa(date="20250213")

In [ ]:
ak.stock_margin_account_info()

In [ ]:
ak.stock_margin_sse(start_date="20250212", end_date="20250212")

In [ ]:
ak.stock_margin_szse(date="20250212")

In [ ]:
ak.stock_margin_detail_sse(date="20250212")

In [ ]:
ak.stock_margin_detail_szse(date="20250212")

In [ ]:
ak.stock_margin_underlying_info_szse(date="20250212")

盈利预测-东方财富  symbol="", 默认为获取全部数据; symbol="船舶制造", 则获取具体行业板块的数据; 行业板块可以通过 ak.stock_board_industry_name_em() 接口获取

In [ ]:
ak.stock_profit_forecast_em()

indicator="预测年报每股收益"; choice of {"预测年报每股收益", "预测年报净利润", "业绩预测详表-机构", "业绩预测详表-详细指标预测"}

In [ ]:
ak.stock_profit_forecast_ths(symbol="600519", indicator="预测年报每股收益")

### 概念板块
* 同花顺

In [ ]:
ak.stock_board_concept_name_ths()

* 东方财富

In [ ]:
ak.stock_board_concept_name_em()

东方财富-成份股 symbol="车联网"; 可以通过调用 ak.stock_board_concept_name_em() 查看东方财富-概念板块的所有行业名称

In [ ]:
ak.stock_board_concept_cons_em(symbol="高带宽内存")

东方财富-指数 symbol="长寿药"; 可以通过调用 ak.stock_board_concept_name_em() 查看东方财富-概念板块的所有概念代码
 
 period="5"; choice of {"1", "5", "15", "30", "60"}

In [ ]:
ak.stock_board_concept_hist_em(symbol="高带宽内存", period="daily", start_date="20220101", end_date="20250212", adjust="")

### 行业板块
* 同花顺

In [ ]:
ak.stock_board_industry_summary_ths()

* 东方财富

In [ ]:
ak.stock_board_industry_name_em()

东方财富-成份股

In [ ]:
ak.stock_board_industry_cons_em(symbol="电机")

In [ ]:
ak.stock_board_industry_hist_em(symbol="小金属", start_date="20211201", end_date="20250212", period="日k", adjust="")

同花顺  行业板块

In [ ]:
ak.stock_board_industry_summary_ths()

In [ ]:
ak.stock_board_industry_index_ths(symbol="元件", start_date="20240101", end_date="20250212")

股票热度 关注 讨论 交易

关注排行榜 symbol="最热门"; choice of {"本周新增", "最热门"}

In [ ]:
ak.stock_hot_follow_xq(symbol="最热门")

In [ ]:
ak.stock_hot_tweet_xq(symbol="最热门")

In [ ]:
ak.stock_hot_deal_xq(symbol="最热门")

问财

In [ ]:
ak.stock_hot_rank_wc(date="20250212")

东财 单次返回当前交易日前 100 个股票的人气排名数据

In [ ]:
ak.stock_hot_rank_em()

飙升榜-A股

In [ ]:
ak.stock_hot_up_em()

历史趋势及粉丝特征

In [ ]:
ak.stock_hot_rank_detail_em(symbol="SH600996")

热门关键词

In [ ]:
ak.stock_hot_keyword_em(symbol="SH600996")

内部交易

In [ ]:
ak.stock_inner_trade_xq()

热搜股票 time="今日"; choice of {"今日", "1小时"}

In [ ]:
ak.stock_hot_search_baidu(symbol="A股", date="20240213", time="今日")

强势股池

In [ ]:
ak.stock_zt_pool_strong_em(date='20250206')

In [ ]:
ak.stock_zt_pool_sub_new_em(date='20250123')

In [ ]:
ak.stock_info_cjzc_em()

In [ ]:
ak.stock_info_global_em()

In [ ]:
ak.stock_info_global_sina()

In [ ]:
ak.stock_info_global_futu()

In [ ]:
ak.stock_info_global_ths()

In [ ]:
ak.stock_info_global_cls(symbol="全部")

技术指标 symbol="创月新高"; choice of {"创月新高", "半年新高", "一年新高", "历史新高"}

创新高cxg 创新低cxd 

连续上涨lxsz 连续下跌lxxd 持续放量cxfl 持续缩量cxsl 向上突破xstp 向下突破xxtp 量价齐升ljqs 量价齐跌ljqd 险资举牌xzjp

In [ ]:
ak.stock_rank_cxg_ths(symbol="创月新高")

In [ ]:
ak.stock_rank_cxd_ths(symbol="创月新低")

In [ ]:
ak.stock_rank_lxsz_ths()

In [ ]:
ak.stock_rank_cxfl_ths()

In [ ]:
ak.stock_rank_cxsl_ths()

In [ ]:
ak.stock_rank_xzjp_ths()

ESG评级

In [ ]:
ak.stock_esg_rate_sina()

In [ ]:
ak.stock_esg_msci_sina()

In [ ]:
ak.stock_esg_rft_sina()

In [ ]:
ak.stock_esg_zd_sina()

In [ ]:
ak.stock_esg_hz_sina()

A股股票指数数据 symbol="上证系列指数"；choice of {"沪深重要指数", "上证系列指数", "深证系列指数", "指数成份", "中证系列指数"}

In [ ]:
ak.stock_zh_index_spot_em(symbol="中证系列指数")

历史行情数据-东方财富 period="daily"; choice of {'daily', 'weekly', 'monthly'}

In [ ]:
ak.index_zh_a_hist(symbol="931144", period="daily", start_date="20250212", end_date="20250212")

中国股票指数成份

In [ ]:
ak.index_stock_info()

In [ ]:
ak.index_stock_cons(symbol="000300")

In [ ]:
ak.index_stock_cons_csindex(symbol="000300")

In [ ]:
ak.sw_index_first_info()

In [ ]:
ak.sw_index_second_info()

In [ ]:
ak.sw_index_third_info()

申万三级行业成份 symbol="850111.SI"; 行业代码; 可以通过 ak.sw_index_third_info() 获取所有行业代码

In [ ]:
ak.sw_index_third_cons(symbol="859822.SI")

In [ ]:
ak.drewry_wci_index(symbol="composite")

In [ ]:
ak.index_neaw_cx()

汽车销量排行

In [ ]:
ak.car_market_cate_cpca(symbol="占比", indicator="零售")

In [ ]:
ak.car_market_cate_cpca(symbol="轿车", indicator="零售")

盖世研究院 symbol="车型榜"; choice of {"车企榜", "品牌榜", "车型榜"}

In [ ]:
ak.car_sale_rank_gasgoo(symbol="车企榜", date="202412")

In [ ]:
ak.car_sale_rank_gasgoo(symbol="品牌榜", date="202412")

In [ ]:
ak.car_sale_rank_gasgoo(symbol="车型榜", date="202412")

电影票房

In [ ]:
ak.movie_boxoffice_realtime()

In [ ]:
ak.movie_boxoffice_daily(date="20250201")

In [ ]:
ak.movie_boxoffice_yearly(date="2025")

In [ ]:
ak.video_tv()

In [ ]:
ak.video_variety_show()

In [ ]:
ak.business_value_artist()

In [ ]:
ak.online_value_artist()

微博舆情报告 time_period="CNHOUR12"

CNHOUR2	2小时
CNHOUR6	6小时
CNHOUR12	12小时
CNHOUR24	1天
CNDAY7	1周
CNDAY30	1月

In [ ]:
ak.stock_js_weibo_report(time_period="CNHOUR24")

In [ ]:
df = ak.index_news_sentiment_scope()

In [ ]:
df

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(df.tail(100), x='日期', y='市场情绪指数',)
fig.show()

In [ ]:
fig = px.line(df.tail(100), x='日期', y='沪深300指数',)
fig.show()

In [ ]:
ak.index_analysis_weekly_sw(symbol="市场表征", date="20250228")

In [ ]:
dfg = ak.macro_cons_gold()

In [ ]:
from datetime import datetime, date

dfgg = dfg[dfg['日期'] >= datetime.strptime('2016-12-19',  "%Y-%m-%d").date()]

In [ ]:
fig = px.line(dfgg, x='日期', y='总库存',)
fig.show()

In [ ]:
dfd = ak.spot_hist_sge(symbol='Au99.99')

In [ ]:
fig = px.line(dfd, x='date', y='close',)
fig.show()