In [1]:
import pandas as pd

In [2]:
dfs = pd.DataFrame(columns=['IndexCode', 'IndexName','IndexSTL', 'Num', 'From'])
dfi =pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsConsBLK.xlsx',dtype={'IndexCode':object})

In [5]:
dfs = dfi[['IndexCode','IndexName','IndexSTL']].drop_duplicates().reset_index(drop=True)

In [7]:
n = 0
while n < dfs.shape[0]:
    dfs.loc[n,'Num'] = len(dfi.groupby('IndexCode').groups[dfs.iloc[n,0]])
    n = n + 1

In [1]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
eapi =  TdxExHq_API()
api = TdxHq_API()

In [2]:
api.connect('180.153.18.170', 7709)

In [11]:
api.to_df(api.get_index_bars(9, 1, '950081', 0, 1))

  value
0  None

In [21]:
eapi.connect('47.112.95.207', 7720)

In [22]:
eapi.to_df(eapi.get_instrument_bars(9, 62, '000938', 0, 10))

Empty DataFrame
Columns: []
Index: []