##### 分红派息

In [1]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import plotly.express as px

/home/ts/.local/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py:15: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
# engS = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/qfqStock')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [3]:
StockList = pd.read_sql('StocksList', engS)

* 历史股息

In [ ]:
ak.stock_history_dividend()

* 各股历史股息详情

In [ ]:
ak.stock_fhps_detail_ths(symbol="000550")

* 个股最新详情

In [5]:
df = ak.stock_individual_spot_xq(symbol="SZ000001")

In [13]:
df

        item                value
0         代码             SZ000001
1      52周最高              13.0581
2        流通股          19405600653
3         跌停                 9.96
4         最高                11.09
5        流通值       213267551176.0
6     最小交易单位                  100
7         涨跌                -0.08
8       每股收益                 2.22
9         昨收                11.07
10       成交量            110999429
11       周转率                 0.57
12     52周最低               9.9526
13        名称                 平安银行
14       交易所                   SZ
15    市盈率(动)                4.172
16  基金份额/总股本          19405918198
17   净资产中的商誉             1.461201
18        均价               11.035
19        涨幅                -0.72
20        振幅                 0.99
21        现价                10.99
22    今年以来涨幅                -3.68
23      发行日期  1991-04-03 00:00:00
24        最低                10.98
25  资产净值/总市值       213271040996.0
26   股息(TTM)                0.598
27  股息率(TTM)                5.441
28        货币                  CNY
29     每股净资产                23.08
30    市盈率(静)                4.792
31       成交额        1224886435.95
32       市净率                0.476
33        涨停                12.18
34  市盈率(TTM)                4.946
35        时间  2026-01-23 15:04:45
36        今开                11.07

In [4]:
"SZ" + StockList['code'].tolist()[:3][0]

'SZ000001'

In [7]:
ls = []
for n in tqdm(StockList['code'].tolist()[:3]):
    dfs = ak.stock_individual_spot_xq(symbol="SZ"+n)
    ls.append(dfs)
    
rows = []
for df in ls:
    # 将 item-value 转为 dict，再转为 Series 或 dict
    row = df.set_index('item')['value'].to_dict()
    rows.append(row)

# 合并为新 DataFrame
result = pd.DataFrame(rows)

100%|██████████| 3/3 [00:00<00:00,  3.02it/s]

In [16]:
result[['代码', '名称','52周最高', '52周最低', '昨收','均价', '今年以来涨幅','每股收益',  '每股净资产','流通股','流通值', '基金份额/总股本', '资产净值/总市值','净资产中的商誉', '市盈率(动)','市净率', '市盈率(TTM)','市盈率(静)','股息(TTM)','股息率(TTM)',  '发行日期', '时间']]

,代码,名称,52周最高,52周最低,昨收,均价,今年以来涨幅,每股收益,每股净资产,流通股,...,资产净值/总市值,净资产中的商誉,市盈率(动),市净率,市盈率(TTM),市盈率(静),股息(TTM),股息率(TTM),发行日期,时间
0,SZ000001,平安银行,13.0581,9.9526,11.07,11.035,-3.68,2.22,23.0800,19405600653,...,2.132710e+11,1.461201,4.172,0.476,4.946,4.792,0.598,5.441,1991-04-03 00:00:00,2026-01-23 15:04:45
1,SZ000002,万科A,8.2200,4.6200,4.95,4.922,6.45,-4.99,14.7314,9716399629,...,5.905701e+10,3.247993,-1.565,0.336,-0.992,-1.182,NaN,NaN,1991-01-29 00:00:00,2026-01-23 15:04:45
2,SZ000004,*ST国华,14.5900,7.1900,11.99,12.461,13.63,-0.93,0.2791,126287768,...,1.666668e+09,1.952485,-45.591,45.109,-13.572,-12.520,NaN,NaN,1990-12-01 00:00:00,2026-01-23 15:04:45