In [1]:
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import numpy as np
from typing import Dict, List, Tuple

from scipy.stats import zscore
from scipy.stats.mstats import winsorize

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


import warnings
warnings.filterwarnings("ignore")

In [2]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [112]:
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [113]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [128]:
StockList

        code     name
0     000001     平安银行
1     000002      万科A
2     000004    *ST国华
3     000006     深振业A
4     000007      全新好
...      ...      ...
5178  688807     优迅股份
5179  688809     强一股份
5180  688819     天能股份
5181  688981     中芯国际
5182  689009  九号公司-WD

[5183 rows x 2 columns]

In [124]:
n = 50

In [125]:
Fai.append(n)

In [126]:
Fai

[0, 50]

In [127]:
StockList.iloc[Fai]

      code  name
0   000001  平安银行
50  000090  天健集团

In [88]:
df_biz = pd.read_sql('mBiz', engB)

In [83]:
StockICRAW = pd.read_sql('akStockIC', engB)
#申万分类
StockIC = StockICRAW[StockICRAW['ICSCode']=='008003']

In [28]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(行业|产品|业务)'))].groupby('项目名').size().reset_index(name='count').sort_values(by='count', ascending=False).to_excel('./行业_产品_业务.xlsx', index=False)

In [100]:
bizDF = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].drop_duplicates(subset=['StockCode', '项目名']).drop_duplicates(subset=['StockCode'], keep='first')

In [79]:
bizDF['产品'] = bizDF['项目名'].str.replace('（产品）', '', regex=False).str.replace('(产品)', '', regex=False)

In [101]:
# 2. 将“营业收入(元)”中含“万”的数值转换为亿元单位
def convert_to_yi_yuan(value):
    if pd.isna(value):
        return value
    value = str(value).strip()
    if '万' in value:
        # 去掉“万”，转为 float，再除以 10000 得到“亿元”
        num = float(value.replace('万', '').replace(',', ''))
        return num / 10000  # 万元 → 亿元
    else:
        # 如果没有“万”，假设已经是“元”，则除以 1e8 转为亿元
        try:
            num = float(value.replace('亿', '').replace(',', ''))
            return num
        except ValueError:
            return value  # 无法转换的保留原值（如非数字）

In [102]:
bizDF['营业收入(亿元)'] = bizDF['营业收入(元)'].apply(convert_to_yi_yuan).round(3)

In [103]:
df = bizDF[['StockCode', '项目名','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)']]

In [90]:
df_biz

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
0,2025-06-30,000001,平安银行,总部(地区),401.52亿,57.87,295.37亿,59.61,73.56
1,2025-06-30,000001,平安银行,南区(地区),100.43亿,14.47,72.09亿,14.55,71.78
2,2025-06-30,000001,平安银行,东区(地区),95.88亿,13.82,67.41亿,13.60,70.31
3,2025-06-30,000001,平安银行,北区(地区),64.04亿,9.23,40.15亿,8.10,62.70
4,2025-06-30,000001,平安银行,西区(地区),26.43亿,3.81,16.27亿,3.28,61.56
...,...,...,...,...,...,...,...,...,...
168736,2024-06-30,689009,九号公司-WD,其他产品(产品),1.13亿,1.69,4008.34万,1.97,35.60
168737,2024-06-30,689009,九号公司-WD,中国大陆境内(地区),38.63亿,57.95,9.57亿,47.13,24.76
168738,2024-06-30,689009,九号公司-WD,中国大陆境外(地区),28.03亿,42.05,10.73亿,52.87,38.29
168739,2024-06-30,689009,九号公司-WD,自主品牌销售(销售模式),58.60亿,87.91,17.36亿,85.54,29.63
168740,2024-06-30,689009,九号公司-WD,B及定制产品销售(销售模式),8.06亿,12.09,2.94亿,14.46,36.43

In [110]:
df_biz[(df_biz['StockCode']=='600580')]

Empty DataFrame
Columns: [日期, StockCode, StockName, 项目名, 营业收入(元), 收入比例(%), 营业利润(元), 利润比例(%), 毛利率(%)]
Index: []

In [58]:
df_biz[(df_biz['StockCode']=='688793') &(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品)'))].drop_duplicates(subset=['StockCode', '项目名'])

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
168508,2025-06-30,688793,倍轻松,其他(产品),9332.36万,24.24,5506.08万,22.84,59.00
168509,2025-06-30,688793,倍轻松,肩部(产品),8478.31万,22.03,5276.32万,21.89,62.23
168510,2025-06-30,688793,倍轻松,头部+头皮(产品),6965.61万,18.10,4629.16万,19.20,66.46
168511,2025-06-30,688793,倍轻松,眼部(产品),5034.82万,13.08,3156.54万,13.09,62.69
168512,2025-06-30,688793,倍轻松,腰背部(产品),4614.22万,11.99,2874.99万,11.93,62.31
168513,2025-06-30,688793,倍轻松,颈部(产品),4068.40万,10.57,2665.44万,11.06,65.52
168519,2024-12-31,688793,倍轻松,头皮+头部(产品),2.38亿,21.91,1.60亿,24.37,67.37
168520,2024-12-31,688793,倍轻松,主营业务:其他(产品),1.29亿,11.86,5530.71万,8.41,42.98

In [105]:
StockIC.merge(df, left_on='StockCode', right_on='StockCode',how='left')

,StockCode,StockName,ICS,DP,IC4,IC3,IC2,IC1,ICode,ICSCode,项目名,营业收入(亿元),收入比例(%),利润比例(%),毛利率(%)
0,600000,浦发银行,申银万国行业分类标准,2021-07-30,股份制银行Ⅲ,股份制银行Ⅲ,股份制银行Ⅱ,银行,S480301,008003,NaN,NaN,NaN,NaN,NaN
1,600004,白云机场,申银万国行业分类标准,2021-07-30,机场,机场,航空机场,交通运输,S421002,008003,航空服务(产品),30.21,81.08,72.20,25.69
2,600006,东风股份,申银万国行业分类标准,2021-07-30,商用载货车,商用载货车,商用车,汽车,S280601,008003,汽车制造业(行业),108.92,99.59,84.95,1.51
3,600007,中国国贸,申银万国行业分类标准,2021-07-30,商业地产,商业地产,房地产开发,房地产,S430102,008003,物业租赁及管理(行业),33.86,86.56,98.32,66.04
4,600008,首创环保,申银万国行业分类标准,2021-07-30,水务及水治理,水务及水治理,环境治理,环保,S760102,008003,污水水处理业务(行业),66.06,32.95,37.47,39.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5149,301658,首航新能,申银万国行业分类标准,2025-03-14,逆变器,逆变器,光伏设备,电力设备,S630503,008003,光伏行业(行业),11.09,99.66,99.34,30.17
5150,301662,宏工科技,申银万国行业分类标准,2025-03-28,锂电专用设备,锂电专用设备,电池,电力设备,S630703,008003,锂电池产线及设备(产品),6.88,90.77,87.83,26.60
5151,301665,泰禾股份,申银万国行业分类标准,2025-03-20,农药,农药,农化制品,基础化工,S220803,008003,除草剂(产品),10.41,43.14,36.24,22.16
5152,301678,新恒汇,申银万国行业分类标准,2025-05-30,半导体材料,半导体材料,半导体,电子,S270103,008003,智能卡业务(业务),2.83,59.74,81.97,41.48
5153,302132,中航成飞,申银万国行业分类标准,2021-07-30,军工电子Ⅲ,军工电子Ⅲ,军工电子Ⅱ,国防军工,S650501,008003,航空产品(产品),199.43,96.33,84.09,7.77