In [13]:
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import numpy as np
from typing import Dict, List, Tuple

from scipy.stats import zscore
from scipy.stats.mstats import winsorize

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


import warnings
warnings.filterwarnings("ignore")

In [14]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [5]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [128]:
StockList

        code     name
0     000001     平安银行
1     000002      万科A
2     000004    *ST国华
3     000006     深振业A
4     000007      全新好
...      ...      ...
5178  688807     优迅股份
5179  688809     强一股份
5180  688819     天能股份
5181  688981     中芯国际
5182  689009  九号公司-WD

[5183 rows x 2 columns]

In [11]:
df_biz = pd.read_sql('mBiz', engB)

In [ ]:
df_biz[(df_biz['项目名'].str.endswith('(自营)'))]

In [15]:
dddf  =  df_biz[~df_biz['项目名'].astype(str).str.endswith('地区)|模式)')]
dddf['收入比例(%)'] = pd.to_numeric(dddf['收入比例(%)'], errors='coerce')
ffd = dddf.sort_values(by = '收入比例(%)', ascending=False).drop_duplicates(subset='StockCode',keep='first')

In [ ]:
ffd

In [8]:
StockICRAW = pd.read_sql('akStockIC', engB)
#申万分类
StockIC = StockICRAW[StockICRAW['ICSCode']=='008003']

In [ ]:
df_biz.info()

In [28]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(行业|产品|业务)'))].groupby('项目名').size().reset_index(name='count').sort_values(by='count', ascending=False).to_excel('./行业_产品_业务.xlsx', index=False)

In [25]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False]).drop_duplicates(subset=['StockCode'], keep='first')

In [36]:
ddf = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False])

In [ ]:
df_biz[~df_biz['项目名'].astype(str).str.contains('地区|销售模式')]

In [ ]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & ~df_biz['项目名'].str.contains(r[()())]

In [ ]:
bizDF = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False]).drop_duplicates(subset=['StockCode'], keep='first')

In [91]:
bizDF = ffd.copy()

In [62]:
bizDF['产品'] = bizDF['项目名'].str.replace('（产品）', '', regex=False).str.replace('(产品)', '', regex=False)

In [63]:
# 2. 将“营业收入(元)”中含“万”的数值转换为亿元单位
def convert_to_yi_yuan(value):
    if pd.isna(value):
        return value
    value = str(value).strip()
    if '万' in value:
        # 去掉“万”，转为 float，再除以 10000 得到“亿元”
        num = float(value.replace('万', '').replace(',', ''))
        return num / 10000  # 万元 → 亿元
    else:
        # 如果没有“万”，假设已经是“元”，则除以 1e8 转为亿元
        try:
            num = float(value.replace('亿', '').replace(',', ''))
            return num
        except ValueError:
            return value  # 无法转换的保留原值（如非数字）

In [100]:
bizDF['营业收入(亿元)'] = bizDF['营业收入(元)'].apply(convert_to_yi_yuan).round(3)
df = bizDF[['StockCode', '项目名','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)','日期']]

In [90]:
df_biz

In [80]:
df_biz[(df_biz['StockCode']=='600007')].sort_values(by='收入比例(%)', ascending=False)

In [78]:
dddf[(dddf['StockCode']=='600007')].sort_values(by='收入比例(%)', ascending=False)

In [41]:
df_biz[(df_biz['StockCode']=='688306') &(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品)'))].drop_duplicates(subset=['StockCode', '项目名'])

In [101]:
stdf = StockIC.merge(df, left_on='StockCode', right_on='StockCode',how='left')[['日期','StockCode','StockName','IC4','项目名','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)']]

In [102]:
stdf['IC4'].drop_duplicates()

0       股份制银行Ⅲ
1           机场
2        商用载货车
3         商业地产
4       水务及水治理
         ...
3382    其他能源发电
3471        白银
3627      宠物食品
4147      视频媒体
4688    纺织鞋类制造
Name: IC4, Length: 337, dtype: object

In [107]:
stdf[stdf['IC4']=='航空装备Ⅲ']

,日期,StockCode,StockName,IC4,项目名,营业收入(亿元),收入比例(%),利润比例(%),毛利率(%)
30,2025-06-30,600038,中直股份,航空装备Ⅲ,航空产品(产品),101.800,99.41,98.05,6.20
235,2025-06-30,600316,洪都航空,航空装备Ⅲ,关联方(其他),15.220,99.91,99.72,4.03
280,2022-12-31,600372,中航机载,航空装备Ⅲ,飞机制造业(行业),103.600,92.61,90.96,30.98
295,2024-12-31,600391,航发科技,航空装备Ⅲ,制造业(行业),37.800,98.17,90.69,14.86
582,2025-06-30,600760,中航沈飞,航空装备Ⅲ,航空产品(产品),145.390,99.39,99.41,12.26
586,2024-06-30,600765,中航重机,航空装备Ⅲ,锻铸分部(产品),53.820,98.36,None,None
663,2024-06-30,600862,中航高科,航空装备Ⅲ,航空新材料分部(业务),25.180,98.88,99.07,37.32
690,2024-12-31,600893,航发动力,航空装备Ⅲ,制造业(行业),471.680,98.51,98.12,10.02
1188,2024-12-31,603261,*ST立航,航空装备Ⅲ,航空产品(产品),2.900,100.00,100.00,6.21
1619,2024-12-31,605123,派克新材,航空装备Ⅲ,锻造行业(行业),27.950,87.00,93.45,20.06
1755,2024-12-31,688070,纵横股份,航空装备Ⅲ,工业无人机(行业),4.740,100.00,100.00,42.20
1803,2024-12-31,688122,西部超导,航空装备Ⅲ,有色金属冶炼及压延加工(行业),43.830,95.02,98.93,34.93
1904,2024-12-31,688237,超卓航科,航空装备Ⅲ,制造业(行业),3.950,97.76,95.28,24.63
1906,2024-12-31,688239,航宇科技,航空装备Ⅲ,锻造行业(行业),16.810,93.11,97.71,29.41
1938,2024-06-30,688281,华秦科技,航空装备Ⅲ,非关联方(其他),4.850,100.00,100.00,56.27
1943,2024-12-31,688287,*ST观典,航空装备Ⅲ,航空装备制造及相关服务(行业),0.767,85.27,129.90,-24.32
1952,2024-12-31,688297,中无人机,航空装备Ⅲ,无人机系统产品及服务(产品),6.850,100.00,100.00,32.05
2094,2024-06-30,688510,航亚科技,航空装备Ⅲ,航空产品(产品),3.120,91.98,91.74,42.57
2133,2024-12-31,688563,航材股份,航空装备Ⅲ,制造业(行业),27.500,93.78,93.63,29.60
2153,2024-12-31,688586,江航装备,航空装备Ⅲ,航空相关设备制造(行业),9.020,82.51,85.04,35.91
2226,2024-06-30,688685,迈信林,航空装备Ⅲ,销售商品或提供劳务(产品),1.690,91.07,79.69,34.68
2243,2025-06-30,688708,佳驰科技,航空装备Ⅲ,电磁功能结构件(产品),1.990,71.46,74.22,76.66
2421,2023-12-31,000561,烽火电子,航空装备Ⅲ,通信行业(行业),14.480,98.47,98.09,35.64
2502,2025-06-30,000697,*ST炼石,航空装备Ⅲ,航空制造(行业),8.990,99.83,99.06,9.07
2535,2024-12-31,000738,航发控制,航空装备Ⅲ,制造业(行业),54.810,100.00,100.00,28.11
2550,2025-06-30,000768,中航西飞,航空装备Ⅲ,航空产品(产品),192.590,99.19,97.56,7.15
2823,2024-12-31,002023,海特高新,航空装备Ⅲ,航空工程技术与服务(产品),9.910,75.10,79.10,33.84
2907,2025-06-30,002111,威海广泰,航空装备Ⅲ,保障装备制造业(行业),14.230,99.92,99.74,24.10
3084,2024-06-30,002297,博云新材,航空装备Ⅲ,高性能硬质合金及相关材料(产品),2.130,70.66,18.09,4.37
3172,2024-12-31,002389,航天彩虹,航空装备Ⅲ,航空航天产品制造(行业),17.030,66.34,87.61,28.18
3388,2024-06-30,002625,光启技术,航空装备Ⅲ,超材料行业(行业),8.500,99.81,100.00,53.37
3414,2025-06-30,002651,利君股份,航空装备Ⅲ,制造业(行业),3.140,100.00,100.00,40.31
3665,2024-06-30,002933,新兴装备,航空装备Ⅲ,铁路、船舶、航空航天和其他运输设备,2.140,100.00,100.00,24.29
3712,2024-12-31,002985,北摩高科,航空装备Ⅲ,军品(行业),4.730,88.00,86.52,51.94
3799,2024-12-31,300034,钢研高纳,航空装备Ⅲ,有色金属冶炼及压延加工(行业),35.240,100.00,100.00,31.66
4129,2025-06-30,300395,菲利华,航空装备Ⅲ,非金属矿物制品业(业务),9.050,99.70,99.75,49.24
4158,2024-12-31,300424,航新科技,航空装备Ⅲ,航空制造及服务(行业),17.000,99.84,99.58,27.60
4309,2024-12-31,300581,晨曦航空,航空装备Ⅲ,航空机电产品(行业),1.210,86.27,78.10,38.29
4422,2024-06-30,300696,爱乐达,航空装备Ⅲ,航空零部件制造(产品),1.370,100.00,100.00,1.02
4425,2024-12-31,300699,光威复材,航空装备Ⅲ,新材料制造(行业),23.540,96.08,97.75,46.34
4443,2025-06-30,300719,安达维尔,航空装备Ⅲ,航空机载产品分部(行业),2.640,100.00,100.00,40.57
4493,2024-12-31,300775,三角防务,航空装备Ⅲ,特种合金锻压(行业),15.230,95.81,92.40,33.21
4495,2024-12-31,300777,中简科技,航空装备Ⅲ,新材料制造业(行业),8.120,99.93,100.35,63.39
4615,2025-06-30,300900,广联航空,航空装备Ⅲ,航空航天装备制造(行业),5.710,99.02,99.94,31.31
4675,2024-12-31,300965,恒宇信通,航空装备Ⅲ,航空产品及服务(行业),1.790,99.34,99.17,48.27
5117,2024-12-31,301586,佳力奇,航空装备Ⅲ,航空装备制造业(行业),6.270,100.00,100.00,28.30