In [3]:
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import numpy as np
from typing import Dict, List, Tuple

from scipy.stats import zscore
from scipy.stats.mstats import winsorize

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


import warnings
warnings.filterwarnings("ignore")

In [4]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [5]:
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [6]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [128]:
StockList

        code     name
0     000001     平安银行
1     000002      万科A
2     000004    *ST国华
3     000006     深振业A
4     000007      全新好
...      ...      ...
5178  688807     优迅股份
5179  688809     强一股份
5180  688819     天能股份
5181  688981     中芯国际
5182  689009  九号公司-WD

[5183 rows x 2 columns]

In [70]:
df_biz = pd.read_sql('mBiz', engB)

In [21]:
df_biz[(df_biz['项目名'].str.endswith('(自营)'))]

Empty DataFrame
Columns: [日期, StockCode, StockName, 项目名, 营业收入(元), 收入比例(%), 营业利润(元), 利润比例(%), 毛利率(%)]
Index: []

In [90]:
dddf  =  df_biz[~df_biz['项目名'].astype(str).str.contains('地区|销售模式')]
dddf['收入比例(%)'] = pd.to_numeric(dddf['收入比例(%)'], errors='coerce')
ffd = dddf.sort_values(by = '收入比例(%)', ascending=False).drop_duplicates(subset='StockCode',keep='first')

In [8]:
StockICRAW = pd.read_sql('akStockIC', engB)
#申万分类
StockIC = StockICRAW[StockICRAW['ICSCode']=='008003']

In [ ]:
df_biz.info()

In [28]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(行业|产品|业务)'))].groupby('项目名').size().reset_index(name='count').sort_values(by='count', ascending=False).to_excel('./行业_产品_业务.xlsx', index=False)

In [25]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False]).drop_duplicates(subset=['StockCode'], keep='first')

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
6,2025-06-30,000001,平安银行,零售金融业务(业务),310.81亿,44.79,200.57亿,40.48,64.53
27,2025-06-30,000002,万科A,房地产开发及相关资产经营业务(行业),844.36亿,80.17,73.49亿,69.99,8.70
54,2025-06-30,000004,*ST国华,移动网络安全(行业),2343.65万,82.23,1445.37万,88.21,61.67
103,2025-06-30,000006,深振业A,房产销售(产品),18.09亿,96.09,2.90亿,94.37,16.03
135,2025-06-30,000007,全新好,汽车销售及服务(行业),1.71亿,88.54,560.84万,26.53,3.28
...,...,...,...,...,...,...,...,...,...
166136,2025-09-30,688807,优迅股份,光通信收发合一芯片(产品),3.06亿,85.54,1.35亿,85.78,44.27
166181,2025-06-30,688809,强一股份,探针卡销售(业务),3.59亿,95.87,2.50亿,96.70,69.59
166237,2025-06-30,688819,天能股份,铅酸电池(产品),191.51亿,91.56,30.58亿,97.31,15.97
166257,2025-06-30,688981,中芯国际,集成电路晶圆代工(产品),303.53亿,93.83,66.28亿,93.51,21.83
166280,2025-06-30,689009,九号公司-WD,电动两轮车(产品),68.23亿,58.11,16.17亿,45.32,23.71

In [36]:
ddf = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False])

In [ ]:
df_biz[~df_biz['项目名'].astype(str).str.contains('地区|销售模式')]

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
6,2025-06-30,000001,平安银行,零售金融业务(业务),310.81亿,44.79,200.57亿,40.48,64.53
7,2025-06-30,000001,平安银行,批发金融业务(业务),304.25亿,43.85,223.86亿,45.18,73.58
8,2025-06-30,000001,平安银行,其他业务(业务),78.79亿,11.36,71.09亿,14.35,90.23
15,2024-12-31,000001,平安银行,零售金融业务(业务),712.55亿,48.57,492.19亿,47.04,69.07
16,2024-12-31,000001,平安银行,批发金融业务(业务),638.41亿,43.52,448.01亿,42.82,70.18
...,...,...,...,...,...,...,...,...,...
167538,2023-12-31,688729,屹唐股份,专用设备:干法刻蚀设备(产品),2.24亿,5.70,2075.81万,1.51,9.26
167539,2023-12-31,688729,屹唐股份,服务(产品),9190.20万,2.34,3916.70万,2.84,42.62
167540,2023-12-31,688729,屹唐股份,特许权使用费(产品),2097.75万,0.53,2097.75万,1.52,100.00
167549,2023-12-31,688729,屹唐股份,直销(销售模式),37.86亿,96.30,None,None,None
167550,2023-12-31,688729,屹唐股份,经销(销售模式),1.46亿,3.70,None,None,None

In [49]:
df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & ~df_biz['项目名'].str.contains(r[()())]]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (563101807.py, line 1)

In [ ]:
bizDF = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False]).drop_duplicates(subset=['StockCode'], keep='first')

In [91]:
bizDF = ffd.copy()

In [62]:
bizDF['产品'] = bizDF['项目名'].str.replace('（产品）', '', regex=False).str.replace('(产品)', '', regex=False)

In [63]:
# 2. 将“营业收入(元)”中含“万”的数值转换为亿元单位
def convert_to_yi_yuan(value):
    if pd.isna(value):
        return value
    value = str(value).strip()
    if '万' in value:
        # 去掉“万”，转为 float，再除以 10000 得到“亿元”
        num = float(value.replace('万', '').replace(',', ''))
        return num / 10000  # 万元 → 亿元
    else:
        # 如果没有“万”，假设已经是“元”，则除以 1e8 转为亿元
        try:
            num = float(value.replace('亿', '').replace(',', ''))
            return num
        except ValueError:
            return value  # 无法转换的保留原值（如非数字）

In [100]:
bizDF['营业收入(亿元)'] = bizDF['营业收入(元)'].apply(convert_to_yi_yuan).round(3)
df = bizDF[['StockCode', '项目名','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)','日期']]

In [90]:
df_biz

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
0,2025-06-30,000001,平安银行,总部(地区),401.52亿,57.87,295.37亿,59.61,73.56
1,2025-06-30,000001,平安银行,南区(地区),100.43亿,14.47,72.09亿,14.55,71.78
2,2025-06-30,000001,平安银行,东区(地区),95.88亿,13.82,67.41亿,13.60,70.31
3,2025-06-30,000001,平安银行,北区(地区),64.04亿,9.23,40.15亿,8.10,62.70
4,2025-06-30,000001,平安银行,西区(地区),26.43亿,3.81,16.27亿,3.28,61.56
...,...,...,...,...,...,...,...,...,...
168736,2024-06-30,689009,九号公司-WD,其他产品(产品),1.13亿,1.69,4008.34万,1.97,35.60
168737,2024-06-30,689009,九号公司-WD,中国大陆境内(地区),38.63亿,57.95,9.57亿,47.13,24.76
168738,2024-06-30,689009,九号公司-WD,中国大陆境外(地区),28.03亿,42.05,10.73亿,52.87,38.29
168739,2024-06-30,689009,九号公司-WD,自主品牌销售(销售模式),58.60亿,87.91,17.36亿,85.54,29.63
168740,2024-06-30,689009,九号公司-WD,B及定制产品销售(销售模式),8.06亿,12.09,2.94亿,14.46,36.43

In [80]:
df_biz[(df_biz['StockCode']=='600007')].sort_values(by='收入比例(%)', ascending=False)

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
95383,2025-06-30,600007,中国国贸,其他(产品),1.88亿,9.95,None,None,None
95397,2024-06-30,600007,中国国贸,其他(产品),1.91亿,9.72,None,None,None
95378,2025-06-30,600007,中国国贸,物业租赁及管理(行业),16.52亿,87.41,11.22亿,99.54,67.91
95392,2024-06-30,600007,中国国贸,物业租赁及管理(行业),17.09亿,86.96,11.76亿,98.29,68.81
95385,2024-12-31,600007,中国国贸,物业租赁及管理(行业),33.86亿,86.56,22.36亿,98.32,66.04
95384,2025-06-30,600007,中国国贸,公寓(产品),9300.28万,4.92,None,None,None
95391,2024-12-31,600007,中国国贸,公寓(产品),1.87亿,4.78,None,None,None
95398,2024-06-30,600007,中国国贸,公寓(产品),9398.06万,4.78,None,None,None
95394,2024-06-30,600007,中国国贸,写字楼(产品),7.68亿,39.07,None,None,None
95387,2024-12-31,600007,中国国贸,写字楼(产品),15.11亿,38.63,None,None,None
95380,2025-06-30,600007,中国国贸,写字楼(产品),7.29亿,38.56,None,None,None
95381,2025-06-30,600007,中国国贸,商城(产品),6.42亿,33.97,None,None,None
95395,2024-06-30,600007,中国国贸,商城(产品),6.56亿,33.39,None,None,None
95388,2024-12-31,600007,中国国贸,商城(产品),12.86亿,32.88,None,None,None
95386,2024-12-31,600007,中国国贸,酒店经营(行业),5.26亿,13.44,3820.84万,1.68,7.27
95389,2024-12-31,600007,中国国贸,酒店(产品),5.26亿,13.44,3820.84万,1.68,7.27
95393,2024-06-30,600007,中国国贸,酒店经营(行业),2.56亿,13.04,2049.33万,1.71,8.00
95396,2024-06-30,600007,中国国贸,酒店(产品),2.56亿,13.04,None,None,None
95379,2025-06-30,600007,中国国贸,酒店经营(行业),2.38亿,12.59,521.79万,0.46,2.19
95382,2025-06-30,600007,中国国贸,酒店(产品),2.38亿,12.59,521.79万,0.46,2.19
95390,2024-12-31,600007,中国国贸,其他(产品),4.02亿,10.27,None,None,None

In [78]:
dddf[(dddf['StockCode']=='600007')].sort_values(by='收入比例(%)', ascending=False)

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
95383,2025-06-30,600007,中国国贸,其他(产品),1.88亿,9.95,None,None,None

In [41]:
df_biz[(df_biz['StockCode']=='688306') &(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品)'))].drop_duplicates(subset=['StockCode', '项目名'])

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
156462,2025-06-30,688306,均普智能,智能设备应用以及售后服务(产品),1.31亿,12.70,4927.08万,23.81,37.60
156479,2024-12-31,688306,均普智能,智能制造装备产品(产品),26.62亿,100.00,5.12亿,100.00,19.23
156484,2024-06-30,688306,均普智能,汽车通用零部件智能制造装备(产品),2.71亿,24.21,4279.55万,21.60,15.78

In [101]:
stdf = StockIC.merge(df, left_on='StockCode', right_on='StockCode',how='left')[['日期','StockCode','StockName','IC4','项目名','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)']]

In [102]:
stdf['IC4'].drop_duplicates()

0       股份制银行Ⅲ
1           机场
2        商用载货车
3         商业地产
4       水务及水治理
         ...
3382    其他能源发电
3471        白银
3627      宠物食品
4147      视频媒体
4688    纺织鞋类制造
Name: IC4, Length: 337, dtype: object

In [107]:
stdf[stdf['IC4']=='航空装备Ⅲ']

,日期,StockCode,StockName,IC4,项目名,营业收入(亿元),收入比例(%),利润比例(%),毛利率(%)
30,2025-06-30,600038,中直股份,航空装备Ⅲ,航空产品(产品),101.800,99.41,98.05,6.20
235,2025-06-30,600316,洪都航空,航空装备Ⅲ,关联方(其他),15.220,99.91,99.72,4.03
280,2022-12-31,600372,中航机载,航空装备Ⅲ,飞机制造业(行业),103.600,92.61,90.96,30.98
295,2024-12-31,600391,航发科技,航空装备Ⅲ,制造业(行业),37.800,98.17,90.69,14.86
582,2025-06-30,600760,中航沈飞,航空装备Ⅲ,航空产品(产品),145.390,99.39,99.41,12.26
586,2024-06-30,600765,中航重机,航空装备Ⅲ,锻铸分部(产品),53.820,98.36,None,None
663,2024-06-30,600862,中航高科,航空装备Ⅲ,航空新材料分部(业务),25.180,98.88,99.07,37.32
690,2024-12-31,600893,航发动力,航空装备Ⅲ,制造业(行业),471.680,98.51,98.12,10.02
1188,2024-12-31,603261,*ST立航,航空装备Ⅲ,航空产品(产品),2.900,100.00,100.00,6.21
1619,2024-12-31,605123,派克新材,航空装备Ⅲ,锻造行业(行业),27.950,87.00,93.45,20.06
1755,2024-12-31,688070,纵横股份,航空装备Ⅲ,工业无人机(行业),4.740,100.00,100.00,42.20
1803,2024-12-31,688122,西部超导,航空装备Ⅲ,有色金属冶炼及压延加工(行业),43.830,95.02,98.93,34.93
1904,2024-12-31,688237,超卓航科,航空装备Ⅲ,制造业(行业),3.950,97.76,95.28,24.63
1906,2024-12-31,688239,航宇科技,航空装备Ⅲ,锻造行业(行业),16.810,93.11,97.71,29.41
1938,2024-06-30,688281,华秦科技,航空装备Ⅲ,非关联方(其他),4.850,100.00,100.00,56.27
1943,2024-12-31,688287,*ST观典,航空装备Ⅲ,航空装备制造及相关服务(行业),0.767,85.27,129.90,-24.32
1952,2024-12-31,688297,中无人机,航空装备Ⅲ,无人机系统产品及服务(产品),6.850,100.00,100.00,32.05
2094,2024-06-30,688510,航亚科技,航空装备Ⅲ,航空产品(产品),3.120,91.98,91.74,42.57
2133,2024-12-31,688563,航材股份,航空装备Ⅲ,制造业(行业),27.500,93.78,93.63,29.60
2153,2024-12-31,688586,江航装备,航空装备Ⅲ,航空相关设备制造(行业),9.020,82.51,85.04,35.91
2226,2024-06-30,688685,迈信林,航空装备Ⅲ,销售商品或提供劳务(产品),1.690,91.07,79.69,34.68
2243,2025-06-30,688708,佳驰科技,航空装备Ⅲ,电磁功能结构件(产品),1.990,71.46,74.22,76.66
2421,2023-12-31,000561,烽火电子,航空装备Ⅲ,通信行业(行业),14.480,98.47,98.09,35.64
2502,2025-06-30,000697,*ST炼石,航空装备Ⅲ,航空制造(行业),8.990,99.83,99.06,9.07
2535,2024-12-31,000738,航发控制,航空装备Ⅲ,制造业(行业),54.810,100.00,100.00,28.11
2550,2025-06-30,000768,中航西飞,航空装备Ⅲ,航空产品(产品),192.590,99.19,97.56,7.15
2823,2024-12-31,002023,海特高新,航空装备Ⅲ,航空工程技术与服务(产品),9.910,75.10,79.10,33.84
2907,2025-06-30,002111,威海广泰,航空装备Ⅲ,保障装备制造业(行业),14.230,99.92,99.74,24.10
3084,2024-06-30,002297,博云新材,航空装备Ⅲ,高性能硬质合金及相关材料(产品),2.130,70.66,18.09,4.37
3172,2024-12-31,002389,航天彩虹,航空装备Ⅲ,航空航天产品制造(行业),17.030,66.34,87.61,28.18
3388,2024-06-30,002625,光启技术,航空装备Ⅲ,超材料行业(行业),8.500,99.81,100.00,53.37
3414,2025-06-30,002651,利君股份,航空装备Ⅲ,制造业(行业),3.140,100.00,100.00,40.31
3665,2024-06-30,002933,新兴装备,航空装备Ⅲ,铁路、船舶、航空航天和其他运输设备,2.140,100.00,100.00,24.29
3712,2024-12-31,002985,北摩高科,航空装备Ⅲ,军品(行业),4.730,88.00,86.52,51.94
3799,2024-12-31,300034,钢研高纳,航空装备Ⅲ,有色金属冶炼及压延加工(行业),35.240,100.00,100.00,31.66
4129,2025-06-30,300395,菲利华,航空装备Ⅲ,非金属矿物制品业(业务),9.050,99.70,99.75,49.24
4158,2024-12-31,300424,航新科技,航空装备Ⅲ,航空制造及服务(行业),17.000,99.84,99.58,27.60
4309,2024-12-31,300581,晨曦航空,航空装备Ⅲ,航空机电产品(行业),1.210,86.27,78.10,38.29
4422,2024-06-30,300696,爱乐达,航空装备Ⅲ,航空零部件制造(产品),1.370,100.00,100.00,1.02
4425,2024-12-31,300699,光威复材,航空装备Ⅲ,新材料制造(行业),23.540,96.08,97.75,46.34
4443,2025-06-30,300719,安达维尔,航空装备Ⅲ,航空机载产品分部(行业),2.640,100.00,100.00,40.57
4493,2024-12-31,300775,三角防务,航空装备Ⅲ,特种合金锻压(行业),15.230,95.81,92.40,33.21
4495,2024-12-31,300777,中简科技,航空装备Ⅲ,新材料制造业(行业),8.120,99.93,100.35,63.39
4615,2025-06-30,300900,广联航空,航空装备Ⅲ,航空航天装备制造(行业),5.710,99.02,99.94,31.31
4675,2024-12-31,300965,恒宇信通,航空装备Ⅲ,航空产品及服务(行业),1.790,99.34,99.17,48.27
5117,2024-12-31,301586,佳力奇,航空装备Ⅲ,航空装备制造业(行业),6.270,100.00,100.00,28.30