In [ ]:
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import numpy as np
from typing import Dict, List, Tuple

from scipy.stats import zscore
from scipy.stats.mstats import winsorize

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


import warnings
warnings.filterwarnings("ignore")

In [ ]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [ ]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [ ]:
StockICRAW = pd.read_sql('akStockIC', engB)
#申万分类
StockIC = StockICRAW[StockICRAW['ICSCode']=='008003']

In [21]:
len(StockIC)

5154

In [ ]:
BizRAW = pd.read_sql('mBiz', engB)

In [23]:
BizRAW.drop_duplicates(subset='StockCode').shape

(5182, 9)

In [ ]:
biz_tmp  =  BizRAW[~BizRAW['项目名'].astype(str).str.endswith(('地区)','模式)'), na=False)]
biz_tmp['收入比例(%)'] = pd.to_numeric(biz_tmp['收入比例(%)'], errors='coerce')

In [29]:
biz_tmp[biz_tmp['日期']=='2024-06-30'].sort_values(by=['StockCode','收入比例(%)'],ascending=[True,False]).drop_duplicates(subset='StockCode',keep='first').shape

(4541, 9)

In [24]:
df_biz = biz_tmp.sort_values(by=['日期','收入比例(%)'], ascending=False).drop_duplicates(subset='StockCode',keep='first')

In [ ]:
# 2. 将“营业收入(元)”中含“万”的数值转换为亿元单位
def convert_to_yi_yuan(value):
    if pd.isna(value):
        return value
    value = str(value).strip()
    if '万' in value:
        # 去掉“万”，转为 float，再除以 10000 得到“亿元”
        num = float(value.replace('万', '').replace(',', ''))
        return num / 10000  # 万元 → 亿元
    else:
        # 如果没有“万”，假设已经是“元”，则除以 1e8 转为亿元
        try:
            num = float(value.replace('亿', '').replace(',', ''))
            return num
        except ValueError:
            return value  # 无法转换的保留原值（如非数字）

In [ ]:
df_biz['营业收入(亿元)'] = df_biz['营业收入(元)'].apply(convert_to_yi_yuan).round(3)
df_biz['产品'] = df_biz['项目名']
df = df_biz[['StockCode', '产品','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)','日期']]

In [ ]:
fin_biz = StockIC.merge(df, left_on='StockCode', right_on='StockCode',how='left')[['日期','StockCode','StockName','IC4','产品','营业收入(亿元)', '收入比例(%)','利润比例(%)', '毛利率(%)']]

In [ ]:
fin_biz

=============================================

In [ ]:
ddf = df_biz[(df_biz['收入比例(%)'].astype(float)>=10) & (df_biz['项目名'].str.contains('(产品|业务|行业)'))].sort_values(by=['StockCode','日期','收入比例(%)'], ascending=[True,False, False])

In [ ]:
ddf

In [ ]:
bizDF['产品'] = bizDF['项目名'].str.replace('（产品）', '', regex=False).str.replace('(产品)', '', regex=False)

In [16]:
biz_tmp[biz_tmp['StockName'].str.contains('银行')]

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
6,2025-06-30,000001,平安银行,零售金融业务(业务),310.81亿,44.79,200.57亿,40.48,64.53
7,2025-06-30,000001,平安银行,批发金融业务(业务),304.25亿,43.85,223.86亿,45.18,73.58
8,2025-06-30,000001,平安银行,其他业务(业务),78.79亿,11.36,71.09亿,14.35,90.23
15,2024-12-31,000001,平安银行,零售金融业务(业务),712.55亿,48.57,492.19亿,47.04,69.07
16,2024-12-31,000001,平安银行,批发金融业务(业务),638.41亿,43.52,448.01亿,42.82,70.18
...,...,...,...,...,...,...,...,...,...
166854,2024-12-31,601009,南京银行,其他业务(业务),1.64亿,0.33,-5128.70万,-0.21,-31.25
166857,2024-06-30,601009,南京银行,公司银行业务(业务),119.96亿,45.76,75.18亿,53.23,62.67
166858,2024-06-30,601009,南京银行,资金业务(业务),78.35亿,29.89,72.78亿,51.53,92.90
166859,2024-06-30,601009,南京银行,个人银行业务(业务),62.96亿,24.02,-6.73亿,-4.76,-10.68
166860,2024-06-30,601009,南京银行,其他业务(业务),8897.40万,0.34,-22.40万,0.00,-0.25

In [30]:
biz_tmp[biz_tmp['StockCode']=='600761']

,日期,StockCode,StockName,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%)
114325,2022-12-31,600761,安徽合力,叉车及配件(产品),155.47亿,99.2,25.97亿,97.52,16.71
114326,2022-12-31,600761,安徽合力,其他(补充)(产品),1.26亿,0.8,6591.99万,2.48,52.44