#### 获取基础数据

In [2]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm

In [3]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
# engS = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/qfqStock')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [4]:
StockList = pd.read_sql('StocksList', engS)

In [6]:
df = pd.DataFrame()
for code in tqdm(StockList['code'].tolist()):
    dftmp = ak.stock_individual_info_em(symbol=code)
    df = pd.concat([df, dftmp], axis=1)

100%|██████████| 5178/5178 [14:26<00:00,  5.97it/s]

In [11]:
ddf = df.T[df.T.index=='value']

In [13]:
df.T

,0,1,2,3,4,5,6,7,8
item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
value,11.55,000001,平安银行,19405918198.0,19405600653.0,224138355186.900024,224134687542.150024,银行,19910403
item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
value,4.73,000002,万 科Ａ,11930709471.0,9716399629.0,56432255797.830002,45958570245.170006,房地产开发,19910129
item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
...,...,...,...,...,...,...,...,...,...
value,33.5,688819,天能股份,972100000.0,972100000.0,32565350000.0,32565350000.0,电池,20210118
item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
value,122.52,688981,中芯国际,8000402692.0,1999562549.0,980209337823.839966,244986403503.47998,半导体,20200716
item,最新,股票代码,股票简称,总股本,流通股,总市值,流通市值,行业,上市时间
value,55.66,689009,九号公司-WD,720335578.0,553091879.0,40093878271.479996,30785093985.139999,交运设备,20201029

In [27]:
dff = ddf[[1,2,3,4]]

In [28]:
dff.columns = [ 'StockCode', 'StockName', 'TCap', 'FCap' ]

In [31]:
dff

      StockCode StockName           TCap           FCap  CapRatio
value    000001      平安银行  19405918198.0  19405600653.0  0.999984
value    000002     万  科Ａ  11930709471.0   9716399629.0  0.814403
value    000004     *ST国华    132380282.0    126287768.0  0.953977
value    000006      深振业Ａ   1349995046.0   1349987396.0  0.999994
value    000007       全新好    346448044.0    346448044.0       1.0
...         ...       ...            ...            ...       ...
value    688805       C健信    167680000.0     31518859.0   0.18797
value    688807      优迅股份     80000000.0     15035656.0  0.187946
value    688819      天能股份    972100000.0    972100000.0       1.0
value    688981      中芯国际   8000402692.0   1999562549.0  0.249933
value    689009   九号公司-WD    720335578.0    553091879.0  0.767825

[5178 rows x 5 columns]

In [32]:
dff.set_index('StockCode').to_sql('StockCap', engB, if_exists='replace')

-1

In [30]:
dff['CapRatio'] = dff['FCap'] / (dff['TCap'])

/tmp/ipykernel_2915670/3066315244.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['CapRatio'] = dff['FCap'] / (dff['TCap'])