#### akshare获取股票股本数据及财报发布日期数据

In [99]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm

In [98]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
# engS = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/qfqStock')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [ ]:
StockList = pd.read_sql('StocksList', engS)

##### 个股信息查询-东财

In [ ]:
df = pd.DataFrame()
for code in tqdm(StockList['code'].tolist()):
    dftmp = ak.stock_individual_info_em(symbol=code)
    df = pd.concat([df, dftmp], axis=1)

In [ ]:
ddf = df.T[df.T.index=='value']

In [ ]:
df.T

In [ ]:
dff = ddf[[1,2,3,4]]

In [ ]:
dff.columns = [ 'StockCode', 'StockName', 'TCap', 'FCap' ]

In [ ]:
dff.set_index('StockCode').to_sql('StockCap', engB, if_exists='replace')

In [ ]:
dff['CapRatio'] = dff['FCap'] / (dff['TCap'])

##### 信息披露公告-巨潮资讯

In [ ]:
StockList['code'].tolist()[442]

In [ ]:
cl = ['年报', '半年报', '一季报', '三季报']
ak.stock_zh_a_disclosure_report_cninfo(symbol="001222", market="沪深京", category="一季报", start_date="19990101", end_date="20301231")

In [ ]:
cl = ['年报', '半年报', '一季报', '三季报']
code = '001234'
df = pd.DataFrame()
for category in cl:
    dftmp = ak.stock_zh_a_disclosure_report_cninfo(symbol=code, market="沪深京", category=category, start_date="19990101", end_date="20301231")[['代码', '简称', '公告时间']].drop_duplicates(subset=['公告时间'])
    df = pd.concat([df, dftmp])

In [ ]:
df

In [ ]:
df['公告时间'].astype(str).str[:10]

In [ ]:
df.set_index('代码').to_excel('./test.xlsx')

In [ ]:
df.sort_values(by=['公告时间'])

In [ ]:
StockList['code'].tolist()[:3]

In [ ]:

cl = ['年报', '半年报', '一季报', '三季报']
df = pd.DataFrame()
for code in tqdm(StockList['code'].tolist()[:2]):
    dff = pd.DataFrame()
    for category in cl:
        try:
            dftmp = ak.stock_zh_a_disclosure_report_cninfo(symbol=code, market="沪深京", category=category, start_date="19990101", end_date="20301231")[['代码', '简称', '公告时间']].drop_duplicates(subset=['公告时间'])
            
            dff = pd.concat([dff, dftmp])
        except:
            continue
    dff['公告时间'] = dff['公告时间'].astype(str).str[:10]
    
    df = pd.concat([df, dff.drop_duplicates(subset=['公告时间']).sort_values(by='公告时间',ascending=True)])
# df.set_index('代码').to_excel('./AllStockReportDates.xlsx')

In [ ]:
df['公告时间'] = df['公告时间'].astype(str).str[:10]

=========================== 申万行业数据

In [31]:
swRAW = ak.stock_industry_category_cninfo(symbol="申银万国行业分类标准")[['类目编码', '类目名称', '终止日期',  '父类编码', '分级']]

In [37]:
swRAW

        类目编码      类目名称 终止日期   父类编码  分级
0          S  申银万国行业分类  NaT    008   0
1        S11      农林牧渔  NaT      S   1
2      S1101       种植业  NaT    S11   2
3    S110101        种子  NaT  S1101   3
4    S110102      粮食种植  NaT  S1101   3
..       ...       ...  ...    ...  ..
507  S770201  化妆品制造及其他  NaT  S7702   3
508  S770202     品牌化妆品  NaT  S7702   3
509    S7703      医疗美容  NaT    S77   2
510  S770301      医美耗材  NaT  S7703   3
511  S770302      医美服务  NaT  S7703   3

[512 rows x 5 columns]

In [54]:
swRAW[swRAW['类目编码']=='S'+'280203']

        类目编码      类目名称 终止日期   父类编码  分级
125  S280203  底盘与发动机系统  NaT  S2802   3

In [55]:
swStockICRAW = ak.stock_industry_clf_hist_sw().sort_values(by=['symbol','start_date'], ascending=[True,False]).drop_duplicates(subset=['symbol'], keep='first')

In [84]:
swStockICRAW.columns.values

array(['symbol', 'start_date', 'industry_code', 'update_time'],
      dtype=object)

In [58]:
swList = swStockICRAW['industry_code'].to_list()

In [79]:
lis_tmp2 = swRAW[swRAW['类目编码']=='S'+swList[0]][['类目名称','父类编码']].iloc[0].tolist()

In [80]:
lis_tmp1 = swRAW[swRAW['类目编码']==lis_tmp2[1]][['类目名称','父类编码']].iloc[0].tolist()

In [83]:
swRAW[swRAW['类目编码']==lis_tmp1[1]][['类目名称','父类编码']].iloc[0].tolist()[0]

'银行'

In [74]:
swRAW[swRAW['类目编码']=='S'+swList[0]][['类目名称','父类编码']].iloc[0].tolist()

['股份制银行Ⅲ', 'S4803']

==============AI code

In [85]:
code_to_info = swRAW.set_index('类目编码')[['类目名称', '父类编码']].to_dict('index')

In [87]:
# 2. 定义函数：输入不带 'S' 的三级编码，返回 (IC1, IC2, IC3)
def get_ic_levels(third_code_raw):
    third_code = 'S' + str(third_code_raw).strip()  # 确保转为字符串并加 'S'
    
    # 第三级
    if third_code not in code_to_info:
        return pd.NA, pd.NA, pd.NA
    ic3_name = code_to_info[third_code]['类目名称']
    second_code = code_to_info[third_code]['父类编码']
    
    # 第二级
    if second_code not in code_to_info:
        return pd.NA, pd.NA, ic3_name
    ic2_name = code_to_info[second_code]['类目名称']
    first_code = code_to_info[second_code]['父类编码']
    
    # 第一级
    if first_code not in code_to_info:
        return pd.NA, ic2_name, ic3_name
    ic1_name = code_to_info[first_code]['类目名称']
    
    return ic1_name, ic2_name, ic3_name

In [90]:
ic_tuples = swStockICRAW['industry_code'].apply(get_ic_levels)

In [91]:
swStockICRAW[['IC1', 'IC2', 'IC3']] = pd.DataFrame(ic_tuples.tolist(), index=swStockICRAW.index)

In [101]:
Stocks = pd.read_sql('StocksList', engS)

In [108]:
df = Stocks[['code', 'name', 'area','market','list_date', 'act_name', 'act_ent_type']].merge(swStockICRAW[['symbol', 'IC1','IC2', 'IC3']], left_on='code', right_on='symbol', how='left').drop(columns=['symbol']).rename(columns={'code':'StockCode', 'name':'StockName','list_date':'ListDate', 'area':'Area', 'market':'Market', 'act_name':'ActName', 'act_ent_type':'ActEntType '})

In [95]:
swStockICRAW[['symbol', 'IC1','IC2', 'IC3']]

       symbol   IC1     IC2       IC3
2      000001    银行  股份制银行Ⅱ    股份制银行Ⅲ
3      000002   房地产   房地产开发      住宅开发
4      000003    综合     综合Ⅱ       综合Ⅲ
11     000004   计算机    软件开发    横向通用软件
14     000005    环保    环境治理    综合环境治理
...       ...   ...     ...       ...
12712  920978    汽车   汽车零部件  底盘与发动机系统
12713  920981    电子      元件      被动元件
12714  920982  美容护理    医疗美容      医美耗材
12715  920985  电力设备    光伏设备    光伏电池组件
12716  920992  医药生物    医疗器械      医疗设备

[5805 rows x 4 columns]

#### 申万个股行业分类变动历史