#### akshare获取股票股本数据及财报发布日期数据

In [1]:
import akshare as ak
from sqlalchemy import create_engine
import pandas as pd
from tqdm import tqdm
import plotly.express as px

In [ ]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
# engS = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/qfqStock')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engDF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/dFunds')

##### 雪球信息需检测

In [2]:
ak.stock_individual_spot_xq(symbol='SH600489')

        item                value
0         代码             SH600489
1      52周最高                41.48
2        流通股           4847312564
3         跌停                29.66
4         最高                33.05
5        流通值       152981184520.0
6     最小交易单位                  100
7         涨跌                -1.39
8       每股收益                 0.91
9         昨收                32.95
10       成交量            182103688
11       周转率                 3.76
12     52周最低              11.7256
13        名称                 中金黄金
14       交易所                   SH
15    市盈率(动)               31.188
16  基金份额/总股本           4847312564
17   净资产中的商誉             1.107367
18        均价               31.722
19        涨幅                -4.22
20        振幅                 6.13
21        现价                31.56
22    今年以来涨幅                 35.1
23      发行日期  2003-08-14 00:00:00
24        最低                31.03
25  资产净值/总市值       152981184520.0
26   股息(TTM)                0.388
27  股息率(TTM)                1.229
28        货币                  CNY
29     每股净资产                6.023
30    市盈率(静)               45.181
31       成交额         5776637440.0
32       市净率                 5.24
33        涨停                36.25
34  市盈率(TTM)               34.598
35        时间  2026-02-04 15:00:00
36        今开                33.01

* 国证

In [9]:
df_cni = ak.index_all_cni()

In [12]:
df_cni.shape

(1388, 10)

In [15]:
df_cni.head(500)

,指数代码,指数简称,样本数,收盘点位,涨跌幅,PE滚动,成交量,成交额,总市值,自由流通市值
0,399001,深证成指,500,14127.1059,0.0219,26.5897,292305.57791,7352.739704,284889.469014,156125.552427
1,399002,深成指R,500,18973.7075,0.0219,26.5897,292305.57791,7352.739704,284889.469014,156125.552427
2,399003,成份Ｂ指,10,8094.2920,0.0082,7.9380,72.52235,0.350639,314.947738,251.512791
3,399004,深证100R,100,8295.0637,0.0119,22.4447,59041.98747,2526.923174,154432.339802,83341.800107
4,399005,中小100,100,8524.4271,0.0216,24.8991,60995.55684,1584.667336,79038.948353,42202.502335
...,...,...,...,...,...,...,...,...,...,...
495,983041,深港通服装纺织,0,6365.7565,0.0126,NaN,6060.85597,78.653326,10103.404031,3720.179444
496,983042,深港通服装纺织（港币）,0,6381.1749,0.0153,NaN,6060.85597,88.598851,11380.930431,4190.578774
497,983043,深港通电脑硬件,0,9533.3296,0.0222,NaN,61736.32608,1627.273835,62709.577073,35038.659155
498,983044,深港通电脑硬件（港币）,0,9554.5338,0.0250,NaN,61736.32608,1833.042338,70639.169912,39469.282590
499,983045,深港通消费服务,0,2712.3791,0.0165,NaN,9176.18535,73.125382,10496.170392,3743.332150

In [22]:
ak.index_detail_cni(symbol='399001')

             日期    样本代码   样本简称  所属行业     总市值    权重
0    2026-01-30  000937   冀中能源    能源  197.88  0.03
1    2026-01-30  000951   中国重汽    工业  222.40  0.07
2    2026-01-30  000959   首钢股份   原材料  438.93  0.05
3    2026-01-30  000960   锡业股份   原材料  655.36  0.23
4    2026-01-30  000966   长源电力  公用事业  159.43  0.04
..          ...     ...    ...   ...     ...   ...
495  2026-01-30  000987   越秀资本    金融  513.75  0.08
496  2026-01-30  000997  新 大 陆  信息技术  276.78  0.12
497  2026-01-30  002850    科达利    工业  425.73  0.17
498  2026-01-30  002851   麦格米特    工业  699.69  0.32
499  2026-01-30  300919   中伟新材    工业  513.76  0.14

[500 rows x 6 columns]

* 中证

In [19]:
ak.index_csindex_all()

,指数代码,指数简称,指数全称,基日,基点,指数系列,样本数量,最新收盘,近一个月收益率,资产类别,指数热点,指数币种,合作指数,跟踪产品,指数合规,指数类别,发布时间
0,000300,沪深300,沪深300指数,2004-12-31,1000.0,中证系列指数,300.0,4698.68,1.48,股票,NaN,人民币,否,是,IOSCO,规模,2005-04-08
1,000510,中证A500,中证A500指数,2004-12-31,1000.0,中证系列指数,500.0,5886.58,4.32,股票,NaN,人民币,否,是,无,规模,2024-09-23
2,000802,500沪市,中证500沪市指数,2004-12-31,1000.0,中证系列指数,276.0,8363.69,9.90,股票,NaN,人民币,否,否,无,主题,2011-11-08
3,000814,细分医药,中证细分医药产业主题指数,2004-12-31,1000.0,中证系列指数,49.0,8379.08,0.39,股票,NaN,人民币,否,是,无,主题,2012-04-11
4,000819,有色金属,中证申万有色金属指数,2004-12-31,1000.0,中证系列指数,50.0,10964.10,17.36,股票,NaN,人民币,是,是,无,行业,2012-05-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2283,L11643,300证券公司,沪深300证券公司指数,2005-12-31,1000.0,中证系列指数,22.0,549.55,-2.58,股票,NaN,人民币,否,否,IOSCO,行业,2009-06-16
2284,L11644,300保险(三级),沪深300保险(三级行业)指数,2007-12-31,1000.0,中证系列指数,5.0,1116.44,1.42,股票,NaN,人民币,否,否,IOSCO,行业,2009-06-16
2285,L11649,300电脑,沪深300电脑指数,2004-12-31,1000.0,中证系列指数,3.0,5842.21,-4.00,股票,NaN,人民币,否,否,IOSCO,行业,2009-06-16
2286,L11655,300电力,沪深300电力指数,2004-12-31,1000.0,中证系列指数,12.0,2461.16,-2.17,股票,NaN,人民币,否,否,IOSCO,行业,2009-06-16
2287,SHHKSI,沪港精明,中证恒生沪港通AH股精明指数,2014-04-09,5000.0,中证系列指数,NaN,12613.85,2.98,股票,互联互通,人民币,否,否,无,策略,2014-11-17

In [21]:
ak.index_stock_cons_csindex(symbol="000819")

,日期,指数代码,指数名称,指数英文名称,成分券代码,成分券名称,成分券英文名称,交易所,交易所英文名称
0,2026-02-04,000819,有色金属,Non-ferrous Metal,000060,中金岭南,Shenzhen Zhongjin Lingnan Nonfemet Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
1,2026-02-04,000819,有色金属,Non-ferrous Metal,000408,藏格矿业,ZANGGE MINING COMPANY LIMITED,深圳证券交易所,Shenzhen Stock Exchange
2,2026-02-04,000819,有色金属,Non-ferrous Metal,000426,兴业银锡,"INNER MONGOLIA XINGYE SILVER & TIN MINING CO.,LTD",深圳证券交易所,Shenzhen Stock Exchange
3,2026-02-04,000819,有色金属,Non-ferrous Metal,000630,铜陵有色,Tongling Nonferrous Metals Group Co. Ltd,深圳证券交易所,Shenzhen Stock Exchange
4,2026-02-04,000819,有色金属,Non-ferrous Metal,000657,中钨高新,China Tungsten and Hightech Materials Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
5,2026-02-04,000819,有色金属,Non-ferrous Metal,000688,国城矿业,"Guocheng Mining CO.,LTD",深圳证券交易所,Shenzhen Stock Exchange
6,2026-02-04,000819,有色金属,Non-ferrous Metal,000737,北方铜业,"NORTH COPPER (SHANXI) CO., LTD.",深圳证券交易所,Shenzhen Stock Exchange
7,2026-02-04,000819,有色金属,Non-ferrous Metal,000807,云铝股份,Yunnan Aluminium Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
8,2026-02-04,000819,有色金属,Non-ferrous Metal,000831,中国稀土,"CHINA RARE EARTH RESOURCES AND TECHNOLOGY CO.,...",深圳证券交易所,Shenzhen Stock Exchange
9,2026-02-04,000819,有色金属,Non-ferrous Metal,000878,云南铜业,Yunnan Copper Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
10,2026-02-04,000819,有色金属,Non-ferrous Metal,000933,神火股份,Henan Shen Huo Coal Industry and Electricity P...,深圳证券交易所,Shenzhen Stock Exchange
11,2026-02-04,000819,有色金属,Non-ferrous Metal,000960,锡业股份,Yunnan Tin Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
12,2026-02-04,000819,有色金属,Non-ferrous Metal,000970,中科三环,Beijing Zhong Ke San Huan High-Tech Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
13,2026-02-04,000819,有色金属,Non-ferrous Metal,000975,山金国际,"Shanjin International Gold Co.,Ltd.",深圳证券交易所,Shenzhen Stock Exchange
14,2026-02-04,000819,有色金属,Non-ferrous Metal,002155,湖南黄金,Hunan Gold Corporation Limited,深圳证券交易所,Shenzhen Stock Exchange
15,2026-02-04,000819,有色金属,Non-ferrous Metal,002203,海亮股份,Zhejiang Hailiang Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
16,2026-02-04,000819,有色金属,Non-ferrous Metal,002460,赣锋锂业,Ganfeng Lithium Co Ltd,深圳证券交易所,Shenzhen Stock Exchange
17,2026-02-04,000819,有色金属,Non-ferrous Metal,002466,天齐锂业,"Tianqi Lithium Industries, Inc.",深圳证券交易所,Shenzhen Stock Exchange
18,2026-02-04,000819,有色金属,Non-ferrous Metal,002532,天山铝业,"TIANSHAN ALUMINUM GROUP CO.,LTD.",深圳证券交易所,Shenzhen Stock Exchange
19,2026-02-04,000819,有色金属,Non-ferrous Metal,002738,中矿资源,"Sinomine Resource Group Co., Ltd.",深圳证券交易所,Shenzhen Stock Exchange
20,2026-02-04,000819,有色金属,Non-ferrous Metal,002756,永兴材料,"Yongxing Special Materials Technology Co.,Ltd.",深圳证券交易所,Shenzhen Stock Exchange
21,2026-02-04,000819,有色金属,Non-ferrous Metal,300748,金力永磁,"JL MAG RARE-EARTH CO., LTD.",深圳证券交易所,Shenzhen Stock Exchange
22,2026-02-04,000819,有色金属,Non-ferrous Metal,300811,铂科新材,"POCO Holding Co., Ltd.",深圳证券交易所,Shenzhen Stock Exchange
23,2026-02-04,000819,有色金属,Non-ferrous Metal,301219,腾远钴业,"Ganzhou Teng Yuan Cobalt New Material CO., LTD.",深圳证券交易所,Shenzhen Stock Exchange
24,2026-02-04,000819,有色金属,Non-ferrous Metal,600111,北方稀土,China Northern Rare Earth (Group) High-Tech Co...,上海证券交易所,Shanghai Stock Exchange
25,2026-02-04,000819,有色金属,Non-ferrous Metal,600219,南山铝业,"Shandong Nanshan Aluminium Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
26,2026-02-04,000819,有色金属,Non-ferrous Metal,600259,中稀有色,"China Rare Earth Nonferrous Metals Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
27,2026-02-04,000819,有色金属,Non-ferrous Metal,600361,创新新材,"Innovation New Material Technology Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
28,2026-02-04,000819,有色金属,Non-ferrous Metal,600362,江西铜业,Jiangxi Copper Co Ltd,上海证券交易所,Shanghai Stock Exchange
29,2026-02-04,000819,有色金属,Non-ferrous Metal,600392,盛和资源,"Shenghe Resources Holding Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
30,2026-02-04,000819,有色金属,Non-ferrous Metal,600489,中金黄金,Zhongjin Gold Co Ltd,上海证券交易所,Shanghai Stock Exchange
31,2026-02-04,000819,有色金属,Non-ferrous Metal,600497,驰宏锌锗,Yunnan Chihong Zinc&Germanium Co Ltd,上海证券交易所,Shanghai Stock Exchange
32,2026-02-04,000819,有色金属,Non-ferrous Metal,600547,山东黄金,Shandong Gold-Mining Co Ltd,上海证券交易所,Shanghai Stock Exchange
33,2026-02-04,000819,有色金属,Non-ferrous Metal,600549,厦门钨业,Xiamen Tungsten Co Ltd,上海证券交易所,Shanghai Stock Exchange
34,2026-02-04,000819,有色金属,Non-ferrous Metal,600595,中孚实业,Henan Zhongfu Industry Co Ltd,上海证券交易所,Shanghai Stock Exchange
35,2026-02-04,000819,有色金属,Non-ferrous Metal,600988,赤峰黄金,"Chifeng Jilong Gold Mining Co.,Ltd.",上海证券交易所,Shanghai Stock Exchange
36,2026-02-04,000819,有色金属,Non-ferrous Metal,601020,华钰矿业,"Tibet Huayu Mining Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
37,2026-02-04,000819,有色金属,Non-ferrous Metal,601069,西部黄金,"Western Region Gold Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
38,2026-02-04,000819,有色金属,Non-ferrous Metal,601137,博威合金,Ningbo Powerway Alloy Material Co Ltd,上海证券交易所,Shanghai Stock Exchange
39,2026-02-04,000819,有色金属,Non-ferrous Metal,601168,西部矿业,Western Mining Co Ltd,上海证券交易所,Shanghai Stock Exchange
40,2026-02-04,000819,有色金属,Non-ferrous Metal,601212,白银有色,"Baiyin Nonferrous Group Co., Ltd.",上海证券交易所,Shanghai Stock Exchange
41,2026-02-04,000819,有色金属,Non-ferrous Metal,601600,中国铝业,Aluminum Corporation of China Limited,上海证券交易所,Shanghai Stock Exchange
42,2026-02-04,000819,有色金属,Non-ferrous Metal,601677,明泰铝业,Henan Mingtai AL.Industrial Co Ltd,上海证券交易所,Shanghai Stock Exchange
43,2026-02-04,000819,有色金属,Non-ferrous Metal,601702,华峰铝业,Shanghai Huafon Aluminium Corporation,上海证券交易所,Shanghai Stock Exchange
44,2026-02-04,000819,有色金属,Non-ferrous Metal,601899,紫金矿业,Zijin Mining Group Co Ltd,上海证券交易所,Shanghai Stock Exchange
45,2026-02-04,000819,有色金属,Non-ferrous Metal,601958,金钼股份,Jinduicheng Molybdenum Co Ltd,上海证券交易所,Shanghai Stock Exchange
46,2026-02-04,000819,有色金属,Non-ferrous Metal,603688,石英股份,"JIANGSU PACIFIC QUARTZ CO., LTD",上海证券交易所,Shanghai Stock Exchange
47,2026-02-04,000819,有色金属,Non-ferrous Metal,603799,华友钴业,"ZHEJIANG HUAYOU COBALT CO., LTD.",上海证券交易所,Shanghai Stock Exchange
48,2026-02-04,000819,有色金属,Non-ferrous Metal,603979,金诚信,"JCHX MINING MANAGEMENT CO.,LTD.",上海证券交易所,Shanghai Stock Exchange
49,2026-02-04,000819,有色金属,Non-ferrous Metal,603993,洛阳钼业,"China Molybdenum Co., Ltd.",上海证券交易所,Shanghai Stock Exchange

In [ ]:
ak.index_stock_cons('931234')

In [ ]:
mk = pd.read_sql('mkFound', engDF)

In [ ]:
Day = pd.read_sql('mkFund', engDF).tail(1)['date'].to_list()[0]

In [ ]:
Dayup = m_tmp.tail(1)['date'].to_list()[0]

In [ ]:
pd.to_datetime(Day) < pd.to_datetime(Dayup)

In [ ]:
m_tmp = ak.stock_market_fund_flow().rename(columns={'日期':'date',
                    '上证-收盘价':'sh_colse',
                    '上证-涨跌幅':'sh_pct',
                    '深证-收盘价':'sz_colse',
                    '深证-涨跌幅':'sz_pct',
                    '主力净流入-净额':'main_net',
                    '主力净流入-净占比':'main_net_pct',
                    '超大单净流入-净额':'super_net',
                    '超大单净流入-净占比':'super_net_pct',
                    '大单净流入-净额':'latge_net',
                    '大单净流入-净占比':'large_net_pct',
                    '中单净流入-净额':'mid_net',
                    '中单净流入-净占比':'mid_net_pct',
                    '小单净流入-净额':'small_net',
                    '小单净流入-净占比':'small_net_pct'})

In [ ]:
df = ak.stock_fund_flow_industry(symbol= "20日排行")

In [ ]:
StockLists = pd.read_sql('StocksList', engS).ts_code.tolist()

In [ ]:
StockLists[0][:6]

In [ ]:
StockLists[9][7:].lower()

In [ ]:
StockIC = pd.read_sql('swStockIC', engB)

同花 B 6&30 M 1-6&5-30 S 1&5  东方 SB 50&100 B 10-50&20-100 M 2-10&4-20 S 2&4

##### 东方

In [ ]:
fundm = ak.stock_market_fund_flow()

In [ ]:
fundm.columns.values.tolist()

In [ ]:
ak.stock_market_fund_flow().rename(columns={'日期':'date',
 '上证-收盘价':'sh_colse',
 '上证-涨跌幅':'sh_pct',
 '深证-收盘价':'sz_colse',
 '深证-涨跌幅':'sz_pct',
 '主力净流入-净额':'main_net',
 '主力净流入-净占比':'main_net_pct',
 '超大单净流入-净额':'super_net',
 '超大单净流入-净占比':'super_net_pct',
 '大单净流入-净额':'latge_net',
 '大单净流入-净占比':'large_net_pct',
 '中单净流入-净额':'mid_net',
 '中单净流入-净占比':'mid_net_pct',
 '小单净流入-净额':'small_net',
 '小单净流入-净占比':'small_net_pct'})

In [ ]:
ls = []
for ID in StockLists[:3]:
    try:
        df_tmp = ak.stock_individual_fund_flow(stock=ID[:6], market=ID[7:].lower())
        df_tmp.to_sql(ID[:6], engDF, if_exists='replace',index=False)
    except:
        ls.append(ID)
        continue

In [ ]:
ak.stock_individual_fund_flow(stock="000001", market="sz").rename(columns={'日期':'date',
 '收盘价':'colse',
 '涨跌幅':'pct',
 '主力净流入-净额':'main_net',
 '主力净流入-净占比':'main_net_pct',
 '超大单净流入-净额':'super_net',
 '超大单净流入-净占比':'super_net_pct',
 '大单净流入-净额':'latge_net',
 '大单净流入-净占比':'large_net_pct',
 '中单净流入-净额':'mid_net',
 '中单净流入-净占比':'mid_net_pct',
 '小单净流入-净额':'small_net',
 '小单净流入-净占比':'small_net_pct'})

In [ ]:
ak.stock_individual_fund_flow(stock="000001", market="sz")

##### 主业构成

In [ ]:
ak.stock_zygc_em(symbol="SH600489")

In [ ]:
StockList = pd.read_sql('StocksList', engS)

In [ ]:
df = pd.DataFrame()
for n in tqdm(StockList['ts_code'].tolist()[:3]):
    df_tmp = ak.stock_zygc_em(symbol=n[7:]+n[:6])
    df = pd.concat([df, df_tmp])

In [ ]:
df.rename(columns={'股票代码':'StockCode'})

In [ ]:
ak.stock_fhps_detail_ths(symbol="000550")

In [ ]:
ak.stock_history_dividend()

In [ ]:
ak.stock_individual_spot_xq(symbol="SH600489")

In [ ]:
ak.stock_individual_info_em(symbol="000001")

##### 个股信息查询-东财

In [ ]:
df = pd.DataFrame()
for code in tqdm(StockList['code'].tolist()):
    dftmp = ak.stock_individual_info_em(symbol=code)
    df = pd.concat([df, dftmp], axis=1)

In [ ]:
ddf = df.T[df.T.index=='value']

In [ ]:
df.T

In [ ]:
dff = ddf[[1,2,3,4]]

In [ ]:
dff.columns = [ 'StockCode', 'StockName', 'TCap', 'FCap' ]

In [ ]:
dff.set_index('StockCode').to_sql('StockCap', engB, if_exists='replace')

In [ ]:
dff['CapRatio'] = dff['FCap'] / (dff['TCap'])

##### 信息披露公告-巨潮资讯

In [ ]:
StockList['code'].tolist()[442]

In [ ]:
cl = ['年报', '半年报', '一季报', '三季报']
ak.stock_zh_a_disclosure_report_cninfo(symbol="001222", market="沪深京", category="一季报", start_date="19990101", end_date="20301231")

In [ ]:
cl = ['年报', '半年报', '一季报', '三季报']
code = '001234'
df = pd.DataFrame()
for category in cl:
    dftmp = ak.stock_zh_a_disclosure_report_cninfo(symbol=code, market="沪深京", category=category, start_date="19990101", end_date="20301231")[['代码', '简称', '公告时间']].drop_duplicates(subset=['公告时间'])
    df = pd.concat([df, dftmp])

In [ ]:
df

In [ ]:
df['公告时间'].astype(str).str[:10]

In [ ]:
df.set_index('代码').to_excel('./test.xlsx')

In [ ]:
df.sort_values(by=['公告时间'])

In [ ]:
StockList['code'].tolist()[:3]

In [ ]:

cl = ['年报', '半年报', '一季报', '三季报']
df = pd.DataFrame()
for code in tqdm(StockList['code'].tolist()[:2]):
    dff = pd.DataFrame()
    for category in cl:
        try:
            dftmp = ak.stock_zh_a_disclosure_report_cninfo(symbol=code, market="沪深京", category=category, start_date="19990101", end_date="20301231")[['代码', '简称', '公告时间']].drop_duplicates(subset=['公告时间'])
            
            dff = pd.concat([dff, dftmp])
        except:
            continue
    dff['公告时间'] = dff['公告时间'].astype(str).str[:10]
    
    df = pd.concat([df, dff.drop_duplicates(subset=['公告时间']).sort_values(by='公告时间',ascending=True)])
# df.set_index('代码').to_excel('./AllStockReportDates.xlsx')

In [ ]:
df['公告时间'] = df['公告时间'].astype(str).str[:10]

=========================== 申万行业数据 IC1:31 IC2:134 IC3:346

In [ ]:
swRAW = ak.stock_industry_category_cninfo(symbol="申银万国行业分类标准")[['类目编码', '类目名称', '终止日期',  '父类编码', '分级']]

In [ ]:
swIC1 = swRAW[swRAW['分级']==1]['类目名称'].unique().tolist()
swIC2 = swRAW[swRAW['分级']==2]['类目名称'].unique().tolist()
swIC3 = swRAW[swRAW['分级']==3]['类目名称'].unique().tolist()

In [ ]:
swStockICRAW = ak.stock_industry_clf_hist_sw().sort_values(by=['symbol','start_date'], ascending=[True,False])

In [ ]:
code_to_info = swRAW.set_index('类目编码')[['类目名称', '父类编码']].to_dict('index')

##### 定义函数：输入不带 'S' 的三级编码，返回 (IC1, IC2, IC3)

In [ ]:
def get_ic_levels(third_code_raw):
    third_code = 'S' + str(third_code_raw).strip()  # 确保转为字符串并加 'S'
    
    # 第三级
    if third_code not in code_to_info:
        return pd.NA, pd.NA, pd.NA
    ic3_name = code_to_info[third_code]['类目名称']
    second_code = code_to_info[third_code]['父类编码']
    
    # 第二级
    if second_code not in code_to_info:
        return pd.NA, pd.NA, ic3_name
    ic2_name = code_to_info[second_code]['类目名称']
    first_code = code_to_info[second_code]['父类编码']
    
    # 第一级
    if first_code not in code_to_info:
        return pd.NA, ic2_name, ic3_name
    ic1_name = code_to_info[first_code]['类目名称']
    
    return ic1_name, ic2_name, ic3_name

In [ ]:
ic_tuples = swStockICRAW['industry_code'].apply(get_ic_levels)

In [ ]:
swStockICRAW[['IC1', 'IC2', 'IC3']] = pd.DataFrame(ic_tuples.tolist(), index=swStockICRAW.index)

In [ ]:
StockIC = pd.read_sql('swStockIC', engB)

In [ ]:
StockIC.groupby('IC3').size()

In [ ]:
set(swStockICRAW['IC3'].unique().tolist()) - set(StockIC['IC3'].unique().tolist())

In [ ]:
Stocks = pd.read_sql('StocksList', engS)

In [ ]:
df = Stocks[['code', 'name', 'area','market','list_date', 'act_name', 'act_ent_type']].merge(swStockICRAW[['symbol', 'IC1','IC2', 'IC3']], left_on='code', right_on='symbol', how='left').drop(columns=['symbol']).rename(columns={'code':'StockCode', 'name':'StockName','list_date':'ListDate', 'area':'Area', 'market':'Market', 'act_name':'ActName', 'act_ent_type':'ActEntType '})

In [ ]:
swStockICRAW[swStockICRAW['IC2']=='本地生活服务Ⅱ']

In [ ]:
swStockICRAW

In [ ]:
drop_swStockICRAW = swStockICRAW.dropna(subset='IC3').sort_values(by=['symbol','start_date'],ascending=[True,False]).drop_duplicates(subset=['symbol'], keep='first')

In [ ]:
drop_swStockICRAW['IC2'].drop_duplicates()

In [ ]:
swStockICRAW[['symbol', 'IC1','IC2', 'IC3']].dropna(subset='IC3')

In [ ]:
dsw1 = drop_swStockICRAW['IC1'].drop_duplicates().unique().tolist()
dsw2 = drop_swStockICRAW['IC2'].drop_duplicates().unique().tolist()
dsw3 = drop_swStockICRAW['IC3'].drop_duplicates().unique().tolist()

In [ ]:
sw1 = swStockICRAW['IC1'].drop_duplicates().unique().tolist()
sw2 = swStockICRAW['IC2'].drop_duplicates().unique().tolist()
sw3 = swStockICRAW['IC3'].drop_duplicates().unique().tolist()

In [ ]:
set(swIC2) - set(sw2)

In [ ]:
set(swIC2) - set(nsw2)

In [ ]:
set(swIC2) - set(dsw2)

In [ ]:
set(swIC3) - set(sw3)

In [ ]:
set(swIC3) - set(nsw3)

In [ ]:
set(swIC3) - set(dsw3)

In [ ]:
StockIC = pd.read_sql('swStockIC', engB)

##### 层次分类函数

In [ ]:
def hierarchical_classify(df, threshold=20):
    """
    对 StockIC DataFrame 按照 IC1 -> IC2 -> IC3 进行层次分类统计，
    并在每层结果中标注所属 IC 层次。
    
    参数:
        df (pd.DataFrame): 包含列 'StockCode', 'StockName', 'IC1', 'IC2', 'IC3'
        threshold (int): 触发下一级分类的最小计数阈值，默认为 20
    
    返回:
        dict: 嵌套结构，每层包含 level, code, count, children
    """
    def build_ic1():
        result = []
        ic1_groups = df.groupby('IC1')
        for ic1_val, group1 in ic1_groups:
            count1 = len(group1)
            node = {
                'level': 'IC1',
                'code': ic1_val,
                'count': count1,
                'children': []
            }
            if count1 > threshold:
                node['children'] = build_ic2(group1)
            result.append(node)
        return result

    def build_ic2(group1):
        result = []
        ic2_groups = group1.groupby('IC2')
        for ic2_val, group2 in ic2_groups:
            count2 = len(group2)
            node = {
                'level': 'IC2',
                'code': ic2_val,
                'count': count2,
                'children': []
            }
            if count2 > threshold:
                node['children'] = build_ic3(group2)
            result.append(node)
        return result

    def build_ic3(group2):
        result = []
        ic3_groups = group2.groupby('IC3')
        for ic3_val, group3 in ic3_groups:
            count3 = len(group3)
            node = {
                'level': 'IC3',
                'code': ic3_val,
                'count': count3,
                'children': []  # 不再往下分
            }
            result.append(node)
        return result

    return build_ic1()

In [ ]:
def extract_leaf_counts(hierarchical_result):
    """
    从 hierarchical_classify() 的嵌套结果中提取叶子节点，
    返回一个 pandas DataFrame，包含三列：
        - 'ic_path': 完整 IC 路径（如 'A/A1/A1a'）
        - 'codes': 仅叶子节点的分类编码（即子类名称）
        - 'count': 对应数量
    
    参数:
        hierarchical_result (list): hierarchical_classify() 的返回值
        
    返回:
        pd.DataFrame: 包含 'ic_path', 'codes', 'count' 三列
    """
    leaves = []

    def traverse(nodes, path_codes):
        for node in nodes:
            current_path = path_codes + [node['code']]
            if node['children']:
                traverse(node['children'], current_path)
            else:
                leaves.append({
                    'ic_path': '/'.join(current_path),
                    'codes': node['code'],      # 仅叶子节点的 code
                    'count': node['count']
                })

    traverse(hierarchical_result, [])
    return pd.DataFrame(leaves, columns=['ic_path', 'codes', 'count'])

In [ ]:
r = hierarchical_classify(StockIC, threshold=15)

In [ ]:
extract_leaf_counts(hierarchical_classify(StockIC, threshold=1))

##### 申万分类绘图

In [ ]:
def plot_stock_ic_hierarchical(
    df,
    threshold=1,
    chart_type='sunburst',  # 'sunburst' 或 'treemap'
    # width=1100,
    height=600,
    title=None,
    show=True
):
    """
    一键绘制 StockIC 数据的层次结构图（Sunburst 或 Treemap），
    悬浮提示包含：数量、本层占比、总占比。
    
    参数:
        df (pd.DataFrame): 必须包含列 'IC1', 'IC2', 'IC3'
        threshold (int): 触发下一级分类的阈值，默认 20
        chart_type (str): 'sunburst' 或 'treemap'
        width (int): 图形宽度（像素）
        height (int): 图形高度（像素）
        title (str or None): 图表标题，若为 None 则自动设置
        show (bool): 是否立即显示图形
    
    返回:
        plotly.graph_objects.Figure
    """
    if chart_type not in ('sunburst', 'treemap'):
        raise ValueError("chart_type 必须是 'sunburst' 或 'treemap'")
    
    # Step 1: 层级分类
    result = hierarchical_classify(df, threshold=threshold)
    
    # Step 2: 扁平化为 Plotly 所需格式
    flat_data = []
    def traverse(nodes, parent_path, parent_label):
        for node in nodes:
            current_label = node['code']
            full_label = '/'.join(parent_path + [current_label])
            flat_data.append({
                'labels': full_label,
                'parents': parent_label,
                'values': node['count']
            })
            if node['children']:
                traverse(node['children'], parent_path + [current_label], full_label)
    traverse(result, [], '')
    df_plot = pd.DataFrame(flat_data)

    # Step 3: 计算占比
    total_overall = df_plot[df_plot['parents'] == '']['values'].sum()
    df_plot['ratio_overall'] = df_plot['values'] / total_overall

    parent_totals = df_plot.groupby('parents')['values'].sum().to_dict()
    df_plot['parent_total'] = df_plot['parents'].map(parent_totals)
    df_plot['ratio_in_parent'] = df_plot.apply(
        lambda row: 1.0 if row['parents'] == '' else row['values'] / row['parent_total'],
        axis=1
    )
    df_plot['label_simple'] = df_plot['labels'].str.split('/').str[-1]

    # Step 4: 选择图表类型
    if chart_type == 'sunburst':
        fig = px.sunburst(
            df_plot,
            names='labels',
            parents='parents',
            values='values',
            custom_data=['label_simple', 'values', 'ratio_in_parent', 'ratio_overall']
        )
    else:  # treemap
        fig = px.treemap(
            df_plot,
            names='labels',
            parents='parents',
            values='values',
            custom_data=['label_simple', 'values', 'ratio_in_parent', 'ratio_overall']
        )

    # 统一设置悬浮提示
    fig.update_traces(
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>" +
            "数量: %{customdata[1]}<br>" +
            "本层占比: %{customdata[2]:.1%}<br>" +
            "总占比: %{customdata[3]:.1%}<extra></extra>"
        ),
        textinfo="label+value"
    )

    # 自动标题
    if title is None:
        title = f"申万行业层次分类"

    fig.update_layout(
        # width=width,
        height=height,
        title=title,
        title_x=0.5,
        margin=dict(t=60, l=20, r=20, b=20)
    )

    if show:
        fig.show()
    
    return fig

In [ ]:
plot_stock_ic_hierarchical(StockIC, chart_type='treemap',height=600);

##### industry层次绘图

In [ ]:
industry_hierarchy = {
    "农林牧渔与食品饮料": {
        "农业与养殖": [
            "农林牧渔",
            "肉制品",
            "乳品",
            "预加工食品",
            "保健品"
        ],
        "农化与饲料": [
            "农化制品",
            "食品及饲料添加剂"
        ],
        "食品制造与消费": [
            "休闲食品",
            "白酒Ⅱ",
            "调味发酵品Ⅱ",
            "非白酒",
            "软饮料"
        ]
    },
    "大消费与社会服务": {
        "可选消费品": [
            "家用电器",
            "家纺",
            "运动服装",
            "非运动服装",
            "鞋帽及其他",
            "饰品",
            "文娱用品",
            "其他家居用品",
            "卫浴制品",
            "定制家居",
            "成品家居",
            "瓷砖地板",
            "纺织制造"  
        ],
        "必需消费品包装": [
            "造纸",
            "印刷",
            "塑料包装",
            "纸包装",
            "综合包装",
            "金属包装"
        ],
        "零售与生活服务": [
            "商贸零售",
            "美容护理",
            "社会服务"
        ],
        "传媒与数字内容": [
            "广告营销",
            "影视院线",
            "数字媒体",
            "电视广播Ⅱ",
            "大众出版",
            "教育出版",
            "游戏Ⅲ"
        ]
    },
    "医药健康": {
        "制药与生物技术": [
            "中药Ⅲ",
            "化学制剂",
            "原料药",
            "其他生物制品",
            "疫苗",
            "血液制品"
        ],
        "医疗器械与服务": [
            "医疗服务",
            "体外诊断",
            "医疗耗材",
            "医疗设备"
        ],
        "医药流通与零售": [
            "医药流通",
            "线下药店"
        ]
    },
    "能源与资源": {
        "传统化石能源": [
            "动力煤",
            "焦煤",
            "焦炭Ⅱ",
            "油气开采Ⅱ",
            "油服工程",
            "炼油化工",
            "其他石化",
            "油品石化贸易"
        ],
        "公用事业与燃气": [
            "电力",
            "燃气Ⅲ"
        ],
        "金属与矿业": [
            "普钢",
            "特钢Ⅱ",
            "冶钢原料",
            "铅锌",
            "铜",
            "铝",
            "小金属",
            "能源金属",
            "贵金属",
            "其他金属新材料",
            "磁性材料"
        ]
    },
    "基础材料与化工": {
        "基础化工": [
            "其他化学制品",
            "有机硅",
            "民爆制品",
            "氟化工",
            "涂料油墨",
            "纺织化学制品",
            "聚氨酯",
            "胶黏剂及胶带",
            "其他化学原料",
            "无机盐",
            "氯碱",
            "煤化工",
            "纯碱",
            "钛白粉"
        ],
        "化学纤维与橡胶": [
            "化学纤维",
            "橡胶"
        ],
        "建材与非金属材料": [
            "非金属材料Ⅱ",
            "水泥",
            "玻璃玻纤",
            "装修建材"
        ],
        "金属制品与加工": [
            "金属制品",
            "磨具磨料"
        ],
        "塑料与高分子材料": [
            "其他塑料制品",
            "合成树脂",
            "改性塑料",
            "膜材料"
        ]
    },
    "工业制造与高端装备": {
        "通用与专用设备": [
            "其他专用设备",
            "农用机械",
            "印刷包装机械",
            "楼宇设备",
            "纺织服装设备",
            "能源及重型设备",
            "工程机械整机",
            "工程机械器件",
            "其他自动化设备",
            "工控设备",
            "机器人",
            "激光设备",
            "仪器仪表",
            "其他通用设备",
            "制冷空调设备",
            "机床工具",
            "环保设备Ⅲ"
        ],
        "交通运输设备": [
            "乘用车",
            "商用车",
            "摩托车及其他",
            "汽车服务",
            "其他汽车零部件",
            "底盘与发动机系统",
            "汽车电子电气系统",
            "车身附件及饰件",
            "轮胎轮毂",
            "轨交设备Ⅲ"
        ],
        "电机与电气设备": [
            "电机Ⅲ",
            "电工仪器仪表",
            "电网自动化设备",
            "线缆部件及其他",
            "输变电设备",
            "配电设备"
        ]
    },
    "新能源与绿色经济": {
        "光伏产业链": [
            "光伏加工设备",
            "光伏电池组件",
            "光伏辅材",
            "硅料硅片",
            "逆变器"
        ],
        "风电与储能": [
            "风电整机",
            "风电零部件",
            "电池",
            "其他电源设备Ⅱ"
        ],
        "环保与水务": [
            "固废治理",
            "大气治理",
            "水务及水治理",
            "综合环境治理"
        ]
    },
    "基础设施与交通运输": {
        "交通运营": [
            "航空机场",
            "港口",
            "航运",
            "公交",
            "铁路运输",
            "高速公路",
            "公路货运"
        ],
        "物流与供应链": [
            "仓储物流",
            "快递",
            "跨境物流",
            "中间产品及消费品供应链服务",
            "原材料供应链服务"
        ],
        "工程建设与服务": [
            "房屋建设Ⅱ",
            "装修装饰Ⅱ",
            "房地产服务",
            "其他专业工程",
            "化学工程",
            "国际工程",
            "钢结构",
            "园林工程",
            "基建市政工程",
            "工程咨询服务Ⅲ"
        ]
    },
    "房地产与建筑": {
        "地产开发": [
            "住宅开发",
            "商业地产",
            "产业地产"
        ]
    },
    "TMT科技与数字经济": {
        "半导体与电子元器件": [
            "半导体材料",
            "半导体设备",
            "数字芯片设计",
            "模拟芯片设计",
            "集成电路制造",
            "集成电路封测",
            "印制电路板",
            "被动元件",
            "LED",
            "光学元件",
            "面板",
            "分立器件",
            "电子化学品Ⅲ",
            "其他电子Ⅲ"
        ],
        "消费电子与智能硬件": [
            "品牌消费电子",
            "消费电子零部件及组装"
        ],
        "软件与信息技术": [
            "IT服务Ⅲ",
            "其他计算机设备",
            "安防设备",
            "垂直应用软件",
            "横向通用软件"
        ],
        "通信与网络设备": [
            "通信服务",
            "其他通信设备",
            "通信线缆及配套",
            "通信终端及配件",
            "通信网络设备及器件"
        ]
    },
    "金融业": {
        "银行业": [
            "国有大型银行Ⅱ",
            "股份制银行Ⅱ",
            "城商行Ⅱ",
            "农商行Ⅱ"
        ],
        "保险与多元金融": [
            "保险Ⅱ",
            "多元金融"
        ],
        "资本市场服务": [
            "证券Ⅲ"
        ]
    },
    "国防军工": {
        "国防装备整机": [
            "地面兵装Ⅱ",
            "航天装备Ⅱ",
            "航海装备Ⅱ",
            "航空装备Ⅲ" 
        ],
        "军工电子与配套": [
            "军工电子Ⅲ"
        ]
    },
    "综合与其他": {
        "综合类企业": [
            "综合"
        ]
    }
}

In [ ]:
def plot_industry_hierarchy_with_stock_count(
    stock_df,
    industry_dict,
    chart_type='sunburst',
    # width=1200,
    height=600,
    title="行业分类分布（基于 StockIC 匹配）",
    show=True
):
    """
    根据 StockIC 数据和 industry_hierarchy 字典，绘制带数量的行业结构图。
    
    匹配规则：优先 IC3 → IC2 → IC1
    只显示数量 > 0 的分支。
    """
    # Step 1: 构建反向映射：leaf_name -> (top, mid)
    leaf_to_path = {}
    for top, mid_dict in industry_dict.items():
        for mid, leaves in mid_dict.items():
            for leaf in leaves:
                if leaf in leaf_to_path:
                    print(f"警告：叶子行业 '{leaf}' 重复出现！")
                leaf_to_path[leaf] = (top, mid)
    
    all_leaves_set = set(leaf_to_path.keys())
    
    # Step 2: 为每行股票匹配行业（优先 IC3 → IC2 → IC1）
    def match_industry(row):
        # 尝试 IC3
        if pd.notna(row['IC3']) and str(row['IC3']) in all_leaves_set:
            return str(row['IC3'])
        # 尝试 IC2
        if pd.notna(row['IC2']) and str(row['IC2']) in all_leaves_set:
            return str(row['IC2'])
        # 尝试 IC1
        if pd.notna(row['IC1']) and str(row['IC1']) in all_leaves_set:
            return str(row['IC1'])
        return None  # 未匹配
    
    stock_df = stock_df.copy()
    stock_df['matched_leaf'] = stock_df.apply(match_industry, axis=1)
    
    # 过滤未匹配的
    matched_df = stock_df.dropna(subset=['matched_leaf'])
    
    # Step 3: 统计每个叶子的数量
    leaf_counts = matched_df['matched_leaf'].value_counts().to_dict()
    
    # 只保留数量 > 0 的叶子（自然满足）
    valid_leaves = {leaf: cnt for leaf, cnt in leaf_counts.items() if cnt > 0}
    
    if not valid_leaves:
        raise ValueError("没有匹配到任何行业！请检查 IC 列值是否在 industry_hierarchy 中。")
    
    # Step 4: 构建有效路径集合（用于过滤中间节点）
    valid_nodes = set()
    leaf_info = {}  # leaf -> (top, mid, count)
    
    for leaf, count in valid_leaves.items():
        top, mid = leaf_to_path[leaf]
        leaf_info[leaf] = (top, mid, count)
        valid_nodes.update([leaf, mid, top])
    
    # Step 5: 聚合中层和顶层数量
    mid_count = defaultdict(int)
    top_count = defaultdict(int)
    
    for leaf, (top, mid, cnt) in leaf_info.items():
        mid_count[mid] += cnt
        top_count[top] += cnt
    
    # Step 6: 构建扁平 DataFrame（仅包含有效节点）
    rows = []
    
    # 添加顶层
    for top, cnt in top_count.items():
        rows.append({'label': top, 'parent': '', 'value': cnt})
    
    # 添加中层
    for mid, cnt in mid_count.items():
        top = next(t for t, m_dict in industry_dict.items() if mid in m_dict)
        rows.append({'label': mid, 'parent': top, 'value': cnt})
    
    # 添加叶子
    for leaf, (top, mid, cnt) in leaf_info.items():
        rows.append({'label': leaf, 'parent': mid, 'value': cnt})
    
    df_plot = pd.DataFrame(rows)
    
    # Step 7: 计算占比
    total = sum(top_count.values())  # 或 df_plot[df_plot['parent']=='']['value'].sum()
    df_plot['ratio_overall'] = df_plot['value'] / total
    
    # 父节点 value 映射
    parent_value_map = df_plot.set_index('label')['value'].to_dict()
    parent_value_map[''] = total
    df_plot['parent_value'] = df_plot['parent'].map(parent_value_map)
    df_plot['ratio_in_parent'] = df_plot.apply(
        lambda row: 1.0 if row['parent'] == '' else row['value'] / row['parent_value'],
        axis=1
    )
    
    # Step 8: 绘图
    if chart_type == 'sunburst':
        fig = px.sunburst(
            df_plot,
            names='label',
            parents='parent',
            values='value',
            custom_data=['label', 'value', 'ratio_in_parent', 'ratio_overall']
        )
    elif chart_type == 'treemap':
        fig = px.treemap(
            df_plot,
            names='label',
            parents='parent',
            values='value',
            custom_data=['label', 'value', 'ratio_in_parent', 'ratio_overall']
        )
    else:
        raise ValueError("chart_type 必须是 'sunburst' 或 'treemap'")
    
    # 自定义悬浮提示：显示数量 + 两个百分比
    fig.update_traces(
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>" +
            "数量: %{customdata[1]}<br>" +
            "本层占比: %{customdata[2]:.1%}<br>" +
            "总占比: %{customdata[3]:.1%}<extra></extra>"
        ),
        textinfo="label+value"
    )
    
    fig.update_layout(
        # width=width,
        height=height,
        title=title,
        title_x=0.5,
        margin=dict(t=60, l=20, r=20, b=20)
    )
    
    if show:
        fig.show()
    
    return fig

In [ ]:
plot_industry_hierarchy_with_stock_count(
    industry_dict=industry_hierarchy,
    stock_df=StockIC,
    chart_type='treemap',
    # width=1200,
    height=600,
    title="INDUSTRY 行业分类分布"
);

In [ ]:
leaf_industries = set()
for mid_dict in industry_hierarchy.values():
    for leaves in mid_dict.values():
        leaf_industries.update(leaves)

print(f"共定义 {len(leaf_industries)} 个叶子行业。")

#### 申万个股行业分类变动历史

======================   TEST

In [ ]:
StockIC = pd.read_sql('swStockIC', engB)

In [ ]:
StockIC.groupby('IC1').size()