##### 财报披露日期
* 年报（1231） 1.1--4.30
* 一季报（0331）4.1--4.30 
* 中报（0630）7.1--8.30 
* 三季报（0930）10.1--10.31

##### 数据更新
* 年报、一季报（5.15）
* 中报（9.15）
* 三季报（11.15）

In [1]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [2]:
eapi =  TdxExHq_API()
api = TdxHq_API()

##### 历史财务数据列表

In [ ]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data).head(16))

In [3]:
import pandas as pd
from sqlalchemy import create_engine
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
# 生成文件列表
fsList = []
for year in range(2020, 2026):
    fsList.extend([
        f"gpcw{year}0331.zip", f"gpcw{year}0630.zip", f"gpcw{year}0930.zip", f"gpcw{year}1231.zip"
    ])

In [ ]:
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

##### 获取历史财务数据存入数据库

In [ ]:
for ls in fsList[:-1]:
    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls, path_to_download="/tmp/tmpfile.zip")
    df_tmp = datacrawler.to_df(data=result)
    df_tmp['report_date']= df_tmp['report_date'].astype(object)
    df_tmp.to_sql(ls[:12], engF,if_exists='replace')
    print(ls + 'saved ! ')

##### 手动历史财务数据

In [ ]:
filename = 'gpcw20250930.zip'
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=filename, path_to_download="/tmp/tmpfile.zip")
df_tmp = datacrawler.to_df(data=result)
df_tmp['report_date']= df_tmp['report_date'].astype(object)
df_tmp.to_sql(filename[:12], engF, if_exists='replace')

=============== 接口

* 标准接口

In [3]:
api.connect('180.153.18.170', 7709)

* 历史k线
* 市场代码 0:深圳，1:上海
* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (市场代码, 证券代码, 开始位置, 请求的数目)

* 股票

In [10]:
api.to_df(api.get_security_bars(9,1, '588080', 4, 3))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.478,1.486,1.487,1.469,7167863.0,1.060778e+09,2026,2,9,15,0,2026-02-09 15:00
1,1.490,1.500,1.515,1.490,6661342.0,1.000998e+09,2026,2,10,15,0,2026-02-10 15:00
2,1.496,1.486,1.496,1.481,5409577.0,8.050521e+08,2026,2,11,15,0,2026-02-11 15:00

* 指数

In [ ]:
api.to_df(api.get_index_bars(9,0, '932294', 1, 2))

* 扩展接口

In [13]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(eapi.get_instrument_count())

##### ======获取扩展接口代码

In [5]:
mID = api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

In [6]:
df_inst = pd.DataFrame()
total = eapi.get_instrument_count()
for start in range(0, total, 1000):
    df_tmp = api.to_df(eapi.get_instrument_info(start, 999))
    df_inst = pd.concat([df_inst, df_tmp], ignore_index=True)

In [8]:
df_merg = pd.merge(df_inst, mID, left_on='market', right_on='market', how='left').rename(columns={'name':'code_name','market':'market_code'})[['code', 'code_name', 'category','market_code', 'market_name']]

In [9]:
df_merg.to_sql('tdxAPIcode', engI, if_exists='replace', index=False)

-1

In [38]:
df_merg.sort_values(by=['market','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket.xlsx', index=False)

==============================

* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (K线周期， 市场ID， 证券代码，起始位置， 数量)

In [10]:
eapi.connect('47.112.95.207', 7720)

In [11]:
api.to_df(eapi.get_instrument_bars(9,74, 'SPXD', 0, 690))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,24.969999,24.969999,24.857100,24.857100,1166670623,1,0.0,2025,7,24,15,0,2025-07-24 15:00,4415.390137
1,24.936701,24.936701,24.936701,24.936701,1158289407,0,0.0,2025,7,25,15,0,2025-07-25 15:00,2209.499756
2,24.900000,24.900000,24.837700,24.837700,1183715409,7,0.0,2025,7,28,15,0,2025-07-28 15:00,18184.158203
3,24.799999,24.815100,24.799999,24.815100,1187816668,10,0.0,2025,7,29,15,0,2025-07-29 15:00,26194.429688
4,24.820000,24.820000,24.699400,24.699400,1183132877,6,0.0,2025,7,30,15,0,2025-07-30 15:00,17046.400391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,27.580000,27.674999,27.580000,27.674999,1172960153,2,0.0,2026,2,20,15,0,2026-02-20 15:00,7486.449707
146,27.530001,27.530001,27.456400,27.456400,1187415227,9,0.0,2026,2,23,15,0,2026-02-23 15:00,25410.365234
147,27.530001,27.645000,27.529900,27.645000,1183091369,6,0.0,2026,2,24,15,0,2026-02-24 15:00,16965.330078
148,27.610001,27.625000,27.610001,27.625000,1199252553,23,0.0,2026,2,25,15,0,2026-02-25 15:00,64292.285156
149,27.639999,27.727600,27.639999,27.727600,1186993244,8,0.0,2026,2,26,15,0,2026-02-26 15:00,24586.179688

In [ ]:
a = pd.read_excel('/home/ts/app/AiStock/indexAi.xlsx')
b = pd.read_excel('/home/ts/app/AiStock/indexAii.xlsx')

In [ ]:
c = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
a.columns.values

In [ ]:
b.columns.values

In [ ]:
c.columns.values

In [ ]:
c['入选原因']=c['入选原因'] .str.replace('**跟踪**','4')

In [ ]:
c.to_excel('/home/ts/app/AiStock/indexAA.xlsx', index=False)

In [ ]:
pd.merge(b, a , right_on='指数代码', left_on='指数代码',how='left').drop_duplicates(subset='指数代码')

In [ ]:
index = pd.read_sql('optIndexs', engI)

In [ ]:
indexAi = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
index.query("IndexCode >= '000001'& IndexCode <'000019'")