##### 财报披露日期
* 年报（1231） 1.1--4.30
* 一季报（0331）4.1--4.30 
* 中报（0630）7.1--8.30 
* 三季报（0930）10.1--10.31

##### 数据更新
* 年报、一季报（5.15）
* 中报（9.15）
* 三季报（11.15）

In [1]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [2]:
eapi =  TdxExHq_API()
api = TdxHq_API()

##### 历史财务数据列表

In [ ]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data).head(16))

In [3]:
import pandas as pd
from sqlalchemy import create_engine
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
# 生成文件列表
fsList = []
for year in range(2020, 2026):
    fsList.extend([
        f"gpcw{year}0331.zip", f"gpcw{year}0630.zip", f"gpcw{year}0930.zip", f"gpcw{year}1231.zip"
    ])

In [ ]:
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

##### 获取历史财务数据存入数据库

In [ ]:
for ls in fsList[:-1]:
    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls, path_to_download="/tmp/tmpfile.zip")
    df_tmp = datacrawler.to_df(data=result)
    df_tmp['report_date']= df_tmp['report_date'].astype(object)
    df_tmp.to_sql(ls[:12], engF,if_exists='replace')
    print(ls + 'saved ! ')

##### 手动历史财务数据

In [ ]:
filename = 'gpcw20250930.zip'
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=filename, path_to_download="/tmp/tmpfile.zip")
df_tmp = datacrawler.to_df(data=result)
df_tmp['report_date']= df_tmp['report_date'].astype(object)
df_tmp.to_sql(filename[:12], engF, if_exists='replace')

=============== 接口

* 标准接口

In [3]:
api.connect('180.153.18.170', 7709)

* 历史k线
* 市场代码 0:深圳，1:上海
* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (市场代码, 证券代码, 开始位置, 请求的数目)

* 股票

In [10]:
api.to_df(api.get_security_bars(9,1, '588080', 4, 3))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.478,1.486,1.487,1.469,7167863.0,1.060778e+09,2026,2,9,15,0,2026-02-09 15:00
1,1.490,1.500,1.515,1.490,6661342.0,1.000998e+09,2026,2,10,15,0,2026-02-10 15:00
2,1.496,1.486,1.496,1.481,5409577.0,8.050521e+08,2026,2,11,15,0,2026-02-11 15:00

* 指数

In [ ]:
api.to_df(api.get_index_bars(9,0, '932294', 1, 2))

* 扩展接口

In [3]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(eapi.get_instrument_count())

##### ======获取扩展接口代码

In [5]:
mID = api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

In [6]:
df_inst = pd.DataFrame()
total = eapi.get_instrument_count()
for start in range(0, total, 1000):
    df_tmp = api.to_df(eapi.get_instrument_info(start, 999))
    df_inst = pd.concat([df_inst, df_tmp], ignore_index=True)

In [8]:
df_merg = pd.merge(df_inst, mID, left_on='market', right_on='market', how='left').rename(columns={'name':'code_name','market':'market_code'})[['code', 'code_name', 'category','market_code', 'market_name']]

In [9]:
df_merg.to_sql('tdxAPIcode', engI, if_exists='replace', index=False)

-1

In [38]:
df_merg.sort_values(by=['market','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket.xlsx', index=False)

==============================

* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (K线周期， 市场ID， 证券代码，起始位置， 数量)

In [3]:
eapi.connect('47.112.95.207', 7720)

In [14]:
api.to_df(eapi.get_instrument_bars(9,8, '10010910', 0, 690))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,0.0695,0.0755,0.0608,0.0618,2311,38,0.0,2026,1,19,15,0,2026-01-19 15:00,3.238401e-42
1,0.0641,0.0644,0.0455,0.0513,5514,89,0.0,2026,1,20,15,0,2026-01-20 15:00,7.726760e-42
2,0.0503,0.0616,0.0480,0.0527,7964,114,0.0,2026,1,21,15,0,2026-01-21 15:00,1.115994e-41
3,0.0559,0.0610,0.0497,0.0534,9481,50,0.0,2026,1,22,15,0,2026-01-22 15:00,1.328571e-41
4,0.0568,0.0641,0.0535,0.0610,9196,81,0.0,2026,1,23,15,0,2026-01-23 15:00,1.288634e-41
5,0.0581,0.0857,0.0581,0.0691,8521,97,0.0,2026,1,26,15,0,2026-01-26 15:00,1.194046e-41
6,0.0700,0.0700,0.0558,0.0616,9033,42,0.0,2026,1,27,15,0,2026-01-27 15:00,1.265793e-41
7,0.0613,0.0690,0.0613,0.0662,10336,52,0.0,2026,1,28,15,0,2026-01-28 15:00,1.448382e-41
8,0.0643,0.0813,0.0610,0.0761,13497,115,0.0,2026,1,29,15,0,2026-01-29 15:00,1.891333e-41
9,0.0718,0.0754,0.0523,0.0611,14964,131,0.0,2026,1,30,15,0,2026-01-30 15:00,2.096903e-41
10,0.0530,0.0591,0.0360,0.0380,19134,176,0.0,2026,2,2,15,0,2026-02-02 15:00,2.681244e-41
11,0.0421,0.0462,0.0343,0.0407,21144,106,0.0,2026,2,3,15,0,2026-02-03 15:00,2.962905e-41
12,0.0386,0.0400,0.0328,0.0383,24361,134,0.0,2026,2,4,15,0,2026-02-04 15:00,3.413703e-41
13,0.0350,0.0365,0.0285,0.0309,26097,100,0.0,2026,2,5,15,0,2026-02-05 15:00,3.656969e-41
14,0.0248,0.0313,0.0231,0.0238,27295,115,0.0,2026,2,6,15,0,2026-02-06 15:00,3.824844e-41
15,0.0318,0.0344,0.0272,0.0340,28657,147,0.0,2026,2,9,15,0,2026-02-09 15:00,4.015701e-41
16,0.0350,0.0350,0.0259,0.0267,35378,142,0.0,2026,2,10,15,0,2026-02-10 15:00,4.957514e-41
17,0.0260,0.0265,0.0228,0.0240,38217,97,0.0,2026,2,11,15,0,2026-02-11 15:00,5.355342e-41
18,0.0239,0.0260,0.0214,0.0255,38397,143,0.0,2026,2,12,15,0,2026-02-12 15:00,5.380566e-41
19,0.0216,0.0233,0.0137,0.0138,40791,199,0.0,2026,2,13,15,0,2026-02-13 15:00,5.716037e-41
20,0.0142,0.0150,0.0067,0.0067,40981,334,0.0,2026,2,24,15,0,2026-02-24 15:00,5.742661e-41
21,0.0070,0.0173,0.0070,0.0107,42045,446,0.0,2026,2,25,15,0,2026-02-25 15:00,5.891759e-41
22,0.0108,0.0114,0.0061,0.0072,46856,386,0.0,2026,2,26,15,0,2026-02-26 15:00,6.565924e-41
23,0.0066,0.0078,0.0051,0.0066,47939,245,0.0,2026,2,27,15,0,2026-02-27 15:00,6.717685e-41

In [ ]:
a = pd.read_excel('/home/ts/app/AiStock/indexAi.xlsx')
b = pd.read_excel('/home/ts/app/AiStock/indexAii.xlsx')

In [ ]:
c = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
a.columns.values

In [ ]:
b.columns.values

In [ ]:
c.columns.values

In [ ]:
c['入选原因']=c['入选原因'] .str.replace('**跟踪**','4')

In [ ]:
c.to_excel('/home/ts/app/AiStock/indexAA.xlsx', index=False)

In [ ]:
pd.merge(b, a , right_on='指数代码', left_on='指数代码',how='left').drop_duplicates(subset='指数代码')

In [ ]:
index = pd.read_sql('optIndexs', engI)

In [ ]:
indexAi = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
index.query("IndexCode >= '000001'& IndexCode <'000019'")