##### 财报披露日期
* 年报（1231） 1.1--4.30
* 一季报（0331）4.1--4.30 
* 中报（0630）7.1--8.30 
* 三季报（0930）10.1--10.31

##### 数据更新
* 年报、一季报（5.15）
* 中报（9.15）
* 三季报（11.15）

In [1]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [2]:
eapi =  TdxExHq_API()
api = TdxHq_API()

##### 历史财务数据列表

In [3]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data).head(16))

            filename                              hash  filesize
0   gpcw20260930.zip  00cfd49dd9b9fd920484cb0a6c3f5279       164
1   gpcw20260630.zip  1ac6d127df933096659214a0a783815f       164
2   gpcw20260331.zip  db99744101dd2bd41212d8e52f7ff5a1     42865
3   gpcw20251231.zip  debc9c5c7378c91f35c90cd09c0379c2   1807005
4   gpcw20250930.zip  5d2fab875c5975760eafa3c1104e8ba7   5347905
5   gpcw20250630.zip  d3a8c059810a9e01067c0466820e1b4b   5635029
6   gpcw20250331.zip  288418094edde3167e9e03ec29dbc0af   4980003
7   gpcw20241231.zip  23ebb484435d107f2e49d1f4e722bccc   5694748
8   gpcw20240930.zip  f38f660813b3fd41fc4a2b681e741a51   5217365
9   gpcw20240630.zip  081fc65b0f87aa9a3980c688a9f40169   5549825
10  gpcw20240331.zip  89c673a1a6150780c934fa1bded8344c   4874632
11  gpcw20231231.zip  7d5b9d3d31453a651cd3ab081af6a412   5674502
12  gpcw20230930.zip  50270679cc82ebd24b0f0a798836be98   5122328
13  gpcw20230630.zip  1afd1994eb70ec158414f508aa6bd230   5456785
14  gpcw20230331.zip  0bfaa684ae6cc19d4af762b8701ca948   4746585
15  gpcw20221231.zip  254ade8c27afce6303c648eef8bb4692   5625222

In [14]:
import pandas as pd
from sqlalchemy import create_engine
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
# 生成文件列表
fsList = []
for year in range(2020, 2026):
    fsList.extend([
        f"gpcw{year}0331.zip", f"gpcw{year}0630.zip", f"gpcw{year}0930.zip", f"gpcw{year}1231.zip"
    ])

In [ ]:
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

##### 获取历史财务数据存入数据库

In [ ]:
for ls in fsList[:-1]:
    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls, path_to_download="/tmp/tmpfile.zip")
    df_tmp = datacrawler.to_df(data=result)
    df_tmp['report_date']= df_tmp['report_date'].astype(object)
    df_tmp.to_sql(ls[:12], engF,if_exists='replace')
    print(ls + 'saved ! ')

##### 手动历史财务数据

In [ ]:
filename = 'gpcw20250930.zip'
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=filename, path_to_download="/tmp/tmpfile.zip")
df_tmp = datacrawler.to_df(data=result)
df_tmp['report_date']= df_tmp['report_date'].astype(object)
df_tmp.to_sql(filename[:12], engF, if_exists='replace')

=============== 接口

* 标准接口

In [ ]:
api.connect('180.153.18.170', 7709)

* 历史k线
* 市场代码 0:深圳，1:上海
* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (市场代码, 证券代码, 开始位置, 请求的数目)

* 股票

In [ ]:
api.to_df(api.get_security_bars(9,1, '588080', 4, 3))

* 指数

In [ ]:
api.to_df(api.get_index_bars(9,0, '932294', 1, 2))

* 扩展接口

In [27]:
eapi.connect('47.112.95.207', 7720)

In [29]:
api.to_df(eapi.get_instrument_info(77500, 999))

    category  market    code       name       desc
0         13      74    ZJAN  创新者股权1年1月          
1         13      74     ZJK        中金科          
2         13      74    ZJUL  1年7个月股权保护          
3         13      74    ZJUN    股票型定义保护          
4         13      74    ZJYL       中进医疗          
..       ...     ...     ...        ...        ...
84         5     102  988006     CNTHKD
85         5     102  988007     CNTUSD
86         5     102  988106   CNTTRHKD
87         5     102  988107   CNTTRUSD
88         5     102  988201     湾创100R

[89 rows x 5 columns]

In [5]:
api.to_df(eapi.get_instrument_count())

   value
0  77595

##### ======获取扩展接口代码

In [6]:
api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

    market market_name
0        1         临时股
1        7       中金所期权
2        8        个股期权
3        9        深圳期权
4       27        香港指数
5       28        郑州商品
6       29        大连商品
7       30        上海期货
8       31        香港主板
9       33       开放式基金
10      34       货币型基金
11      35      银河理财产品
12      37    全球指数(静态)
13      38        宏观指标
14      40       中国概念股
15      43       B股转H股
16      44        股份转让
17      47       中金所期货
18      48       香港创业板
19      49        香港基金
20      54       国债预发行
21      56      阳光私募基金
22      57      券商集合理财
23      58      券商货币理财
24      60      主力期货合约
25      62        中证指数
26      65      广州套利期货
27      66        广州期货
28      71         港股通
29      74        美国股票
30     102        国证指数

In [11]:
mID = api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

In [10]:
df_inst = pd.DataFrame()
total = eapi.get_instrument_count()
for start in range(0, total, 1000):
    df_tmp = api.to_df(eapi.get_instrument_info(start, 999))
    df_inst = pd.concat([df_inst, df_tmp], ignore_index=True)

In [12]:
df_merg = pd.merge(df_inst, mID, left_on='market', right_on='market', how='left').rename(columns={'name':'code_name','market':'market_code'})[['code', 'code_name', 'category','market_code', 'market_name']]

In [15]:
df_merg.to_sql('tdxAPIcode', engI, if_exists='replace', index=False)

-1

In [30]:
df_inst.head(2)

   category  market   code  name desc
0         2      71  00001    长和
1         2      71  00002  中电控股

In [31]:
df_inst.sort_values(by=['market','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket2026.xlsx', index=False)

In [ ]:
df_merg.sort_values(by=['market_code','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket.xlsx', index=False)

==============================

* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (K线周期， 市场ID， 证券代码，起始位置， 数量)

In [ ]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(eapi.get_instrument_bars(9,66, 'LCL8', 0, 690))

In [ ]:
a = pd.read_excel('/home/ts/app/AiStock/indexAi.xlsx')
b = pd.read_excel('/home/ts/app/AiStock/indexAii.xlsx')

In [ ]:
c = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
a.columns.values

In [ ]:
b.columns.values

In [ ]:
c.columns.values

In [ ]:
c['入选原因']=c['入选原因'] .str.replace('**跟踪**','4')

In [ ]:
c.to_excel('/home/ts/app/AiStock/indexAA.xlsx', index=False)

In [ ]:
pd.merge(b, a , right_on='指数代码', left_on='指数代码',how='left').drop_duplicates(subset='指数代码')

In [ ]:
index = pd.read_sql('optIndexs', engI)

In [ ]:
indexAi = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
index.query("IndexCode >= '000001'& IndexCode <'000019'")