##### 财报披露日期
* 年报（1231） 1.1--4.30
* 一季报（0331）4.1--4.30 
* 中报（0630）7.1--8.30 
* 三季报（0930）10.1--10.31

##### 数据更新
* 年报、一季报（5.15）
* 中报（9.15）
* 三季报（11.15）

In [1]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [2]:
eapi =  TdxExHq_API()
api = TdxHq_API()

##### 历史财务数据列表(2026.5.6)

In [3]:
from datetime import datetime
print(datetime.now().strftime("%Y-%m-%d"))
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data).head(16))

2026-05-06
            filename                              hash  filesize
0   gpcw20260930.zip  00cfd49dd9b9fd920484cb0a6c3f5279       164
1   gpcw20260630.zip  1ac6d127df933096659214a0a783815f       164
2   gpcw20260331.zip  1ba9a4847a476cf624b1a66ac2b8f7dd   5028530
3   gpcw20251231.zip  7b7980eb0483491b72339182e46097a9   5727672
4   gpcw20250930.zip  7d3413897af0b86bfc41a988a14e8b4b   5347652
5   gpcw20250630.zip  45ae946e94276bd64d4dee9b62a9ac99   5646561
6   gpcw20250331.zip  2d97410433747aaa548512acdc0348c6   4979292
7   gpcw20241231.zip  5c858b32f46bd31d2604438136d6b3e3   5703625
8   gpcw20240930.zip  e5a6513a98189dd8483caa5dd7561e07   5215650
9   gpcw20240630.zip  14722f0cef4a631dcd3128e40ddb2c10   5547961
10  gpcw20240331.zip  ee86d8159632d8edce459b31a58e8ac3   4872955
11  gpcw20231231.zip  6472f9f9b65c40ce5b5c3a77c3b7ee28   5683256
12  gpcw20230930.zip  6dcf7f8dbfa3d895b6eb491e36aac058   5120432
13  gpcw20230630.zip  a466bb2126962383ca4c2c9a9c9f1162   5455681
14  gpcw20230331.zip  fabec516e748498c88d0fa1bae13f87a   4744792
15  gpcw20221231.zip  3471331dc7e427c1a2a58abc46587b5d   5633102

In [14]:
import pandas as pd
from sqlalchemy import create_engine
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
# 生成文件列表
fsList = []
for year in range(2020, 2026):
    fsList.extend([
        f"gpcw{year}0331.zip", f"gpcw{year}0630.zip", f"gpcw{year}0930.zip", f"gpcw{year}1231.zip"
    ])

In [ ]:
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

##### 获取历史财务数据存入数据库

In [ ]:
for ls in fsList[:-1]:
    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls, path_to_download="/tmp/tmpfile.zip")
    df_tmp = datacrawler.to_df(data=result)
    df_tmp['report_date']= df_tmp['report_date'].astype(object)
    df_tmp.to_sql(ls[:12], engF,if_exists='replace')
    print(ls + 'saved ! ')

##### 手动历史财务数据

In [ ]:
filename = 'gpcw20250930.zip'
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=filename, path_to_download="/tmp/tmpfile.zip")
df_tmp = datacrawler.to_df(data=result)
df_tmp['report_date']= df_tmp['report_date'].astype(object)
df_tmp.to_sql(filename[:12], engF, if_exists='replace')

=============== 接口

* 标准接口

In [4]:
api.connect('180.153.18.170', 7709)

* 历史k线
* 市场代码 0:深圳，1:上海
* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (市场代码, 证券代码, 开始位置, 请求的数目)

* 股票

In [6]:
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.505,1.544,1.548,1.497,10759549.0,1.642966e+09,2026,4,27,15,0,2026-04-27 15:00

* 指数

In [ ]:
api.to_df(api.get_index_bars(9,0, '932294', 1, 2))

* 扩展接口

In [4]:
eapi.connect('47.112.95.207', 7720)

In [5]:
api.to_df(eapi.get_instrument_info(77500, 999))

     category  market    code       name       desc
0          13      74    VRSN        威瑞信          
1          13      74     VRT       维谛技术          
2          13      74    VRTL  2倍做多VRT每日          
3          13      74    VRTS      维德思投资          
4          13      74    VRTV    Veritiv          
..        ...     ...     ...        ...        ...
930         5     102  988006     CNTHKD
931         5     102  988007     CNTUSD
932         5     102  988106   CNTTRHKD
933         5     102  988107   CNTTRUSD
934         5     102  988201     湾创100R

[935 rows x 5 columns]

In [5]:
api.to_df(eapi.get_instrument_count())

   value
0  77595

##### ======获取扩展接口代码

In [6]:
api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

    market market_name
0        1         临时股
1        7       中金所期权
2        8        个股期权
3        9        深圳期权
4       27        香港指数
5       28        郑州商品
6       29        大连商品
7       30        上海期货
8       31        香港主板
9       33       开放式基金
10      34       货币型基金
11      35      银河理财产品
12      37    全球指数(静态)
13      38        宏观指标
14      40       中国概念股
15      43       B股转H股
16      44        股份转让
17      47       中金所期货
18      48       香港创业板
19      49        香港基金
20      54       国债预发行
21      56      阳光私募基金
22      57      券商集合理财
23      58      券商货币理财
24      60      主力期货合约
25      62        中证指数
26      65      广州套利期货
27      66        广州期货
28      71         港股通
29      74        美国股票
30     102        国证指数

In [11]:
mID = api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

In [10]:
df_inst = pd.DataFrame()
total = eapi.get_instrument_count()
for start in range(0, total, 1000):
    df_tmp = api.to_df(eapi.get_instrument_info(start, 999))
    df_inst = pd.concat([df_inst, df_tmp], ignore_index=True)

In [12]:
df_merg = pd.merge(df_inst, mID, left_on='market', right_on='market', how='left').rename(columns={'name':'code_name','market':'market_code'})[['code', 'code_name', 'category','market_code', 'market_name']]

In [15]:
df_merg.to_sql('tdxAPIcode', engI, if_exists='replace', index=False)

-1

In [30]:
df_inst.head(2)

   category  market   code  name desc
0         2      71  00001    长和
1         2      71  00002  中电控股

In [31]:
df_inst.sort_values(by=['market','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket2026.xlsx', index=False)

In [ ]:
df_merg.sort_values(by=['market_code','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket.xlsx', index=False)

==============================

* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (K线周期， 市场ID， 证券代码，起始位置， 数量)

In [ ]:
eapi.connect('47.112.95.207', 7720)

In [13]:
api.to_df(eapi.get_instrument_bars(9,38, '6_TEC', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,4508.0,4508.0,4508.0,4508.0,0,0,0.0,2014,10,31,15,0,2014-10-31 15:00,0.0
1,4632.0,4632.0,4632.0,4632.0,0,0,0.0,2014,11,30,15,0,2014-11-30 15:00,0.0
2,5117.0,5117.0,5117.0,5117.0,0,0,0.0,2014,12,31,15,0,2014-12-31 15:00,0.0
3,3595.0,3595.0,3595.0,3595.0,0,0,0.0,2015,2,28,15,0,2015-02-28 15:00,0.0
4,4448.0,4448.0,4448.0,4448.0,0,0,0.0,2015,3,31,15,0,2015-03-31 15:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,10154.0,10154.0,10154.0,10154.0,0,0,0.0,2025,8,31,15,0,2025-08-31 15:00,0.0
116,8886.0,8886.0,8886.0,8886.0,0,0,0.0,2025,9,30,15,0,2025-09-30 15:00,0.0
117,8572.0,8572.0,8572.0,8572.0,0,0,0.0,2025,10,31,15,0,2025-10-31 15:00,0.0
118,8356.0,8356.0,8356.0,8356.0,0,0,0.0,2025,11,30,15,0,2025-11-30 15:00,0.0
119,8595.0,8595.0,8595.0,8595.0,0,0,0.0,2026,3,31,15,0,2026-03-31 15:00,0.0

In [ ]:
a = pd.read_excel('/home/ts/app/AiStock/indexAi.xlsx')
b = pd.read_excel('/home/ts/app/AiStock/indexAii.xlsx')

In [ ]:
c = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
a.columns.values

In [ ]:
b.columns.values

In [ ]:
c.columns.values

In [ ]:
c['入选原因']=c['入选原因'] .str.replace('**跟踪**','4')

In [ ]:
c.to_excel('/home/ts/app/AiStock/indexAA.xlsx', index=False)

In [ ]:
pd.merge(b, a , right_on='指数代码', left_on='指数代码',how='left').drop_duplicates(subset='指数代码')

In [ ]:
index = pd.read_sql('optIndexs', engI)

In [ ]:
indexAi = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
index.query("IndexCode >= '000001'& IndexCode <'000019'")