In [147]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [141]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data))

             filename                              hash  filesize
0    gpcw20250930.zip  1f43e000d0fd371127b8a68a3246308c       164
1    gpcw20250630.zip  7958c560453aac4fcada4861bd62fd8e       164
2    gpcw20250331.zip  39b36d0513446ab3e8a1fb49f5e25b4b   4856246
3    gpcw20241231.zip  317a8cc0a9f2ba5cf4f1e472c8e81a7d   5539530
4    gpcw20240930.zip  249d0ecb420ca1bb9554ce00861c8bf8   5195779
..                ...                               ...       ...
138  gpcw19910331.zip  1792cb5b47b6a1ae01794d3972b0adbf       165
139  gpcw19901231.zip  ae0b3a7b5754b7058a8fe02e8b016690     12934
140  gpcw19900630.zip  6bb4c75c61c7066d3a03b3e24008b33f       165
141  gpcw19891231.zip  b0ad534ba255a73fe9368b8a0d5551c6       333
142  gpcw19881231.zip  4fcec5f4cf87d4f97d7f39adbf58145d       164

[143 rows x 3 columns]

In [145]:
ls = ['gpcw20241231.zip']
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

In [153]:
ls[0][:12]

'gpcw20241231'

In [149]:
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls[0], path_to_download="/tmp/tmpfile.zip")
dd = datacrawler.to_df(data=result)

Downloaded 30000, Total is 0
Downloaded 60000, Total is 0
Downloaded 90000, Total is 0
Downloaded 120000, Total is 0
Downloaded 150000, Total is 0
Downloaded 180000, Total is 0
Downloaded 210000, Total is 0
Downloaded 240000, Total is 0
Downloaded 270000, Total is 0
Downloaded 300000, Total is 0
Downloaded 330000, Total is 0
Downloaded 360000, Total is 0
Downloaded 390000, Total is 0
Downloaded 420000, Total is 0
Downloaded 450000, Total is 0
Downloaded 480000, Total is 0
Downloaded 510000, Total is 0
Downloaded 540000, Total is 0
Downloaded 570000, Total is 0
Downloaded 600000, Total is 0
Downloaded 630000, Total is 0
Downloaded 660000, Total is 0
Downloaded 690000, Total is 0
Downloaded 720000, Total is 0
Downloaded 750000, Total is 0
Downloaded 780000, Total is 0
Downloaded 810000, Total is 0
Downloaded 840000, Total is 0
Downloaded 870000, Total is 0
Downloaded 900000, Total is 0
Downloaded 930000, Total is 0
Downloaded 960000, Total is 0
Downloaded 990000, Total is 0
Downloaded 1020000, Total is 0
Downloaded 1050000, Total is 0
Downloaded 1080000, Total is 0
Downloaded 1110000, Total is 0
Downloaded 1140000, Total is 0
Downloaded 1170000, Total is 0
Downloaded 1200000, Total is 0
Downloaded 1230000, Total is 0
Downloaded 1260000, Total is 0
Downloaded 1290000, Total is 0
Downloaded 1320000, Total is 0
Downloaded 1350000, Total is 0
Downloaded 1380000, Total is 0
Downloaded 1410000, Total is 0
Downloaded 1440000, Total is 0
Downloaded 1470000, Total is 0
Downloaded 1500000, Total is 0
Downloaded 1530000, Total is 0
Downloaded 1560000, Total is 0
Downloaded 1590000, Total is 0
Downloaded 1620000, Total is 0
Downloaded 1650000, Total is 0
Downloaded 1680000, Total is 0
Downloaded 1710000, Total is 0
Downloaded 1740000, Total is 0
Downloaded 1770000, Total is 0
Downloaded 1800000, Total is 0
Downloaded 1830000, Total is 0
Downloaded 1860000, Total is 0
Downloaded 1890000, Total is 0
Downloaded 1920000, Total is 0
Downloaded 1950000, Total is 0
Downloaded 1980000, Total is 0
Downloaded 2010000, Total is 0
Downloaded 2040000, Total is 0
Downloaded 2070000, Total is 0
Downloaded 2100000, Total is 0
Downloaded 2130000, Total is 0
Downloaded 2160000, Total is 0
Downloaded 2190000, Total is 0
Downloaded 2220000, Total is 0
Downloaded 2250000, Total is 0
Downloaded 2280000, Total is 0
Downloaded 2310000, Total is 0
Downloaded 2340000, Total is 0
Downloaded 2370000, Total is 0
Downloaded 2400000, Total is 0
Downloaded 2430000, Total is 0
Downloaded 2460000, Total is 0
Downloaded 2490000, Total is 0
Downloaded 2520000, Total is 0
Downloaded 2550000, Total is 0
Downloaded 2580000, Total is 0
Downloaded 2610000, Total is 0
Downloaded 2640000, Total is 0
Downloaded 2670000, Total is 0
Downloaded 2700000, Total is 0
Downloaded 2730000, Total is 0
Downloaded 2760000, Total is 0
Downloaded 2790000, Total is 0
Downloaded 2820000, Total is 0
Downloaded 2850000, Total is 0
Downloaded 2880000, Total is 0
Downloaded 2910000, Total is 0
Downloaded 2940000, Total is 0
Downloaded 2970000, Total is 0
Downloaded 3000000, Total is 0
Downloaded 3030000, Total is 0
Downloaded 3060000, Total is 0
Downloaded 3090000, Total is 0
Downloaded 3120000, Total is 0
Downloaded 3150000, Total is 0
Downloaded 3180000, Total is 0
Downloaded 3210000, Total is 0
Downloaded 3240000, Total is 0
Downloaded 3270000, Total is 0
Downloaded 3300000, Total is 0
Downloaded 3330000, Total is 0
Downloaded 3360000, Total is 0
Downloaded 3390000, Total is 0
Downloaded 3420000, Total is 0
Downloaded 3450000, Total is 0
Downloaded 3480000, Total is 0
Downloaded 3510000, Total is 0
Downloaded 3540000, Total is 0
Downloaded 3570000, Total is 0
Downloaded 3600000, Total is 0
Downloaded 3630000, Total is 0
Downloaded 3660000, Total is 0
Downloaded 3690000, Total is 0
Downloaded 3720000, Total is 0
Downloaded 3750000, Total is 0
Downloaded 3780000, Total is 0
Downloaded 3810000, Total is 0
Downloaded 3840000, Total is 0
Downloaded 3870000, Total is 0
Downloaded 3900000, Total is 0
Downloaded 3930000, Total is 0
Downloaded 3960000, Total is 0
Downloaded 3990000, Total is 0
Downloaded 4020000, Total is 0
Downloaded 4050000, Total is 0
Downloaded 4080000, Total is 0
Downloaded 4110000, Total is 0
Downloaded 4140000, Total is 0
Downloaded 4170000, Total is 0
Downloaded 4200000, Total is 0
Downloaded 4230000, Total is 0
Downloaded 4260000, Total is 0
Downloaded 4290000, Total is 0
Downloaded 4320000, Total is 0
Downloaded 4350000, Total is 0
Downloaded 4380000, Total is 0
Downloaded 4410000, Total is 0
Downloaded 4440000, Total is 0
Downloaded 4470000, Total is 0
Downloaded 4500000, Total is 0
Downloaded 4530000, Total is 0
Downloaded 4560000, Total is 0
Downloaded 4590000, Total is 0
Downloaded 4620000, Total is 0
Downloaded 4650000, Total is 0
Downloaded 4680000, Total is 0
Downloaded 4710000, Total is 0
Downloaded 4740000, Total is 0
Downloaded 4770000, Total is 0
Downloaded 4800000, Total is 0
Downloaded 4830000, Total is 0
Downloaded 4860000, Total is 0
Downloaded 4890000, Total is 0
Downloaded 4920000, Total is 0
Downloaded 4950000, Total is 0
Downloaded 4980000, Total is 0
Downloaded 5010000, Total is 0
Downloaded 5040000, Total is 0
Downloaded 5070000, Total is 0
Downloaded 5100000, Total is 0
Downloaded 5130000, Total is 0
Downloaded 5160000, Total is 0
Downloaded 5190000, Total is 0
Downloaded 5220000, Total is 0
Downloaded 5250000, Total is 0
Downloaded 5280000, Total is 0
Downloaded 5310000, Total is 0
Downloaded 5340000, Total is 0
Downloaded 5370000, Total is 0
Downloaded 5400000, Total is 0
Downloaded 5430000, Total is 0
Downloaded 5460000, Total is 0
Downloaded 5490000, Total is 0
Downloaded 5520000, Total is 0
Downloaded 5539530, Total is 0

In [154]:
dd['report_date']= dd['report_date'].astype(object)
dd = dd.round(2)

In [155]:
dd

,report_date,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50,col51,col52,col53,col54,col55,col56,col57,col58,col59,col60,col61,col62,col63,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80,col81,col82,col83,col84,col85,col86,col87,col88,col89,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99,col100,col101,col102,col103,col104,col105,col106,col107,col108,col109,col110,col111,col112,col113,col114,col115,col116,col117,col118,col119,col120,col121,col122,col123,col124,col125,col126,col127,col128,col129,col130,col131,col132,col133,col134,col135,col136,col137,col138,col139,col140,col141,col142,col143,col144,col145,col146,col147,col148,col149,col150,col151,col152,col153,col154,col155,col156,col157,col158,col159,col160,col161,col162,col163,col164,col165,col166,col167,col168,col169,col170,col171,col172,col173,col174,col175,col176,col177,col178,col179,col180,col181,col182,col183,col184,col185,col186,col187,col188,col189,col190,col191,col192,col193,col194,col195,col196,col197,col198,col199,col200,col201,col202,col203,col204,col205,col206,col207,col208,col209,col210,col211,col212,col213,col214,col215,col216,col217,col218,col219,col220,col221,col222,col223,col224,col225,col226,col227,col228,col229,col230,col231,col232,col233,col234,col235,col236,col237,col238,col239,col240,col241,col242,col243,col244,col245,col246,col247,col248,col249,col250,col251,col252,col253,col254,col255,col256,col257,col258,col259,col260,col261,col262,col263,col264,col265,col266,col267,col268,col269,col270,col271,col272,col273,col274,col275,col276,col277,col278,col279,col280,col281,col282,col283,col284,col285,col286,col287,col288,col289,col290,col291,col292,col293,col294,col295,col296,col297,col298,col299,col300,col301,col302,col303,col304,col305,col306,col307,col308,col309,col310,col311,col312,col313,col314,col315,col316,col317,col318,col319,col320,col321,col322,col323,col324,col325,col326,col327,col328,col329,col330,col331,col332,col333,col334,col335,col336,col337,col338,col339,col340,col341,col342,col343,col344,col345,col346,col347,col348,col349,col350,col351,col352,col353,col354,col355,col356,col357,col358,col359,col360,col361,col362,col363,col364,col365,col366,col367,col368,col369,col370,col371,col372,col373,col374,col375,col376,col377,col378,col379,col380,col381,col382,col383,col384,col385,col386,col387,col388,col389,col390,col391,col392,col393,col394,col395,col396,col397,col398,col399,col400,col401,col402,col403,col404,col405,col406,col407,col408,col409,col410,col411,col412,col413,col414,col415,col416,col417,col418,col419,col420,col421,col422,col423,col424,col425,col426,col427,col428,col429,col430,col431,col432,col433,col434,col435,col436,col437,col438,col439,col440,col441,col442,col443,col444,col445,col446,col447,col448,col449,col450,col451,col452,col453,col454,col455,col456,col457,col458,col459,col460,col461,col462,col463,col464,col465,col466,col467,col468,col469,col470,col471,col472,col473,col474,col475,col476,col477,col478,col479,col480,col481,col482,col483,col484,col485,col486,col487,col488,col489,col490,col491,col492,col493,col494,col495,col496,col497,col498,col499,col500,col501,col502,col503,col504,col505,col506,col507,col508,col509,col510,col511,col512,col513,col514,col515,col516,col517,col518,col519,col520,col521,col522,col523,col524,col525,col526,col527,col528,col529,col530,col531,col532,col533,col534,col535,col536,col537,col538,col539,col540,col541,col542,col543,col544,col545,col546,col547,col548,col549,col550,col551,col552,col553,col554,col555,col556,col557,col558,col559,col560,col561,col562,col563,col564,col565,col566,col567,col568,col569,col570,col571,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
000001,20241231,2.15,2.16,12.55,21.89,4.16,8.99,3.26,4.010630e+11,6.295710e+11,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,2.980000e+08,8.634000e+09,0.000000e+00,0.0,0.0,0.0,0.0,6.238000e+09,0.0,7.568000e+09,0.000000e+00,5.232900e+10,0.000000e+00,0.000000e+00,5.769270e+12,0.000000e+00,1.373560e+11,0.0,0.000000e+00,0.000000e+00,1.616300e+10,1.417200e+10,0.0,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.952000e+11,0.00,0.0,5.828000e+09,0.000000e+00,0.000000e+00,0.000000e+00,5.274428e+12,1.940600e+10,8.071300e+10,1.078100e+10,0.000000e+00,2.436050e+11,0.000000e+00,0.0,0.0,4.948420e+11,5.769270e+12,1.466950e+11,9.148900e+10,1.479000e+09,0.000000e+00,4.058200e+10,0.0,0.000000e+00,489000000.0,3.104000e+09,2.460400e+10,0.000000e+00,382000000.0,5.520600e+10,0.0,3.700000e+07,5.050000e+08,0.0,0.0,5.473800e+10,1.023000e+10,0.0,4.450800e+10,4.450800e+10,0.000000e+00,0.000000e+00,0.000000e+00,1.337920e+11,5.308070e+11,0.000000e+00,2.015200e+10,2.382700e+10,2.833490e+11,4.674710e+11,6.333600e+10,6.097200e+11,3.681200e+10,3.450000e+08,0.000000e+00,0.000000e+00,6.468770e+11,2.388000e+09,6.763480e+11,0.000000e+00,0.0,6.787360e+11,-3.185900e+10,0.000000e+00,0.000000e+00,0.0,7.339970e+11,7.784650e+11,2.157600e+10,4.700000e+07,8.079300e+11,-7.393300e+10,1.183000e+09,0.0,-4.127300e+10,2.982190e+11,2.569460e+11,4.450800e+10,4.890000e+08,1.591000e+09,8.140000e+08,6.090000e+08,3.200000e+07,0.00,-6.184000e+09,0.000000e+00,-3.670700e+10,-6.507000e+09,0.00,0.000000e+00,-2.029850e+11,1.998980e+11,0.0,6.333600e+10,0.0,0.0,0.0,3.421000e+09,3.687000e+09,2.535250e+11,2.945320e+11,-4.127300e+10,0.00,0.00,0.00,0.00,0.00,0.00,0.0,1096.47,11.66,9.38,7.77,1.20,0.00,0.00,0.00,0.00,0.03,15.90,0.0,0.0,0.00,0.0,13935.0,0.30,-10.93,-4.19,4.77,-12.02,3.26,53.26,-4.70,-4.00,-3.43,0.0,105.82,37.63,1.01,0.00,8.99,4.56,30.34,0.78,30.34,0.00,27.66,27.66,0.00,4.483800e+10,0.000000e+00,0.000000e+00,0.00,91.42,0.00,0.00,0.00,0.15,0.00,0.00,0.00,0.00,3.26,361.84,239.62,0.00,43.18,78.84,-2.13,0.00,1.20,142.30,1.10,3.511300e+10,7.337000e+09,4.779000e+09,5.090000e+09,-7.382200e+10,-2.132000e+10,7.159900e+10,-2.176600e+10,1.940592e+10,1.940557e+10,0.0,0.000000e+00,486258.0,9.618541e+09,1.291641e+10,1.291641e+10,625.0,1.340276e+10,0.0,0.0,0.0,0.0,3.0,1.124512e+10,619.0,919002752.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.291641e+10,9.618541e+09,8.160453e+09,346348.0,6.826200e+10,-3.740000e+08,4.413400e+10,4.948420e+11,0.0,0.0,1.0,6.252337e+07,4.450800e+10,0.0,0.0,1.0,429232704.0,10.08,0.26,14669500.00,42923.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,2.127000e+09,6.994800e+10,1.780000e+08,8.000000e+06,4.450800e+10,0.0,0.0,0.000000e+00,0.000000e+00,6.333600e+10,4450800.00,4483800.00,-4127300.00,0.21,3511300.00,0.0,250315.0,0.0,-3185900.00,0.0,0.0,14669500.00,41011.0,0.00,0.00,5520600.00,477900.00,1.0,746881728.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,15.78,0.00,9148900.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,26725200.0,0.0,6541200.0,0.0,0.0,0.0,3271900.0,0.0,0.0,8611000.0,404019008.0,5564100.0,6455300.00,13118100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1995300.0,4999500.0,78507504.0,17665500.0,577300.00,0.00,0.00,0.00,1896200.0,0.00,504800.00,541000.00,329405312.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.15,14669500.00,88000.0,0.00,0.00,9342700.0,0.0,2411200.0,10495400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4893900.0,0.0,9148900.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9448600.0,0.0,0.0,0.0,0.0,0.0,0.0,21897900.0,660200.0,7292400.0,5612900.0,0.0,0.0,8401400.0,0.0,0.00,0.00,1500.0,4893900.00,0.00
000002,20241231,-4.17,-3.83,3.70,17.09,2.19,-24.41,0.32,8.816286e+10,1.767481e+08,18859528.0,8.110758e+09,5.445857e+10,2.214253e+11,0.0,0.0,0.0,5.190094e+11,0.0,0.0,1.334834e+10,9.175121e+11,0.0,0.0,0.0,1.155686e+11,1.410574e+11,2.061054e+10,1.539035e+09,0.0,0.0,253894480.0,0.0,8.297477e+09,0.0,5.540442e+09,7.964030e+09,4.406704e+10,5.195548e+09,3.687478e+11,1.286260e+12,1.597306e+10,0.000000e+00,0.0,1.600330e+11,1.890662e+09,3.716231e+09,2.892741e+10,0.0,0.00,1.523171e+11,0.0,1.460456e+11,1.775002e+10,7.190618e+11,1.788862e+11,2.411313e+10,0.00,0.0,1.327118e+09,5.348730e+09,1.775205e+09,2.283434e+11,9.474052e+11,1.193071e+10,2.609774e+10,1.262275e+11,1.291800e+09,4.413787e+10,1.361882e+11,0.0,0.0,3.388547e+11,1.286260e+12,3.431764e+11,3.082649e+11,1.836092e+10,1.038357e+10,6.394206e+09,0.0,5.938736e+09,0.0,-1.048092e+07,-2.859268e+09,-3.195824e+09,0.0,-4.564380e+10,0.0,9.359063e+08,2.478669e+09,0.0,0.0,-4.718656e+10,1.517375e+09,0.0,-4.870393e+10,-4.947843e+10,7.744948e+08,2.009983e+11,0.000000e+00,1.862389e+10,2.196222e+11,1.456297e+11,1.958304e+10,3.189102e+10,1.871860e+10,2.158223e+11,3.799848e+09,3.628292e+09,4.247741e+09,3.704233e+09,2.086556e+09,6.021378e+09,1.968820e+10,4.519612e+09,2.629422e+09,1.148035e+09,582000320.0,8.879070e+09,1.080913e+10,4.843215e+08,7.780713e+10,0.0,7.829146e+10,7.902029e+10,1.716904e+10,2.645283e+09,1.059645e+11,-2.767300e+10,1.308358e+08,0.0,-1.293319e+10,9.694258e+10,8.400939e+10,-4.870393e+10,7.168377e+09,4.287308e+09,2.309870e+09,0.000000e+00,2.534175e+09,0.00,1.048092e+07,5.938736e+09,2.859268e+09,-3.792366e+09,43877652.00,1.988905e+11,4.787210e+09,-2.010559e+11,0.0,3.799848e+09,0.0,0.0,0.0,8.400939e+10,9.694258e+10,0.000000e+00,0.000000e+00,-1.293319e+10,1.28,0.55,12.26,-7.73,24.10,75.90,0.0,501.73,3.80,35.77,11.48,0.40,-3.71,44.56,0.50,1.30,0.25,17.23,8.0,713.0,0.33,1085.0,1464.0,1.51,-26.32,-506.81,-19.19,7.16,-14.53,-206.38,-256.04,-561.45,-563.49,0.0,-13.94,-13.30,5.35,89.83,-24.41,-2.32,-14.19,-3.55,-14.42,10.17,6.62,1.86,1.73,-4.539372e+10,-4.178007e+10,-3.518290e+10,-10.25,73.66,71.33,9.61,56.57,1.60,314.90,35.70,92.82,39.28,0.32,64.00,0.00,58.57,1.11,51.82,-1.08,0.53,0.40,-7.80,0.29,1.232816e+11,-3.097656e+10,-3.153513e+10,-3.092611e+10,8.647498e+09,5.177626e+09,-7.267151e+09,6.681761e+09,1.193071e+10,9.716936e+09,0.0,2.206513e+09,572979.0,3.242811e+09,6.425681e+09,6.425681e+09,367.0,4.753035e+09,0.0,0.0,0.0,0.0,0.0,0.000000e+00,362.0,839720000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.219360e+09,3.242811e+09,6.474125e+09,7260668.0,0.000000e+00,3.270909e+08,-4.837684e+10,2.026665e+11,0.0,0.0,1.0,3.242811e+09,-4.870393e+10,0.0,0.0,2.0,318147584.0,-21.82,-2.59,34317644.00,31814.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.600330e+11,8.129618e+09,0.0,-4.435569e+09,0.000000e+00,0.000000e+00,-2.534175e+09,-4.870393e+10,0.0,507843776.0,7.446693e+09,2.040207e+09,3.799848e+09,-4947843.00,-4539372.00,-1293318.50,-2.66,12328161.00,0.0,250401.0,0.0,1080913.00,0.0,0.0,34317644.00,127638.0,7.64,7.53,-4564379.50,-3230582.50,1.0,206101296.0,38.53,10926474.00,-6.92,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,30826488.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4763.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113217.96,103637.28,19236112.00,1280124.50,0.0,0.00,1648528.62,1689298.62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.17,34317644.00,0.0,-4916353.00,78668.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34985016.00,-2639778.25,-716837.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48432.15,388128.53,0.0,2639778.25,212450.73
000004,20241231,-0.99,-0.94,-9.93,0.48,9.31,-205.40,-0.13,7.225388e+07,0.000000e+00,135200.0,7.870248e+07,6.309883e+06,9.677819e+06,0.0,0.0,0.0,5.224578e+06,0.0,0.0,2.612143e+06,1.749160e+08,0.0,0.0,0.0,0.000000e+00,3.248622e+05,1.123674e+07,5.933809e+04,0.0,0.0,0.0,0.0,3.319552e+07,0.0,6.000000e+05,0.000000e+00,7.145849e+07,0.000000e+00,1.362928e+08,3.112088e+08,3.303428e+06,0.000000e+00,0.0,9.926132e+07,0.000000e+00,1.445015e+07,3.637395e+07,0.0,212157.58,1.086101e+07,0.0,3.951011e+06,2.697971e+06,2.012310e+08,0.000000e+00,0.000000e+00,800000.00,0.0,2.496800e+07,4.573655e+06,0.000000e+00,3.706457e+07,2.382956e+08,1.323803e+08,1.232191e+09,1.341421e+07,0.000000e+00,-1.313947e+09,8.874545e+06,0.0,0.0,7.291317e+07,3.112088e+08,9.866035e+07,2.278943e+07,4.559255e+05,3.855981e+07,3.558326e+07,0.0,1.488844e+05,0.0,0.000000e+00,3.299202e+05,0.000000e+00,0.0,-1.514314e+08,0.0,3.370679e+06,1.095195e+07,0.0,0.0,-1.590126e+08,-2.179516e+07,0.0,-1.372175e+08,-1.315354e+08,-5.682056e+06,1.211885e+08,0.000000e+00,8.473426e+06,1.296620e+08,2.846411e+07,7.736424e+07,5.612256e+06,3.489325e+07,1.463339e+08,-1.667189e+07,0.000000e+00,2.711306e+05,0.000000e+00,2.875132e+04,9.389862e+07,9.419851e+07,3.517907e+06,6.000000e+05,0.000000e+00,90000000.0,9.411790e+07,8.060230e+04,1.441087e+06,0.000000e+00,0.0,1.441087e+06,0.000000e+00,0.000000e+00,4.361576e+06,4.361576e+06,-2.920490e+06,-2.009300e+02,0.0,-1.951198e+07,8.990077e+07,7.038879e+07,-1.372175e+08,1.163522e+08,6.610997e+05,4.393822e+06,0.000000e+00,0.000000e+00,0.00,0.000000e+00,6.651819e+05,-3.299202e+05,-2.230460e+07,2614829.25,-4.064850e+06,1.757456e+07,1.980048e+06,0.0,-1.667189e+07,0.0,0.0,0.0,7.038879e+07,8.990077e+07,0.000000e+00,0.000000e+00,-1.951198e+07,0.87,0.84,35.91,-1430.56,15.55,84.45,0.0,787.93,4.27,30.60,35.04,-7.00,-64.56,0.76,7.14,1.92,0.27,15.38,475.0,50.0,0.40,911.0,1322.0,0.76,-10.35,16.22,-67.26,604.59,-24.73,-34.24,0.82,9.97,10.16,0.0,-140.68,-153.49,0.46,23.10,-205.40,0.00,-139.08,-36.30,-133.32,76.90,75.30,36.07,0.15,-1.242331e+08,-1.589016e+08,-1.538466e+08,-155.94,76.57,56.21,41.31,2.99,3.61,542.92,89.56,976.52,-128.87,-0.13,131.42,0.00,122.83,-16.90,43.66,-0.15,-8.28,-7.00,12.15,-5.36,2.276598e+07,-1.143894e+08,-9.570866e+07,-9.105405e+07,7.147442e+06,3.527168e+06,-4.946587e+05,1.017975e+07,1.323803e+08,1.262881e+08,0.0,0.000000e+00,43814.0,2.420685e+07,4.317627e+07,4.778478e+07,5.0,3.726585e+07,1.0,392553.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.317627e+07,2.420685e+07,9.339390e+07,6092189.0,0.000000e+00,0.000000e+00,-1.372175e+08,6.403862e+07,0.0,0.0,4.0,3.687330e+07,-1.372175e+08,0.0,0.0,0.0,0.0,-101.33,-0.69,9866.04,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.926132e+07,7.883768e+07,471532.5,0.000000e+00,0.000000e+00,5.876499e+05,1.790425e+05,-1.372175e+08,0.0,37298772.0,6.651819e+05,5.541057e+05,-1.667189e+07,-13153.54,-12423.31,-1951.20,-0.72,2276.60,0.0,250429.0,0.0,8.06,0.0,0.0,9866.04,0.0,0.17,0.17,-15143.14,-9984.07,0.0,0.0,3.13,226.52,-94.67,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,2278.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1084.96,0.00,3033.22,0.00,0.0,0.00,856.82,625.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.99,9866.04,0.0,-13153.54,-568.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13483.61,-11635.22,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,144.11,0.00,0.0,0.00,300.32

In [164]:
dd

,report_date,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50,col51,col52,col53,col54,col55,col56,col57,col58,col59,col60,col61,col62,col63,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80,col81,col82,col83,col84,col85,col86,col87,col88,col89,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99,col100,col101,col102,col103,col104,col105,col106,col107,col108,col109,col110,col111,col112,col113,col114,col115,col116,col117,col118,col119,col120,col121,col122,col123,col124,col125,col126,col127,col128,col129,col130,col131,col132,col133,col134,col135,col136,col137,col138,col139,col140,col141,col142,col143,col144,col145,col146,col147,col148,col149,col150,col151,col152,col153,col154,col155,col156,col157,col158,col159,col160,col161,col162,col163,col164,col165,col166,col167,col168,col169,col170,col171,col172,col173,col174,col175,col176,col177,col178,col179,col180,col181,col182,col183,col184,col185,col186,col187,col188,col189,col190,col191,col192,col193,col194,col195,col196,col197,col198,col199,col200,col201,col202,col203,col204,col205,col206,col207,col208,col209,col210,col211,col212,col213,col214,col215,col216,col217,col218,col219,col220,col221,col222,col223,col224,col225,col226,col227,col228,col229,col230,col231,col232,col233,col234,col235,col236,col237,col238,col239,col240,col241,col242,col243,col244,col245,col246,col247,col248,col249,col250,col251,col252,col253,col254,col255,col256,col257,col258,col259,col260,col261,col262,col263,col264,col265,col266,col267,col268,col269,col270,col271,col272,col273,col274,col275,col276,col277,col278,col279,col280,col281,col282,col283,col284,col285,col286,col287,col288,col289,col290,col291,col292,col293,col294,col295,col296,col297,col298,col299,col300,col301,col302,col303,col304,col305,col306,col307,col308,col309,col310,col311,col312,col313,col314,col315,col316,col317,col318,col319,col320,col321,col322,col323,col324,col325,col326,col327,col328,col329,col330,col331,col332,col333,col334,col335,col336,col337,col338,col339,col340,col341,col342,col343,col344,col345,col346,col347,col348,col349,col350,col351,col352,col353,col354,col355,col356,col357,col358,col359,col360,col361,col362,col363,col364,col365,col366,col367,col368,col369,col370,col371,col372,col373,col374,col375,col376,col377,col378,col379,col380,col381,col382,col383,col384,col385,col386,col387,col388,col389,col390,col391,col392,col393,col394,col395,col396,col397,col398,col399,col400,col401,col402,col403,col404,col405,col406,col407,col408,col409,col410,col411,col412,col413,col414,col415,col416,col417,col418,col419,col420,col421,col422,col423,col424,col425,col426,col427,col428,col429,col430,col431,col432,col433,col434,col435,col436,col437,col438,col439,col440,col441,col442,col443,col444,col445,col446,col447,col448,col449,col450,col451,col452,col453,col454,col455,col456,col457,col458,col459,col460,col461,col462,col463,col464,col465,col466,col467,col468,col469,col470,col471,col472,col473,col474,col475,col476,col477,col478,col479,col480,col481,col482,col483,col484,col485,col486,col487,col488,col489,col490,col491,col492,col493,col494,col495,col496,col497,col498,col499,col500,col501,col502,col503,col504,col505,col506,col507,col508,col509,col510,col511,col512,col513,col514,col515,col516,col517,col518,col519,col520,col521,col522,col523,col524,col525,col526,col527,col528,col529,col530,col531,col532,col533,col534,col535,col536,col537,col538,col539,col540,col541,col542,col543,col544,col545,col546,col547,col548,col549,col550,col551,col552,col553,col554,col555,col556,col557,col558,col559,col560,col561,col562,col563,col564,col565,col566,col567,col568,col569,col570,col571,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
000001,20241231,2.15,2.16,12.55,21.89,4.16,8.99,3.26,4.010630e+11,6.295710e+11,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,2.980000e+08,8.634000e+09,0.000000e+00,0.0,0.0,0.0,0.0,6.238000e+09,0.0,7.568000e+09,0.000000e+00,5.232900e+10,0.000000e+00,0.000000e+00,5.769270e+12,0.000000e+00,1.373560e+11,0.0,0.000000e+00,0.000000e+00,1.616300e+10,1.417200e+10,0.0,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.952000e+11,0.00,0.0,5.828000e+09,0.000000e+00,0.000000e+00,0.000000e+00,5.274428e+12,1.940600e+10,8.071300e+10,1.078100e+10,0.000000e+00,2.436050e+11,0.000000e+00,0.0,0.0,4.948420e+11,5.769270e+12,1.466950e+11,9.148900e+10,1.479000e+09,0.000000e+00,4.058200e+10,0.0,0.000000e+00,489000000.0,3.104000e+09,2.460400e+10,0.000000e+00,382000000.0,5.520600e+10,0.0,3.700000e+07,5.050000e+08,0.0,0.0,5.473800e+10,1.023000e+10,0.0,4.450800e+10,4.450800e+10,0.000000e+00,0.000000e+00,0.000000e+00,1.337920e+11,5.308070e+11,0.000000e+00,2.015200e+10,2.382700e+10,2.833490e+11,4.674710e+11,6.333600e+10,6.097200e+11,3.681200e+10,3.450000e+08,0.000000e+00,0.000000e+00,6.468770e+11,2.388000e+09,6.763480e+11,0.000000e+00,0.0,6.787360e+11,-3.185900e+10,0.000000e+00,0.000000e+00,0.0,7.339970e+11,7.784650e+11,2.157600e+10,4.700000e+07,8.079300e+11,-7.393300e+10,1.183000e+09,0.0,-4.127300e+10,2.982190e+11,2.569460e+11,4.450800e+10,4.890000e+08,1.591000e+09,8.140000e+08,6.090000e+08,3.200000e+07,0.00,-6.184000e+09,0.000000e+00,-3.670700e+10,-6.507000e+09,0.00,0.000000e+00,-2.029850e+11,1.998980e+11,0.0,6.333600e+10,0.0,0.0,0.0,3.421000e+09,3.687000e+09,2.535250e+11,2.945320e+11,-4.127300e+10,0.00,0.00,0.00,0.00,0.00,0.00,0.0,1096.47,11.66,9.38,7.77,1.20,0.00,0.00,0.00,0.00,0.03,15.90,0.0,0.0,0.00,0.0,13935.0,0.30,-10.93,-4.19,4.77,-12.02,3.26,53.26,-4.70,-4.00,-3.43,0.0,105.82,37.63,1.01,0.00,8.99,4.56,30.34,0.78,30.34,0.00,27.66,27.66,0.00,4.483800e+10,0.000000e+00,0.000000e+00,0.00,91.42,0.00,0.00,0.00,0.15,0.00,0.00,0.00,0.00,3.26,361.84,239.62,0.00,43.18,78.84,-2.13,0.00,1.20,142.30,1.10,3.511300e+10,7.337000e+09,4.779000e+09,5.090000e+09,-7.382200e+10,-2.132000e+10,7.159900e+10,-2.176600e+10,1.940592e+10,1.940557e+10,0.0,0.000000e+00,486258.0,9.618541e+09,1.291641e+10,1.291641e+10,625.0,1.340276e+10,0.0,0.0,0.0,0.0,3.0,1.124512e+10,619.0,919002752.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.291641e+10,9.618541e+09,8.160453e+09,346348.0,6.826200e+10,-3.740000e+08,4.413400e+10,4.948420e+11,0.0,0.0,1.0,6.252337e+07,4.450800e+10,0.0,0.0,1.0,429232704.0,10.08,0.26,14669500.00,42923.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,2.127000e+09,6.994800e+10,1.780000e+08,8.000000e+06,4.450800e+10,0.0,0.0,0.000000e+00,0.000000e+00,6.333600e+10,4450800.00,4483800.00,-4127300.00,0.21,3511300.00,0.0,250315.0,0.0,-3185900.00,0.0,0.0,14669500.00,41011.0,0.00,0.00,5520600.00,477900.00,1.0,746881728.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,15.78,0.00,9148900.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,26725200.0,0.0,6541200.0,0.0,0.0,0.0,3271900.0,0.0,0.0,8611000.0,404019008.0,5564100.0,6455300.00,13118100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1995300.0,4999500.0,78507504.0,17665500.0,577300.00,0.00,0.00,0.00,1896200.0,0.00,504800.00,541000.00,329405312.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.15,14669500.00,88000.0,0.00,0.00,9342700.0,0.0,2411200.0,10495400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4893900.0,0.0,9148900.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9448600.0,0.0,0.0,0.0,0.0,0.0,0.0,21897900.0,660200.0,7292400.0,5612900.0,0.0,0.0,8401400.0,0.0,0.00,0.00,1500.0,4893900.00,0.00
000002,20241231,-4.17,-3.83,3.70,17.09,2.19,-24.41,0.32,8.816286e+10,1.767481e+08,18859528.0,8.110758e+09,5.445857e+10,2.214253e+11,0.0,0.0,0.0,5.190094e+11,0.0,0.0,1.334834e+10,9.175121e+11,0.0,0.0,0.0,1.155686e+11,1.410574e+11,2.061054e+10,1.539035e+09,0.0,0.0,253894480.0,0.0,8.297477e+09,0.0,5.540442e+09,7.964030e+09,4.406704e+10,5.195548e+09,3.687478e+11,1.286260e+12,1.597306e+10,0.000000e+00,0.0,1.600330e+11,1.890662e+09,3.716231e+09,2.892741e+10,0.0,0.00,1.523171e+11,0.0,1.460456e+11,1.775002e+10,7.190618e+11,1.788862e+11,2.411313e+10,0.00,0.0,1.327118e+09,5.348730e+09,1.775205e+09,2.283434e+11,9.474052e+11,1.193071e+10,2.609774e+10,1.262275e+11,1.291800e+09,4.413787e+10,1.361882e+11,0.0,0.0,3.388547e+11,1.286260e+12,3.431764e+11,3.082649e+11,1.836092e+10,1.038357e+10,6.394206e+09,0.0,5.938736e+09,0.0,-1.048092e+07,-2.859268e+09,-3.195824e+09,0.0,-4.564380e+10,0.0,9.359063e+08,2.478669e+09,0.0,0.0,-4.718656e+10,1.517375e+09,0.0,-4.870393e+10,-4.947843e+10,7.744948e+08,2.009983e+11,0.000000e+00,1.862389e+10,2.196222e+11,1.456297e+11,1.958304e+10,3.189102e+10,1.871860e+10,2.158223e+11,3.799848e+09,3.628292e+09,4.247741e+09,3.704233e+09,2.086556e+09,6.021378e+09,1.968820e+10,4.519612e+09,2.629422e+09,1.148035e+09,582000320.0,8.879070e+09,1.080913e+10,4.843215e+08,7.780713e+10,0.0,7.829146e+10,7.902029e+10,1.716904e+10,2.645283e+09,1.059645e+11,-2.767300e+10,1.308358e+08,0.0,-1.293319e+10,9.694258e+10,8.400939e+10,-4.870393e+10,7.168377e+09,4.287308e+09,2.309870e+09,0.000000e+00,2.534175e+09,0.00,1.048092e+07,5.938736e+09,2.859268e+09,-3.792366e+09,43877652.00,1.988905e+11,4.787210e+09,-2.010559e+11,0.0,3.799848e+09,0.0,0.0,0.0,8.400939e+10,9.694258e+10,0.000000e+00,0.000000e+00,-1.293319e+10,1.28,0.55,12.26,-7.73,24.10,75.90,0.0,501.73,3.80,35.77,11.48,0.40,-3.71,44.56,0.50,1.30,0.25,17.23,8.0,713.0,0.33,1085.0,1464.0,1.51,-26.32,-506.81,-19.19,7.16,-14.53,-206.38,-256.04,-561.45,-563.49,0.0,-13.94,-13.30,5.35,89.83,-24.41,-2.32,-14.19,-3.55,-14.42,10.17,6.62,1.86,1.73,-4.539372e+10,-4.178007e+10,-3.518290e+10,-10.25,73.66,71.33,9.61,56.57,1.60,314.90,35.70,92.82,39.28,0.32,64.00,0.00,58.57,1.11,51.82,-1.08,0.53,0.40,-7.80,0.29,1.232816e+11,-3.097656e+10,-3.153513e+10,-3.092611e+10,8.647498e+09,5.177626e+09,-7.267151e+09,6.681761e+09,1.193071e+10,9.716936e+09,0.0,2.206513e+09,572979.0,3.242811e+09,6.425681e+09,6.425681e+09,367.0,4.753035e+09,0.0,0.0,0.0,0.0,0.0,0.000000e+00,362.0,839720000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.219360e+09,3.242811e+09,6.474125e+09,7260668.0,0.000000e+00,3.270909e+08,-4.837684e+10,2.026665e+11,0.0,0.0,1.0,3.242811e+09,-4.870393e+10,0.0,0.0,2.0,318147584.0,-21.82,-2.59,34317644.00,31814.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.600330e+11,8.129618e+09,0.0,-4.435569e+09,0.000000e+00,0.000000e+00,-2.534175e+09,-4.870393e+10,0.0,507843776.0,7.446693e+09,2.040207e+09,3.799848e+09,-4947843.00,-4539372.00,-1293318.50,-2.66,12328161.00,0.0,250401.0,0.0,1080913.00,0.0,0.0,34317644.00,127638.0,7.64,7.53,-4564379.50,-3230582.50,1.0,206101296.0,38.53,10926474.00,-6.92,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,30826488.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4763.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113217.96,103637.28,19236112.00,1280124.50,0.0,0.00,1648528.62,1689298.62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.17,34317644.00,0.0,-4916353.00,78668.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34985016.00,-2639778.25,-716837.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48432.15,388128.53,0.0,2639778.25,212450.73
000004,20241231,-0.99,-0.94,-9.93,0.48,9.31,-205.40,-0.13,7.225388e+07,0.000000e+00,135200.0,7.870248e+07,6.309883e+06,9.677819e+06,0.0,0.0,0.0,5.224578e+06,0.0,0.0,2.612143e+06,1.749160e+08,0.0,0.0,0.0,0.000000e+00,3.248622e+05,1.123674e+07,5.933809e+04,0.0,0.0,0.0,0.0,3.319552e+07,0.0,6.000000e+05,0.000000e+00,7.145849e+07,0.000000e+00,1.362928e+08,3.112088e+08,3.303428e+06,0.000000e+00,0.0,9.926132e+07,0.000000e+00,1.445015e+07,3.637395e+07,0.0,212157.58,1.086101e+07,0.0,3.951011e+06,2.697971e+06,2.012310e+08,0.000000e+00,0.000000e+00,800000.00,0.0,2.496800e+07,4.573655e+06,0.000000e+00,3.706457e+07,2.382956e+08,1.323803e+08,1.232191e+09,1.341421e+07,0.000000e+00,-1.313947e+09,8.874545e+06,0.0,0.0,7.291317e+07,3.112088e+08,9.866035e+07,2.278943e+07,4.559255e+05,3.855981e+07,3.558326e+07,0.0,1.488844e+05,0.0,0.000000e+00,3.299202e+05,0.000000e+00,0.0,-1.514314e+08,0.0,3.370679e+06,1.095195e+07,0.0,0.0,-1.590126e+08,-2.179516e+07,0.0,-1.372175e+08,-1.315354e+08,-5.682056e+06,1.211885e+08,0.000000e+00,8.473426e+06,1.296620e+08,2.846411e+07,7.736424e+07,5.612256e+06,3.489325e+07,1.463339e+08,-1.667189e+07,0.000000e+00,2.711306e+05,0.000000e+00,2.875132e+04,9.389862e+07,9.419851e+07,3.517907e+06,6.000000e+05,0.000000e+00,90000000.0,9.411790e+07,8.060230e+04,1.441087e+06,0.000000e+00,0.0,1.441087e+06,0.000000e+00,0.000000e+00,4.361576e+06,4.361576e+06,-2.920490e+06,-2.009300e+02,0.0,-1.951198e+07,8.990077e+07,7.038879e+07,-1.372175e+08,1.163522e+08,6.610997e+05,4.393822e+06,0.000000e+00,0.000000e+00,0.00,0.000000e+00,6.651819e+05,-3.299202e+05,-2.230460e+07,2614829.25,-4.064850e+06,1.757456e+07,1.980048e+06,0.0,-1.667189e+07,0.0,0.0,0.0,7.038879e+07,8.990077e+07,0.000000e+00,0.000000e+00,-1.951198e+07,0.87,0.84,35.91,-1430.56,15.55,84.45,0.0,787.93,4.27,30.60,35.04,-7.00,-64.56,0.76,7.14,1.92,0.27,15.38,475.0,50.0,0.40,911.0,1322.0,0.76,-10.35,16.22,-67.26,604.59,-24.73,-34.24,0.82,9.97,10.16,0.0,-140.68,-153.49,0.46,23.10,-205.40,0.00,-139.08,-36.30,-133.32,76.90,75.30,36.07,0.15,-1.242331e+08,-1.589016e+08,-1.538466e+08,-155.94,76.57,56.21,41.31,2.99,3.61,542.92,89.56,976.52,-128.87,-0.13,131.42,0.00,122.83,-16.90,43.66,-0.15,-8.28,-7.00,12.15,-5.36,2.276598e+07,-1.143894e+08,-9.570866e+07,-9.105405e+07,7.147442e+06,3.527168e+06,-4.946587e+05,1.017975e+07,1.323803e+08,1.262881e+08,0.0,0.000000e+00,43814.0,2.420685e+07,4.317627e+07,4.778478e+07,5.0,3.726585e+07,1.0,392553.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.317627e+07,2.420685e+07,9.339390e+07,6092189.0,0.000000e+00,0.000000e+00,-1.372175e+08,6.403862e+07,0.0,0.0,4.0,3.687330e+07,-1.372175e+08,0.0,0.0,0.0,0.0,-101.33,-0.69,9866.04,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.926132e+07,7.883768e+07,471532.5,0.000000e+00,0.000000e+00,5.876499e+05,1.790425e+05,-1.372175e+08,0.0,37298772.0,6.651819e+05,5.541057e+05,-1.667189e+07,-13153.54,-12423.31,-1951.20,-0.72,2276.60,0.0,250429.0,0.0,8.06,0.0,0.0,9866.04,0.0,0.17,0.17,-15143.14,-9984.07,0.0,0.0,3.13,226.52,-94.67,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,2278.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1084.96,0.00,3033.22,0.00,0.0,0.00,856.82,625.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.99,9866.04,0.0,-13153.54,-568.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13483.61,-11635.22,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,144.11,0.00,0.0,0.00,300.32

In [167]:
from sqlalchemy import create_engine
conn = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')

In [176]:
raw = pd.read_sql('000001', conn)

In [171]:
raw['report_date'].tail(1).tolist()[0] == 20250331

True

In [178]:
raw.drop(raw.tail(1).index).set_index('report_date')

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50,col51,col52,col53,col54,col55,col56,col57,col58,col59,col60,col61,col62,col63,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80,col81,col82,col83,col84,col85,col86,col87,col88,col89,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99,col100,col101,col102,col103,col104,col105,col106,col107,col108,col109,col110,col111,col112,col113,col114,col115,col116,col117,col118,col119,col120,col121,col122,col123,col124,col125,col126,col127,col128,col129,col130,col131,col132,col133,col134,col135,col136,col137,col138,col139,col140,col141,col142,col143,col144,col145,col146,col147,col148,col149,col150,col151,col152,col153,col154,col155,col156,col157,col158,col159,col160,col161,col162,col163,col164,col165,col166,col167,col168,col169,col170,col171,col172,col173,col174,col175,col176,col177,col178,col179,col180,col181,col182,col183,col184,col185,col186,col187,col188,col189,col190,col191,col192,col193,col194,col195,col196,col197,col198,col199,col200,col201,col202,col203,col204,col205,col206,col207,col208,col209,col210,col211,col212,col213,col214,col215,col216,col217,col218,col219,col220,col221,col222,col223,col224,col225,col226,col227,col228,col229,col230,col231,col232,col233,col234,col235,col236,col237,col238,col239,col240,col241,col242,col243,col244,col245,col246,col247,col248,col249,col250,col251,col252,col253,col254,col255,col256,col257,col258,col259,col260,col261,col262,col263,col264,col265,col266,col267,col268,col269,col270,col271,col272,col273,col274,col275,col276,col277,col278,col279,col280,col281,col282,col283,col284,col285,col286,col287,col288,col289,col290,col291,col292,col293,col294,col295,col296,col297,col298,col299,col300,col301,col302,col303,col304,col305,col306,col307,col308,col309,col310,col311,col312,col313,col314,col315,col316,col317,col318,col319,col320,col321,col322,col323,col324,col325,col326,col327,col328,col329,col330,col331,col332,col333,col334,col335,col336,col337,col338,col339,col340,col341,col342,col343,col344,col345,col346,col347,col348,col349,col350,col351,col352,col353,col354,col355,col356,col357,col358,col359,col360,col361,col362,col363,col364,col365,col366,col367,col368,col369,col370,col371,col372,col373,col374,col375,col376,col377,col378,col379,col380,col381,col382,col383,col384,col385,col386,col387,col388,col389,col390,col391,col392,col393,col394,col395,col396,col397,col398,col399,col400,col401,col402,col403,col404,col405,col406,col407,col408,col409,col410,col411,col412,col413,col414,col415,col416,col417,col418,col419,col420,col421,col422,col423,col424,col425,col426,col427,col428,col429,col430,col431,col432,col433,col434,col435,col436,col437,col438,col439,col440,col441,col442,col443,col444,col445,col446,col447,col448,col449,col450,col451,col452,col453,col454,col455,col456,col457,col458,col459,col460,col461,col462,col463,col464,col465,col466,col467,col468,col469,col470,col471,col472,col473,col474,col475,col476,col477,col478,col479,col480,col481,col482,col483,col484,col485,col486,col487,col488,col489,col490,col491,col492,col493,col494,col495,col496,col497,col498,col499,col500,col501,col502,col503,col504,col505,col506,col507,col508,col509,col510,col511,col512,col513,col514,col515,col516,col517,col518,col519,col520,col521,col522,col523,col524,col525,col526,col527,col528,col529,col530,col531,col532,col533,col534,col535,col536,col537,col538,col539,col540,col541,col542,col543,col544,col545,col546,col547,col548,col549,col550,col551,col552,col553,col554,col555,col556,col557,col558,col559,col560,col561,col562,col563,col564,col565,col566,col567,col568,col569,col570,col571,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
report_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20000630,0.12,0.00,0.22,1.98,0.19,5.78,0.11,3.266945e+08,2.967018e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,552948224.0,0.0,0.0,0.0,3.086580e+10,0.0,6.104075e+09,0.0,255992368.0,0.0,0.000000e+00,586453824.0,0.0,21338.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,308094848.0,0.000000e+00,0.0,2.522661e+10,4.973234e+10,103000000.0,0.000000e+00,0.0,217029200.0,70685568.0,1.080875e+08,5.526311e+07,0.0,0.0,0.0,0.0,41396500.0,0.0,3.457447e+10,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,1.207935e+10,4.665383e+10,1.551847e+09,2.913358e+08,8.942272e+08,0.0,3.411025e+08,0.0,0.0,0.0,3.078513e+09,4.973234e+10,7.251027e+08,5.245139e+08,7.316054e+07,0.0,2.917609e+08,0.0,0.0,0.0,0.000000e+00,1.610216e+08,0.0,-128402528.0,2.005888e+08,0.0,3883126.0,4019027.0,0.0,0.0,2.004528e+08,2.250000e+07,0.0,1.779528e+08,1.779528e+08,0.0,24487596.0,0.0,1.969778e+10,1.972227e+10,12849088.0,1.869859e+08,2.591014e+07,1.932418e+10,1.954993e+10,1.723404e+08,1.839519e+08,1.270354e+08,2573953.0,0.0,0.0,3.135612e+08,2.964215e+08,1.755095e+09,0.0,0.0,2.051516e+09,-1.737955e+09,0.000000e+00,80000000.0,0.0,8.000000e+07,7.451370e+07,1.330536e+08,0.000000e+00,2.075673e+08,-1.275673e+08,-2.709950e+05,0.0,-1.693453e+09,6.326918e+09,4.633465e+09,1.779528e+08,10100000.0,6.826802e+07,24585548.0,0.0,-2150888.0,87693.0,0.000000e+00,0.0,-1.610216e+08,0.000000e+00,0.0,5479993.0,-3.771740e+09,3.798001e+09,22778128.0,1.723404e+08,0.0,0.0,0.0,4.633465e+09,6.326918e+09,0.000000e+00,0.000000e+00,1.693453e+09,0.89,0.88,0.94,0.0,25.89,74.11,0.0,1515.47,16.15,6.60,0.70,0.37,0.0,2.44,0.0,0.0,0.01,0.66,74.0,0.0,0.02,7631.0,11866.0,0.24,-6.69,-26.14,6.12,-100.00,8.42,47.93,-28.10,0.00,0.00,0.0,48.76,27.66,10.09,0.0,5.78,2.88,24.54,0.37,24.54,0.0,40.24,40.24,0.0,1.779528e+08,0.0,0.0,0.0,93.81,62.06,1.06,1.79,0.00,286.23,6.25,6.66,0.71,0.00,2719.93,435.71,3.38,23.77,319.24,-0.09,0.5,0.37,96.85,0.35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.551847e+09,1.071634e+09,0.0,0.0,764125.0,0.000000e+00,0.000000e+00,4.725146e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.071634e+09,0.0,0.000000e+00,0.0,0.000000e+00,3.078513e+09,0.0,0.0,0.0,0.0,4.922253e+08,0.0,0.0,0.0,0.0,0.00,0.00,167426.48,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217029200.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,6.334547e+09,0.00,73314.39,287935.69,0.00,0.0,0.0,630.0,0.0,-275904.06,0.0,0.0,167426.48,0.0,0.0,0.0,52798.47,0.00,0.0,0.0,99.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,72510.27,1.32,0.0,0.0,52419.77,0.0,868.01,38538.29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,52451.39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
20001231,0.26,0.26,0.00,2.44,1.44,10.68,0.82,1.409918e+10,2.967786e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,7.382383e+09,0.0,109494760.0,0.0,1.587091e+09,309717248.0,0.0,36.0,0.0,0.0,1.982460e+06,0.0,0.000000e+00,204976880.0,0.000000e+00,0.0,0.000000e+00,6.722750e+10,0.0,0.000000e+00,0.0,264338496.0,0.0,1.382745e+08,5.829812e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,6.248862e+10,1.945822e+09,2.793062e+09,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,4.738884e+09,6.722750e+10,1.812893e+09,1.259262e+09,1.827924e+08,0.0,7.045079e+08,0.0,0.0,0.0,0.000000e+00,3.567043e+08,0.0,-356925568.0,5.536314e+08,0.0,9955727.0,16819034.0,0.0,0.0,5.467681e+08,4.021636e+07,0.0,5.065518e+08,5.065518e+08,0.0,0.0,0.0,1.320163e+10,8.068764e+10,0.0,3.611632e+08,2.342922e+08,4.978329e+10,7.909658e+10,1.591065e+09,1.389444e+09,2.667109e+08,0.0,0.0,2819826.0,1.658974e+09,5.767461e+08,4.182527e+09,0.0,0.0,4.759273e+09,-3.100298e+09,3.151801e+09,0.0,0.0,3.151801e+09,0.000000e+00,2.638908e+08,6.082232e+07,3.247131e+08,2.827087e+09,-3.869800e+04,0.0,1.317816e+09,6.306977e+09,7.624793e+09,5.065518e+08,105700240.0,1.395985e+08,0.0,85481624.0,11495405.0,0.0,0.000000e+00,0.0,-3.567043e+08,0.000000e+00,0.0,0.0,-1.888561e+10,1.998456e+10,0.0,1.591065e+09,0.0,0.0,0.0,3.818351e+08,8.226618e+08,7.242958e+09,5.484316e+09,1.317816e+09,0.00,0.00,0.00,0.0,0.00,0.00,0.0,1319.19,14.19,7.58,25.10,2.55,0.0,0.00,0.0,0.0,0.03,1.22,0.0,0.0,0.00,0.0,11035.0,0.62,34.88,126.61,315.11,14.28,53.10,44.88,102.20,0.00,0.00,0.0,57.09,30.54,10.08,0.0,10.68,5.87,27.94,0.91,27.94,0.0,38.86,38.86,0.0,0.000000e+00,0.0,0.0,0.0,92.95,0.00,0.00,0.00,2.36,0.00,0.00,0.00,0.00,0.82,4450.77,924.91,0.00,87.76,256.24,0.07,0.0,2.55,314.10,2.37,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.393125e+09,0.0,0.0,810000.0,0.000000e+00,0.000000e+00,5.614903e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.393125e+09,0.0,0.000000e+00,0.0,0.000000e+00,4.738884e+09,0.0,0.0,0.0,0.0,5.065518e+08,0.0,0.0,0.0,0.0,0.00,0.00,181289.34,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,264338496.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.591065e+09,50655.18,0.00,131781.56,0.00,0.0,0.0,10414.0,0.0,-310029.84,0.0,0.0,181289.34,0.0,0.0,0.0,55363.14,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,447199.75,0.0,0.0,0.0,0.0,0.0,143202.20,0.0,0.0,210625.64,5836672.0,24689.21,0.0,88000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89720.14,0.0,0.0,0.0,3670177.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,181289.34,2490.29,0.0,0.0,137689.95,0.0,3935.06,96377.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125926.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6374801.50,0.0,135322.23,0.0,0.0,0.0,0.0,238478.38,0.0,0.0,2440608.00,331091.62,0.0,100084.00,0.0,0.0,0.0,0.0,0.0,0.0
20010630,0.12,0.00,0.11,2.55,1.44,4.50,0.63,1.595289e+10,5.930400e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,7.757859e+09,0.0,109492408.0,0.0,1.725761e+09,397029920.0,0.0,26237.0,0.0,0.0,2.430274e+07,0.0,0.000000e+00,291256896.0,0.000000e+00,0.0,0.000000e+00,8.518142e+10,0.0,0.000000e+00,0.0,472936032.0,0.0,9.757162e+07,4.962526e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,8.021960e+10,1.945822e+09,2.793062e+09,0.000000e+00,0.0,2.229405e+08,0.0,0.0,0.0,4.961824e+09,8.518142e+10,1.035590e+09,7.680241e+08,9.856335e+07,0.0,3.837052e+08,0.0,0.0,0.0,0.000000e+00,1.990545e+08,0.0,-275824224.0,2.675663e+08,0.0,1926983.0,5061701.0,0.0,0.0,2.644315e+08,4.121985e+07,0.0,2.232117e+08,2.232117e+08,0.0,0.0,0.0,1.666984e+09,6.498752e+10,0.0,1.877345e+08,1.568475e+08,4.861368e+10,6.375734e+10,1.230181e+09,1.575473e+09,2.392806e+08,0.0,0.0,82243.0,1.814836e+09,6.039660e+08,1.793234e+09,0.0,0.0,2.397200e+09,-5.823643e+08,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,1.410685e+06,0.000000e+00,1.410685e+06,-1.410685e+06,-8.896800e+04,0.0,6.463173e+08,7.624793e+09,8.271110e+09,2.232117e+08,121706040.0,8.127729e+07,1128050.0,80069416.0,24272.0,0.0,0.000000e+00,0.0,-1.990545e+08,0.000000e+00,0.0,0.0,-1.681058e+10,1.773240e+10,0.0,1.230181e+09,0.0,0.0,0.0,3.619087e+08,3.818351e+08,7.909201e+09,7.242958e+09,6.463173e+08,0.00,0.00,0.00,0.0,0.00,0.00,0.0,1624.69,17.17,6.19,22.04,1.53,0.0,0.00,0.0,0.0,0.01,0.62,0.0,0.0,0.00,0.0,13245.0,0.21,62.64,59.65,4.70,8.74,26.71,28.62,72.27,0.00,27.19,0.0,46.28,25.84,9.52,0.0,4.50,2.58,21.55,0.29,21.55,0.0,37.05,37.05,0.0,2.263464e+08,0.0,0.0,0.0,94.18,0.00,0.00,0.00,2.03,0.00,0.00,0.00,0.00,0.63,6275.41,1796.15,0.00,118.79,371.73,0.03,0.0,1.53,551.13,1.44,3.105849e+08,1.057906e+08,8.438325e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.393125e+09,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.393125e+09,0.0,0.000000e+00,0.0,0.000000e+00,4.961824e+09,0.0,0.0,0.0,0.0,5.899487e+08,0.0,0.0,0.0,0.0,0.00,0.00,221174.69,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,472936032.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.643999e+09,58994.87,0.00,365241.22,0.00,0.0,0.0,10810.0,0.0,-195018.22,0.0,0.0,221174.69,0.0,0.0,0.0,66588.41,8438.32,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,640962.81,0.0,0.0,0.0,0.0,0.0,282302.22,0.0,0.0,0.00,7855152.5,32.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104554.78,0.0,0.0,0.0,4858530.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,103559.03,2.17,0.0,0.0,80654.02,0.0,2004.28,72732.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76802.41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6499169.00,0.0,-323282.72,0.0,0.0,0.0,0.0,156167.12,0.0,0.0,1306681.12,120739.72,0.0,52487.04,0.0,0.0,0.0,0.0,0.0,0.0
20011231,0.21,0.21,0.03,1.86,0.81,11.09,7.52,2.508153e+10,7.908800e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,1.293867e+10,0.0,105491552.0,0.0,1.763257e+09,475151136.0,0.0,0.0,0.0,0.0,3.566298e+07,0.0,0.000000e+00,214034896.0,0.000000e+00,0.0,0.000000e+00,1.201270e+11,0.0,0.000000e+00,0.0,384039488.0,0.0,2.195154e+08,2.023954e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,1.164993e+11,1.945822e+09,1.571729e+09,6.035406e+07,0.0,4.976324e+07,0.0,0.0,0.0,3.627669e+09,1.201270e+11,2.597465e+09,2.035716e+09,2.618429e+08,0.0,1.077854e+09,0.0,0.0,0.0,0.000000e+00,4.424909e+08,0.0,-674270592.0,5.617485e+08,0.0,10887163.0,13680079.0,0.0,0.0,5.589556e+08,1.565952e+08,0.0,4.023604e+08,4.023604e+08,0.0,0.0,0.0,4.036932e+09,5.610152e+10,0.0,4.950079e+08,2.984303e+08,2.238122e+09,4.145938e+10,1.464214e+10,2.485845e+09,4.424909e+08,0.0,0.0,6016404.0,2.934352e+09,7.001516e+08,8.087545e+09,0.0,0.0,8.787697e+09,-5.853344e+09,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,1.410685e+06,0.000000e+00,1.410685e+06,-1.410685e+06,-3.107430e+05,0.0,8.787071e+09,1.316404e+10,2.195111e+10,4.023604e+08,334905280.0,1.667791e+08,6734119.0,97299944.0,-752928.0,61895.0,0.000000e+00,0.0,-4.424909e+08,0.000000e+00,0.0,0.0,-3.957891e+10,5.363491e+10,21232396.0,1.464214e+10,0.0,0.0,0.0,2.195111e+10,1.316404e+10,0.000000e+00,0.000000e+00,8.787071e+09,0.00,0.00,0.00,0.0,0.00,0.00,0.0,3243.29,33.11,3.11,23.04,12.57,0.0,0.00,0.0,0.0,0.03,1.55,0.0,0.0,0.00,0.0,12899.0,0.73,43.28,-13.09,3.13,11.10,81.99,24.05,10.13,-19.07,0.00,0.0,30.03,21.63,10.08,0.0,11.09,4.29,15.49,0.43,15.49,0.0,41.50,41.50,0.0,4.051533e+08,0.0,0.0,0.0,96.98,0.00,0.00,0.00,1.47,0.00,0.00,0.00,0.00,7.52,2159.86,17699.69,0.00,563.71,258.54,0.45,0.0,12.57,3639.06,12.19,1.726177e+07,-2.147729e+07,3.727922e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.409362e+09,0.0,0.0,778568.0,0.000000e+00,0.000000e+00,5.491827e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.409362e+09,0.0,0.000000e+00,0.0,0.000000e+00,3.627669e+09,0.0,0.0,0.0,0.0,4.023604e+08,0.0,0.0,0.0,0.0,0.00,0.00,259746.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,384039488.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.464214e+10,40236.04,40515.33,878707.12,0.00,0.0,0.0,20418.0,0.0,-585334.38,0.0,0.0,259746.45,0.0,0.0,0.0,56174.85,3727.92,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,435069.97,0.0,0.0,0.0,0.0,0.0,638726.69,0.0,0.0,110946.20,9820083.0,1549723.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115773.46,0.0,0.0,0.0,6753839.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,259746.45,3653.22,0.0,0.0,203376.88,0.0,6292.37,169919.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,203571.59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3983410.75,0.0,840569.56,0.0,0.0,0.0,0.0,382478.16,0.0,0.0,3631091.75,52055.70,0.0,159634.44,0.0,0.0,0.0,0.0,0.0,0.0

In [175]:
raw

,report_date,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50,col51,col52,col53,col54,col55,col56,col57,col58,col59,col60,col61,col62,col63,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73,col74,col75,col76,col77,col78,col79,col80,col81,col82,col83,col84,col85,col86,col87,col88,col89,col90,col91,col92,col93,col94,col95,col96,col97,col98,col99,col100,col101,col102,col103,col104,col105,col106,col107,col108,col109,col110,col111,col112,col113,col114,col115,col116,col117,col118,col119,col120,col121,col122,col123,col124,col125,col126,col127,col128,col129,col130,col131,col132,col133,col134,col135,col136,col137,col138,col139,col140,col141,col142,col143,col144,col145,col146,col147,col148,col149,col150,col151,col152,col153,col154,col155,col156,col157,col158,col159,col160,col161,col162,col163,col164,col165,col166,col167,col168,col169,col170,col171,col172,col173,col174,col175,col176,col177,col178,col179,col180,col181,col182,col183,col184,col185,col186,col187,col188,col189,col190,col191,col192,col193,col194,col195,col196,col197,col198,col199,col200,col201,col202,col203,col204,col205,col206,col207,col208,col209,col210,col211,col212,col213,col214,col215,col216,col217,col218,col219,col220,col221,col222,col223,col224,col225,col226,col227,col228,col229,col230,col231,col232,col233,col234,col235,col236,col237,col238,col239,col240,col241,col242,col243,col244,col245,col246,col247,col248,col249,col250,col251,col252,col253,col254,col255,col256,col257,col258,col259,col260,col261,col262,col263,col264,col265,col266,col267,col268,col269,col270,col271,col272,col273,col274,col275,col276,col277,col278,col279,col280,col281,col282,col283,col284,col285,col286,col287,col288,col289,col290,col291,col292,col293,col294,col295,col296,col297,col298,col299,col300,col301,col302,col303,col304,col305,col306,col307,col308,col309,col310,col311,col312,col313,col314,col315,col316,col317,col318,col319,col320,col321,col322,col323,col324,col325,col326,col327,col328,col329,col330,col331,col332,col333,col334,col335,col336,col337,col338,col339,col340,col341,col342,col343,col344,col345,col346,col347,col348,col349,col350,col351,col352,col353,col354,col355,col356,col357,col358,col359,col360,col361,col362,col363,col364,col365,col366,col367,col368,col369,col370,col371,col372,col373,col374,col375,col376,col377,col378,col379,col380,col381,col382,col383,col384,col385,col386,col387,col388,col389,col390,col391,col392,col393,col394,col395,col396,col397,col398,col399,col400,col401,col402,col403,col404,col405,col406,col407,col408,col409,col410,col411,col412,col413,col414,col415,col416,col417,col418,col419,col420,col421,col422,col423,col424,col425,col426,col427,col428,col429,col430,col431,col432,col433,col434,col435,col436,col437,col438,col439,col440,col441,col442,col443,col444,col445,col446,col447,col448,col449,col450,col451,col452,col453,col454,col455,col456,col457,col458,col459,col460,col461,col462,col463,col464,col465,col466,col467,col468,col469,col470,col471,col472,col473,col474,col475,col476,col477,col478,col479,col480,col481,col482,col483,col484,col485,col486,col487,col488,col489,col490,col491,col492,col493,col494,col495,col496,col497,col498,col499,col500,col501,col502,col503,col504,col505,col506,col507,col508,col509,col510,col511,col512,col513,col514,col515,col516,col517,col518,col519,col520,col521,col522,col523,col524,col525,col526,col527,col528,col529,col530,col531,col532,col533,col534,col535,col536,col537,col538,col539,col540,col541,col542,col543,col544,col545,col546,col547,col548,col549,col550,col551,col552,col553,col554,col555,col556,col557,col558,col559,col560,col561,col562,col563,col564,col565,col566,col567,col568,col569,col570,col571,col572,col573,col574,col575,col576,col577,col578,col579,col580,col581
0,20000630,0.12,0.00,0.22,1.98,0.19,5.78,0.11,3.266945e+08,2.967018e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,552948224.0,0.0,0.0,0.0,3.086580e+10,0.0,6.104075e+09,0.0,255992368.0,0.0,0.000000e+00,586453824.0,0.0,21338.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,308094848.0,0.000000e+00,0.0,2.522661e+10,4.973234e+10,103000000.0,0.000000e+00,0.0,217029200.0,70685568.0,1.080875e+08,5.526311e+07,0.0,0.0,0.0,0.0,41396500.0,0.0,3.457447e+10,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,1.207935e+10,4.665383e+10,1.551847e+09,2.913358e+08,8.942272e+08,0.0,3.411025e+08,0.0,0.0,0.0,3.078513e+09,4.973234e+10,7.251027e+08,5.245139e+08,7.316054e+07,0.0,2.917609e+08,0.0,0.0,0.0,0.000000e+00,1.610216e+08,0.0,-128402528.0,2.005888e+08,0.0,3883126.0,4019027.0,0.0,0.0,2.004528e+08,2.250000e+07,0.0,1.779528e+08,1.779528e+08,0.0,24487596.0,0.0,1.969778e+10,1.972227e+10,12849088.0,1.869859e+08,2.591014e+07,1.932418e+10,1.954993e+10,1.723404e+08,1.839519e+08,1.270354e+08,2573953.0,0.0,0.0,3.135612e+08,2.964215e+08,1.755095e+09,0.0,0.0,2.051516e+09,-1.737955e+09,0.000000e+00,80000000.0,0.0,8.000000e+07,7.451370e+07,1.330536e+08,0.000000e+00,2.075673e+08,-1.275673e+08,-2.709950e+05,0.0,-1.693453e+09,6.326918e+09,4.633465e+09,1.779528e+08,10100000.0,6.826802e+07,24585548.0,0.0,-2150888.0,87693.0,0.000000e+00,0.0,-1.610216e+08,0.000000e+00,0.0,5479993.0,-3.771740e+09,3.798001e+09,22778128.0,1.723404e+08,0.0,0.0,0.0,4.633465e+09,6.326918e+09,0.000000e+00,0.000000e+00,1.693453e+09,0.89,0.88,0.94,0.0,25.89,74.11,0.0,1515.47,16.15,6.60,0.70,0.37,0.0,2.44,0.0,0.0,0.01,0.66,74.0,0.0,0.02,7631.0,11866.0,0.24,-6.69,-26.14,6.12,-100.00,8.42,47.93,-28.10,0.00,0.00,0.0,48.76,27.66,10.09,0.0,5.78,2.88,24.54,0.37,24.54,0.0,40.24,40.24,0.0,1.779528e+08,0.0,0.0,0.0,93.81,62.06,1.06,1.79,0.00,286.23,6.25,6.66,0.71,0.00,2719.93,435.71,3.38,23.77,319.24,-0.09,0.5,0.37,96.85,0.35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.551847e+09,1.071634e+09,0.0,0.0,764125.0,0.000000e+00,0.000000e+00,4.725146e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.071634e+09,0.0,0.000000e+00,0.0,0.000000e+00,3.078513e+09,0.0,0.0,0.0,0.0,4.922253e+08,0.0,0.0,0.0,0.0,0.00,0.00,167426.48,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217029200.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,6.334547e+09,0.00,73314.39,287935.69,0.00,0.0,0.0,630.0,0.0,-275904.06,0.0,0.0,167426.48,0.0,0.0,0.0,52798.47,0.00,0.0,0.0,99.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,72510.27,1.32,0.0,0.0,52419.77,0.0,868.01,38538.29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,52451.39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,20001231,0.26,0.26,0.00,2.44,1.44,10.68,0.82,1.409918e+10,2.967786e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,7.382383e+09,0.0,109494760.0,0.0,1.587091e+09,309717248.0,0.0,36.0,0.0,0.0,1.982460e+06,0.0,0.000000e+00,204976880.0,0.000000e+00,0.0,0.000000e+00,6.722750e+10,0.0,0.000000e+00,0.0,264338496.0,0.0,1.382745e+08,5.829812e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,6.248862e+10,1.945822e+09,2.793062e+09,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,4.738884e+09,6.722750e+10,1.812893e+09,1.259262e+09,1.827924e+08,0.0,7.045079e+08,0.0,0.0,0.0,0.000000e+00,3.567043e+08,0.0,-356925568.0,5.536314e+08,0.0,9955727.0,16819034.0,0.0,0.0,5.467681e+08,4.021636e+07,0.0,5.065518e+08,5.065518e+08,0.0,0.0,0.0,1.320163e+10,8.068764e+10,0.0,3.611632e+08,2.342922e+08,4.978329e+10,7.909658e+10,1.591065e+09,1.389444e+09,2.667109e+08,0.0,0.0,2819826.0,1.658974e+09,5.767461e+08,4.182527e+09,0.0,0.0,4.759273e+09,-3.100298e+09,3.151801e+09,0.0,0.0,3.151801e+09,0.000000e+00,2.638908e+08,6.082232e+07,3.247131e+08,2.827087e+09,-3.869800e+04,0.0,1.317816e+09,6.306977e+09,7.624793e+09,5.065518e+08,105700240.0,1.395985e+08,0.0,85481624.0,11495405.0,0.0,0.000000e+00,0.0,-3.567043e+08,0.000000e+00,0.0,0.0,-1.888561e+10,1.998456e+10,0.0,1.591065e+09,0.0,0.0,0.0,3.818351e+08,8.226618e+08,7.242958e+09,5.484316e+09,1.317816e+09,0.00,0.00,0.00,0.0,0.00,0.00,0.0,1319.19,14.19,7.58,25.10,2.55,0.0,0.00,0.0,0.0,0.03,1.22,0.0,0.0,0.00,0.0,11035.0,0.62,34.88,126.61,315.11,14.28,53.10,44.88,102.20,0.00,0.00,0.0,57.09,30.54,10.08,0.0,10.68,5.87,27.94,0.91,27.94,0.0,38.86,38.86,0.0,0.000000e+00,0.0,0.0,0.0,92.95,0.00,0.00,0.00,2.36,0.00,0.00,0.00,0.00,0.82,4450.77,924.91,0.00,87.76,256.24,0.07,0.0,2.55,314.10,2.37,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.393125e+09,0.0,0.0,810000.0,0.000000e+00,0.000000e+00,5.614903e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.393125e+09,0.0,0.000000e+00,0.0,0.000000e+00,4.738884e+09,0.0,0.0,0.0,0.0,5.065518e+08,0.0,0.0,0.0,0.0,0.00,0.00,181289.34,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,264338496.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.591065e+09,50655.18,0.00,131781.56,0.00,0.0,0.0,10414.0,0.0,-310029.84,0.0,0.0,181289.34,0.0,0.0,0.0,55363.14,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,447199.75,0.0,0.0,0.0,0.0,0.0,143202.20,0.0,0.0,210625.64,5836672.0,24689.21,0.0,88000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89720.14,0.0,0.0,0.0,3670177.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,181289.34,2490.29,0.0,0.0,137689.95,0.0,3935.06,96377.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125926.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6374801.50,0.0,135322.23,0.0,0.0,0.0,0.0,238478.38,0.0,0.0,2440608.00,331091.62,0.0,100084.00,0.0,0.0,0.0,0.0,0.0,0.0
2,20010630,0.12,0.00,0.11,2.55,1.44,4.50,0.63,1.595289e+10,5.930400e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,7.757859e+09,0.0,109492408.0,0.0,1.725761e+09,397029920.0,0.0,26237.0,0.0,0.0,2.430274e+07,0.0,0.000000e+00,291256896.0,0.000000e+00,0.0,0.000000e+00,8.518142e+10,0.0,0.000000e+00,0.0,472936032.0,0.0,9.757162e+07,4.962526e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,8.021960e+10,1.945822e+09,2.793062e+09,0.000000e+00,0.0,2.229405e+08,0.0,0.0,0.0,4.961824e+09,8.518142e+10,1.035590e+09,7.680241e+08,9.856335e+07,0.0,3.837052e+08,0.0,0.0,0.0,0.000000e+00,1.990545e+08,0.0,-275824224.0,2.675663e+08,0.0,1926983.0,5061701.0,0.0,0.0,2.644315e+08,4.121985e+07,0.0,2.232117e+08,2.232117e+08,0.0,0.0,0.0,1.666984e+09,6.498752e+10,0.0,1.877345e+08,1.568475e+08,4.861368e+10,6.375734e+10,1.230181e+09,1.575473e+09,2.392806e+08,0.0,0.0,82243.0,1.814836e+09,6.039660e+08,1.793234e+09,0.0,0.0,2.397200e+09,-5.823643e+08,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,1.410685e+06,0.000000e+00,1.410685e+06,-1.410685e+06,-8.896800e+04,0.0,6.463173e+08,7.624793e+09,8.271110e+09,2.232117e+08,121706040.0,8.127729e+07,1128050.0,80069416.0,24272.0,0.0,0.000000e+00,0.0,-1.990545e+08,0.000000e+00,0.0,0.0,-1.681058e+10,1.773240e+10,0.0,1.230181e+09,0.0,0.0,0.0,3.619087e+08,3.818351e+08,7.909201e+09,7.242958e+09,6.463173e+08,0.00,0.00,0.00,0.0,0.00,0.00,0.0,1624.69,17.17,6.19,22.04,1.53,0.0,0.00,0.0,0.0,0.01,0.62,0.0,0.0,0.00,0.0,13245.0,0.21,62.64,59.65,4.70,8.74,26.71,28.62,72.27,0.00,27.19,0.0,46.28,25.84,9.52,0.0,4.50,2.58,21.55,0.29,21.55,0.0,37.05,37.05,0.0,2.263464e+08,0.0,0.0,0.0,94.18,0.00,0.00,0.00,2.03,0.00,0.00,0.00,0.00,0.63,6275.41,1796.15,0.00,118.79,371.73,0.03,0.0,1.53,551.13,1.44,3.105849e+08,1.057906e+08,8.438325e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.393125e+09,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.393125e+09,0.0,0.000000e+00,0.0,0.000000e+00,4.961824e+09,0.0,0.0,0.0,0.0,5.899487e+08,0.0,0.0,0.0,0.0,0.00,0.00,221174.69,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,472936032.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.643999e+09,58994.87,0.00,365241.22,0.00,0.0,0.0,10810.0,0.0,-195018.22,0.0,0.0,221174.69,0.0,0.0,0.0,66588.41,8438.32,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,640962.81,0.0,0.0,0.0,0.0,0.0,282302.22,0.0,0.0,0.00,7855152.5,32.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,104554.78,0.0,0.0,0.0,4858530.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,103559.03,2.17,0.0,0.0,80654.02,0.0,2004.28,72732.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76802.41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6499169.00,0.0,-323282.72,0.0,0.0,0.0,0.0,156167.12,0.0,0.0,1306681.12,120739.72,0.0,52487.04,0.0,0.0,0.0,0.0,0.0,0.0
3,20011231,0.21,0.21,0.03,1.86,0.81,11.09,7.52,2.508153e+10,7.908800e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,1.293867e+10,0.0,105491552.0,0.0,1.763257e+09,475151136.0,0.0,0.0,0.0,0.0,3.566298e+07,0.0,0.000000e+00,214034896.0,0.000000e+00,0.0,0.000000e+00,1.201270e+11,0.0,0.000000e+00,0.0,384039488.0,0.0,2.195154e+08,2.023954e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,1.164993e+11,1.945822e+09,1.571729e+09,6.035406e+07,0.0,4.976324e+07,0.0,0.0,0.0,3.627669e+09,1.201270e+11,2.597465e+09,2.035716e+09,2.618429e+08,0.0,1.077854e+09,0.0,0.0,0.0,0.000000e+00,4.424909e+08,0.0,-674270592.0,5.617485e+08,0.0,10887163.0,13680079.0,0.0,0.0,5.589556e+08,1.565952e+08,0.0,4.023604e+08,4.023604e+08,0.0,0.0,0.0,4.036932e+09,5.610152e+10,0.0,4.950079e+08,2.984303e+08,2.238122e+09,4.145938e+10,1.464214e+10,2.485845e+09,4.424909e+08,0.0,0.0,6016404.0,2.934352e+09,7.001516e+08,8.087545e+09,0.0,0.0,8.787697e+09,-5.853344e+09,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,1.410685e+06,0.000000e+00,1.410685e+06,-1.410685e+06,-3.107430e+05,0.0,8.787071e+09,1.316404e+10,2.195111e+10,4.023604e+08,334905280.0,1.667791e+08,6734119.0,97299944.0,-752928.0,61895.0,0.000000e+00,0.0,-4.424909e+08,0.000000e+00,0.0,0.0,-3.957891e+10,5.363491e+10,21232396.0,1.464214e+10,0.0,0.0,0.0,2.195111e+10,1.316404e+10,0.000000e+00,0.000000e+00,8.787071e+09,0.00,0.00,0.00,0.0,0.00,0.00,0.0,3243.29,33.11,3.11,23.04,12.57,0.0,0.00,0.0,0.0,0.03,1.55,0.0,0.0,0.00,0.0,12899.0,0.73,43.28,-13.09,3.13,11.10,81.99,24.05,10.13,-19.07,0.00,0.0,30.03,21.63,10.08,0.0,11.09,4.29,15.49,0.43,15.49,0.0,41.50,41.50,0.0,4.051533e+08,0.0,0.0,0.0,96.98,0.00,0.00,0.00,1.47,0.00,0.00,0.00,0.00,7.52,2159.86,17699.69,0.00,563.71,258.54,0.45,0.0,12.57,3639.06,12.19,1.726177e+07,-2.147729e+07,3.727922e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.945822e+09,1.409362e+09,0.0,0.0,778568.0,0.000000e+00,0.000000e+00,5.491827e+08,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,1.409362e+09,0.0,0.000000e+00,0.0,0.000000e+00,3.627669e+09,0.0,0.0,0.0,0.0,4.023604e+08,0.0,0.0,0.0,0.0,0.00,0.00,259746.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,384039488.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.464214e+10,40236.04,40515.33,878707.12,0.00,0.0,0.0,20418.0,0.0,-585334.38,0.0,0.0,259746.45,0.0,0.0,0.0,56174.85,3727.92,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,435069.97,0.0,0.0,0.0,0.0,0.0,638726.69,0.0,0.0,110946.20,9820083.0,1549723.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115773.46,0.0,0.0,0.0,6753839.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,259746.45,3653.22,0.0,0.0,203376.88,0.0,6292.37,169919.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,203571.59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3983410.75,0.0,840569.56,0.0,0.0,0.0,0.0,382478.16,0.0,0.0,3631091.75,52055.70,0.0,159634.44,0.0,0.0,0.0,0.0,0.0,0.0