In [1]:

import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import plotly.express as px
from tqdm import tqdm

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [3]:
IndexRAW = pd.read_sql('optIndexs', engI)

#### List筛选

In [4]:
IndexRAW.groupby(by='IndexSTL').count()

          IndexCode  IndexName  Market  MarketName  MarketCode   DP  From  Num
IndexSTL
主题              450        450     450         450         450  432   450  450
地区               32         32      32          32          32   32    32   32
定制指数             14         14      14          14          14   11    14   14
概念              269        269     269         269         269  269   269  269
策略              175        175     175         175         175  174   175  175
综合                5          5       5           5           5    5     5    5
行业              410        410     410         410         410  410   410  410
规模               77         77      77          77          77   76    77   77
风格              188        188     188         188         188  188   188  188

In [ ]:
cls = [['000001','上证指数']] + IndexRAW[IndexRAW['IndexSTL'].str.contains('行业') & IndexRAW['IndexName'].str.contains('指数')][['IndexCode','IndexName']].values.tolist()

### 数据生成

In [ ]:
def genData(List):
    dfI = pd.DataFrame()
    for code in tqdm(List):
        try:
            df_tmp = pd.read_sql(code[0], engI).set_index('datetime')['close'].to_frame()
            # df_tmp['close'] = np.log(df_tmp['close']).diff()        
            df_tmp.rename(columns={'close':code[0]+':'+code[1]}, inplace=True)
            dfI = pd.merge(dfI,df_tmp,right_index=True, left_index=True,how='outer')
        except:
            pass
            print(code+' pass ! ')
    return dfI

In [5]:
dfmerg = pd.read_excel('/home/ts/app/AiStock/Linkage/MergIndex.xlsx').set_index('datetime')

In [ ]:
dfmerg.tail()

In [6]:
dfRAW = dfmerg.copy()

In [ ]:
dfRAW = dfmerg[dfmerg.columns[dfmerg.columns.str.contains('180')]].dropna()

In [ ]:
dfRAW = genData(cls).dropna()

In [ ]:
IndexCode = '000065'
df2RAW = pd.read_sql(IndexCode, engI)

In [ ]:
dfRAW[dfRAW.index > '2021-08-08']['880229:贵州板块']

#### 数据归一化

In [ ]:
n = min(df1RAW.shape[0],df2RAW.shape[0])

In [ ]:
n = 500

In [ ]:
df1 = df1RAW.tail(n).set_index('datetime')
df2 = df2RAW.tail(n).set_index('datetime')
df = pd.DataFrame()
df['000001'] = df1['close']
df[IndexCode] = df2['close']

#### Min-Max 归一化（线性缩放到 [0,1]）

In [ ]:


dfn = pd.DataFrame(MinMaxScaler().fit_transform(df),columns=['000001', IndexCode])

#### Z-Score 标准化（均值为0，标准差为1）

In [ ]:
dfn = pd.DataFrame(StandardScaler().fit_transform(df),columns=['000001', IndexCode])

In [ ]:
dfRAW.head()

#### 以基准日为100的相对收益归一化（最常用）

In [14]:
dfn = dfRAW.copy()
# dfn = dfRAW[(dfRAW.index > '2018-01-04') & (dfRAW.index < '2020-07-31')].copy()
# dfn = dfRAW[(dfRAW.index > '2015-06-15') & (dfRAW.index < '2016-01-04')].copy()
for col in dfn.columns:
    dfn[col] = 100 * dfn[col] / dfn[col].iloc[6279] 
    # dfn[col] = StandardScaler().fit_transform(dfn[col].values.reshape(-1, 1)).flatten() 
    # dfn[col] = MinMaxScaler().fit_transform(dfn[col].values.reshape(-1, 1)).flatten()

In [13]:
dfmerg.shape

(6280, 1620)

In [29]:
dfn.tail(55)

,000001:上证指数,000009:上证380,000010:上证180,000015:红利指数,000016:上证50,000018:180金融,000019:治理指数,000020:中型综指,000021:180治理,000025:180基建,...,H50036:上证军工,H50037:上证城镇,H50038:沪智慧城,H50039:上证TMT,H50040:上红低波,H50042:上红价值,H50052:上国改革,H50053:上证移动,H50054:上证休闲,H50055:沪大农业
datetime,,,,,,,,,,,,,,,,,,,,,
2025-07-21 15:00,91.346230,86.243864,88.577808,103.888867,93.189236,107.642856,95.891315,81.526360,97.229348,103.139626,...,92.860108,88.578620,85.934115,75.533452,106.415303,103.243261,92.123055,75.517141,92.929876,92.727146
2025-07-22 15:00,91.912559,87.159808,89.435586,105.557663,93.859522,106.816173,96.825069,81.644502,98.197704,104.639263,...,92.842564,90.095622,87.093115,75.334068,106.848709,104.677413,93.674489,75.233184,93.143327,93.590726
2025-07-23 15:00,91.923850,86.904828,89.476037,105.537701,94.162731,107.807040,96.853940,81.550701,98.281003,104.254250,...,91.518799,89.718523,86.633418,75.575288,106.896276,104.834564,93.399738,75.515452,93.157404,93.358768
2025-07-24 15:00,92.525077,88.178375,90.213122,105.807516,94.540565,107.488933,97.125323,82.523154,98.433403,104.668207,...,93.149599,90.943513,87.446372,76.596612,106.171706,104.765867,94.356425,76.803603,94.499376,94.174806
2025-07-25 15:00,92.215354,88.221798,89.790056,105.310138,93.971461,107.050568,96.236111,83.531821,97.367549,103.068631,...,93.334796,90.469962,87.137175,77.530733,105.465323,104.031523,93.703966,77.653720,94.945883,94.177588
2025-07-28 15:00,92.325181,88.242984,90.010135,103.983685,94.215507,107.879231,96.330147,84.069105,97.457475,102.420936,...,94.262575,90.478631,87.155905,77.965864,104.833502,103.114319,93.594334,78.145542,95.047029,93.843966
2025-07-29 15:00,92.627206,88.804630,90.442971,103.804362,94.411147,106.937871,96.203941,84.959630,97.248280,102.624638,...,95.292058,90.888240,87.920910,79.202548,104.156572,102.669794,93.899457,79.654489,95.063498,93.493314
2025-07-30 15:00,92.781426,88.297075,90.660751,104.267473,94.772846,107.564724,96.762379,84.012111,97.932660,102.847999,...,94.358560,90.575312,87.149069,78.535465,104.430568,102.933142,93.918453,79.287136,96.071298,94.012267
2025-07-31 15:00,91.690595,86.864260,89.130340,102.576054,93.315293,106.150794,95.260288,83.643434,96.402980,101.303581,...,93.758289,89.212316,86.480764,78.119477,103.137288,101.234435,92.221566,79.237414,94.776795,92.004320
2025-08-01 15:00,91.350336,86.820236,88.447631,102.500532,92.580466,105.866172,94.858576,83.690929,95.891824,100.860134,...,92.622378,89.093620,86.386628,77.214476,103.140619,101.319493,91.251785,78.258478,95.037991,91.941579
2025-08-04 15:00,91.949767,87.484205,88.840204,103.035838,93.093433,106.494105,95.446709,84.928164,96.456935,100.901093,...,95.294432,89.252573,86.854233,77.640423,103.750583,101.990694,91.829096,78.685786,95.745673,92.327821
2025-08-05 15:00,92.829668,88.186488,89.524285,104.088483,93.810780,108.073300,96.272406,85.527191,97.317380,101.273544,...,95.734990,89.883159,87.183581,77.854302,104.848605,103.332654,92.349117,79.177766,96.959170,92.826243
2025-08-06 15:00,93.250244,88.837686,89.742785,104.449457,94.035666,108.042515,96.525641,86.377345,97.501018,100.930583,...,99.472910,90.128526,87.704673,78.164429,104.878903,103.669024,92.936038,79.392089,97.388499,92.887489
2025-08-07 15:00,93.395996,88.598182,89.827162,104.762190,94.065583,108.233884,96.651022,86.373189,97.648685,100.951882,...,99.072460,90.241965,87.987214,78.213196,105.152486,103.880058,93.287402,79.507521,97.558383,93.140440
2025-08-08 15:00,93.279497,88.483238,89.688705,104.785146,93.758341,107.699744,96.598230,85.824626,97.577691,101.560256,...,98.630519,90.255767,87.238009,77.276340,105.309464,103.870301,93.213040,78.194068,96.966062,93.254075
2025-08-11 15:00,93.598202,89.296860,89.674692,104.150697,93.782880,107.151743,96.472024,87.510093,97.315487,101.034345,...,98.993343,91.163121,88.345537,78.310766,104.445066,103.123191,92.875265,79.044611,97.442847,93.403727
2025-08-12 15:00,94.069586,89.453424,90.135950,104.792465,94.358035,107.532679,96.699689,88.526478,97.560652,100.955704,...,98.320522,91.435689,88.614929,79.254194,104.907862,103.892194,93.035656,79.736420,97.577807,93.456156
2025-08-13 15:00,94.519673,90.450354,90.573918,103.987677,94.558717,107.021943,96.739283,89.765495,97.468834,100.691930,...,99.153809,91.957098,89.212927,80.664719,104.313716,103.060789,93.208274,81.361666,98.628772,93.733452
2025-08-14 15:00,94.082930,89.276125,90.689686,103.196197,95.113031,107.625213,96.615552,88.822133,97.508590,100.208071,...,97.210606,91.120396,88.264113,79.986327,104.283170,102.717505,93.314230,80.678625,97.709485,93.006713
2025-08-15 15:00,94.861215,91.105308,91.141174,103.021865,95.227659,107.419082,96.748356,90.635835,97.470727,99.993993,...,97.728570,92.251422,90.074101,81.452922,103.774376,102.526096,93.710975,82.426712,98.923893,94.582874
2025-08-18 15:00,95.663364,92.007729,91.560875,102.894110,95.429013,107.726928,97.014790,92.727381,97.629753,100.363168,...,99.588181,93.027024,91.962268,83.356256,103.954128,102.456403,94.245450,84.036328,100.273020,95.305280
2025-08-19 15:00,95.644375,91.888278,90.946950,102.830898,94.539893,107.077032,96.585857,92.576585,97.143209,100.144175,...,98.606473,93.000103,92.363239,83.347257,104.019533,102.410550,93.739865,84.357346,99.893763,95.933170
2025-08-20 15:00,96.643085,93.062657,92.212696,103.584784,95.701968,107.942780,97.591375,93.914153,98.153214,100.447816,...,98.689957,94.282118,93.187127,85.417133,104.865929,103.029405,94.857300,85.675605,100.485092,97.247721
2025-08-21 15:00,96.768565,92.682967,92.695368,104.108112,96.212582,108.232443,98.147339,93.167300,98.786479,101.510559,...,98.052604,94.542512,93.136745,85.082548,105.399386,103.589630,95.265893,85.647358,101.517647,97.580823
2025-08-22 15:00,98.171171,93.845627,94.896163,103.953409,98.445636,109.288480,98.923543,96.476490,99.554159,101.996603,...,100.032877,95.882102,95.076036,89.312680,104.902530,103.082692,97.098961,89.827760,102.715177,97.502802
2025-08-25 15:00,99.654352,95.230060,97.119260,104.663047,100.504227,109.989504,100.437182,98.173830,101.123596,103.214990,...,102.040081,97.598780,96.796586,91.354349,105.676631,104.114777,99.147810,91.752138,103.435689,99.036498
2025-08-26 15:00,99.264825,95.545592,96.407833,104.360960,99.829571,109.057146,100.185596,97.707195,100.810276,102.906434,...,101.473057,98.022296,97.858302,90.831535,105.615181,103.707421,98.573559,91.689410,104.004414,100.223364
2025-08-27 15:00,97.519136,94.174531,94.955572,102.415030,98.101753,106.627685,98.511107,96.688435,99.023125,101.072027,...,99.747002,95.896827,96.361976,90.804036,103.931061,101.821929,96.970647,90.926995,102.301741,98.313894
2025-08-28 15:00,98.628956,95.651521,96.633528,102.530142,99.525354,107.363814,98.955713,99.972691,99.376201,101.317234,...,101.888426,96.777665,97.946779,95.283972,104.059594,102.092312,97.965018,94.567056,103.166389,98.034757
2025-08-29 15:00,98.996672,95.937152,97.277947,101.824164,100.054457,107.073431,99.675001,99.110663,100.227180,101.210741,...,103.315538,97.470409,96.907491,94.636293,103.525806,101.533558,97.687545,94.204756,103.732787,98.591636
2025-09-01 15:00,99.448298,96.476110,98.058158,101.332109,100.213456,105.569308,99.757488,99.861672,100.132522,100.600182,...,103.422870,98.125883,97.081621,94.966257,103.243543,101.216846,98.181767,95.568140,104.747741,99.407723
2025-09-02 15:00,99.001804,94.635358,97.730520,101.860095,100.606081,106.680613,99.960406,97.678105,100.626639,101.029976,...,101.255506,96.994929,94.288717,91.271832,104.214774,102.087987,97.425729,91.750808,101.956875,98.403786
2025-09-03 15:00,97.858112,93.605672,96.930671,100.835729,99.534094,104.906089,99.241943,96.109594,99.952671,100.010922,...,96.294718,95.954257,92.880084,89.541841,103.152474,100.907513,96.171955,90.443484,101.072066,96.423660
2025-09-04 15:00,96.634617,91.649525,94.718035,101.394323,97.835857,105.206554,98.327985,92.679292,99.127249,99.542900,...,93.671103,94.223869,90.831459,84.923291,103.237257,101.190695,94.511113,86.408503,99.761568,96.301275
2025-09-05 15:00,97.831169,93.999186,96.279640,101.120848,98.903138,104.758107,99.227920,95.499881,99.894929,99.423847,...,95.028823,96.070050,93.095031,87.533792,102.785518,100.963565,95.563553,89.121121,101.725226,97.026016
2025-09-08 15:00,98.198885,95.362734,96.533954,101.267899,98.824479,103.988133,99.528998,96.127404,100.034077,100.603459,...,95.529853,97.259937,94.182617,88.030541,102.879863,101.029043,96.113686,89.531223,103.223712,99.262661
2025-09-09 15:00,97.697221,94.857582,95.922595,101.403306,98.446308,104.655672,99.591689,94.356447,100.181744,99.948119,...,93.983920,96.688357,93.082274,86.038403,103.326656,101.380169,95.870987,86.898539,102.631129,99.280244
2025-09-10 15:00,97.823727,94.469929,96.169309,101.227643,98.814730,104.607065,99.652729,94.748278,100.263150,100.298180,...,94.287688,96.476879,93.257800,87.435672,103.217428,101.282700,95.811151,88.568499,103.213158,98.804474
2025-09-11 15:00,99.442652,96.275973,97.886849,101.495129,100.276653,105.839168,100.501522,97.742816,100.982554,100.601275,...,96.101179,97.906254,95.708826,91.804148,103.473128,101.739604,97.228321,93.205055,104.041890,99.464429
2025-09-12 15:00,99.321791,96.268460,97.757758,100.836727,99.787888,104.102450,99.882043,98.368559,100.260311,100.252306,...,96.163089,97.794101,95.311814,93.048671,102.691880,101.177277,97.116203,94.354512,104.710250,98.861023
2025-09-15 15:00,99.062619,95.910407,97.737034,100.413872,99.588887,103.279007,99.527349,98.085372,99.910074,99.830704,...,95.427792,98.193765,95.523848,92.952563,101.977046,100.795054,97.155936,94.533562,104.860936,98.527674
2025-09-16 15:00,99.097774,96.537113,97.560692,100.146386,99.091383,102.058606,99.068720,99.328544,99.301421,99.493750,...,94.698048,98.327955,95.928516,94.433886,101.642215,100.626875,96.754425,95.662748,104.964649,98.231358
2025-09-17 15:00,99.469083,97.489118,97.995887,100.492055,99.258114,101.760482,99.241118,100.511755,99.421637,99.714381,...,94.697046,99.297674,98.167882,95.078109,101.748754,101.162641,96.969438,96.714891,104.396048,97.781939
2025-09-18 15:00,98.322569,96.681507,96.942316,98.693176,97.915189,99.659749,97.719230,100.172762,97.726305,97.866868,...,94.132504,98.299105,97.867579,96.421534,99.837994,99.224991,95.705202,98.074105,102.475235,96.531012
2025-09-19 15:00,98.025676,96.699237,96.913895,99.376863,97.811318,99.483683,97.818215,99.057231,97.889117,97.857038,...,95.410041,98.275503,97.924745,95.711013,100.397850,100.423761,96.018495,97.299184,102.964951,96.851838
2025-09-22 15:00,98.243534,96.789839,97.579432,98.545127,98.229491,99.173137,97.621071,100.427452,97.668563,97.259040,...,95.782503,98.074001,98.111135,99.230940,99.549968,99.781985,96.418132,100.035557,101.517363,95.693849
2025-09-23 15:00,98.070325,96.363120,97.208077,99.244118,98.139738,99.847877,97.824814,99.267989,97.988508,97.574149,...,95.158153,97.057595,97.020610,98.489529,100.521777,100.777731,96.383394,99.314193,100.285471,94.588966
2025-09-24 15:00,98.886588,98.223255,97.979209,99.357567,98.812041,99.826994,98.276843,101.634410,98.192024,97.552304,...,95.931022,97.980950,98.385628,100.803341,100.789185,101.036399,96.771824,101.796956,102.199370,95.183035
2025-09-25 15:00,98.877863,98.306496,98.484185,98.712805,99.256769,99.406092,98.304889,101.516861,98.197704,97.077729,...,95.670085,98.235671,99.058667,102.132150,99.809283,100.264896,96.921643,103.003655,103.060590,95.065108
2025-09-26 15:00,98.231474,97.572208,97.769610,98.801302,98.862800,99.528690,98.068976,99.986939,98.057609,97.221358,...,95.908969,97.375626,97.450573,99.565665,99.783389,99.683642,96.825310,99.890831,100.748980,95.584862
2025-09-29 15:00,99.114710,98.640809,99.002384,98.509528,99.939157,100.467169,98.901271,101.206958,98.870725,97.346964,...,96.283250,98.457083,98.499305,100.962394,99.667233,99.309528,98.050895,101.295200,101.195998,96.139124
2025-09-30 15:00,99.634337,99.775822,100.036316,98.239048,100.473637,99.558754,99.204824,102.326051,99.114944,97.448542,...,99.214695,99.632463,99.662517,102.221495,99.057782,98.701824,98.559105,102.094264,101.547618,96.913653
2025-10-08 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10-09 15:00,100.947901,101.435069,101.832489,98.872831,101.537893,99.406092,100.560913,102.694728,100.503583,99.701820,...,100.998064,100.965084,101.740239,105.461128,99.245013,99.195764,101.066731,104.595661,100.398163,98.449587
2025-10-10 15:00,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [30]:
dfn.tail(151).describe().T.sort_values(by='mean',ascending=False).head(20)

,count,mean,std,min,25%,50%,75%,max
880556:昨ST连板,139.0,443.993751,432.452959,25.779608,53.773122,375.804716,743.630981,1352.011758
880866:近期新低,146.0,301.097324,146.550609,97.551416,133.960850,401.959790,412.743244,491.699714
880812:昨日连板,149.0,223.214596,261.467421,12.970172,40.348241,107.723712,288.872799,1147.272960
880751:昨日跌停,148.0,205.394134,160.958565,33.355775,66.833109,171.783363,282.798474,725.516158
880874:昨曾涨停,149.0,195.164167,81.307617,100.000000,125.753817,170.111901,237.131360,378.540323
880690:昨日强势,149.0,178.279996,78.408055,97.660748,119.003905,138.897612,224.721182,366.408987
880864:昨日振荡,149.0,149.794889,42.521756,100.000000,115.639734,136.538513,173.068944,249.726540
880867:昨高换手,148.0,135.350073,29.411073,98.634690,113.516123,128.797269,145.456077,208.838588
880884:最近异动,149.0,134.478713,23.641455,99.748349,114.511901,130.365943,147.929118,190.867149
880784:昨日较弱,149.0,127.392292,23.565743,99.063060,112.963437,118.702192,130.183362,185.934927
880886:昨日较强,149.0,116.289457,14.769439,98.757891,103.796090,109.754811,126.376955,149.366184
880313:石油贸易,149.0,112.111237,12.341564,96.075885,101.739536,106.445698,120.809008,141.189822
880466:路桥,149.0,108.886139,4.460631,97.326568,107.257245,110.422027,112.083136,115.528931
H50027:沪金融红,149.0,106.897799,5.935662,96.955990,101.282032,107.033068,111.354517,119.031751
881442:公路铁路,149.0,106.881303,3.110681,98.955243,105.400060,107.735357,109.134815,111.474411
880460:铁路,149.0,106.303227,2.741403,99.771756,104.336636,106.567918,108.471788,112.090636
000134:上证银行,148.0,106.194937,5.415557,96.649918,101.128513,106.457544,110.230059,117.849545
931039:银行AH,151.0,106.181575,5.523616,94.677191,101.081821,106.083984,110.806839,117.962407
881344:电信服务,149.0,106.090153,2.804597,98.558117,105.006540,106.452804,107.413434,115.248669
H30022:800银行,149.0,105.957571,5.199963,96.514385,101.072162,105.968565,109.883471,117.465642

In [21]:
dfn.describe().T.sort_values(by='mean',ascending=False)

,count,mean,std,min,25%,50%,75%,max
880884:最近异动,1983.0,416.409186,305.736690,55.887596,152.364475,311.680822,631.891580,1354.356716
880812:昨日连板,1782.0,382.588833,820.250972,12.285123,34.317620,92.131564,254.959093,5763.677119
880780:融资增加,1490.0,337.562837,211.718361,73.799003,114.951564,268.921369,522.933662,806.344890
880556:昨ST连板,270.0,289.002186,354.787105,25.124455,47.433965,107.452592,391.465928,1352.011758
880409:电器连锁,4944.0,231.609246,109.235892,23.026454,123.869268,252.652335,318.995603,591.495079
...,...,...,...,...,...,...,...,...
930703:福建50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930846:300SNLV,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930949:价值回报,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931373:股息龙头,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931823:国资央企50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
pd.read_sql('931823', engI)

Empty DataFrame
Columns: [datetime, open, high, low, close, position, trade, price, year, month, day, hour, minute, amount]
Index: []

In [ ]:
dfn.describe().T.sort_values(by='mean',ascending=False)

In [ ]:
dfn.describe().T.sort_values(by='mean',ascending=False)

In [ ]:
dfn['datetime'] = df1.index

#### 画图

In [ ]:
def plt(dfn, name = 'name'):
    fig = px.line(dfn,title=name)

    fig.update_layout(
        # hovermode='x unified',
        dragmode='pan',
        width=1200,
        height=500,
        
    )
    fig.update_xaxes(showspikes=True, spikemode='across', spikesnap='cursor')
    fig.update_yaxes(showspikes=True, spikemode='across', spikesnap='cursor')
    fig.update_xaxes(tickformat="%Y-%m-%d")
    fig.update_traces(line=dict(width=1))
    fig.show(config={'scrollZoom': True})

In [ ]:
plt(dfn,'100')

In [ ]:
plt(dfn,'100')

In [ ]:
plt(dfn,"NM")

In [ ]:
plt(dfn, '100')

In [ ]:
plt(dfRAW, '100')

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=dfn['datetime'],  # x轴数据
    y=dfn[dfn.columns[0]],     # y轴数据
    mode='lines',       # 设置为线图模式
    name='000001'   # 图例名称
))
# fig = px.line(df1, x='datetime', y='close',title='重大政策节点')
# 添加第二个线图
fig.add_trace(go.Scatter(
    x=dfn['datetime'],  # x轴数据
    y=dfn[dfn.columns[1]],     # y轴数据
    mode='lines',       # 设置为线图模式
    name=IndexCode   # 图例名称
))

fig.show()

In [ ]:
fig = px.line(dfn, x='datetime', y=dfn.columns[:2],title='重大政策节点')

# 添加政策事件标记
policy_events = [
    ('2005-04-29', '股权分置<br>2005/04/29'),
    ('2008-11-05', '国常会4万亿<br>2008/11/05'),
    ('2010-03-31', '融资融券<br>2010/03/31'),
    ('2014-11-17', '沪港通2014/11/17'),
    ('2015-06-15', '&nbsp;<br>清场外配资2015/06/15'),
    ('2016-01-04', '&nbsp;<br>&nbsp;<br>熔断2016/01/04'),
    ('2019-07-22', '科创板<br>2018/07/22'),
    ('2023-02-01', '注册制<br>2023/02/01'),
    ('2024-09-24', '货币政策<br>2024/09/24')
]
policy_events1 = [
    ('2006-11-08', '变点<br>2006/11/08'),
    ('2010-01-18', '变点<br>2010/01/18'),
    ('2014-11-25', '变点<br>2014/11/25'),
    ('2016-04-01', '变点<br>2016/04/01'),
    ('2018-01-24', '变点<br>2018/01/24'),
]

for date, event in policy_events:
    fig.add_vline(x=date, line_dash="dash", line_color="red",line_width=0.6)
    fig.add_annotation(x=date, y=0.95, yref="paper", text=event, showarrow=False, 
                       bgcolor="rgba(0,0,0,0)", opacity=0.7)
for date, event in policy_events1:
    fig.add_vline(x=date, line_dash="dash", line_color="green",line_width=0.6)
    fig.add_annotation(x=date, y=0.05, yref="paper", text=event, showarrow=False, 
                       bgcolor="rgba(0,0,0,0)", opacity=0.7)

# 添加0轴
# fig.add_hline(y=0, line_dash="dot", line_color="black", opacity=0.6)
fig.add_ohlc(df2)

# 十字参考线
fig.update_xaxes(showspikes=True, spikemode='across', spikesnap='cursor')
fig.update_yaxes(showspikes=True, spikemode='across', spikesnap='cursor')

# 交互设置
fig.update_layout(
    hovermode='x unified',
    dragmode='pan',
    width=1200
)
fig.update_xaxes(tickformat="%Y-%m-%d")
fig.update_traces(line=dict(width=1))
fig.show(config={'scrollZoom': True})