In [1]:

import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import plotly.express as px
from tqdm import tqdm

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
engS = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [3]:
IndexRAW = pd.read_sql('optIndexs', engI)

#### List筛选

In [4]:
IndexRAW.groupby(by='IndexSTL').count()

          IndexCode  IndexName  Market  MarketName  MarketCode   DP  From  Num
IndexSTL
主题              450        450     450         450         450  432   450  450
地区               32         32      32          32          32   32    32   32
定制指数             14         14      14          14          14   11    14   14
概念              269        269     269         269         269  269   269  269
策略              175        175     175         175         175  174   175  175
综合                5          5       5           5           5    5     5    5
行业              410        410     410         410         410  410   410  410
规模               77         77      77          77          77   76    77   77
风格              188        188     188         188         188  188   188  188

In [ ]:
cls = [['000001','上证指数']] + IndexRAW[IndexRAW['IndexSTL'].str.contains('行业') & IndexRAW['IndexName'].str.contains('指数')][['IndexCode','IndexName']].values.tolist()

### 数据生成

In [ ]:
def genData(List):
    dfI = pd.DataFrame()
    for code in tqdm(List):
        try:
            df_tmp = pd.read_sql(code[0], engI).set_index('datetime')['close'].to_frame()
            # df_tmp['close'] = np.log(df_tmp['close']).diff()        
            df_tmp.rename(columns={'close':code[0]+':'+code[1]}, inplace=True)
            dfI = pd.merge(dfI,df_tmp,right_index=True, left_index=True,how='outer')
        except:
            pass
            print(code+' pass ! ')
    return dfI

In [5]:
dfmerg = pd.read_excel('/home/ts/app/AiStock/Linkage/MergIndex.xlsx').set_index('datetime')

In [ ]:
dfmerg.shape

In [6]:
dfRAW = dfmerg.copy()

In [ ]:
dfRAW.dropna(thresh=3000,axis=1).dropna()

In [ ]:
dfRAW = dfmerg[dfmerg.columns[dfmerg.columns.str.contains('180')]].dropna()

In [ ]:
dfRAW = genData(cls).dropna()

In [ ]:
IndexCode = '000065'
df2RAW = pd.read_sql(IndexCode, engI)

In [ ]:
dfRAW[dfRAW.index > '2021-08-08']['880229:贵州板块']

#### 数据归一化

In [ ]:
n = min(df1RAW.shape[0],df2RAW.shape[0])

In [ ]:
n = 500

In [ ]:
df1 = df1RAW.tail(n).set_index('datetime')
df2 = df2RAW.tail(n).set_index('datetime')
df = pd.DataFrame()
df['000001'] = df1['close']
df[IndexCode] = df2['close']

#### Min-Max 归一化（线性缩放到 [0,1]）

In [ ]:


dfn = pd.DataFrame(MinMaxScaler().fit_transform(df),columns=['000001', IndexCode])

#### Z-Score 标准化（均值为0，标准差为1）

In [ ]:
dfn = pd.DataFrame(StandardScaler().fit_transform(df),columns=['000001', IndexCode])

In [ ]:
dfRAW.head()

#### 以基准日为100的相对收益归一化（最常用）

In [7]:
dfn = dfRAW.copy()
# dfn = dfRAW[(dfRAW.index > '2018-01-04') & (dfRAW.index < '2020-07-31')].copy()
# dfn = dfRAW[(dfRAW.index > '2015-06-15') & (dfRAW.index < '2016-01-04')].copy()
for col in dfn.columns:
    dfn[col] = 100 * dfn[col] / dfn[col].iloc[6303] 
    # dfn[col] = StandardScaler().fit_transform(dfn[col].values.reshape(-1, 1)).flatten() 
    # dfn[col] = MinMaxScaler().fit_transform(dfn[col].values.reshape(-1, 1)).flatten()

In [ ]:
dfn.tail(55)

In [8]:
dfn.tail(55).describe().T.sort_values(by='mean',ascending=False).tail(20)

,count,mean,std,min,25%,50%,75%,max
880326:铝,55.0,83.135021,8.125050,74.038288,76.482521,79.662759,87.731795,102.661097
881416:装修装饰,55.0,81.998667,7.600630,73.947193,76.560975,78.696538,85.733608,100.000000
881078:能源金属,55.0,81.275974,9.710200,66.739106,73.560890,81.609778,89.255078,101.403572
881062:冶钢原料,55.0,75.130598,9.014005,66.238537,68.153206,71.353088,76.358758,100.000000
880915:昨日突涨,55.0,73.712523,10.876924,56.245538,62.831493,74.285575,79.123972,100.000000
399249:综企指数,55.0,71.026087,6.967359,64.452265,66.795231,68.943387,72.343412,100.000000
880774:昨日首板,55.0,64.438782,16.768377,38.241053,50.575802,62.905268,75.158015,100.000000
880665:昨ST首板,54.0,64.238134,18.164582,39.166068,47.617444,60.997814,76.649951,100.000000
H30047:AMAC木材,55.0,63.826855,13.216871,53.717160,55.335479,56.280456,67.568404,100.000000
880863:昨日涨停,55.0,61.574418,17.427405,35.317209,47.292058,59.241520,72.852889,100.000000
881115:林业,55.0,56.397401,15.587462,45.173738,47.093109,48.055174,59.443411,100.000000
880812:昨日连板,55.0,50.127866,21.113773,20.373083,32.212531,46.976480,65.954511,100.000000
880556:昨ST连板,53.0,50.078183,22.297045,23.877984,31.023514,41.420485,65.278579,100.000000
000963:中证下游,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930703:福建50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930846:300SNLV,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930949:价值回报,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931373:股息龙头,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931478:苏州绿色发展,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931823:国资央企50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dfn.describe().T.sort_values(by='mean',ascending=False)

In [ ]:
pd.read_sql('931823', engI)

In [ ]:
dfn.describe().T.sort_values(by='mean',ascending=False)

In [ ]:
dfn.describe().T.sort_values(by='mean',ascending=False)

In [ ]:
dfn['datetime'] = df1.index

#### 画图

In [ ]:
def plt(dfn, name = 'name'):
    fig = px.line(dfn,title=name)

    fig.update_layout(
        # hovermode='x unified',
        dragmode='pan',
        width=1200,
        height=500,
        
    )
    fig.update_xaxes(showspikes=True, spikemode='across', spikesnap='cursor')
    fig.update_yaxes(showspikes=True, spikemode='across', spikesnap='cursor')
    fig.update_xaxes(tickformat="%Y-%m-%d")
    fig.update_traces(line=dict(width=1))
    fig.show(config={'scrollZoom': True})

In [ ]:
plt(dfn.tail(55),'100')

In [ ]:
plt(dfn,'100')

In [ ]:
plt(dfn,"NM")

In [ ]:
plt(dfn, '100')

In [ ]:
plt(dfRAW, '100')

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=dfn['datetime'],  # x轴数据
    y=dfn[dfn.columns[0]],     # y轴数据
    mode='lines',       # 设置为线图模式
    name='000001'   # 图例名称
))
# fig = px.line(df1, x='datetime', y='close',title='重大政策节点')
# 添加第二个线图
fig.add_trace(go.Scatter(
    x=dfn['datetime'],  # x轴数据
    y=dfn[dfn.columns[1]],     # y轴数据
    mode='lines',       # 设置为线图模式
    name=IndexCode   # 图例名称
))

fig.show()

In [ ]:
fig = px.line(dfn, x='datetime', y=dfn.columns[:2],title='重大政策节点')

# 添加政策事件标记
policy_events = [
    ('2005-04-29', '股权分置<br>2005/04/29'),
    ('2008-11-05', '国常会4万亿<br>2008/11/05'),
    ('2010-03-31', '融资融券<br>2010/03/31'),
    ('2014-11-17', '沪港通2014/11/17'),
    ('2015-06-15', '&nbsp;<br>清场外配资2015/06/15'),
    ('2016-01-04', '&nbsp;<br>&nbsp;<br>熔断2016/01/04'),
    ('2019-07-22', '科创板<br>2018/07/22'),
    ('2023-02-01', '注册制<br>2023/02/01'),
    ('2024-09-24', '货币政策<br>2024/09/24')
]
policy_events1 = [
    ('2006-11-08', '变点<br>2006/11/08'),
    ('2010-01-18', '变点<br>2010/01/18'),
    ('2014-11-25', '变点<br>2014/11/25'),
    ('2016-04-01', '变点<br>2016/04/01'),
    ('2018-01-24', '变点<br>2018/01/24'),
]

for date, event in policy_events:
    fig.add_vline(x=date, line_dash="dash", line_color="red",line_width=0.6)
    fig.add_annotation(x=date, y=0.95, yref="paper", text=event, showarrow=False, 
                       bgcolor="rgba(0,0,0,0)", opacity=0.7)
for date, event in policy_events1:
    fig.add_vline(x=date, line_dash="dash", line_color="green",line_width=0.6)
    fig.add_annotation(x=date, y=0.05, yref="paper", text=event, showarrow=False, 
                       bgcolor="rgba(0,0,0,0)", opacity=0.7)

# 添加0轴
# fig.add_hline(y=0, line_dash="dot", line_color="black", opacity=0.6)
fig.add_ohlc(df2)

# 十字参考线
fig.update_xaxes(showspikes=True, spikemode='across', spikesnap='cursor')
fig.update_yaxes(showspikes=True, spikemode='across', spikesnap='cursor')

# 交互设置
fig.update_layout(
    hovermode='x unified',
    dragmode='pan',
    width=1200
)
fig.update_xaxes(tickformat="%Y-%m-%d")
fig.update_traces(line=dict(width=1))
fig.show(config={'scrollZoom': True})